/* export_check.c — does the generated C source carry the same resource as the
 * .rsc it came from?
 *
 * Compiling the generated code only proves it parses.  This walks the generated
 * OBJECT tree and the original file's tree in lockstep, following the AES links,
 * and diffs every field: geometry, links, type/flags/state, box words, strings,
 * TEDINFO text/template/valid, and ICONBLK bitplanes.
 *
 * Driven by `make check`, which exports a sample .rsc to build/check/res.[ch]
 * and compiles this against it:
 *
 *     make check                                  # uses $GEM_DIR/resources
 *     make check RSC_SAMPLE=path/to/other.rsc
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "res.h"          /* generated by rockscli: OBJECT, TEDINFO, rs_trees[] */
#include "rsc.h"          /* the reader we are checking against                 */

static int fails = 0, checks = 0;

#define CK(cond, fmt, ...) do {                                            \
    checks++;                                                              \
    if (!(cond)) { fails++; printf("  MISMATCH " fmt "\n", __VA_ARGS__); } \
} while (0)

static const char *sstr(const char *s) { return s ? s : "(null)"; }
static int streq(const char *a, const char *b) { return strcmp(sstr(a), sstr(b)) == 0; }

static void walk(OBJECT *g, RSC_OBJECT *r, int i, int tree)
{
    OBJECT     *go = &g[i];
    RSC_OBJECT *ro = &r[i];

    CK(go->ob_next == ro->ob_next,   "t%d[%d].ob_next %d != %d",     tree, i, go->ob_next, ro->ob_next);
    CK(go->ob_head == ro->ob_head,   "t%d[%d].ob_head %d != %d",     tree, i, go->ob_head, ro->ob_head);
    CK(go->ob_tail == ro->ob_tail,   "t%d[%d].ob_tail %d != %d",     tree, i, go->ob_tail, ro->ob_tail);
    CK(go->ob_type == ro->ob_type,   "t%d[%d].ob_type %04X != %04X", tree, i, go->ob_type, ro->ob_type);
    CK(go->ob_flags == ro->ob_flags, "t%d[%d].ob_flags %04X != %04X",tree, i, go->ob_flags, ro->ob_flags);
    CK(go->ob_state == ro->ob_state, "t%d[%d].ob_state %04X != %04X",tree, i, go->ob_state, ro->ob_state);
    CK(go->ob_x == ro->ob_x,         "t%d[%d].ob_x %d != %d",        tree, i, go->ob_x, ro->ob_x);
    CK(go->ob_y == ro->ob_y,         "t%d[%d].ob_y %d != %d",        tree, i, go->ob_y, ro->ob_y);
    CK(go->ob_w == ro->ob_w,         "t%d[%d].ob_w %d != %d",        tree, i, go->ob_w, ro->ob_w);
    CK(go->ob_h == ro->ob_h,         "t%d[%d].ob_h %d != %d",        tree, i, go->ob_h, ro->ob_h);

    switch (ro->ob_type & 0xFF) {
    case G_BOX: case G_IBOX: case G_BOXCHAR: {
        unsigned long gw = (unsigned long)(uintptr_t)go->ob_spec;
        unsigned long rw = (unsigned long)(uintptr_t)ro->ob_spec;
        CK(gw == rw, "t%d[%d] box word %08lX != %08lX", tree, i, gw, rw);
        break;
    }
    case G_STRING: case G_BUTTON: case G_TITLE: {
        const char *gs = (const char *)go->ob_spec, *rs = (const char *)ro->ob_spec;
        CK(streq(gs, rs), "t%d[%d] string '%s' != '%s'", tree, i, sstr(gs), sstr(rs));
        break;
    }
    case G_TEXT: case G_BOXTEXT: case G_FTEXT: case G_FBOXTEXT: {
        TEDINFO     *gt = (TEDINFO *)go->ob_spec;
        RSC_TEDINFO *rt = (RSC_TEDINFO *)ro->ob_spec;
        if (!gt || !rt) { CK(0, "t%d[%d] TEDINFO missing (%p/%p)", tree, i, (void *)gt, (void *)rt); break; }
        CK(streq(gt->te_ptext,  rt->te_ptext),  "t%d[%d] te_ptext '%s' != '%s'",  tree, i, sstr(gt->te_ptext),  sstr(rt->te_ptext));
        CK(streq(gt->te_ptmplt, rt->te_ptmplt), "t%d[%d] te_ptmplt '%s' != '%s'", tree, i, sstr(gt->te_ptmplt), sstr(rt->te_ptmplt));
        CK(streq(gt->te_pvalid, rt->te_pvalid), "t%d[%d] te_pvalid '%s' != '%s'", tree, i, sstr(gt->te_pvalid), sstr(rt->te_pvalid));
        CK(gt->te_font == rt->te_font, "t%d[%d] te_font %d != %d", tree, i, gt->te_font, rt->te_font);
        CK(gt->te_just == rt->te_just, "t%d[%d] te_just %d != %d", tree, i, gt->te_just, rt->te_just);
        CK((uint16_t)gt->te_color == (uint16_t)rt->te_color,
           "t%d[%d] te_color %04X != %04X", tree, i, (uint16_t)gt->te_color, (uint16_t)rt->te_color);
        break;
    }
    case G_ICON: {
        ICONBLK     *gi = (ICONBLK *)go->ob_spec;
        RSC_ICONBLK *ri = (RSC_ICONBLK *)ro->ob_spec;
        if (!gi || !ri) { CK(0, "t%d[%d] ICONBLK missing%s", tree, i, ""); break; }
        CK(streq(gi->ib_ptext, ri->ib_ptext), "t%d[%d] ib_ptext '%s' != '%s'", tree, i, sstr(gi->ib_ptext), sstr(ri->ib_ptext));
        CK(gi->ib_wicon == ri->ib_wicon, "t%d[%d] ib_wicon %d != %d", tree, i, gi->ib_wicon, ri->ib_wicon);
        CK(gi->ib_hicon == ri->ib_hicon, "t%d[%d] ib_hicon %d != %d", tree, i, gi->ib_hicon, ri->ib_hicon);
        int bytes = ((ri->ib_wicon + 15) / 16) * 2 * ri->ib_hicon;
        if (bytes > 0 && ri->ib_pdata && gi->ib_pdata)
            CK(memcmp(gi->ib_pdata, ri->ib_pdata, bytes) == 0, "t%d[%d] ib_pdata bitplanes differ%s", tree, i, "");
        if (bytes > 0 && ri->ib_pmask && gi->ib_pmask)
            CK(memcmp(gi->ib_pmask, ri->ib_pmask, bytes) == 0, "t%d[%d] ib_pmask bitplanes differ%s", tree, i, "");
        break;
    }
    default: break;
    }

    if (ro->ob_head == RSC_NIL) return;
    for (int c = ro->ob_head;;) {
        walk(g, r, c, tree);
        if (c == ro->ob_tail) break;
        int n = r[c].ob_next;
        if (n == RSC_NIL || n == i) break;
        c = n;
    }
}

int main(int argc, char **argv)
{
    if (argc < 2) { fprintf(stderr, "usage: export_check <original.rsc>\n"); return 2; }

    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror(argv[1]); return 1; }
    fseek(f, 0, SEEK_END); long len = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc(len);
    if (!buf || fread(buf, 1, len, f) != (size_t)len) { fprintf(stderr, "short read\n"); return 1; }
    fclose(f);

    const char *err = NULL;
    RSC *r = rsc_read(buf, len, &err);
    if (!r) { fprintf(stderr, "rsc_read: %s\n", err ? err : "?"); return 1; }

    int ntree = rsc_ntrees(r);
    printf("export_check: %s — %d tree(s) in the file, %d generated\n",
           argv[1], ntree, NUM_TREES);
    if (ntree != NUM_TREES) { printf("  MISMATCH tree count\n"); fails++; }

    for (int t = 0; t < ntree && t < NUM_TREES; t++)
        walk(rs_trees[t], rsc_tree(r, t), 0, t);

    rsc_free(r);
    free(buf);
    printf("  %d field checks, %d mismatch(es) — %s\n", checks, fails, fails ? "FAIL" : "OK");
    return fails ? 1 : 0;
}
