// XAArm64Assembler — encodes the AArch64 asm subset emitted by XTArm64Backend
// into machine code. Phase 1 of the self-hosted native toolchain (see
// private:docs/Design/native-toolchain.md). Byte-parity with `clang -c` is the bar.
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(int, XAArm64FixupKind) {
    XAArm64FixupBranch26,   // bl / b  -> ARM64_RELOC_BRANCH26   (in __text)
    XAArm64FixupPage21,     // adrp @PAGE   -> ARM64_RELOC_PAGE21   (in __text)
    XAArm64FixupPageOff12,  // add  @PAGEOFF -> ARM64_RELOC_PAGEOFF12 (in __text)
    XAArm64FixupPointer64,  // .quad <symbol> -> absolute 8-byte pointer (in __data; rebased)
    // GOT-indirect refs to an IMPORTED data symbol (produced by the static-archive
    // reader for an ARM64_RELOC_GOT_LOAD_* whose target stays external). They
    // resolve to the symbol's __got slot, not to the symbol: the adrp takes the
    // slot's page and the ldr its (8-scaled) page offset, and the slot is bound at
    // load like any other import. A GOT ref whose target IS in-image is instead
    // relaxed to Page21/PageOff12 by the caller.
    XAArm64FixupGotPage21,    // adrp @GOTPAGE    -> page of the import's __got slot
    XAArm64FixupGotPageOff12, // ldr  @GOTPAGEOFF -> offset of that slot in its page
};

@interface XAArm64Fixup : NSObject
@property (nonatomic) uint64_t offset;      // byte offset in the section
@property (nonatomic) XAArm64FixupKind kind;
@property (nonatomic, copy) NSString *symbol;
@property (nonatomic) uint32_t scale;       // PageOff12: log2(access size); 0 for add / byte
// Constant added to the resolved symbol address (`sym + addend`). The assembler
// never sets it; the static-archive reader does, for an ARM64_RELOC_ADDEND that
// pairs with the following PAGE21/PAGEOFF12 (e.g. `&table[2]`).
@property (nonatomic) int64_t addend;
@end

@interface XAArm64Assembler : NSObject
// Rewrite GNU/ELF-flavoured AArch64 asm into the Mach-O flavour this assembler
// parses. The two differ only in how a symbol reference is spelled — the
// instructions are identical — so one normalising pre-pass buys the whole ELF
// dialect rather than a second spelling at every operand site:
//
//     adrp x1, sym          ->  adrp x1, sym@PAGE
//     :lo12:sym             ->  sym@PAGEOFF
//     :got:sym              ->  sym@GOTPAGE
//     :got_lo12:sym         ->  sym@GOTPAGEOFF
//
// Needed because the Android runtime (support/arm64/runtime/rt-android.s) is
// generated by the NDK clang, which targets ELF: it must be assembled from
// exactly the text clang produced, or the ABI it was generated for stops being
// the ABI it is checked against. Idempotent on asm that is already Mach-O
// flavoured, so it is safe to run over a mixed input.
+ (NSString *)machoDialectFromElf:(NSString *)elfAsm;

// Assemble full asm text -> __text bytes. Intra-text relative branches are
// resolved; adrp/add @PAGE/@PAGEOFF and calls to non-local symbols are left as
// `fixups` for the linker. Data lines (`.section __DATA,__data` + `.byte`/`.quad`
// /`.asciz`/…) accumulate into `data`; a symbol defined there is listed in
// `dataSymbols`, and `symbols[name]` is its offset within its own section.
- (nullable NSData *)assemble:(NSString *)asmText error:(NSError **)error;
@property (nonatomic, readonly) NSArray<XAArm64Fixup *> *fixups;
@property (nonatomic, readonly) NSDictionary<NSString *, NSNumber *> *symbols;
@property (nonatomic, readonly) NSData *data;                       // __DATA,__data bytes
@property (nonatomic, readonly) NSSet<NSString *> *dataSymbols;     // names living in `data`
@property (nonatomic, readonly) NSSet<NSString *> *globalSymbols;   // names under `.globl` — the object's exports
// `.comm` COMMON (tentative) symbols: name → @[size, log2align]. External,
// undefined-with-size — no storage in this object; the linker merges them.
@property (nonatomic, readonly) NSDictionary<NSString *, NSArray<NSNumber *> *> *commonSymbols;
// Give every COMMON real storage in __data and define it locally, then clear the
// common set. For single-unit IMAGE builds (executable/dylib), which have no
// separate link stage; the `--object` path leaves commons as commons.
- (void)demoteCommonsToLocalData;
// Bug 066: the `__DATA,__mod_init_func` pointer array — the load-time
// constructors — kept SEPARATE from `data`, with its fixups' offsets relative
// to itself. The linker appends it after every other contribution to __data and
// shifts these fixups to match, then hands its length to the writer, which
// gives it a real S_MOD_INIT_FUNC_POINTERS section. Without that section type
// dyld treats the pointers as inert data and no constructor ever runs.
// Empty when the module has none.
@property (nonatomic, readonly) NSData *modInitData;
@property (nonatomic, readonly) NSArray<XAArm64Fixup *> *modInitFixups;

// Encode one instruction at `pc`. `resolve(name, &isLocal)` returns the target
// address for a local label (isLocal=YES) or 0 (isLocal=NO) for an external
// symbol that becomes a fixup. Pass nil for register-only instructions.
- (uint32_t)encodeLine:(NSString *)line
                    pc:(uint64_t)pc
               resolve:(uint32_t (^_Nullable)(NSString *name, BOOL *isLocal))resolve
                 error:(NSError **)error;
@end

NS_ASSUME_NONNULL_END
