#!/usr/bin/env python3
"""Regenerate tests/fixtures/struct_byval.xc.

The fixture is a loop-unrolled sweep that defines Sn structs
for n in 1..32, a matching sumSn function, and a main that
fills each one and passes it by value. Keeping the generator
around means we can tune the widths, shapes or reporting
without hand-editing the (large) generated file.

The generator is idempotent — running it again produces byte-
identical output.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "tests" / "fixtures" / "struct_byval.xc"
WIDTHS = range(1, 21)  # 1..20 inclusive. Widths 17-20 exercise
                       # the banked target's wide-arg spill path;
                       # wider than that pushes the generated
                       # binary past the non-banked code window
                       # ($2000-$5FFF, 16KB) on the banked target
                       # and past ~23KB on the xl target.
                       # If you bump this, inline-pack main tighter
                       # or refactor the PASS/FAIL reporter.


def main() -> None:
    out = []

    header = '''// AUTOGENERATED — DO NOT EDIT BY HAND.
// Source of truth: tests/gen_struct_byval.py (run to regenerate).
//
// Regression test for struct-by-value parameter passing across
// every struct width from 1 to 20 bytes. Each Sn struct has n
// u8 fields named a0..a{n-1}; sumSn takes Sn by value and
// returns the u16 sum of its fields. main fills 1..n into the
// fields, calls sumSn(s), and checks against n*(n+1)/2.
//
// The 1-16 range fits in the banked target's $B0..$BF register
// window. Widths 17-20 force the compiler onto the wide-arg
// spill path: the banked caller packs bytes into a per-callee
// `_args_<fn>` data-section buffer and the callee prologue
// reads them back from there.
//
// Expected output is 20 consecutive "PASS" lines (one per
// width), at every optimisation level, on both -m xl
// and -m banked. Any divergence means struct-by-value is
// broken at that width — either caller-side push truncation,
// callee-side pop mis-sizing, ZP allocator spill, wide-arg
// label mismatch, or the bank-register routing on the
// banked target.
//
// Fixture hygiene notes:
//   - All fields are u8 so the orthogonal u16-literal-
//     assignment stale-X bug doesn't poison the setup.
//   - Struct instances are globals so main doesn't burn
//     hundreds of bytes of ZP on 32 struct instances and
//     interfere with the banked swappable bank region.
//   - The check logic is inlined at each call site rather
//     than factored into a helper function — a banked helper
//     would itself cross-bank-call Stdio.printf and cross-
//     bank calls from a banked caller are currently broken
//     (the inline bank-switch sequence is interrupted mid-
//     fetch when $82 changes), out of scope for this test.

#include "Stdio.xc"

'''
    out.append(header)

    # Struct definitions S1..SN
    for n in WIDTHS:
        fields = " ".join(f"u8 a{i};" for i in range(n))
        out.append(f"struct S{n} {{ {fields} }}\n")

    out.append("\n")

    # Global struct instances so main doesn't blow through ZP.
    for n in WIDTHS:
        out.append(f"S{n} g{n};\n")

    out.append("\n")

    # Sum functions sumS1..sumSN
    for n in WIDTHS:
        body = " + ".join(f"(u16)s.a{i}" for i in range(n))
        out.append(f"u16 sumS{n}(S{n} s) {{ return {body}; }}\n")

    # One test block (set the global struct's fields, call sumSn, report).
    def emit_block(n: int) -> None:
        for i in range(n):
            out.append(f"    g{n}.a{i} = {i + 1};\n")
        expected = n * (n + 1) // 2
        out.append(f"    id = {n};\n")
        out.append(f"    exp = {expected};\n")
        out.append(f"    got = sumS{n}(g{n});\n")
        out.append(f"    if (got == exp) {{ Stdio.printf(\"T%u PASS\\n\", id); }}\n")
        out.append(f"    else {{ Stdio.printf(\"T%u FAIL got=%u exp=%u\\n\", id, got, exp); }}\n\n")

    # Emit the tests in chunked functions called from main. A single main
    # holding every block overflows the xt6502 unbanked code budget (the
    # entry can't be banked or split); each chunk is its own function, which
    # the backend packs into a code bank. exp/got/id are per-chunk locals;
    # the struct instances are globals shared across chunks.
    widths = list(WIDTHS)
    chunk_sz = 5
    chunks = [widths[i:i + chunk_sz] for i in range(0, len(widths), chunk_sz)]
    for ci, chunk in enumerate(chunks):
        out.append(f"\nvoid t_chunk{ci + 1}(void)\n{{\n")
        out.append("    u16 exp;\n    u16 got;\n    u16 id;\n")
        for n in chunk:
            emit_block(n)
        out.append("}\n")

    out.append("\nvoid main(void)\n{\n")
    for ci in range(len(chunks)):
        out.append(f"    t_chunk{ci + 1}();\n")
    out.append("}\n")

    OUT.write_text("".join(out))
    print(f"Wrote {OUT} ({len(WIDTHS)} widths)")


if __name__ == "__main__":
    main()
