// libc WITHOUT declaring it. `libc9.xc` declares `write` itself; here nothing
// is declared and nothing is imported by name — on arm9 the front end finds
// libc and brings in the functions the source mentions, and the ported front
// end has to do the same from its bundled interface stub
// (`support/arm9/selfhost-iface/c.xc`, generated by `selfhost/tools/gen-c-iface.sh`).
//
// So this fixture fails if the stub's signature for `snprintf` disagrees with
// the real one by so much as an argument width: the varargs tail travels under
// the C ABI, and a `%d` reading the wrong half of a register prints rubbish.
void main(void)
{
    u8 buf[64];
    i32 n = snprintf((u8*)buf, (u32)64, "auto-imported libc: %d\n", (i32)42);
    write((i32)1, (pointer)buf, (u32)n);
}
