// XTIR.h — umbrella header for the new-IR data structures
#import "XTIROpcode.h"
#import "XTIRSupport.h"
#import "XTIRType.h"
#import "XTIRLayout.h"
#import "XTIROperand.h"
#import "XTIRValue.h"
#import "XTIRInsn.h"
#import "XTIRBlock.h"
#import "XTIRFunction.h"
#import "XTIRSymbol.h"
#import "XTIRConstant.h"
#import "XTIRModule.h"
#import "XTIRPrinter.h"
#import "XTIRParser.h"
#import "XTIRVerifier.h"
#import "XTIRLowering.h"
