#!/bin/bash
# x65-diff.sh — the ported banked-6502 back end against xcc-cg-6502.
# =================================================================
#
# self-hosting M17. The fifth and last back end, and the one whose code
# generator is not fixed by an ABI: the ZP pools, the code regions and the
# bank windows all come from the layout file, so the port reads the same
# `.lnk` the oracle does.
#
# The oracle WRAPS its output in the runtime harness, which the driver
# prepends and the back end knows nothing about — so the comparison starts at
# the backend's own banner and runs to the end.
#
#   bash selfhost/tools/x65-diff.sh [pattern]

set -u
cd "$(dirname "$0")/../.." || exit 1
BIN=bin/osx
[ -x "$BIN/xcc-fe" ] || BIN=bin/linux
LAYOUT=support/xt6502/layouts/xt.lnk
PATTERN=${1:-}
WORK=${TMPDIR:-/tmp}/x65diff.$$
mkdir -p "$WORK"
trap 'rm -rf "$WORK"' EXIT

echo "building xtcg65 (xtc → native arm64 host binary)…"
"$BIN/xcc" -O2 -A arm64 -H . -o "$WORK/xtcg65" selfhost/tools/xtcg65.xc \
    -I selfhost/ir -I selfhost/opt -I selfhost/codegen -I selfhost/driver \
    2>&1 | grep -E "^[^ ].*error" && exit 1

RUN_INCS=(-I selfhost/lexer -I selfhost/preproc -I selfhost/parser
          -I selfhost/sema -I selfhost/ir -I selfhost/opt -I selfhost/codegen)

# The backend's own output begins at its banner; everything before it is the
# driver-prepended runtime harness. It ENDS before the banked float/double
# runtime block, which the driver's runtime emitter appends afterwards (it
# decides which softfloat .asm files to link from a scan of the generated
# text). Both ends belong to the harness layer, not the code generator.
strip_harness() {
    # When the trailing block is present the runtime emitter has put ONE blank
    # separator line in front of it; drop exactly that line, not the blank the
    # back end's own last function ends with.
    awk '/^; Generated by XT6502Backend/{p=1}
         /^; .. Banked float\/double runtime/{found=1; exit}
         p {buf[n++] = $0}
         END {
             if (found && n > 0 && buf[n-1] == "") n--
             for (i = 0; i < n; i++) print buf[i]
         }' "$1"
}

pass=0; fail=0; unsup=0; oracle=0
declare -a FAILED

# SHARD_I/SHARD_N: run only every Nth file, so one harness can be split
# across several parallel slots. all-diff uses it on the long ones; the
# default 0/1 is every file, which is what a direct run gets.
FILES=$(find tests support selfhost -name '*.xc' -not -path 'tests/fuzz/findings/*' | sort | awk -v i="${SHARD_I:-0}" -v n="${SHARD_N:-1}" 'NR % n == i')
for f in $FILES; do
    [ -n "$PATTERN" ] && [[ "$f" != *"$PATTERN"* ]] && continue
    if ! "$BIN/xcc-fe" -m xt -H . "${RUN_INCS[@]}" "$f" -o "$WORK/a.ir" \
         >/dev/null 2>&1 || [ ! -s "$WORK/a.ir" ]; then
        oracle=$((oracle+1)); continue
    fi
    if ! "$BIN/xcc-cg-6502" -m xt -O0 -q -o "$WORK/a.s" "$WORK/a.ir" >/dev/null 2>&1; then
        oracle=$((oracle+1)); continue
    fi
    "$WORK/xtcg65" "$WORK/a.ir" -L "$LAYOUT" -o "$WORK/b.s" >/dev/null 2>&1
    rc=$?
    if [ $rc -eq 3 ]; then unsup=$((unsup+1)); continue; fi
    if [ $rc -ne 0 ]; then fail=$((fail+1)); FAILED+=("$f (exit $rc)"); continue; fi
    strip_harness "$WORK/a.s" > "$WORK/a.gen"
    if diff -q "$WORK/a.gen" "$WORK/b.s" >/dev/null; then
        pass=$((pass+1))
    else
        fail=$((fail+1))
        FAILED+=("$f ($(diff "$WORK/a.gen" "$WORK/b.s" | grep -c '^[<>]') lines)")
    fi
done

if [ "${#FAILED[@]}" -gt 0 ]; then
    echo "--- differing (first 15):"
    printf '  %s\n' "${FAILED[@]}" | head -15
fi
echo "--- x65-diff: pass=$pass fail=$fail unsupported=$unsup oracle-failed=$oracle ---"
# A harness that REPORTS failures must also SIGNAL them. These printed the
# summary and fell off the end with status 0, which is fine for a human
# reading the table and useless to CI, to `&&` chains, and to anything else
# that checks status instead of stdout.  FAILS -> non-zero.
[ "$fail" -eq 0 ] || exit 1
# NOTHING COMPARED is not a pass. Every one of these harnesses counts an oracle
# failure — a file the REFERENCE could not build — and skips it, so a broken
# oracle turns the whole sweep into skips and the summary reads pass=0 fail=0.
# Only `fail` was ever checked, so that exited 0 and showed as a clean row in
# all-diff's table. It has now happened twice on ldx86-diff alone, the second
# time hiding 961 uncompared files. private:docs/bugs/239.
if [ "$pass" -eq 0 ]; then
    echo "--- $(basename "$0"): NOTHING WAS COMPARED — this is not a pass"
    exit 1
fi

