// xtlnandroid.xc — assemble an aarch64 `.s` and write the Android ELF image.
// =================================================================
//
//   xtlnandroid <exe|so> <entry|soname> <exports|-> <needed-csv> <in.s> <out>
//
// The self-hosted counterpart of `xcc-ln-arm64 --android`: no NDK clang, no
// ld.lld. Same argument order as the reference so one harness can drive both
// and compare the files byte for byte.
//
// The input is normalised out of the GNU/ELF dialect first, because the Android
// runtime is generated by the NDK clang and arrives spelled `:lo12:` rather
// than `@PAGEOFF`. The pass is idempotent, so the compiler's own
// Mach-O-flavoured asm in the same file is untouched.

#import "Foundation.xc"
#import "Stdio.xc"
#import "Files.xc"
#import "Process.xc"
#import "U64.xc"
#import "Arm64Asm.xc"
#import "ElfArm64.xc"

Array* splitCsv(String* s)
{
    Array* out = new Array();
    if (s == 0) return out;
    Array* parts = s.splitOnByte((u8)',');
    for (u32 i = (u32)0; i < parts.count(); i = i + (u32)1) {
        String* p = ((String*)parts.get(i)).trimmed();
        if (p.byteLength() == (u32)0) continue;
        if (p.equals(String.withCString("-"))) continue;
        out.add((Object*)p);
    }
    return out;
}

void main(void)
{
    if (Process.argumentCount() < (u32)7) {
        Stdio.printf("usage: xtlnandroid <exe|so> <entry|soname> <exports|-> "
                     "<needed-csv> <in.s> <out>\n");
        Process.exit((i32)2); return;
    }
    bool isExe = Process.argument((u32)1).equals(String.withCString("exe"));
    String* entryOrSoname = Process.argument((u32)2);
    String* exportsPath   = Process.argument((u32)3);
    String* neededCsv     = Process.argument((u32)4);
    String* inPath        = Process.argument((u32)5);
    String* outPath       = Process.argument((u32)6);

    String* src = Files.readText(inPath);
    if (src == 0) {
        Stdio.printf("xtlnandroid: cannot read '%s'\n", inPath.cString());
        Process.exit((i32)1); return;
    }

    Arm64Asm* a = new Arm64Asm();
    a.assemble(Arm64Asm.machoDialectFromElf(src));
    a.demoteCommonsToLocalData();   // single-unit image: give commons storage (bug 169)
    if (a.failed()) {
        Stdio.printf("xtlnandroid: assembly failed: %s\n", a.why().cString());
        Process.exit((i32)1); return;
    }

    Array* exports = new Array();
    if (!exportsPath.equals(String.withCString("-"))) {
        String* e = Files.readText(exportsPath);
        if (e != 0) {
            Array* lines = e.splitOnByte((u8)'\n');
            for (u32 i = (u32)0; i < lines.count(); i = i + (u32)1) {
                String* n = ((String*)lines.get(i)).trimmed();
                if (n.byteLength() > (u32)0) exports.add((Object*)n);
            }
        }
    }

    if (isExe && a.symbols().get((Hashable*)entryOrSoname) == (Object*)0) {
        Stdio.printf("xtlnandroid: entry symbol '%s' is not defined\n",
                     entryOrSoname.cString());
        Process.exit((i32)1); return;
    }

    // Bug 124: the constructor array lives outside dataBytes; append it or the
    // link silently drops every load-time constructor.
    Array* lnData = a.dataBytes();
    Array* lnFix  = a.fixups();
    u32 lnMi = Arm64Asm.appendModInit(a, lnData, lnFix);
    ElfArm64* w = new ElfArm64();
    w.image(a.textBytes(), lnData, a.symbols(), a.dataSyms(),
            exports, lnFix,
            isExe ? (String*)0 : entryOrSoname,
            splitCsv(neededCsv),
            isExe ? entryOrSoname : (String*)0, lnMi);
    if (w.failed()) {
        Stdio.printf("xtlnandroid: android link failed: %s\n", w.why().cString());
        Process.exit((i32)1); return;
    }

    Array* image = w.bytes();
    Data* d = Data.withCapacity((u32)0);
    for (u32 i = (u32)0; i < image.count(); i = i + (u32)1)
        d.appendByte((u8)((Number*)image.get(i)).asU32());
    if (!Files.writeData(outPath, d)) {
        Stdio.printf("xtlnandroid: cannot write '%s'\n", outPath.cString());
        Process.exit((i32)1); return;
    }
    // The loader will not map a file it cannot execute, and a .so that ends up
    // non-executable is a confusing "not found" at dlopen.
    Files.setExecutable(outPath);
}
