// c.xc — the libc declarations the ported front end cannot read for itself.
// =========================================================================
//
// GENERATED by `selfhost/tools/gen-c-iface.sh` from the DWARF in the arm9
// loader's `libc.so`. Do not hand-edit: the signatures are a CONTRACT with
// the original front end, which reads the same declarations out of the real
// libc, and a hand-tuned one diverges silently.
//
// On arm9 the driver auto-imports libc, so source calls `snprintf` and `write`
// without naming a header. The ported front end has no DWARF reader and reads
// this instead; `xtfe` injects only the names a unit actually mentions, plus
// the structs those names reach, and lets any declaration the program makes
// itself shadow the libc one — the rules the driver applies.
//
// A function whose types the language cannot SPELL (a function-pointer
// parameter, a struct with one inside) is left out rather than approximated:
// a guessed layout would put wrong offsets in optimised code, which is the
// one failure mode that does not look like a front-end bug.
//
// Functions are sorted by name — the DWARF importer hands its own back sorted,
// and that order is what makes the two symbol tables match.

struct DBT
{
    void* data;
    u32 size;
}

struct FPI
{
    i32 nbits;
    i32 emin;
    i32 emax;
    i32 rounding;
    i32 sudden_underflow;
}

struct SPLIT_RETURN
{
    _bufhead* newp;
    _bufhead* oldp;
    _bufhead* nextp;
    u16 next_addr;
    u8 __pad0[2];
}

struct _Bigint
{
    _Bigint* _next;
    i32 _k;
    i32 _maxwds;
    i32 _sign;
    i32 _wds;
    u32 _x[1];
}

struct __locale_t
{
}

struct __sFILE
{
    u8* _p;
    i32 _r;
    i32 _w;
    i16 _flags;
    i16 _file;
    __sbuf _bf;
    i32 _lbfsize;
    void* _cookie;
    void** _read;
    void** _write;
    void** _seek;
    void** _close;
    __sbuf _ub;
    u8* _up;
    i32 _ur;
    u8 _ubuf[3];
    u8 _nbuf[1];
    __sbuf _lb;
    i32 _blksize;
    i32 _offset;
    _reent* _data;
    i32 _lock;
    _mbstate_t _mbstate;
    i32 _flags2;
}

struct __sbuf
{
    u8* _base;
    i32 _size;
}

struct __siov
{
    void* iov_base;
    u32 iov_len;
}

struct __suio
{
    __siov* uio_iov;
    i32 uio_iovcnt;
    u32 uio_resid;
}

struct __va_list
{
    void* __ap;
}

struct __xtc_anon_109653
{
    internal_entry* sle_next;
}

struct __xtc_anon_580983
{
    u8 __opaque[4];
}

struct __xtc_anon_582569
{
    u8 __opaque[200];
}

struct _bufhead
{
    _bufhead* prev;
    _bufhead* next;
    _bufhead* ovfl;
    u32 addr;
    u8* page;
    u8 flags;
    u8 __pad0[3];
}

struct _glue
{
    _glue* _next;
    i32 _niobs;
    __sFILE* _iobs;
}

struct _mbstate_t
{
    i32 __count;
    __xtc_anon_580983 __value;
}

struct _reent
{
    i32 _errno;
    __sFILE* _stdin;
    __sFILE* _stdout;
    __sFILE* _stderr;
    i32 _inc;
    u8 _emergency[25];
    u8 __pad0[3];
    __locale_t* _locale;
    void** __cleanup;
    _Bigint* _result;
    i32 _result_k;
    _Bigint* _p5s;
    _Bigint** _freelist;
    i32 _cvtlen;
    u8* _cvtbuf;
    __xtc_anon_582569 _new;
    void*** _sig_func;
    u8 __pad1[4];
}

struct cookie_io_functions_t
{
    void** read;
    void** write;
    void** seek;
    void** close;
}

struct div_t
{
    i32 quot;
    i32 rem;
}

struct entry
{
    u8* key;
    void* data;
}

struct getopt_data
{
    u8* optarg;
    i32 optind;
    i32 opterr;
    i32 optopt;
    i32 optwhere;
    i32 permute_from;
    i32 num_nonopts;
}

struct hashhdr
{
    i32 magic;
    i32 version;
    u32 lorder;
    i32 bsize;
    i32 bshift;
    i32 dsize;
    i32 ssize;
    i32 sshift;
    i32 ovfl_point;
    i32 last_freed;
    i32 max_bucket;
    i32 high_mask;
    i32 low_mask;
    i32 ffactor;
    i32 nkeys;
    i32 hdrpages;
    i32 h_charkey;
    i32 spares[32];
    u16 bitmaps[32];
}

struct hsearch_data
{
    internal_head* htable;
    u32 htablesize;
}

struct htab
{
    hashhdr hdr;
    i32 nsegs;
    i32 exsegs;
    void** hash;
    i32 flags;
    i32 fp;
    u8* tmp_buf;
    u8* tmp_key;
    _bufhead* cpage;
    i32 cbucket;
    i32 cndx;
    i32 error;
    i32 new_file;
    i32 save_file;
    u32* mapp[32];
    u8 __pad0[64];
    i32 nmaps;
    i32 nbufs;
    _bufhead bufhead;
    u8 __pad1[8];
    _bufhead*** dir;
}

struct imaxdiv_t
{
    i32 quot;
    u8 __pad0[4];
    i32 rem;
    u8 __pad1[4];
}

struct internal_entry
{
    __xtc_anon_109653 link;
    u8 __pad0[2];
    entry ent;
    u8 __pad1[4];
}

struct internal_head
{
    internal_entry* slh_first;
}

struct lconv
{
    u8* decimal_point;
    u8* thousands_sep;
    u8* grouping;
    u8* int_curr_symbol;
    u8* currency_symbol;
    u8* mon_decimal_point;
    u8* mon_thousands_sep;
    u8* mon_grouping;
    u8* positive_sign;
    u8* negative_sign;
    u8 int_frac_digits;
    u8 frac_digits;
    u8 p_cs_precedes;
    u8 p_sep_by_space;
    u8 n_cs_precedes;
    u8 n_sep_by_space;
    u8 p_sign_posn;
    u8 n_sign_posn;
    u8 int_n_cs_precedes;
    u8 int_n_sep_by_space;
    u8 int_n_sign_posn;
    u8 int_p_cs_precedes;
    u8 int_p_sep_by_space;
    u8 int_p_sign_posn;
    u8 __pad0[2];
}

struct ldiv_t
{
    i32 quot;
    i32 rem;
}

struct lldiv_t
{
    i32 quot;
    u8 __pad0[4];
    i32 rem;
    u8 __pad1[4];
}

struct mallinfo
{
    i32 arena;
    i32 ordblks;
    i32 smblks;
    i32 hblks;
    i32 hblkhd;
    i32 usmblks;
    i32 fsmblks;
    i32 uordblks;
    i32 fordblks;
    i32 keepcost;
}

struct option
{
    u8* name;
    i32 has_arg;
    i32* flag;
    i32 val;
}

struct stat
{
    i16 st_dev;
    u16 st_ino;
    u32 st_mode;
    u16 st_nlink;
    u16 st_uid;
    u16 st_gid;
    i16 st_rdev;
    i32 st_size;
    u8 __pad0[4];
    timespec st_atim;
    timespec st_mtim;
    timespec st_ctim;
    i32 st_blksize;
    i32 st_blocks;
    i32 st_spare4[2];
}

struct timespec
{
    i32 tv_sec;
    u8 __pad0[4];
    i32 tv_nsec;
    u8 __pad1[4];
}

struct timeval
{
    i32 tv_sec;
    u8 __pad0[4];
    i32 tv_usec;
    u8 __pad1[4];
}

struct tm
{
    i32 tm_sec;
    i32 tm_min;
    i32 tm_hour;
    i32 tm_mday;
    i32 tm_mon;
    i32 tm_year;
    i32 tm_wday;
    i32 tm_yday;
    i32 tm_isdst;
}

struct tms
{
    u32 tms_utime;
    u32 tms_stime;
    u32 tms_cutime;
    u32 tms_cstime;
}

_Bigint* _Balloc(_reent* a0, i32 a1);
void _Bfree(_reent* a0, _Bigint* a1);
void _Exit(i32 a0);
_bufhead* __add_ovflpage(htab* a0, _bufhead* a1);
i32 __addel(htab* a0, _bufhead* a1, DBT* a2, DBT* a3);
double __adjust(_reent* a0, double* a1, i32 a2, i32 a3);
i32 __aeabi_atexit(void* a0, void** a1, void* a2);
void __aeabi_memclr(void* a0, u32 a1);
void __aeabi_memset(void* a0, u32 a1, i32 a2);
u32 __any_on(_Bigint* a0, i32 a1);
i32 __ascii_mbtowc(_reent* a0, u32* a1, u8* a2, u32 a3, _mbstate_t* a4);
i32 __ascii_wctomb(_reent* a0, u8* a1, u32 a2, _mbstate_t* a3);
void __assert(u8* a0, i32 a1, u8* a2);
void __assert_func(u8* a0, i32 a1, u8* a2, u8* a3);
double __b2d(_Bigint* a0, i32* a1);
i32 __big_delete(htab* a0, _bufhead* a1);
i32 __big_insert(htab* a0, _bufhead* a1, DBT* a2, DBT* a3);
i32 __big_keydata(htab* a0, _bufhead* a1, DBT* a2, DBT* a3, i32 a4);
i32 __big_return(htab* a0, _bufhead* a1, i32 a2, DBT* a3, i32 a4);
i32 __big_split(htab* a0, _bufhead* a1, _bufhead* a2, _bufhead* a3, i32 a4, u32 a5, SPLIT_RETURN* a6);
void __bsd_qsort_r(void* a0, u32 a1, u32 a2, void* a3, void** a4);
i32 __buf_free(htab* a0, i32 a1, i32 a2);
void __buf_init(htab* a0, i32 a1);
void __call_exitprocs(i32 a0, void* a1);
u32 __call_hash(htab* a0, u8* a1, i32 a2);
void __chk_fail(void);
void __copybits(u32* a0, i32 a1, _Bigint* a2);
u32* __ctloc(u32* a0, u8* a1, u32* a2);
i32 __ctype_load_locale(__locale_t* a0, u8* a1, void* a2, u8* a3, i32 a4);
i32 __cxa_atexit(void** a0, void* a1, void* a2);
void __cxa_finalize(void* a0);
_Bigint* __d2b(_reent* a0, double a1, i32* a2, i32* a3);
i32 __delpair(htab* a0, _bufhead* a1, i32 a2);
void __dorand48(_reent* a0, u16* a1);
void __dprintf(u8* a0, ...);
u8* __dtoa(double a0, i32 a1, i32 a2, i32* a3, i32* a4, u8** a5);
void __env_lock(_reent* a0);
void __env_unlock(_reent* a0);
void __eprintf(u8* a0, u8* a1, u32 a2, u8* a3);
void __errno(void);
double __exp10(u32 a0);
i32 __expand_table(htab* a0);
u32 __fbufsize(__sFILE* a0);
u32 __fgetwc(_reent* a0, __sFILE* a1);
i32 __find_bigpair(htab* a0, _bufhead* a1, i32 a2, u8* a3, i32 a4);
u16 __find_last_page(htab* a0, _bufhead** a1);
i32 __flbf(__sFILE* a0);
void __fp_lock_all(void);
void __fp_unlock_all(void);
i32 __fpclassifyd(double a0);
i32 __fpclassifyf(float a0);
u32 __fpending(__sFILE* a0);
void __fpurge(__sFILE* a0);
u32 __fputwc(_reent* a0, u32 a1, __sFILE* a2);
i32 __freadable(__sFILE* a0);
i32 __freading(__sFILE* a0);
void __free_ovflpage(htab* a0, _bufhead* a1);
void __freedtoa(_reent* a0, u8* a1);
i32 __fsetlocking(__sFILE* a0, i32 a1);
i32 __fwritable(__sFILE* a0);
i32 __fwriting(__sFILE* a0);
u8* __gdtoa(_reent* a0, FPI* a1, i32 a2, u32* a3, i32* a4, i32 a5, i32 a6, i32* a7, u8** a8);
_bufhead* __get_buf(htab* a0, u32 a1, _bufhead* a2, i32 a3);
i32 __get_page(htab* a0, u8* a1, u32 a2, i32 a3, i32 a4, i32 a5);
i32 __getdelim(u8** a0, u32* a1, i32 a2, __sFILE* a3);
i32 __gethex(_reent* a0, u8** a1, FPI* a2, i32* a3, _Bigint** a4, i32 a5, __locale_t* a6);
i32 __getline(u8** a0, u32* a1, __sFILE* a2);
i32 __getopt_long_only_r(i32 a0, u8** a1, u8* a2, option* a3, i32* a4, getopt_data* a5);
i32 __getopt_long_r(i32 a0, u8** a1, u8* a2, option* a3, i32* a4, getopt_data* a5);
i32 __getopt_r(i32 a0, u8** a1, u8* a2, getopt_data* a3);
_reent* __getreent(void);
u8* __gets_chk(u8* a0, u32 a1);
void __gettzinfo(void);
u8* __gnu_basename(u8* a0);
i32 __hexnan(u8** a0, FPI* a1, u32* a2);
i32 __hi0bits(u32 a0);
_Bigint* __i2b(_reent* a0, i32 a1);
i32 __ibitmap(htab* a0, i32 a1, i32 a2, i32 a3);
i32 __isinfd(double a0);
i32 __isinff(float a0);
i32 __isnand(double a0);
i32 __isnanf(float a0);
u8* __itoa(i32 a0, u8* a1, i32 a2);
void __libc_fini_array(void);
void __libc_init_array(void);
i32 __lo0bits(u32* a0);
void __locale_mb_cur_max(void);
lconv* __localeconv_l(__locale_t* a0);
u32 __log2(u32 a0);
_Bigint* __lshift(_reent* a0, _Bigint* a1, i32 a2);
void __malloc_lock(_reent* a0);
void __malloc_unlock(_reent* a0);
void __malloc_update_mallinfo(void);
i32 __match(u8** a0, u8* a1);
i32 __mcmp(_Bigint* a0, _Bigint* a1);
_Bigint* __mdiff(_reent* a0, _Bigint* a1, _Bigint* a2);
void* __memcpy_chk(void* a0, void* a1, u32 a2, u32 a3);
void* __memmove_chk(void* a0, void* a1, u32 a2, u32 a3);
void* __mempcpy_chk(void* a0, void* a1, u32 a2, u32 a3);
void* __memset_chk(void* a0, i32 a1, u32 a2, u32 a3);
i32 __messages_load_locale(__locale_t* a0, u8* a1, void* a2, u8* a3);
i32 __monetary_load_locale(__locale_t* a0, u8* a1, void* a2, u8* a3);
_Bigint* __multadd(_reent* a0, _Bigint* a1, i32 a2, i32 a3);
_Bigint* __multiply(_reent* a0, _Bigint* a1, _Bigint* a2);
u8* __nrv_alloc_D2A(_reent* a0, u8* a1, u8** a2, i32 a3);
i32 __numeric_load_locale(__locale_t* a0, u8* a1, void* a2, u8* a3);
_Bigint* __pow5mult(_reent* a0, _Bigint* a1, i32 a2);
i32 __put_page(htab* a0, u8* a1, u32 a2, i32 a3, i32 a4);
i32 __quorem_D2A(_Bigint* a0, _Bigint* a1);
double __ratio(_Bigint* a0, _Bigint* a1);
void __reclaim_buf(htab* a0, _bufhead* a1);
i32 __register_exitproc(i32 a0, void** a1, void* a2, void* a3);
void __rshift_D2A(_Bigint* a0, i32 a1);
u8* __rv_alloc_D2A(_reent* a0, i32 a1);
_Bigint* __s2b(_reent* a0, u8* a1, i32 a2, i32 a3, u32 a4);
u8* __sccl(u8* a0, u8* a1);
i32 __sclose(_reent* a0, void* a1);
i32 __seofread(_reent* a0, void* a1, u8* a2, i32 a3);
i32 __sflags(_reent* a0, u8* a1, i32* a2);
i32 __sflush_r(_reent* a0, __sFILE* a1);
__sFILE* __sfp(_reent* a0);
void __sfp_lock_acquire(void);
void __sfp_lock_release(void);
i32 __sfvwrite_r(_reent* a0, __sFILE* a1, __suio* a2);
i32 __sigtramp(i32 a0);
i32 __sigtramp_r(_reent* a0, i32 a1);
void __sinit(_reent* a0);
void __smakebuf_r(_reent* a0, __sFILE* a1);
i32 __snprintf_chk(u8* a0, u32 a1, i32 a2, u32 a3, u8* a4, ...);
i32 __split_page(htab* a0, u32 a1, u32 a2);
i32 __sprint_r(_reent* a0, __sFILE* a1, __suio* a2);
i32 __sprintf_chk(u8* a0, i32 a1, u32 a2, u8* a3, ...);
i32 __sread(_reent* a0, void* a1, u8* a2, i32 a3);
i32 __srefill_r(_reent* a0, __sFILE* a1);
i32 __srget(__sFILE* a0);
i32 __srget_r(_reent* a0, __sFILE* a1);
i32 __sseek(_reent* a0, void* a1, i32 a2, i32 a3);
i32 __ssprint_r(_reent* a0, __sFILE* a1, __suio* a2);
i32 __ssputs_r(_reent* a0, __sFILE* a1, u8* a2, u32 a3);
i32 __ssrefill_r(_reent* a0, __sFILE* a1);
i32 __ssvfiscanf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 __ssvfiwscanf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 __ssvfscanf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 __ssvfwscanf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 __sswprint_r(_reent* a0, __sFILE* a1, __suio* a2);
void __stack_chk_fail(void);
void __stack_chk_init(void);
u8* __stpcpy_chk(u8* a0, u8* a1, u32 a2);
u8* __stpncpy_chk(u8* a0, u8* a1, u32 a2, u32 a3);
u8* __strcat_chk(u8* a0, u8* a1, u32 a2);
u8* __strcpy_chk(u8* a0, u8* a1, u32 a2);
u8* __strncat_chk(u8* a0, u8* a1, u32 a2, u32 a3);
u8* __strncpy_chk(u8* a0, u8* a1, u32 a2, u32 a3);
u8* __strtok_r(u8* a0, u8* a1, u8** a2, i32 a3);
i32 __submore(_reent* a0, __sFILE* a1);
i32 __svfiscanf(__sFILE* a0, u8* a1, __va_list a2);
i32 __svfiscanf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 __svfiwscanf(__sFILE* a0, u32* a1, __va_list a2);
i32 __svfiwscanf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 __svfscanf(__sFILE* a0, u8* a1, __va_list a2);
i32 __svfscanf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 __svfwscanf(__sFILE* a0, u32* a1, __va_list a2);
i32 __svfwscanf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 __swbuf(i32 a0, __sFILE* a1);
i32 __swbuf_r(_reent* a0, i32 a1, __sFILE* a2);
i32 __swbufw_r(_reent* a0, i32 a1, __sFILE* a2);
i32 __swhatbuf_r(_reent* a0, __sFILE* a1, u32* a2, i32* a3);
i32 __swprint_r(_reent* a0, __sFILE* a1, __suio* a2);
i32 __swrite(_reent* a0, void* a1, u8* a2, i32 a3);
i32 __swsetup_r(_reent* a0, __sFILE* a1);
i32 __ten_mul(double* a0, i32 a1);
i32 __time_load_locale(__locale_t* a0, u8* a1, void* a2, u8* a3);
i32 __trailz_D2A(_Bigint* a0);
void __tz_lock(void);
void __tz_unlock(void);
i32 __tzcalc_limits(i32 a0);
double __ulp(double a0);
u8* __utoa(u32 a0, u8* a1, i32 a2);
i32 __vsnprintf_chk(u8* a0, u32 a1, i32 a2, u32 a3, u8* a4, __va_list a5);
i32 __vsprintf_chk(u8* a0, i32 a1, u32 a2, u8* a3, __va_list a4);
i32 __wcwidth(u32 a0);
i32 __xpg_strerror_r(i32 a0, u8* a1, u32 a2);
i32 _asiprintf_r(_reent* a0, u8** a1, u8* a2, ...);
u8* _asniprintf_r(_reent* a0, u8* a1, u32* a2, u8* a3, ...);
u8* _asnprintf_r(_reent* a0, u8* a1, u32* a2, u8* a3, ...);
i32 _asprintf_r(_reent* a0, u8** a1, u8* a2, ...);
i32 _atoi_r(_reent* a0, u8* a1);
i32 _atol_r(_reent* a0, u8* a1);
i32 _atoll_r(_reent* a0, u8* a1);
i32 _buf_findstr(u8* a0, u8** a1, u32* a2);
void* _calloc_r(_reent* a0, u32 a1, u32 a2);
i32 _close_r(_reent* a0, i32 a1);
u8* _dcvt(_reent* a0, u8* a1, double a2, i32 a3, i32 a4, u8 a5, i32 a6);
i32 _diprintf_r(_reent* a0, i32 a1, u8* a2, ...);
i32 _dprintf_r(_reent* a0, i32 a1, u8* a2, ...);
double _drand48_r(_reent* a0);
u8* _dtoa_r(_reent* a0, double a1, i32 a2, i32 a3, i32* a4, i32* a5, u8** a6);
__locale_t* _duplocale_r(_reent* a0, __locale_t* a1);
double _erand48_r(_reent* a0, u16* a1);
i32 _execve_r(_reent* a0, u8* a1, u8** a2, u8** a3);
i32 _fclose_r(_reent* a0, __sFILE* a1);
i32 _fcloseall_r(_reent* a0);
i32 _fcntl_r(_reent* a0, i32 a1, i32 a2, i32 a3);
__sFILE* _fdopen_r(_reent* a0, i32 a1, u8* a2);
i32 _fflush_r(_reent* a0, __sFILE* a1);
i32 _fflush_unlocked_r(_reent* a0, __sFILE* a1);
i32 _fgetc_r(_reent* a0, __sFILE* a1);
i32 _fgetc_unlocked_r(_reent* a0, __sFILE* a1);
i32 _fgetpos_r(_reent* a0, __sFILE* a1, i32* a2);
u8* _fgets_r(_reent* a0, u8* a1, i32 a2, __sFILE* a3);
u8* _fgets_unlocked_r(_reent* a0, u8* a1, i32 a2, __sFILE* a3);
u32 _fgetwc_r(_reent* a0, __sFILE* a1);
u32 _fgetwc_unlocked_r(_reent* a0, __sFILE* a1);
u32* _fgetws_r(_reent* a0, u32* a1, i32 a2, __sFILE* a3);
u32* _fgetws_unlocked_r(_reent* a0, u32* a1, i32 a2, __sFILE* a3);
u8* _findenv(u8* a0, i32* a1);
u8* _findenv_r(_reent* a0, u8* a1, i32* a2);
i32 _fiprintf_r(_reent* a0, __sFILE* a1, u8* a2, ...);
i32 _fiscanf_r(_reent* a0, __sFILE* a1, u8* a2, ...);
__sFILE* _fmemopen_r(_reent* a0, void* a1, u32 a2, u8* a3);
__sFILE* _fopen_r(_reent* a0, u8* a1, u8* a2);
__sFILE* _fopencookie_r(_reent* a0, void* a1, u8* a2, cookie_io_functions_t a3);
i32 _fork_r(_reent* a0);
i32 _fprintf_r(_reent* a0, __sFILE* a1, u8* a2, ...);
i32 _fpurge_r(_reent* a0, __sFILE* a1);
i32 _fputc_r(_reent* a0, i32 a1, __sFILE* a2);
i32 _fputc_unlocked_r(_reent* a0, i32 a1, __sFILE* a2);
i32 _fputs_r(_reent* a0, u8* a1, __sFILE* a2);
i32 _fputs_unlocked_r(_reent* a0, u8* a1, __sFILE* a2);
u32 _fputwc_r(_reent* a0, u32 a1, __sFILE* a2);
u32 _fputwc_unlocked_r(_reent* a0, u32 a1, __sFILE* a2);
i32 _fputws_r(_reent* a0, u32* a1, __sFILE* a2);
i32 _fputws_unlocked_r(_reent* a0, u32* a1, __sFILE* a2);
u32 _fread_r(_reent* a0, void* a1, u32 a2, u32 a3, __sFILE* a4);
u32 _fread_unlocked_r(_reent* a0, void* a1, u32 a2, u32 a3, __sFILE* a4);
void _free_r(_reent* a0, void* a1);
void _freelocale_r(_reent* a0, __locale_t* a1);
__sFILE* _freopen_r(_reent* a0, u8* a1, u8* a2, __sFILE* a3);
i32 _fscanf_r(_reent* a0, __sFILE* a1, u8* a2, ...);
i32 _fseek_r(_reent* a0, __sFILE* a1, i32 a2, i32 a3);
i32 _fseeko_r(_reent* a0, __sFILE* a1, i32 a2, i32 a3);
i32 _fsetpos_r(_reent* a0, __sFILE* a1, i32* a2);
i32 _fstat_r(_reent* a0, i32 a1, stat* a2);
i32 _ftell_r(_reent* a0, __sFILE* a1);
i32 _ftello_r(_reent* a0, __sFILE* a1);
__sFILE* _funopen_r(_reent* a0, void* a1, void** a2, void** a3, void** a4, void** a5);
i32 _fwalk_sglue(_reent* a0, void** a1, _glue* a2);
i32 _fwide_r(_reent* a0, __sFILE* a1, i32 a2);
i32 _fwprintf_r(_reent* a0, __sFILE* a1, u32* a2, ...);
u32 _fwrite_r(_reent* a0, void* a1, u32 a2, u32 a3, __sFILE* a4);
u32 _fwrite_unlocked_r(_reent* a0, void* a1, u32 a2, u32 a3, __sFILE* a4);
i32 _fwscanf_r(_reent* a0, __sFILE* a1, u32* a2, ...);
u8* _gcvt(_reent* a0, double a1, i32 a2, u8* a3, u8 a4, i32 a5);
i32 _getc_r(_reent* a0, __sFILE* a1);
i32 _getc_unlocked_r(_reent* a0, __sFILE* a1);
i32 _getchar_r(_reent* a0);
i32 _getchar_unlocked_r(_reent* a0);
i32 _getentropy_r(_reent* a0, void* a1, u32 a2);
u8* _getenv_r(_reent* a0, u8* a1);
i32 _getpid_r(_reent* a0);
u8* _gets_r(_reent* a0, u8* a1);
i32 _gettimeofday_r(_reent* a0, timeval* a1, void* a2);
u32 _getwc_r(_reent* a0, __sFILE* a1);
u32 _getwc_unlocked_r(_reent* a0, __sFILE* a1);
u32 _getwchar_r(_reent* a0);
u32 _getwchar_unlocked_r(_reent* a0);
i32 _init_signal(void);
i32 _init_signal_r(_reent* a0);
i32 _iprintf_r(_reent* a0, u8* a1, ...);
i32 _isatty_r(_reent* a0, i32 a1);
i32 _iscanf_r(_reent* a0, u8* a1, ...);
i32 _jrand48_r(_reent* a0, u16* a1);
i32 _kill_r(_reent* a0, i32 a1, i32 a2);
u8* _l64a_r(_reent* a0, i32 a1);
void _lcong48_r(_reent* a0, u16* a1);
i32 _ldcheck(double* a0);
u8* _ldtoa_r(_reent* a0, double a1, i32 a2, i32 a3, i32* a4, i32* a5, u8** a6);
i32 _link_r(_reent* a0, u8* a1, u8* a2);
lconv* _localeconv_r(_reent* a0);
i32 _lrand48_r(_reent* a0);
i32 _lseek_r(_reent* a0, i32 a1, i32 a2, i32 a3);
mallinfo _mallinfo_r(_reent* a0);
void* _malloc_r(_reent* a0, u32 a1);
void _malloc_stats_r(_reent* a0);
i32 _malloc_trim_r(_reent* a0, u32 a1);
u32 _malloc_usable_size_r(_reent* a0, void* a1);
i32 _mallopt_r(_reent* a0, i32 a1, i32 a2);
i32 _mblen_r(_reent* a0, u8* a1, u32 a2, _mbstate_t* a3);
u32 _mbrtowc_r(_reent* a0, u32* a1, u8* a2, u32 a3, _mbstate_t* a4);
u32 _mbsnrtowcs_r(_reent* a0, u32* a1, u8** a2, u32 a3, u32 a4, _mbstate_t* a5);
u32 _mbsrtowcs_r(_reent* a0, u32* a1, u8** a2, u32 a3, _mbstate_t* a4);
u32 _mbstowcs_r(_reent* a0, u32* a1, u8* a2, u32 a3, _mbstate_t* a4);
i32 _mbtowc_r(_reent* a0, u32* a1, u8* a2, u32 a3, _mbstate_t* a4);
void* _memalign_r(_reent* a0, u32 a1, u32 a2);
i32 _mkdir_r(_reent* a0, u8* a1, i32 a2);
u8* _mkdtemp_r(_reent* a0, u8* a1);
i32 _mkostemp_r(_reent* a0, u8* a1, i32 a2);
i32 _mkostemps_r(_reent* a0, u8* a1, i32 a2, i32 a3);
i32 _mkstemp_r(_reent* a0, u8* a1);
i32 _mkstemps_r(_reent* a0, u8* a1, i32 a2);
u8* _mktemp_r(_reent* a0, u8* a1);
double _mprec_log10(i32 a0);
i32 _mrand48_r(_reent* a0);
void _mstats_r(_reent* a0, u8* a1);
__locale_t* _newlocale_r(_reent* a0, i32 a1, u8* a2, __locale_t* a3);
i32 _nrand48_r(_reent* a0, u16* a1);
__sFILE* _open_memstream_r(_reent* a0, u8** a1, u32* a2);
i32 _open_r(_reent* a0, u8* a1, i32 a2, i32 a3);
__sFILE* _open_wmemstream_r(_reent* a0, u32** a1, u32* a2);
void _perror_r(_reent* a0, u8* a1);
i32 _printf_r(_reent* a0, u8* a1, ...);
i32 _putc_r(_reent* a0, i32 a1, __sFILE* a2);
i32 _putc_unlocked_r(_reent* a0, i32 a1, __sFILE* a2);
i32 _putchar_r(_reent* a0, i32 a1);
i32 _putchar_unlocked_r(_reent* a0, i32 a1);
i32 _putenv_r(_reent* a0, u8* a1);
i32 _puts_r(_reent* a0, u8* a1);
u32 _putwc_r(_reent* a0, u32 a1, __sFILE* a2);
u32 _putwc_unlocked_r(_reent* a0, u32 a1, __sFILE* a2);
u32 _putwchar_r(_reent* a0, u32 a1);
u32 _putwchar_unlocked_r(_reent* a0, u32 a1);
void* _pvalloc_r(_reent* a0, u32 a1);
i32 _raise_r(_reent* a0, i32 a1);
i32 _read_r(_reent* a0, i32 a1, void* a2, u32 a3);
void* _realloc_r(_reent* a0, void* a1, u32 a2);
void* _reallocf_r(_reent* a0, void* a1, u32 a2);
void _reclaim_reent(_reent* a0);
i32 _remove_r(_reent* a0, u8* a1);
i32 _rename_r(_reent* a0, u8* a1, u8* a2);
void _rewind_r(_reent* a0, __sFILE* a1);
void* _sbrk_r(_reent* a0, i32 a1);
i32 _scanf_r(_reent* a0, u8* a1, ...);
u16* _seed48_r(_reent* a0, u16* a1);
i32 _setenv_r(_reent* a0, u8* a1, u8* a2, i32 a3);
u8* _setlocale_r(_reent* a0, i32 a1, u8* a2);
u32 _sfread_r(_reent* a0, void* a1, u32 a2, u32 a3, __sFILE* a4);
void** _signal_r(_reent* a0, i32 a1, void** a2);
i32 _siprintf_r(_reent* a0, u8* a1, u8* a2, ...);
i32 _siscanf_r(_reent* a0, u8* a1, u8* a2, ...);
i32 _sniprintf_r(_reent* a0, u8* a1, u32 a2, u8* a3, ...);
i32 _snprintf_r(_reent* a0, u8* a1, u32 a2, u8* a3, ...);
i32 _sprintf_r(_reent* a0, u8* a1, u8* a2, ...);
void _srand48_r(_reent* a0, i32 a1);
i32 _sscanf_r(_reent* a0, u8* a1, u8* a2, ...);
i32 _stat_r(_reent* a0, u8* a1, stat* a2);
u8* _strdup_r(_reent* a0, u8* a1);
u8* _strerror_r(_reent* a0, i32 a1, i32 a2, i32* a3);
u8* _strndup_r(_reent* a0, u8* a1, u32 a2);
double _strtod_l(_reent* a0, u8* a1, u8** a2, __locale_t* a3);
double _strtod_r(_reent* a0, u8* a1, u8** a2);
i32 _strtoimax_r(_reent* a0, u8* a1, u8** a2, i32 a3);
i32 _strtol_r(_reent* a0, u8* a1, u8** a2, i32 a3);
double _strtold_r(_reent* a0, u8* a1, u8** a2);
i32 _strtoll_r(_reent* a0, u8* a1, u8** a2, i32 a3);
u32 _strtoul_r(_reent* a0, u8* a1, u8** a2, i32 a3);
u32 _strtoull_r(_reent* a0, u8* a1, u8** a2, i32 a3);
u32 _strtoumax_r(_reent* a0, u8* a1, u8** a2, i32 a3);
i32 _sungetc_r(_reent* a0, i32 a1, __sFILE* a2);
i32 _svfiprintf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 _svfiwprintf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 _svfprintf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 _svfwprintf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 _swprintf_r(_reent* a0, u32* a1, u32 a2, u32* a3, ...);
i32 _swscanf_r(_reent* a0, u32* a1, u32* a2, ...);
i32 _system_r(_reent* a0, u8* a1);
u8* _tempnam_r(_reent* a0, u8* a1, u8* a2);
u32 _times_r(_reent* a0, tms* a1);
__sFILE* _tmpfile_r(_reent* a0);
u8* _tmpnam_r(_reent* a0, u8* a1);
u32 _towctrans_r(_reent* a0, u32 a1, i32 a2);
void _tzset_r(_reent* a0);
void _tzset_unlocked(void);
void _tzset_unlocked_r(_reent* a0);
i32 _ungetc_r(_reent* a0, i32 a1, __sFILE* a2);
u32 _ungetwc_r(_reent* a0, u32 a1, __sFILE* a2);
i32 _unlink_r(_reent* a0, u8* a1);
i32 _unsetenv_r(_reent* a0, u8* a1);
__locale_t* _uselocale_r(_reent* a0, __locale_t* a1);
u8* _user_strerror(i32 a0, i32 a1, i32* a2);
void* _valloc_r(_reent* a0, u32 a1);
i32 _vasiprintf_r(_reent* a0, u8** a1, u8* a2, __va_list a3);
u8* _vasniprintf_r(_reent* a0, u8* a1, u32* a2, u8* a3, __va_list a4);
u8* _vasnprintf_r(_reent* a0, u8* a1, u32* a2, u8* a3, __va_list a4);
i32 _vasprintf_r(_reent* a0, u8** a1, u8* a2, __va_list a3);
i32 _vdiprintf_r(_reent* a0, i32 a1, u8* a2, __va_list a3);
i32 _vdprintf_r(_reent* a0, i32 a1, u8* a2, __va_list a3);
i32 _vfiprintf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 _vfiscanf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 _vfiwprintf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 _vfiwscanf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 _vfprintf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 _vfscanf_r(_reent* a0, __sFILE* a1, u8* a2, __va_list a3);
i32 _vfwprintf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 _vfwscanf_r(_reent* a0, __sFILE* a1, u32* a2, __va_list a3);
i32 _viprintf_r(_reent* a0, u8* a1, __va_list a2);
i32 _viscanf_r(_reent* a0, u8* a1, __va_list a2);
i32 _vprintf_r(_reent* a0, u8* a1, __va_list a2);
i32 _vscanf_r(_reent* a0, u8* a1, __va_list a2);
i32 _vsiprintf_r(_reent* a0, u8* a1, u8* a2, __va_list a3);
i32 _vsiscanf_r(_reent* a0, u8* a1, u8* a2, __va_list a3);
i32 _vsniprintf_r(_reent* a0, u8* a1, u32 a2, u8* a3, __va_list a4);
i32 _vsnprintf_r(_reent* a0, u8* a1, u32 a2, u8* a3, __va_list a4);
i32 _vsprintf_r(_reent* a0, u8* a1, u8* a2, __va_list a3);
i32 _vsscanf_r(_reent* a0, u8* a1, u8* a2, __va_list a3);
i32 _vswprintf_r(_reent* a0, u32* a1, u32 a2, u32* a3, __va_list a4);
i32 _vswscanf_r(_reent* a0, u32* a1, u32* a2, __va_list a3);
i32 _vwprintf_r(_reent* a0, u32* a1, __va_list a2);
i32 _vwscanf_r(_reent* a0, u32* a1, __va_list a2);
i32 _wait_r(_reent* a0, i32* a1);
u32 _wcrtomb_r(_reent* a0, u8* a1, u32 a2, _mbstate_t* a3);
u32* _wcsdup_r(_reent* a0, u32* a1);
u32 _wcsnrtombs_l(_reent* a0, u8* a1, u32** a2, u32 a3, u32 a4, _mbstate_t* a5, __locale_t* a6);
u32 _wcsnrtombs_r(_reent* a0, u8* a1, u32** a2, u32 a3, u32 a4, _mbstate_t* a5);
u32 _wcsrtombs_r(_reent* a0, u8* a1, u32** a2, u32 a3, _mbstate_t* a4);
double _wcstod_l(_reent* a0, u32* a1, u32** a2, __locale_t* a3);
double _wcstod_r(_reent* a0, u32* a1, u32** a2);
float _wcstof_r(_reent* a0, u32* a1, u32** a2);
i32 _wcstoimax_r(_reent* a0, u32* a1, u32** a2, i32 a3);
i32 _wcstol_r(_reent* a0, u32* a1, u32** a2, i32 a3);
i32 _wcstoll_l(_reent* a0, u32* a1, u32** a2, i32 a3, __locale_t* a4);
i32 _wcstoll_r(_reent* a0, u32* a1, u32** a2, i32 a3);
u32 _wcstombs_r(_reent* a0, u8* a1, u32* a2, u32 a3, _mbstate_t* a4);
u32 _wcstoul_l(_reent* a0, u32* a1, u32** a2, i32 a3, __locale_t* a4);
u32 _wcstoul_r(_reent* a0, u32* a1, u32** a2, i32 a3);
u32 _wcstoull_l(_reent* a0, u32* a1, u32** a2, i32 a3, __locale_t* a4);
u32 _wcstoull_r(_reent* a0, u32* a1, u32** a2, i32 a3);
u32 _wcstoumax_r(_reent* a0, u32* a1, u32** a2, i32 a3);
i32 _wctomb_r(_reent* a0, u8* a1, u32 a2, _mbstate_t* a3);
i32 _wctrans_r(_reent* a0, u8* a1);
i32 _wctype_r(_reent* a0, u8* a1);
i32 _wprintf_r(_reent* a0, u32* a1, ...);
i32 _write_r(_reent* a0, i32 a1, void* a2, u32 a3);
i32 _wscanf_r(_reent* a0, u32* a1, ...);
i32 a64l(u8* a0);
void abort(void);
i32 abs(i32 a0);
i32 access(u8* a0, i32 a1);
void* aligned_alloc(u32 a0, u32 a1);
u32 arc4random(void);
void arc4random_buf(void* a0, u32 a1);
u32 arc4random_uniform(u32 a0);
i32 argz_add(u8** a0, u32* a1, u8* a2);
i32 argz_add_sep(u8** a0, u32* a1, u8* a2, i32 a3);
i32 argz_append(u8** a0, u32* a1, u8* a2, u32 a3);
u32 argz_count(u8* a0, u32 a1);
i32 argz_create(u8** a0, u8** a1, u32* a2);
i32 argz_create_sep(u8* a0, i32 a1, u8** a2, u32* a3);
i32 argz_delete(u8** a0, u32* a1, u8* a2);
void argz_extract(u8* a0, u32 a1, u8** a2);
i32 argz_insert(u8** a0, u32* a1, u8* a2, u8* a3);
u8* argz_next(u8* a0, u32 a1, u8* a2);
i32 argz_replace(u8** a0, u32* a1, u8* a2, u8* a3, u32* a4);
void argz_stringify(u8* a0, u32 a1, i32 a2);
u8* asctime(tm* a0);
u8* asctime_r(tm* a0, u8* a1);
i32 asiprintf(u8** a0, u8* a1, ...);
u8* asniprintf(u8* a0, u32* a1, u8* a2, ...);
u8* asnprintf(u8* a0, u32* a1, u8* a2, ...);
i32 asprintf(u8** a0, u8* a1, ...);
i32 at_quick_exit(void** a0);
i32 atexit(void** a0);
double atof(u8* a0);
float atoff(u8* a0);
i32 atoi(u8* a0);
i32 atol(u8* a0);
i32 atoll(u8* a0);
i32 bcmp(void* a0, void* a1, u32 a2);
void bcopy(void* a0, void* a1, u32 a2);
void* bsearch(void* a0, void* a1, u32 a2, u32 a3, void** a4);
u32 btowc(i32 a0);
void bzero(void* a0, u32 a1);
void* calloc(u32 a0, u32 a1);
void cfree(void* a0);
void clearerr(__sFILE* a0);
void clearerr_unlocked(__sFILE* a0);
u32 clock(void);
i32 close(i32 a0);
double copysign(double a0, double a1);
float copysignf(float a0, float a1);
u8* ctime(i32* a0);
u8* ctime_r(i32* a0, u8* a1);
double difftime(i32 a0, i32 a1);
i32 diprintf(i32 a0, u8* a1, ...);
div_t div(i32 a0, i32 a1);
i32 dprintf(i32 a0, u8* a1, ...);
double drand48(void);
__locale_t* duplocale(__locale_t* a0);
u8* ecvt(double a0, i32 a1, i32* a2, i32* a3);
u8* ecvtbuf(double a0, i32 a1, i32* a2, i32* a3, u8* a4);
u8* ecvtf(float a0, i32 a1, i32* a2, i32* a3);
i32 envz_add(u8** a0, u32* a1, u8* a2, u8* a3);
u8* envz_entry(u8* a0, u32 a1, u8* a2);
u8* envz_get(u8* a0, u32 a1, u8* a2);
i32 envz_merge(u8** a0, u32* a1, u8* a2, u32 a3, i32 a4);
void envz_remove(u8** a0, u32* a1, u8* a2);
void envz_strip(u8** a0, u32* a1);
double erand48(u16* a0);
void exit(i32 a0);
void explicit_bzero(void* a0, u32 a1);
i32 fclose(__sFILE* a0);
i32 fcloseall(void);
i32 fcntl(i32 a0, i32 a1, i32 a2);
u8* fcvt(double a0, i32 a1, i32* a2, i32* a3);
u8* fcvtbuf(double a0, i32 a1, i32* a2, i32* a3, u8* a4);
u8* fcvtf(float a0, i32 a1, i32* a2, i32* a3);
__sFILE* fdopen(i32 a0, u8* a1);
i32 feof(__sFILE* a0);
i32 feof_unlocked(__sFILE* a0);
i32 ferror(__sFILE* a0);
i32 ferror_unlocked(__sFILE* a0);
i32 fflush(__sFILE* a0);
i32 fflush_unlocked(__sFILE* a0);
i32 ffs(i32 a0);
i32 ffsl(i32 a0);
i32 ffsll(i32 a0);
i32 fgetc(__sFILE* a0);
i32 fgetc_unlocked(__sFILE* a0);
i32 fgetpos(__sFILE* a0, i32* a1);
u8* fgets(u8* a0, i32 a1, __sFILE* a2);
u8* fgets_unlocked(u8* a0, i32 a1, __sFILE* a2);
u32 fgetwc(__sFILE* a0);
u32 fgetwc_unlocked(__sFILE* a0);
u32* fgetws(u32* a0, i32 a1, __sFILE* a2);
u32* fgetws_unlocked(u32* a0, i32 a1, __sFILE* a2);
i32 fileno(__sFILE* a0);
i32 fileno_unlocked(__sFILE* a0);
i32 finite(double a0);
i32 finitef(float a0);
i32 fiprintf(__sFILE* a0, u8* a1, ...);
i32 fiscanf(__sFILE* a0, u8* a1, ...);
i32 fls(i32 a0);
i32 flsl(i32 a0);
i32 flsll(i32 a0);
__sFILE* fmemopen(void* a0, u32 a1, u8* a2);
__sFILE* fopen(u8* a0, u8* a1);
__sFILE* fopencookie(void* a0, u8* a1, cookie_io_functions_t a2);
i32 fork(void);
i32 fprintf(__sFILE* a0, u8* a1, ...);
i32 fpurge(__sFILE* a0);
i32 fputc(i32 a0, __sFILE* a1);
i32 fputc_unlocked(i32 a0, __sFILE* a1);
i32 fputs(u8* a0, __sFILE* a1);
i32 fputs_unlocked(u8* a0, __sFILE* a1);
u32 fputwc(u32 a0, __sFILE* a1);
u32 fputwc_unlocked(u32 a0, __sFILE* a1);
i32 fputws(u32* a0, __sFILE* a1);
i32 fputws_unlocked(u32* a0, __sFILE* a1);
u32 fread(void* a0, u32 a1, u32 a2, __sFILE* a3);
u32 fread_unlocked(void* a0, u32 a1, u32 a2, __sFILE* a3);
void free(void* a0);
void freelocale(__locale_t* a0);
__sFILE* freopen(u8* a0, u8* a1, __sFILE* a2);
double frexp(double a0, i32* a1);
float frexpf(float a0, i32* a1);
double frexpl(double a0, i32* a1);
i32 fscanf(__sFILE* a0, u8* a1, ...);
i32 fseek(__sFILE* a0, i32 a1, i32 a2);
i32 fseeko(__sFILE* a0, i32 a1, i32 a2);
i32 fsetpos(__sFILE* a0, i32* a1);
i32 fstat(i32 a0, stat* a1);
i32 ftell(__sFILE* a0);
i32 ftello(__sFILE* a0);
__sFILE* funopen(void* a0, void** a1, void** a2, void** a3, void** a4);
i32 fwide(__sFILE* a0, i32 a1);
i32 fwprintf(__sFILE* a0, u32* a1, ...);
u32 fwrite(void* a0, u32 a1, u32 a2, __sFILE* a3);
u32 fwrite_unlocked(void* a0, u32 a1, u32 a2, __sFILE* a3);
i32 fwscanf(__sFILE* a0, u32* a1, ...);
u8* gcvt(double a0, i32 a1, u8* a2);
u8* gcvtf(float a0, i32 a1, u8* a2);
i32 getc(__sFILE* a0);
i32 getc_unlocked(__sFILE* a0);
i32 getchar(void);
i32 getchar_unlocked(void);
i32 getentropy(void* a0, u32 a1);
u8* getenv(u8* a0);
i32 getopt(i32 a0, u8** a1, u8* a2);
i32 getopt_long(i32 a0, u8** a1, u8* a2, option* a3, i32* a4);
i32 getopt_long_only(i32 a0, u8** a1, u8* a2, option* a3, i32* a4);
i32 getpid(void);
u8* gets(u8* a0);
i32 getsubopt(u8** a0, u8** a1, u8** a2);
i32 gettimeofday(timeval* a0, void* a1);
i32 getw(__sFILE* a0);
u32 getwc(__sFILE* a0);
u32 getwc_unlocked(__sFILE* a0);
u32 getwchar(void);
u32 getwchar_unlocked(void);
tm* gmtime(i32* a0);
tm* gmtime_r(i32* a0, tm* a1);
i32 hcreate(u32 a0);
i32 hcreate_r(u32 a0, hsearch_data* a1);
i32 hdestroy(htab* a0);
void hdestroy_r(hsearch_data* a0);
i32 imaxabs(i32 a0);
imaxdiv_t imaxdiv(i32 a0, i32 a1);
u8* index(u8* a0, i32 a1);
i32 iprintf(u8* a0, ...);
i32 isalnum(i32 a0);
i32 isalnum_l(i32 a0, __locale_t* a1);
i32 isalpha(i32 a0);
i32 isalpha_l(i32 a0, __locale_t* a1);
i32 isascii(i32 a0);
i32 isascii_l(i32 a0, __locale_t* a1);
i32 isatty(i32 a0);
i32 isblank(i32 a0);
i32 isblank_l(i32 a0, __locale_t* a1);
i32 iscanf(u8* a0, ...);
i32 iscntrl(i32 a0);
i32 iscntrl_l(i32 a0, __locale_t* a1);
i32 isdigit(i32 a0);
i32 isdigit_l(i32 a0, __locale_t* a1);
i32 isgraph(i32 a0);
i32 isgraph_l(i32 a0, __locale_t* a1);
i32 isinf(double a0);
i32 isinff(float a0);
i32 islower(i32 a0);
i32 islower_l(i32 a0, __locale_t* a1);
i32 isnan(double a0);
i32 isnanf(float a0);
i32 isprint(i32 a0);
i32 isprint_l(i32 a0, __locale_t* a1);
i32 ispunct(i32 a0);
i32 ispunct_l(i32 a0, __locale_t* a1);
i32 isspace(i32 a0);
i32 isspace_l(i32 a0, __locale_t* a1);
i32 isupper(i32 a0);
i32 isupper_l(i32 a0, __locale_t* a1);
i32 iswalnum(u32 a0);
i32 iswalnum_l(u32 a0, __locale_t* a1);
i32 iswalpha(u32 a0);
i32 iswalpha_l(u32 a0, __locale_t* a1);
i32 iswblank(u32 a0);
i32 iswblank_l(u32 a0, __locale_t* a1);
i32 iswcntrl(u32 a0);
i32 iswcntrl_l(u32 a0, __locale_t* a1);
i32 iswctype(u32 a0, i32 a1);
i32 iswctype_l(u32 a0, i32 a1, __locale_t* a2);
i32 iswdigit(u32 a0);
i32 iswdigit_l(u32 a0, __locale_t* a1);
i32 iswgraph(u32 a0);
i32 iswgraph_l(u32 a0, __locale_t* a1);
i32 iswlower(u32 a0);
i32 iswlower_l(u32 a0, __locale_t* a1);
i32 iswprint(u32 a0);
i32 iswprint_l(u32 a0, __locale_t* a1);
i32 iswpunct(u32 a0);
i32 iswpunct_l(u32 a0, __locale_t* a1);
i32 iswspace(u32 a0);
i32 iswspace_l(u32 a0, __locale_t* a1);
i32 iswupper(u32 a0);
i32 iswupper_l(u32 a0, __locale_t* a1);
i32 iswxdigit(u32 a0);
i32 iswxdigit_l(u32 a0, __locale_t* a1);
i32 isxdigit(i32 a0);
i32 isxdigit_l(i32 a0, __locale_t* a1);
u8* itoa(i32 a0, u8* a1, i32 a2);
i32 jrand48(u16* a0);
u8* l64a(i32 a0);
i32 labs(i32 a0);
void lcong48(u16* a0);
double ldexp(double a0, i32 a1);
float ldexpf(float a0, i32 a1);
ldiv_t ldiv(i32 a0, i32 a1);
i32 link(u8* a0, u8* a1);
i32 llabs(i32 a0);
lldiv_t lldiv(i32 a0, i32 a1);
lconv* localeconv(void);
tm* localtime(i32* a0);
tm* localtime_r(i32* a0, tm* a1);
i32 lrand48(void);
i32 lseek(i32 a0, i32 a1, i32 a2);
mallinfo mallinfo(void);
void* malloc(u32 a0);
void malloc_stats(void);
i32 malloc_trim(u32 a0);
u32 malloc_usable_size(void* a0);
i32 mallopt(i32 a0, i32 a1);
i32 mblen(u8* a0, u32 a1);
u32 mbrlen(u8* a0, u32 a1, _mbstate_t* a2);
u32 mbrtowc(u32* a0, u8* a1, u32 a2, _mbstate_t* a3);
i32 mbsinit(_mbstate_t* a0);
u32 mbsnrtowcs(u32* a0, u8** a1, u32 a2, u32 a3, _mbstate_t* a4);
u32 mbsrtowcs(u32* a0, u8** a1, u32 a2, _mbstate_t* a3);
u32 mbstowcs(u32* a0, u8* a1, u32 a2);
i32 mbtowc(u32* a0, u8* a1, u32 a2);
void* memalign(u32 a0, u32 a1);
void* memccpy(void* a0, void* a1, i32 a2, u32 a3);
void memchr(void);
i32 memcmp(void* a0, void* a1, u32 a2);
void memcpy(void);
void* memmem(void* a0, u32 a1, void* a2, u32 a3);
void* memmove(void* a0, void* a1, u32 a2);
void* mempcpy(void* a0, void* a1, u32 a2);
void* memrchr(void* a0, i32 a1, u32 a2);
void* memset(void* a0, i32 a1, u32 a2);
u8* mkdtemp(u8* a0);
i32 mkostemp(u8* a0, i32 a1);
i32 mkostemps(u8* a0, i32 a1, i32 a2);
i32 mkstemp(u8* a0);
i32 mkstemps(u8* a0, i32 a1);
u8* mktemp(u8* a0);
i32 mktime(tm* a0);
double modf(double a0, double* a1);
float modff(float a0, float* a1);
i32 mrand48(void);
void mstats(u8* a0);
double nan(u8* a0);
float nanf(u8* a0);
__locale_t* newlocale(i32 a0, u8* a1, __locale_t* a2);
u8* nl_langinfo(i32 a0);
u8* nl_langinfo_l(i32 a0, __locale_t* a1);
i32 nrand48(u16* a0);
i32 on_exit(void** a0, void* a1);
i32 open(u8* a0, i32 a1, ...);
__sFILE* open_memstream(u8** a0, u32* a1);
__sFILE* open_wmemstream(u32** a0, u32* a1);
void perror(u8* a0);
i32 printf(u8* a0, ...);
void psignal(i32 a0, u8* a1);
i32 putc(i32 a0, __sFILE* a1);
i32 putc_unlocked(i32 a0, __sFILE* a1);
i32 putchar(i32 a0);
i32 putchar_unlocked(i32 a0);
i32 putenv(u8* a0);
i32 puts(u8* a0);
i32 putw(i32 a0, __sFILE* a1);
u32 putwc(u32 a0, __sFILE* a1);
u32 putwc_unlocked(u32 a0, __sFILE* a1);
u32 putwchar(u32 a0);
u32 putwchar_unlocked(u32 a0);
void* pvalloc(u32 a0);
void qsort(void* a0, u32 a1, u32 a2, void** a3);
void qsort_r(void* a0, u32 a1, u32 a2, void** a3, void* a4);
void quick_exit(i32 a0);
i32 raise(i32 a0);
i32 rand(void);
i32 rand_r(u32* a0);
i32 random(void);
void* rawmemchr(void* a0, i32 a1);
void* realloc(void* a0, u32 a1);
void* reallocarray(void* a0, u32 a1, u32 a2);
void* reallocf(void* a0, u32 a1);
i32 remove(u8* a0);
i32 rename(u8* a0, u8* a1);
void rewind(__sFILE* a0);
u8* rindex(u8* a0, i32 a1);
i32 rpmatch(u8* a0);
void* sbrk(i32 a0);
double scalbn(double a0, i32 a1);
float scalbnf(float a0, i32 a1);
i32 scanf(u8* a0, ...);
u16* seed48(u16* a0);
void setbuf(__sFILE* a0, u8* a1);
void setbuffer(__sFILE* a0, u8* a1, i32 a2);
i32 setenv(u8* a0, u8* a1, i32 a2);
i32 setlinebuf(__sFILE* a0);
u8* setlocale(i32 a0, u8* a1);
i32 setvbuf(__sFILE* a0, u8* a1, i32 a2, u32 a3);
i32 sig2str(i32 a0, u8* a1);
i32 siprintf(u8* a0, u8* a1, ...);
i32 siscanf(u8* a0, u8* a1, ...);
i32 sniprintf(u8* a0, u32 a1, u8* a2, ...);
i32 snprintf(u8* a0, u32 a1, u8* a2, ...);
i32 sprintf(u8* a0, u8* a1, ...);
void srand(u32 a0);
void srand48(i32 a0);
void srandom(u32 a0);
i32 sscanf(u8* a0, u8* a1, ...);
i32 stat(u8* a0, stat* a1);
u8* stpcpy(u8* a0, u8* a1);
u8* stpncpy(u8* a0, u8* a1, u32 a2);
i32 str2sig(u8* a0, i32* a1);
i32 strcasecmp(u8* a0, u8* a1);
i32 strcasecmp_l(u8* a0, u8* a1, __locale_t* a2);
u8* strcasestr(u8* a0, u8* a1);
u8* strcat(u8* a0, u8* a1);
u8* strchr(u8* a0, i32 a1);
u8* strchrnul(u8* a0, i32 a1);
void strcmp(void);
i32 strcoll(u8* a0, u8* a1);
i32 strcoll_l(u8* a0, u8* a1, __locale_t* a2);
u8* strcpy(u8* a0, u8* a1);
u32 strcspn(u8* a0, u8* a1);
u8* strdup(u8* a0);
u8* strerror(i32 a0);
u8* strerror_l(i32 a0, __locale_t* a1);
u8* strerror_r(i32 a0, u8* a1, u32 a2);
u32 strftime(u8* a0, u32 a1, u8* a2, tm* a3);
u32 strftime_l(u8* a0, u32 a1, u8* a2, tm* a3, __locale_t* a4);
u32 strlcat(u8* a0, u8* a1, u32 a2);
u32 strlcpy(u8* a0, u8* a1, u32 a2);
void strlen(void);
u8* strlwr(u8* a0);
i32 strncasecmp(u8* a0, u8* a1, u32 a2);
i32 strncasecmp_l(u8* a0, u8* a1, u32 a2, __locale_t* a3);
u8* strncat(u8* a0, u8* a1, u32 a2);
i32 strncmp(u8* a0, u8* a1, u32 a2);
u8* strncpy(u8* a0, u8* a1, u32 a2);
u8* strndup(u8* a0, u32 a1);
u32 strnlen(u8* a0, u32 a1);
u8* strnstr(u8* a0, u8* a1, u32 a2);
u8* strpbrk(u8* a0, u8* a1);
u8* strptime(u8* a0, u8* a1, tm* a2);
u8* strptime_l(u8* a0, u8* a1, tm* a2, __locale_t* a3);
u8* strrchr(u8* a0, i32 a1);
u8* strsep(u8** a0, u8* a1);
u8* strsignal(i32 a0);
u32 strspn(u8* a0, u8* a1);
u8* strstr(u8* a0, u8* a1);
double strtod(u8* a0, u8** a1);
double strtod_l(u8* a0, u8** a1, __locale_t* a2);
float strtof(u8* a0, u8** a1);
float strtof_l(u8* a0, u8** a1, __locale_t* a2);
i32 strtoimax(u8* a0, u8** a1, i32 a2);
i32 strtoimax_l(u8* a0, u8** a1, i32 a2, __locale_t* a3);
u8* strtok(u8* a0, u8* a1);
u8* strtok_r(u8* a0, u8* a1, u8** a2);
i32 strtol(u8* a0, u8** a1, i32 a2);
i32 strtol_l(u8* a0, u8** a1, i32 a2, __locale_t* a3);
double strtold(u8* a0, u8** a1);
double strtold_l(u8* a0, u8** a1, __locale_t* a2);
i32 strtoll(u8* a0, u8** a1, i32 a2);
i32 strtoll_l(u8* a0, u8** a1, i32 a2, __locale_t* a3);
u32 strtoul(u8* a0, u8** a1, i32 a2);
u32 strtoul_l(u8* a0, u8** a1, i32 a2, __locale_t* a3);
u32 strtoull(u8* a0, u8** a1, i32 a2);
u32 strtoull_l(u8* a0, u8** a1, i32 a2, __locale_t* a3);
u32 strtoumax(u8* a0, u8** a1, i32 a2);
u32 strtoumax_l(u8* a0, u8** a1, i32 a2, __locale_t* a3);
u8* strupr(u8* a0);
i32 strverscmp(u8* a0, u8* a1);
u32 strxfrm(u8* a0, u8* a1, u32 a2);
u32 strxfrm_l(u8* a0, u8* a1, u32 a2, __locale_t* a3);
void swab(void* a0, void* a1, i32 a2);
i32 swprintf(u32* a0, u32 a1, u32* a2, ...);
i32 swscanf(u32* a0, u32* a1, ...);
i32 sysconf(i32 a0);
i32 system(u8* a0);
void* tdelete(void* a0, void** a1, void** a2);
void tdestroy(void* a0, void** a1);
u8* tempnam(u8* a0, u8* a1);
void* tfind(void* a0, void** a1, void** a2);
i32 time(i32* a0);
u32 times(tms* a0);
i32 timingsafe_bcmp(void* a0, void* a1, u32 a2);
i32 timingsafe_memcmp(void* a0, void* a1, u32 a2);
__sFILE* tmpfile(void);
u8* tmpnam(u8* a0);
i32 toascii(i32 a0);
i32 toascii_l(i32 a0, __locale_t* a1);
i32 tolower(i32 a0);
i32 tolower_l(i32 a0, __locale_t* a1);
i32 toupper(i32 a0);
i32 toupper_l(i32 a0, __locale_t* a1);
u32 towctrans(u32 a0, i32 a1);
u32 towctrans_l(u32 a0, i32 a1, __locale_t* a2);
u32 towlower(u32 a0);
u32 towlower_l(u32 a0, __locale_t* a1);
u32 towupper(u32 a0);
u32 towupper_l(u32 a0, __locale_t* a1);
void* tsearch(void* a0, void** a1, void** a2);
void twalk(void* a0, void** a1);
void tzset(void);
i32 ungetc(i32 a0, __sFILE* a1);
u32 ungetwc(u32 a0, __sFILE* a1);
i32 unlink(u8* a0);
i32 unsetenv(u8* a0);
__locale_t* uselocale(__locale_t* a0);
u8* utoa(u32 a0, u8* a1, i32 a2);
void* valloc(u32 a0);
i32 vasiprintf(u8** a0, u8* a1, __va_list a2);
u8* vasniprintf(u8* a0, u32* a1, u8* a2, __va_list a3);
u8* vasnprintf(u8* a0, u32* a1, u8* a2, __va_list a3);
i32 vasprintf(u8** a0, u8* a1, __va_list a2);
i32 vdiprintf(i32 a0, u8* a1, __va_list a2);
i32 vdprintf(i32 a0, u8* a1, __va_list a2);
i32 vfiprintf(__sFILE* a0, u8* a1, __va_list a2);
i32 vfiscanf(__sFILE* a0, u8* a1, __va_list a2);
i32 vfiwprintf(__sFILE* a0, u32* a1, __va_list a2);
i32 vfiwscanf(__sFILE* a0, u32* a1, __va_list a2);
i32 vfprintf(__sFILE* a0, u8* a1, __va_list a2);
i32 vfscanf(__sFILE* a0, u8* a1, __va_list a2);
i32 vfwprintf(__sFILE* a0, u32* a1, __va_list a2);
i32 vfwscanf(__sFILE* a0, u32* a1, __va_list a2);
i32 viprintf(u8* a0, __va_list a1);
i32 viscanf(u8* a0, __va_list a1);
i32 vprintf(u8* a0, __va_list a1);
i32 vscanf(u8* a0, __va_list a1);
i32 vsiprintf(u8* a0, u8* a1, __va_list a2);
i32 vsiscanf(u8* a0, u8* a1, __va_list a2);
i32 vsniprintf(u8* a0, u32 a1, u8* a2, __va_list a3);
i32 vsnprintf(u8* a0, u32 a1, u8* a2, __va_list a3);
i32 vsprintf(u8* a0, u8* a1, __va_list a2);
i32 vsscanf(u8* a0, u8* a1, __va_list a2);
i32 vswprintf(u32* a0, u32 a1, u32* a2, __va_list a3);
i32 vswscanf(u32* a0, u32* a1, __va_list a2);
i32 vwprintf(u32* a0, __va_list a1);
i32 vwscanf(u32* a0, __va_list a1);
i32 wait(i32* a0);
u32* wcpcpy(u32* a0, u32* a1);
u32* wcpncpy(u32* a0, u32* a1, u32 a2);
u32 wcrtomb(u8* a0, u32 a1, _mbstate_t* a2);
i32 wcscasecmp(u32* a0, u32* a1);
i32 wcscasecmp_l(u32* a0, u32* a1, __locale_t* a2);
u32* wcscat(u32* a0, u32* a1);
u32* wcschr(u32* a0, u32 a1);
i32 wcscmp(u32* a0, u32* a1);
i32 wcscoll(u32* a0, u32* a1);
i32 wcscoll_l(u32* a0, u32* a1, __locale_t* a2);
u32* wcscpy(u32* a0, u32* a1);
u32 wcscspn(u32* a0, u32* a1);
u32* wcsdup(u32* a0);
u32 wcsftime(u32* a0, u32 a1, u32* a2, tm* a3);
u32 wcsftime_l(u32* a0, u32 a1, u32* a2, tm* a3, __locale_t* a4);
u32 wcslcat(u32* a0, u32* a1, u32 a2);
u32 wcslcpy(u32* a0, u32* a1, u32 a2);
u32 wcslen(u32* a0);
i32 wcsncasecmp(u32* a0, u32* a1, u32 a2);
i32 wcsncasecmp_l(u32* a0, u32* a1, u32 a2, __locale_t* a3);
u32* wcsncat(u32* a0, u32* a1, u32 a2);
i32 wcsncmp(u32* a0, u32* a1, u32 a2);
u32* wcsncpy(u32* a0, u32* a1, u32 a2);
u32 wcsnlen(u32* a0, u32 a1);
u32 wcsnrtombs(u8* a0, u32** a1, u32 a2, u32 a3, _mbstate_t* a4);
u32* wcspbrk(u32* a0, u32* a1);
u32* wcsrchr(u32* a0, u32 a1);
u32 wcsrtombs(u8* a0, u32** a1, u32 a2, _mbstate_t* a3);
u32 wcsspn(u32* a0, u32* a1);
u32* wcsstr(u32* a0, u32* a1);
double wcstod(u32* a0, u32** a1);
double wcstod_l(u32* a0, u32** a1, __locale_t* a2);
float wcstof(u32* a0, u32** a1);
float wcstof_l(u32* a0, u32** a1, __locale_t* a2);
i32 wcstoimax(u32* a0, u32** a1, i32 a2);
i32 wcstoimax_l(u32* a0, u32** a1, i32 a2, __locale_t* a3);
u32* wcstok(u32* a0, u32* a1, u32** a2);
i32 wcstol(u32* a0, u32** a1, i32 a2);
i32 wcstol_l(u32* a0, u32** a1, i32 a2, __locale_t* a3);
double wcstold(u32* a0, u32** a1);
double wcstold_l(u32* a0, u32** a1, __locale_t* a2);
i32 wcstoll(u32* a0, u32** a1, i32 a2);
i32 wcstoll_l(u32* a0, u32** a1, i32 a2, __locale_t* a3);
u32 wcstombs(u8* a0, u32* a1, u32 a2);
u32 wcstoul(u32* a0, u32** a1, i32 a2);
u32 wcstoul_l(u32* a0, u32** a1, i32 a2, __locale_t* a3);
u32 wcstoull(u32* a0, u32** a1, i32 a2);
u32 wcstoull_l(u32* a0, u32** a1, i32 a2, __locale_t* a3);
u32 wcstoumax(u32* a0, u32** a1, i32 a2);
u32 wcstoumax_l(u32* a0, u32** a1, i32 a2, __locale_t* a3);
i32 wcswidth(u32* a0, u32 a1);
u32 wcsxfrm(u32* a0, u32* a1, u32 a2);
u32 wcsxfrm_l(u32* a0, u32* a1, u32 a2, __locale_t* a3);
i32 wctob(u32 a0);
i32 wctomb(u8* a0, u32 a1);
i32 wctrans(u8* a0);
i32 wctrans_l(u8* a0, __locale_t* a1);
i32 wctype(u8* a0);
i32 wctype_l(u8* a0, __locale_t* a1);
i32 wcwidth(u32 a0);
u32* wmemchr(u32* a0, u32 a1, u32 a2);
i32 wmemcmp(u32* a0, u32* a1, u32 a2);
u32* wmemcpy(u32* a0, u32* a1, u32 a2);
u32* wmemmove(u32* a0, u32* a1, u32 a2);
u32* wmempcpy(u32* a0, u32* a1, u32 a2);
u32* wmemset(u32* a0, u32 a1, u32 a2);
i32 wprintf(u32* a0, ...);
i32 write(i32 a0, void* a1, u32 a2);
i32 wscanf(u32* a0, ...);
