#import <Foundation/Foundation.h>
#import "XTWasmWriter.h"

// xcc-ln-wasm32 — WAT → <out>.wasm + <out>.js, in-house.
//
// The "link" step of the wasm32 pipeline: assembles the WAT text that
// xcc-cg-wasm32 emitted (XTWasmWriter — no wat2wasm, no external tools; an
// in-house failure is a HARD error) and writes the universal JS loader
// beside the module, so `xcc -A wasm32 -o prog prog.xc` yields prog.wasm +
// prog.js, runnable with `node prog.js` and loadable in a browser as either
// a classic script or a module (the .wasm resolves beside the page).
//
// Library mode (W2, `xcc --emit-lib -A wasm32`): --emit-lib writes
// <out>.wasm (with the `.xtc.iface` interface JSON embedded as a wasm
// CUSTOM section, the same role the ELF section plays) plus the
// <out>.json placement sidecar {dataSize, tableSize} the loader reads —
// and NO .js/.html (a library is instantiated by its app's loader).
// App mode gains --dep <name> (repeatable): the imported library names are
// baked into <out>.js, and its loader instantiates lib<name>.wasm beside
// the app with the app's memory/table/runtime wired through.
//
// Usage:
//   xcc-ln-wasm32 <input.wat> <output-base> [-q] [--emit-lib]
//                 [--iface <json-path>] [--dep <name>]...

#ifndef XTC_VERSION
#define XTC_VERSION "0.0"
#endif

// The loader: one file that runs under Node (CommonJS), in a browser, and —
// when the page opts in with globalThis.xccConfig = { runLoop: "worker" } —
// as its own Web Worker (the same file detects which role it is playing).
// The host surface is the `env` package; anything the module imports that
// the loader doesn't provide fails AT INSTANTIATION with a message naming
// the import (the Proxy), not at call time deep inside the program.
//
// Worker mode is the compiler-side half of the Xtg web run loop
// (Rocks/doc/XG-WEB-BACKEND.md sec 3, wasm-target.md sec 12.2 option 3):
// the MAIN thread owns the DOM/canvas and pushes normalized events into a
// JS-allocated SharedArrayBuffer ring; the WORKER instantiates the module
// (its own linear memory stays NON-shared — no atomic-ARC forcing, sec 3.1)
// and blocks on Atomics.wait. Needs COOP/COEP headers to get a SAB.
//
// Ring contract (i32 indices into the SAB):
//   [0] writeSeq   — main-thread-owned, monotonic
//   [1] readSeq    — worker-owned; write-read >= capacity drops the OLDEST
//   [2] replySeq / [3] replyValue — the blocking worker->main request lane
//   [8...] event slots, 8 x i32 each: [type,a,b,c,d,e,f,g]
// Default main-side listeners push: 1 mousedown 2 mouseup 3 mousemove
// (x,y,button) 4 keydown 5 keyup (keyCode). The page can push anything via
// globalThis.xccPushEvent(type,a,...). Worker-side env primitives:
//   _xt_ring_wait(timeoutMs) -> 0 timed-out / 1 event pending
//   _xt_ring_read(ptr)       -> event type or -1; copies 8 i32s to ptr
//   _xt_req_block(kind,a,b,c)-> i32 reply from globalThis.xccOnRequest
static NSString* loaderJS(NSString* baseName, NSArray<NSString*>* deps)
    {
    NSString* t = @""
                   "// xcc runtime library.\n"
                   "//\n"
                   "// Copyright (C) 2026 ThrudTheBarbarian@compile-xc.org\n"
                   "//\n"
                   "// This file is part of the xcc runtime library: the code that is combined\n"
                   "// with a program when xcc compiles it. It is free software; you can\n"
                   "// redistribute it and/or modify it under the terms of the GNU General Public\n"
                   "// License as published by the Free Software Foundation, either version 3 of\n"
                   "// the License, or (at your option) any later version.\n"
                   "//\n"
                   "// Under Section 7 of GPL version 3, you are granted additional permissions\n"
                   "// described in the GCC Runtime Library Exception, version 3.1, as published\n"
                   "// by the Free Software Foundation -- see COPYING.RUNTIME in this directory's\n"
                   "// parent.\n"
                   "//\n"
                   "// The effect of that exception is the point: a program compiled by xcc\n"
                   "// contains parts of this file, and the exception is what leaves that program\n"
                   "// under whatever licence its author chooses, including a proprietary one.\n"
                   "//\n"
                   "// This file is distributed in the hope that it will be useful, but WITHOUT\n"
                   "// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n"
                   "// FITNESS FOR A PARTICULAR PURPOSE.\n"
                   "\n"
                   "// Generated by xcc-ln-wasm32 — loader for __BASE__.wasm (Node.js + browser + Worker).\n"
                   "// Node:    node __BASE__.js\n"
                   "// Browser: <script src=\"__BASE__.js\"></script> (with __BASE__.wasm beside the page)\n"
                   "// Worker run loop: set globalThis.xccConfig = { runLoop: \"worker\" } BEFORE the\n"
                   "// script tag (needs COOP/COEP headers for SharedArrayBuffer).\n"
                   "(async () => {\n"
                   "  const isNode = typeof process !== \"undefined\" && !!(process.versions && process.versions.node);\n"
                   "  const isWorker = !isNode && typeof importScripts === \"function\";\n"
                   "  const cfg = (!isNode && !isWorker && globalThis.xccConfig) || {};\n"
                   "  let XCC = null;   // this module's handle; see where it is assigned\n"
                   "\n"
                   "  // ── Worker-mode MAIN-THREAD side: own the DOM, feed the ring, spawn. ──\n"
                   "  if (cfg.runLoop === \"worker\") {\n"
                   "    if (typeof SharedArrayBuffer === \"undefined\")\n"
                   "      throw new Error(\"xcc: the worker run loop needs SharedArrayBuffer — serve with COOP/COEP headers\");\n"
                   "    const ring = new SharedArrayBuffer(cfg.ringBytes || 4096);\n"
                   "    const i32 = new Int32Array(ring);\n"
                   "    const cap = (i32.length - 8) >> 3;\n"
                   "    const push = (t, a=0, b=0, c=0, d=0, e=0, f=0, g=0) => {\n"
                   "      const w = Atomics.load(i32, 0);\n"
                   "      if (w - Atomics.load(i32, 1) >= cap) Atomics.add(i32, 1, 1); // drop oldest\n"
                   "      const s = 8 + (w % cap) * 8;\n"
                   "      i32[s]=t|0; i32[s+1]=a|0; i32[s+2]=b|0; i32[s+3]=c|0;\n"
                   "      i32[s+4]=d|0; i32[s+5]=e|0; i32[s+6]=f|0; i32[s+7]=g|0;\n"
                   "      Atomics.store(i32, 0, w + 1);\n"
                   "      Atomics.notify(i32, 0);\n"
                   "    };\n"
                   "    globalThis.xccPushEvent = push;\n"
                   "    const canvas = cfg.canvas ? document.querySelector(cfg.canvas)\n"
                   "                              : document.getElementById(\"xcc-canvas\");\n"
                   "    if (canvas) {\n"
                   "      canvas.addEventListener(\"mousedown\", (e) => push(1, e.offsetX, e.offsetY, e.button));\n"
                   "      canvas.addEventListener(\"mouseup\",   (e) => push(2, e.offsetX, e.offsetY, e.button));\n"
                   "      canvas.addEventListener(\"mousemove\", (e) => push(3, e.offsetX, e.offsetY));\n"
                   "      window.addEventListener(\"keydown\",   (e) => push(4, e.keyCode));\n"
                   "      window.addEventListener(\"keyup\",     (e) => push(5, e.keyCode));\n"
                   "    }\n"
                   "    const off = (canvas && canvas.transferControlToOffscreen)\n"
                   "              ? canvas.transferControlToOffscreen() : null;\n"
                   "    const url = (document.currentScript && document.currentScript.src) || \"__BASE__.js\";\n"
                   "    const worker = new Worker(url);\n"
                   "    worker.onmessage = (m) => {\n"
                   "      const d = m.data || {};\n"
                   "      if (d.xccOut !== undefined) { (globalThis.xccOut || console.log)(d.xccOut); return; }\n"
                   "      if (d.xccReq !== undefined) {\n"
                   "        const v = (globalThis.xccOnRequest || (() => 0))(d.xccReq) | 0;\n"
                   "        Atomics.store(i32, 3, v);\n"
                   "        Atomics.store(i32, 2, d.xccReq.seq | 0);\n"
                   "        Atomics.notify(i32, 2);\n"
                   "        return;\n"
                   "      }\n"
                   "      if (d.xccExit) console.warn(`main() returned ${d.xccExit}`);\n"
                   "    };\n"
                   "    worker.postMessage({ ring, canvas: off,\n"
                   "                         workerScript: cfg.workerScript || null },\n"
                   "                       off ? [off] : []);\n"
                   "    return;\n"
                   "  }\n"
                   "\n"
                   "  // ── Node, plain browser, or the WORKER side: instantiate and run. ──\n"
                   "  let ringI32 = null, reqSeq = 0;\n"
                   "  if (isWorker) {\n"
                   "    const boot = await new Promise((res) => { self.onmessage = (m) => res(m.data); });\n"
                   "    if (boot.ring) ringI32 = new Int32Array(boot.ring);\n"
                   "    globalThis.xccCanvas = boot.canvas || null;   // OffscreenCanvas for the driver\n"
                   "    if (boot.workerScript) importScripts(boot.workerScript); // may set xccImports HERE\n"
                   "  }\n"
                   "  let line = [];\n"
                   "  const flush = () => {\n"
                   "    if (!line.length) return;\n"
                   "    const text = String.fromCharCode(...line); line = [];\n"
                   "    if (isNode) process.stdout.write(text);\n"
                   "    else if (isWorker) self.postMessage({ xccOut: text.replace(/\\n$/, \"\") });\n"
                   "    else (globalThis.xccOut || console.log)(text.replace(/\\n$/, \"\"));\n"
                   "  };\n"
                   "  let rndState = 0x2545F491;\n"
                   "  const rnd32 = () => {\n"
                   "    rndState ^= rndState << 13; rndState >>>= 0;\n"
                   "    rndState ^= rndState >> 17;\n"
                   "    rndState ^= rndState << 5;  rndState >>>= 0;\n"
                   "    return rndState;\n"
                   "  };\n"
                   "  const putc = (c) => { line.push(c & 0xFF); if ((c & 0xFF) === 10 || line.length > 4096) flush(); };\n"
                   "  const emit = (s) => { for (const ch of s) putc(ch.charCodeAt(0)); };\n"
                   "  // Read a NUL-terminated string out of linear memory; copy one in.\n"
                   "  const mem8 = () => new Uint8Array(XCC.memory.buffer);\n"
                   "  const cdec = new TextDecoder();\n"
                   "  const cstr = (p) => { const m = mem8(); let e = p; while (m[e]) e++; return cdec.decode(m.subarray(p, e)); };\n"
                   "  const argvCache = new Map();\n"
                   "  const argvPtr = (i, s) => {\n"
                   "    const key = i < 0 ? -1 : i;\n"
                   "    if (argvCache.has(key)) return argvCache.get(key);\n"
                   "    const bytes = new TextEncoder().encode(s);\n"
                   "    const p = XCC.instance.exports._xt_browser_alloc(bytes.length + 1);\n"
                   "    mem8().set(bytes, p); mem8()[p + bytes.length] = 0;   // re-derive: alloc may grow memory\n"
                   "    argvCache.set(key, p);\n"
                   "    return p;\n"
                   "  };\n"
                   "  const base = {\n"
                   "    putc, _putc: putc,\n"
                   "    // Fixed-point float/double formatters, matching the corpus C stub's\n"
                   "    // printf(\"%.*f\"): float defaults to 6 decimal places, double to 10.\n"
                   "    _xtc_pf:  (f) => emit(f.toFixed(6)),\n"
                   "    _xtc_pd:  (d) => emit(d.toFixed(10)),\n"
                   "    // Explicit `%.Nf` precision TRUNCATES (the reference _xtc_truncf\n"
                   "    // formats at N+1 digits and drops the last char); N=0 keeps the\n"
                   "    // 6 / 10 digit defaults.\n"
                   "    _xtc_pfp: (f, p) => emit(p ? f.toFixed(p + 1).slice(0, -1) : f.toFixed(6)),\n"
                   "    _xtc_pdp: (d, p) => emit(p ? d.toFixed(p + 1).slice(0, -1) : d.toFixed(10)),\n"
                   "    time_ms: () => Date.now() & 0x7FFFFFFF,\n"
                   "    getpid: () => 1,\n"
                   "    // Files.xc / Process.xc host surface (CI task #81). Node has a\n"
                   "    // filesystem and a command line; a page has neither, so there every\n"
                   "    // file call answers the way a missing file does and argc is 1.\n"
                   "    // Handles are node's fds. Modes are fopen's, with the `b` dropped.\n"
                   "    // `_xt_argv` hands the module a pointer, so the string is copied INTO\n"
                   "    // linear memory through the module's own `_xt_browser_alloc` (every\n"
                   "    // wasm32 build exports it — Platform.xc) once per index and kept.\n"
                   "    _xt_file_open: (p, m) => {\n"
                   "      if (!isNode) return -1;\n"
                   "      try { return require(\"fs\").openSync(cstr(p), cstr(m).replace(/b/g, \"\")); } catch (e) { return -1; }\n"
                   "    },\n"
                   "    _xt_file_read: (fd, buf, n) => {\n"
                   "      if (!isNode) return -1;\n"
                   "      try { return require(\"fs\").readSync(fd, mem8(), buf, n, null); } catch (e) { return -1; }\n"
                   "    },\n"
                   "    _xt_file_write: (fd, buf, n) => {\n"
                   "      if (!isNode) return -1;\n"
                   "      try { return require(\"fs\").writeSync(fd, mem8(), buf, n); } catch (e) { return -1; }\n"
                   "    },\n"
                   "    _xt_file_close: (fd) => { if (isNode) { try { require(\"fs\").closeSync(fd); } catch (e) {} } },\n"
                   "    _xt_file_size: (p) => {\n"
                   "      if (!isNode) return -1;\n"
                   "      try { return require(\"fs\").statSync(cstr(p)).size; } catch (e) { return -1; }\n"
                   "    },\n"
                   "    _xt_file_exists: (p) => (isNode && require(\"fs\").existsSync(cstr(p))) ? 1 : 0,\n"
                   "    _xt_file_exists_exact: (p) => {\n"
                   "      // The host filesystem may be case-insensitive (macOS); ask for the\n"
                   "      // real spelling and compare the last component.\n"
                   "      if (!isNode) return 0;\n"
                   "      try {\n"
                   "        const fs = require(\"fs\"), path = require(\"path\"), q = cstr(p);\n"
                   "        const real = fs.realpathSync.native(q);\n"
                   "        return path.basename(real) === path.basename(q) ? 1 : 0;\n"
                   "      } catch (e) { return 0; }\n"
                   "    },\n"
                   "    _xt_file_chmod_exec: (p) => {\n"
                   "      if (!isNode) return -1;\n"
                   "      try { require(\"fs\").chmodSync(cstr(p), 0o755); return 0; } catch (e) { return -1; }\n"
                   "    },\n"
                   "    _xt_mkdir: (p) => {\n"
                   "      if (!isNode) return -1;\n"
                   "      try { require(\"fs\").mkdirSync(cstr(p)); return 0; } catch (e) { return -1; }\n"
                   "    },\n"
                   "    _xt_argc: () => isNode ? Math.max(1, process.argv.length - 1) : 1,\n"
                   "    _xt_argv: (i) => {\n"
                   "      const args = isNode ? process.argv.slice(1) : [];\n"
                   "      const s = (i >= 0 && i < args.length) ? args[i] : \"\";\n"
                   "      return argvPtr(i, s);\n"
                   "    },\n"
                   "    _xt_exit: (c) => { if (isNode) process.exit(c | 0); throw new Error(`Process.exit(${c})`); },\n"
                   "    // Math.rand host surface: a seeded xorshift32 — deterministic per\n"
                   "    // seed; the rand fixtures assert BOUNDS, not a reference sequence.\n"
                   "    _xt_srand: (s) => { rndState = (s >>> 0) || 1; },\n"
                   "    _xt_rand_u32: rnd32,\n"
                   "    _xt_rand_f: () => Math.fround(0.5 + (rnd32() / 0x100000000) * 0.5),\n"
                   "    _xt_rand_d: () => 0.5 + (rnd32() / 0x100000000) * 0.5,\n"
                   "    // Math.xc's host surface (float variants round through fround).\n"
                   "    _xm_sqrt: Math.sqrt,  _xm_sqrtf: (x) => Math.fround(Math.sqrt(x)),\n"
                   "    _xm_sin:  Math.sin,   _xm_sinf:  (x) => Math.fround(Math.sin(x)),\n"
                   "    _xm_cos:  Math.cos,   _xm_cosf:  (x) => Math.fround(Math.cos(x)),\n"
                   "    _xm_tan:  Math.tan,   _xm_tanf:  (x) => Math.fround(Math.tan(x)),\n"
                   "    _xm_atan: Math.atan,  _xm_atanf: (x) => Math.fround(Math.atan(x)),\n"
                   "    _xm_atan2: Math.atan2, _xm_atan2f: (y, x) => Math.fround(Math.atan2(y, x)),\n"
                   "    _xm_exp:  Math.exp,   _xm_expf:  (x) => Math.fround(Math.exp(x)),\n"
                   "    _xm_log:  Math.log,   _xm_logf:  (x) => Math.fround(Math.log(x)),\n"
                   "    _xm_pow:  Math.pow,   _xm_powf:  (x, y) => Math.fround(Math.pow(x, y)),\n"
                   "    _xm_floor: Math.floor, _xm_floorf: (x) => Math.fround(Math.floor(x)),\n"
                   "    _xm_ceil: Math.ceil,  _xm_ceilf: (x) => Math.fround(Math.ceil(x)),\n"
                   "    _xm_fabs: Math.abs,   _xm_fabsf: (x) => Math.fround(Math.abs(x)),\n"
                   "    _xm_fmod: (a, b) => a % b, _xm_fmodf: (a, b) => Math.fround(a % b),\n"
                   // clock_gettime(clk, ts) writes { i64 sec; i64 nsec; } at ts.
                   // Whatever clock id is asked for, this answers with a
                   // MONOTONIC reading: performance.now() is monotonic, which is
                   // what every caller of this actually wants, and wasm has no
                   // wall clock to offer anyway. The DataView is re-derived per
                   // call because memory.grow detaches the buffer.
                   //
                   // Without it any program that timed itself — every benchmark
                   // in benchmark/src — died on `missing host import
                   // env.clock_gettime` before printing a line.
                   "    clock_gettime: (clk, ts) => {\n"
                   "      const ns = BigInt(Math.round(performance.now() * 1e6));\n"
                   "      const dv = new DataView(XCC.memory.buffer);\n"
                   "      dv.setBigInt64(ts, ns / 1000000000n, true);\n"
                   "      dv.setBigInt64(ts + 8, ns % 1000000000n, true);\n"
                   "      return 0;\n"
                   "    },\n"
                   "  };\n"
                   "  if (isWorker && ringI32) {\n"
                   "    const ri = ringI32;\n"
                   "    // The blocking primitives (XG-WEB-BACKEND sec 3): the worker CAN block.\n"
                   "    // memory views are re-derived per call — memory.grow detaches buffers.\n"
                   "    Object.assign(base, {\n"
                   "      _xt_ring_wait: (timeoutMs) => {\n"
                   "        const w = Atomics.load(ri, 0);\n"
                   "        if (Atomics.load(ri, 1) < w) return 1;\n"
                   "        const r = Atomics.wait(ri, 0, w, timeoutMs < 0 ? Infinity : timeoutMs);\n"
                   "        return r === \"timed-out\" ? 0 : 1;\n"
                   "      },\n"
                   "      _xt_ring_read: (ptr) => {\n"
                   "        const r = Atomics.load(ri, 1);\n"
                   "        if (r >= Atomics.load(ri, 0)) return -1;\n"
                   "        const cap = (ri.length - 8) >> 3;\n"
                   "        const s = 8 + (r % cap) * 8;\n"
                   "        const m = new Int32Array(XCC.memory.buffer);\n"
                   "        for (let k = 0; k < 8; k++) m[(ptr >> 2) + k] = ri[s + k];\n"
                   "        Atomics.store(ri, 1, r + 1);\n"
                   "        return ri[s];\n"
                   "      },\n"
                   "      _xt_req_block: (kind, a, b, c) => {\n"
                   "        const seq = ++reqSeq;\n"
                   "        self.postMessage({ xccReq: { seq, kind, a, b, c } });\n"
                   "        for (;;) {\n"
                   "          const cur = Atomics.load(ri, 2);\n"
                   "          if (cur === seq) break;\n"
                   "          Atomics.wait(ri, 2, cur);\n"
                   "        }\n"
                   "        return Atomics.load(ri, 3);\n"
                   "      },\n"
                   "    });\n"
                   "  }\n"
                   "  // Host-supplied packages (#package <name>): set globalThis.xccImports =\n"
                   "  // { pkgName: { fn: ... }, env: { overrides } } BEFORE this script runs\n"
                   "  // (in worker mode: inside cfg.workerScript, which runs in the WORKER).\n"
                   "  const extra = globalThis.xccImports || {};\n"
                   "  if (extra.env) Object.assign(base, extra.env);\n"
                   "  const env = new Proxy(base, {\n"
                   "    get(t, name) {\n"
                   "      if (name in t) return t[name];\n"
                   "      return () => { throw new Error(`missing host import env.${String(name)}`); };\n"
                   "    },\n"
                   "  });\n"
                   "  const imports = Object.assign({}, extra, { env });\n"
                   "  // The `browser` package (wasm32 Platform.xc, #package browser): default\n"
                   "  // implementations live IN the loader so an app ships with no side files;\n"
                   "  // any key the page sets in xccImports.browser overrides one of these. An\n"
                   "  // imports entry for a package the module never asks for is ignored, so\n"
                   "  // this costs a Browser-free module nothing.\n"
                   "  const bdec = new TextDecoder();\n"
                   "  const bmem = () => new Uint8Array(XCC.memory.buffer);\n"
                   "  const bstr = (p, n) => bdec.decode(bmem().subarray(p, p + n));\n"
                   "  imports.browser = Object.assign({\n"
                   "    _b_fetch(tok, url, n) {\n"
                   "      const u = bstr(url, n);            // decode BEFORE awaiting: the\n"
                   "      Promise.resolve()                  //   pointer dies when this returns\n"
                   "        .then(() => fetch(u))\n"
                   "        .then(r => r.arrayBuffer().then(buf => {\n"
                   "          const b = new Uint8Array(buf);\n"
                   "          const e = XCC.instance.exports;\n"
                   "          const p = e._xt_browser_alloc(b.length);\n"
                   "          bmem().set(b, p);              // re-derive: alloc may grow memory\n"
                   "          e._xt_browser_dispatch(tok, r.status, p, b.length);\n"
                   "        }))\n"
                   "        .catch(() => XCC.instance.exports._xt_browser_dispatch(tok, 0, 0, 0));\n"
                   "    },\n"
                   "    _b_inject(sp, sn, hp, hn) {\n"
                   "      if (typeof document === \"undefined\") return;\n"
                   "      const el = document.querySelector(bstr(sp, sn));\n"
                   "      if (el) el.innerHTML = bstr(hp, hn);\n"
                   "    },\n"
                   "    _b_push_state(p, n) {\n"
                   "      if (typeof history !== \"undefined\") history.pushState(null, \"\", bstr(p, n));\n"
                   "    },\n"
                   "    _b_log(lvl, p, n) {\n"
                   "      (lvl >= 2 ? console.error : lvl === 1 ? console.warn : console.log)(bstr(p, n));\n"
                   "    },\n"
                   "  }, extra.browser || {});\n"
                   "  // Imported xtc libraries (W2): each dep package is satisfied by LAZY\n"
                   "  // thunks so the app can instantiate FIRST (it owns memory + table); the\n"
                   "  // thunks resolve once the dep's exports exist.\n"
                   "  const deps = __DEPS__;\n"
                   "  const depExports = {};\n"
                   "  for (const d of deps)\n"
                   "    imports[d] = new Proxy({}, { get: (t, n) => (...a) => depExports[d][n](...a) });\n"
                   "  let bytes;\n"
                   "  if (isNode) {\n"
                   "    const path = require(\"path\").join(__dirname, \"__BASE__.wasm\");\n"
                   "    bytes = require(\"fs\").readFileSync(path);\n"
                   "  } else {\n"
                   "    bytes = await (await fetch(\"__BASE__.wasm\")).arrayBuffer();\n"
                   "  }\n"
                   "  const { instance } = await WebAssembly.instantiate(bytes, imports);\n"
                   "  // A per-module handle. This used to be ONLY `globalThis.xcc`, so loading a\n"
                   "  // second independent module clobbered the first — and the clobber was not\n"
                   "  // cosmetic: the callbacks below read `XCC.memory`, so module A's\n"
                   "  // browser dispatch would start reading module B's memory. That is the\n"
                   "  // shared-NOTHING model (a group loading its own module on demand), where two\n"
                   "  // unrelated modules must coexist in one realm.\n"
                   "  //\n"
                   "  // `globalThis.xcc` still points at the most recent module, because callers\n"
                   "  // rely on it; `globalThis.xccModules[<base>]` is the stable per-module one,\n"
                   "  // and everything INSIDE this loader now closes over XCC instead.\n"
                   "  XCC = { instance, memory: instance.exports.memory };\n"
                   "  globalThis.xcc = XCC;\n"
                   "  (globalThis.xccModules || (globalThis.xccModules = {}))[\"__BASE__\"] = XCC;\n"
                   "  // Instantiate each dep: data goes BETWEEN the app's static data and the\n"
                   "  // 1 MiB heap base (so the ARC \"is this a heap object\" compare stays a\n"
                   "  // single guard — library statics must NOT read as heap objects), funcs\n"
                   "  // go at the grown end of the app's one table, env is thunked to the\n"
                   "  // app's exported runtime, and the dep's reloc-apply patches the vtable\n"
                   "  // words a data segment cannot compute. __stack_low is raised past the\n"
                   "  // last dep so the shadow stack cannot grow down into library data.\n"
                   "  let dcur = deps.length ? instance.exports.__data_end.value : 0;\n"
                   "  for (const d of deps) {\n"
                   "    let dbytes, dmeta;\n"
                   "    if (isNode) {\n"
                   "      const p = require(\"path\"), f = require(\"fs\");\n"
                   "      dbytes = f.readFileSync(p.join(__dirname, `lib${d}.wasm`));\n"
                   "      dmeta = JSON.parse(f.readFileSync(p.join(__dirname, `lib${d}.json`), \"utf8\"));\n"
                   "    } else {\n"
                   "      dbytes = await (await fetch(`lib${d}.wasm`)).arrayBuffer();\n"
                   "      dmeta = await (await fetch(`lib${d}.json`)).json();\n"
                   "    }\n"
                   "    const dbase = (dcur + 15) & ~15;\n"
                   "    if (dbase < 0x10000) throw new Error(`xcc: lib${d} data base ${dbase} below 0x10000 (classid guard)`);\n"
                   "    if (dbase + dmeta.dataSize > 0x100000)\n"
                   "      throw new Error(`xcc: lib${d} data (${dmeta.dataSize} bytes at ${dbase}) overflows the pre-heap region`);\n"
                   "    const dtable = instance.exports.__indirect_function_table;\n"
                   "    const dtbase = dmeta.tableSize ? dtable.grow(dmeta.tableSize) : dtable.length;\n"
                   "    const denvBase = {\n"
                   "      memory: instance.exports.memory,\n"
                   "      __indirect_function_table: dtable,\n"
                   "      __memory_base: dbase, __table_base: dtbase,\n"
                   "      __sp: instance.exports.__sp, __stack_low: instance.exports.__stack_low,\n"
                   "    };\n"
                   "    const denv = new Proxy(denvBase, {\n"
                   "      get(t, n) {\n"
                   "        if (n in t) return t[n];\n"
                   "        if (n in instance.exports) return instance.exports[n];\n"
                   "        if (n in base) return base[n];\n"
                   "        return () => { throw new Error(`missing library import env.${String(n)} (lib${d})`); };\n"
                   "      },\n"
                   "    });\n"
                   "    // Start from the APP's import object, not just `extra`. The loader builds\n"
                   "    // the `browser` package itself (default implementations ship inside it), and\n"
                   "    // passing only the host-supplied `xccImports` meant a library using\n"
                   "    // `#package browser` died at instantiation with \"Import #8 browser: module\n"
                   "    // is not an object or function\" until the caller re-supplied it by hand.\n"
                   "    // env is the one entry that must be the DEP's thunked version.\n"
                   "    // A library that subclasses another library's class imports that\n"
                   "    // library's methods (into its own table slots) and __addr_ getters (for\n"
                   "    // its vtable words). A dep already instantiated is passed as its real\n"
                   "    // exports, so those table slots hold its wasm functions directly.\n"
                   "    const dimp = Object.assign({}, imports, { env: denv });\n"
                   "    for (const o of deps) if (o !== d) dimp[o] = depExports[o] || imports[o];\n"
                   "    const di = await WebAssembly.instantiate(dbytes, dimp);\n"
                   "    depExports[d] = di.instance.exports;\n"
                   "    dcur = dbase + dmeta.dataSize;\n"
                   "  }\n"
                   "  // Relocate after every dep exists: a library's vtable words can name\n"
                   "  // another library's data, read through that library's __addr_ getter.\n"
                   "  for (const d of deps) depExports[d].__wasm_apply_relocs();\n"
                   "  if (deps.length) instance.exports.__stack_low.value = (dcur + 15) & ~15;\n"
                   "  const rc = instance.exports.main();\n"
                   "  flush();\n"
                   "  if (isNode) process.exitCode = rc | 0;\n"
                   "  else if (isWorker) self.postMessage({ xccExit: rc | 0 });\n"
                   "  else if (rc) console.warn(`main() returned ${rc}`);\n"
                   "})().catch((e) => {\n"
                   "  const isNode = typeof process !== \"undefined\" && !!(process.versions && process.versions.node);\n"
                   "  if (isNode) { console.error(e); process.exitCode = 70; } else { console.error(e); }\n"
                   "});\n";
    t = [t stringByReplacingOccurrencesOfString:@"__BASE__" withString:baseName];
    NSMutableArray<NSString*>* quoted = [NSMutableArray array];
    for (NSString* d in deps)
        [quoted addObject:[NSString stringWithFormat:@"\"%@\"", d]];
    return [t stringByReplacingOccurrencesOfString:@"__DEPS__"
                                        withString:[NSString stringWithFormat:@"[%@]",
                                                                              [quoted componentsJoinedByString:@", "]]];
    }

// A starter page: stdout into a <pre> via the loader's xccOut hook. Written
// only when absent — customised pages must survive a rebuild (the .js and
// .wasm regenerate every build; the page is the user's).
static NSString* starterHTML(NSString* baseName)
    {
    return [NSString stringWithFormat:
                         @"<!doctype html>\n"
                         @"<!-- Generated once by xcc-ln-wasm32 for %@.wasm — edit freely; a rebuild\n"
                         @"     rewrites %@.js and %@.wasm but leaves this page alone. -->\n"
                         @"<html lang=\"en\">\n"
                         @"<head>\n"
                         @"<meta charset=\"utf-8\">\n"
                         @"<title>%@</title>\n"
                         @"<style>\n"
                         @"  body { background: #1e1e1e; color: #d4d4d4; font: 14px/1.5 ui-monospace, monospace;\n"
                         @"         margin: 2rem; }\n"
                         @"  pre  { white-space: pre-wrap; }\n"
                         @"</style>\n"
                         @"</head>\n"
                         @"<body>\n"
                         @"<h1>%@</h1>\n"
                         @"<pre id=\"out\"></pre>\n"
                         @"<script>\n"
                         @"  const out = document.getElementById(\"out\");\n"
                         @"  globalThis.xccOut = (line) => { out.textContent += line + \"\\n\"; };\n"
                         @"  // Host packages (#package): define before the loader runs, e.g.\n"
                         @"  // globalThis.xccImports = { js: { jsPing: (v) => console.log(v) } };\n"
                         @"</script>\n"
                         @"<script src=\"%@.js\"></script>\n"
                         @"</body>\n"
                         @"</html>\n",
                         baseName, baseName, baseName, baseName, baseName, baseName];
    }

int main(int argc, const char* argv[])
    {
    @autoreleasepool
        {
        NSString *inPath = nil, *outBase = nil, *ifacePath = nil;
        NSMutableArray<NSString*>* deps = [NSMutableArray array];
        BOOL quiet = NO, emitLib = NO;
        for (int i = 1; i < argc; i++)
            {
            NSString* a = @(argv[i]);
            if ([a isEqualToString:@"-v"] || [a isEqualToString:@"--version"])
                {
                printf("xcc-ln-wasm32 %s\n", XTC_VERSION);
                return 0;
                }
            else if ([a isEqualToString:@"-q"])
                {
                quiet = YES;
                }
            else if ([a isEqualToString:@"--emit-lib"])
                {
                emitLib = YES;
                }
            else if ([a isEqualToString:@"--iface"] && i + 1 < argc)
                {
                ifacePath = @(argv[++i]);
                }
            else if ([a isEqualToString:@"--dep"] && i + 1 < argc)
                {
                [deps addObject:@(argv[++i])];
                }
            else if (!inPath)
                {
                inPath = a;
                }
            else if (!outBase)
                {
                outBase = a;
                }
            else
                {
                fprintf(stderr, "xcc-ln-wasm32: unexpected argument '%s'\n", argv[i]);
                return 1;
                }
            }
        if (!inPath || !outBase)
            {
            fprintf(stderr, "Usage: xcc-ln-wasm32 <input.wat> <output-base> [-q] "
                            "[--emit-lib] [--iface <json>] [--dep <name>]...\n");
            return 1;
            }
        NSString* wat = [NSString stringWithContentsOfFile:inPath
                                                  encoding:NSUTF8StringEncoding
                                                     error:NULL];
        if (!wat)
            {
            fprintf(stderr, "xcc-ln-wasm32: cannot read '%s'\n", inPath.UTF8String);
            return 1;
            }
        NSError* err = nil;
        NSData* module = [XTWasmWriter wasmModuleFromWat:wat error:&err];
        if (!module)
            {
            fprintf(stderr, "xcc-ln-wasm32: error: %s\n",
                    err ? err.localizedDescription.UTF8String : "(no detail)");
            return 1;
            }

        // `-o prog` → prog.wasm + prog.js; `-o prog.wasm` keeps the base.
        NSString* base = [outBase.pathExtension isEqualToString:@"wasm"]
                             ? outBase.stringByDeletingPathExtension
                             : outBase;
        NSString* wasmPath = [base stringByAppendingPathExtension:@"wasm"];

        if (emitLib)
            {
            // ── Library build (W2). ──────────────────────────────────────
            // 1. Embed the interface JSON as a `xtc.iface` CUSTOM section —
            //    the same role the ELF `.xtc.iface` section plays, so
            //    `#import <X>` reads the types from the binary itself.
            NSMutableData* libModule = [module mutableCopy];
            NSString* ifaceJson = ifacePath
                                      ? [NSString stringWithContentsOfFile:ifacePath
                                                                  encoding:NSUTF8StringEncoding
                                                                     error:NULL]
                                      : nil;
            if (ifaceJson.length)
                {
                NSData* name = [@"xtc.iface" dataUsingEncoding:NSUTF8StringEncoding];
                NSData* json = [ifaceJson dataUsingEncoding:NSUTF8StringEncoding];
                NSMutableData* payload = [NSMutableData data];
                uint8_t nl = (uint8_t)name.length;
                [payload appendBytes:&nl length:1]; // name len < 128: 1-byte LEB
                [payload appendData:name];
                [payload appendData:json];
                uint8_t zero = 0;
                [libModule appendBytes:&zero length:1]; // section id 0 (custom)
                uint64_t v = payload.length;            // section size, LEB128
                do
                    {
                    uint8_t b = v & 0x7F;
                    v >>= 7;
                    if (v)
                        b |= 0x80;
                    [libModule appendBytes:&b length:1];
                    } while (v);
                [libModule appendData:payload];
                }
            if (![libModule writeToFile:wasmPath atomically:YES])
                {
                fprintf(stderr, "xcc-ln-wasm32: cannot write '%s'\n", wasmPath.UTF8String);
                return 1;
                }
            // 2. The placement sidecar: the backend put the two numbers on
            //    the `;; xtc-lib data=<N> table=<M>` marker line.
            uint64_t dataSize = 0, tableSize = 0;
            for (NSString* ln in [wat componentsSeparatedByString:@"\n"])
                {
                NSString* tr = [ln stringByTrimmingCharactersInSet:
                                       [NSCharacterSet whitespaceCharacterSet]];
                if (![tr hasPrefix:@";; xtc-lib "])
                    continue;
                NSScanner* sc = [NSScanner scannerWithString:tr];
                [sc scanUpToString:@"data=" intoString:NULL];
                [sc scanString:@"data=" intoString:NULL];
                long long d = 0, t = 0; // scanLongLong: — GNUstep's
                                        // NSScanner has no
                                        // scanUnsignedLongLong:
                [sc scanLongLong:&d];
                [sc scanUpToString:@"table=" intoString:NULL];
                [sc scanString:@"table=" intoString:NULL];
                [sc scanLongLong:&t];
                dataSize = d;
                tableSize = t;
                break;
                }
            NSString* jsonPath = [base stringByAppendingPathExtension:@"json"];
            NSString* sidecar = [NSString stringWithFormat:
                                              @"{\"dataSize\": %llu, \"tableSize\": %llu}\n",
                                              (unsigned long long)dataSize, (unsigned long long)tableSize];
            if (![sidecar writeToFile:jsonPath
                           atomically:YES
                             encoding:NSUTF8StringEncoding
                                error:NULL])
                {
                fprintf(stderr, "xcc-ln-wasm32: cannot write '%s'\n", jsonPath.UTF8String);
                return 1;
                }
            if (!quiet)
                fprintf(stderr, "xcc-ln-wasm32: %s (%lu bytes, library) + %s\n",
                        wasmPath.UTF8String, (unsigned long)libModule.length,
                        jsonPath.UTF8String);
            return 0;
            }

        NSString* jsPath = [base stringByAppendingPathExtension:@"js"];
        if (![module writeToFile:wasmPath atomically:YES])
            {
            fprintf(stderr, "xcc-ln-wasm32: cannot write '%s'\n", wasmPath.UTF8String);
            return 1;
            }
        NSString* js = loaderJS(base.lastPathComponent, deps);
        if (![js writeToFile:jsPath
                  atomically:YES
                    encoding:NSUTF8StringEncoding
                       error:NULL])
            {
            fprintf(stderr, "xcc-ln-wasm32: cannot write '%s'\n", jsPath.UTF8String);
            return 1;
            }
        NSString* htmlPath = [base stringByAppendingPathExtension:@"html"];
        BOOL wroteHTML = NO;
        if (![[NSFileManager defaultManager] fileExistsAtPath:htmlPath])
            {
            wroteHTML = [starterHTML(base.lastPathComponent)
                writeToFile:htmlPath
                 atomically:YES
                   encoding:NSUTF8StringEncoding
                      error:NULL];
            }
        if (!quiet)
            fprintf(stderr, "xcc-ln-wasm32: %s (%lu bytes) + %s%s\n",
                    wasmPath.UTF8String, (unsigned long)module.length,
                    jsPath.UTF8String, wroteHTML ? " + starter .html" : "");
        return 0;
        }
    }
