;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/arc_struct_return.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module arc_struct_return

    ; === method Stdio.init ===
_init:
LDA $57
STA scrMode
    ; scrMode
    LDA _scrMode
    ; =
    STA _mode
    ; (expr stmt discarded)
    STA $81
LDA $58
STA sbase
LDA $59
STA sbase+1
    ; sbase
    LDA _sbase
    LDX _sbase+1
    ; =
    STA _screenBase
    STX _screenBase+1
    ; (expr stmt discarded)
    ; sbase
    LDA _sbase
    LDX _sbase+1
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; mode
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA _mode
    CMP $84
    ; -> else
    BNE L0
    ; const 40
    LDA #$28
    STA $84
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 1
    LDA #$01
    STA $80
    ; =
    STA _canPrint
    ; (expr stmt discarded)
    ; -> end
    JMP L1
L0:
    ; mode
    ; const 4
    LDA #$04
    STA $84
    ; cmp
    LDA _mode
    CMP $84
    ; -> else
    BCS L2
    ; const 20
    LDA #$14
    STA $80
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 1
    LDA #$01
    STA $82
    ; =
    STA _canPrint
    ; (expr stmt discarded)
    ; -> end
    JMP L3
L2:
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _canPrint
    ; (expr stmt discarded)
L3:
L1:
LDA $02BF
STA botlin
    ; botlin
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _botlin
    CMP $82
    ; -> else
    BNE L4
    ; const 24
    LDA #$18
    STA $81
    ; =
    STA _rows
    ; (expr stmt discarded)
    ; -> end
    JMP L5
L4:
    ; botlin
    LDA _botlin
    ; =
    STA _rows
    ; (expr stmt discarded)
L5:
    ; === end Stdio.init ===
    ; === method Stdio.scroll ===
_scroll:
    ; var sb =
    ; screenBase
    LDA _screenBase
    LDX _screenBase+1
    STA _sb
    STX _sb+1
    ; var numCols =
    ; cols
    LDA _cols
    LDX #$00
    STA _numCols
    STX _numCols+1
    ; var size =
    ; numCols
    STX $83
    LDX _numCols+1
    ; rows
    ; const 1
    LDA #$01
    STA $85
    ; binop
    SEC
    LDA _rows
    SBC $85
    STA $80
    ; binop
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDA $80
    STA $B4
    LDA $81
    STA $B5
    LDA _numCols
    JSR _mul16
    STA $84
    STX $85
    STA _size
    STX _size+1
    ; var src =
    ; sb
    ; numCols
    LDA _numCols
    LDX _numCols+1
    ; binop
    CLC
    ADC _sb
    STA $84
    LDA _sb+1
    ADC _numCols+1
    STA $85
    LDA $84
    LDX $85
    STA _src
    STX _src+1
    ; var dst =
    ; sb
    LDA _sb
    LDX _sb+1
    STA _dst
    STX _dst+1
    ; var szLo =
    ; size
    LDX _size+1
    ; const 255
    LDA #$FF
    STA $85
    ; binop
    LDX #$00
    STX $86
    AND _size
    STA $87
    LDA _size+1
    AND $86
    STA $88
    LDA $87
    LDX $88
    STA _szLo
    ; var szHi =
    ; size
    LDX _size+1
    ; const 8
    LDA #$08
    STA $84
    ; binop
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDX $84
    BEQ _L1
_L0:
    LSR $B1
    ROR $B0
    DEX
    BNE _L0
_L1:
    LDA $B0
    STA $80
    LDA $B1
    STA $81
    LDA $B0
    LDX $B1
    STA _szHi
    ; var cLo =
    ; numCols
    LDA _numCols
    LDX _numCols+1
    STA _cLo
; Set up indirect pointers in $B0 / $B1 ( dst ) and
; $B2 / $B3 ( src ) .The runtime - params region $B0 - $BF
; is reserved against ZP - allocated locals so dst /
; src can ' t collide with anything sema gave us .
LDA dst
STA $B0
LDA dst+1
STA $B1
LDA src
STA $B2
LDA src+1
STA $B3
; -- -- Move ( rows - 1 ) * cols bytes up by one row -- --
; Outer loop uses szHi pages ( 256 - byte chunks ) plus
; an inner DEX / BNE for szLo trailing bytes .Y is
; the byte offset within the current page .After
; each page wrap we INC the high bytes of both
; pointers and walk the next 256 bytes .
LDX szHi
BEQ _stdio_scroll_tail
LDY #$00
_stdio_scroll_page :
LDA ( $B2 ),Y
STA ( $B0 ),Y
INY
BNE _stdio_scroll_page
INC $B1
INC $B3
DEX
BNE _stdio_scroll_page
_stdio_scroll_tail :
LDX szLo
BEQ _stdio_scroll_clear
LDY #$00
_stdio_scroll_tail_lp :
LDA ( $B2 ),Y
STA ( $B0 ),Y
INY
DEX
BNE _stdio_scroll_tail_lp
; Advance the dst pointer past the bytes we just
; copied so the bottom - row clear lands at the
; right address .Y holds the byte offset we ended
; on ; CLC+ADC walks $B0 forward .
CLC
TYA
ADC $B0
STA $B0
BCC _stdio_scroll_clear
INC $B1
_stdio_scroll_clear :
; Clear numCols bytes ( cLo,always less than 256 )
; at the dst ' s current location to give the new
; bottom row a blank screen - code - 0 fill .
LDX cLo
BEQ _stdio_scroll_done
LDY #$00
LDA #$00
_stdio_scroll_clear_lp :
STA ( $B0 ),Y
INY
DEX
BNE _stdio_scroll_clear_lp
_stdio_scroll_done :
    ; === end Stdio.scroll ===
    ; === method Stdio.putChar ===
_putChar:
    ; canPrint
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE L0
    ; return
    RTS
L0:
    ; var endPtr =
    ; screenBase
    LDX _screenBase+1
    ; cols
    ; rows
    LDA _rows
    ; binop
    LDA $83
    STA $B0
    LDA $84
    STA $B1
    LDA $85
    STA $B4
    LDA $86
    STA $B5
    LDA _cols
    LDX #$00
    STX $84
    JSR _mul16
    STA $87
    STX $88
    ; binop
    CLC
    ADC _screenBase
    STA $83
    LDA _screenBase+1
    ADC $88
    STA $84
    LDA $83
    LDX $84
    STA _endPtr
    STX _endPtr+1
    ; var ptr =
    ; screenPtr
    LDA _screenPtr
    LDX _screenPtr+1
    STA _ptr
    STX _ptr+1
    ; ptr
    ; endPtr
    LDX _endPtr+1
    ; cmp
    LDA _ptr+1
    CMP _endPtr+1
    BNE _L2
    LDA _ptr
    CMP _endPtr
_L2:
    ; -> else
    BCC L2
    ; __SAVE__::13
    ; call
    JSR _scroll
    ; __RESTORE__
    ; (expr stmt discarded)
    ; endPtr
    LDX _endPtr+1
    ; cols
    LDA _cols
    ; binop
    SEC
    LDX #$00
    STX $86
    LDA _endPtr
    SBC _cols
    STA $87
    LDA _endPtr+1
    SBC _cols+1
    STA $88
    LDA $87
    LDX $88
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; screenPtr
    LDA _screenPtr
    LDX _screenPtr+1
    ; =
    STA _ptr
    STX _ptr+1
    ; (expr stmt discarded)
L2:
    ; ch
    ; const 10
    LDA #$0A
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> else
    BNE L4
    ; ptr
    ; screenBase
    LDA _screenBase
    LDX _screenBase+1
    ; binop
    SEC
    LDA _ptr
    SBC _screenBase
    STA $85
    LDA _ptr+1
    SBC _screenBase+1
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _off
    STX _off+1
    ; (expr stmt discarded)
    ; off
    LDX _off+1
    ; cols
    LDA _cols
    ; binop
    LDA $81
    STA $B0
    LDA $82
    STA $B1
    LDA $83
    STA $B4
    LDA $84
    STA $B5
    LDA _off
    JSR _mod16
    STA $85
    STX $86
    ; =
    STA _rem
    STX _rem+1
    ; (expr stmt discarded)
    ; ptr
    LDX _ptr+1
    ; cols
    ; rem
    LDA _rem
    LDX _rem+1
    ; binop
    LDA _cols
    LDX #$00
    STX $84
    SEC
    SBC _rem
    STA $87
    LDA _cols+1
    SBC _rem+1
    STA $88
    LDA $87
    LDX $88
    ; binop
    CLC
    ADC _ptr
    STA $83
    LDA _ptr+1
    ADC $88
    STA $84
    LDA $83
    LDX $84
    ; =
    STA _ptr
    STX _ptr+1
    ; (expr stmt discarded)
    ; ptr
    LDA _ptr
    LDX _ptr+1
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; return
    RTS
L4:
    ; ch
    ; const 128
    LDA #$80
    STA $84
    ; binop
    AND _ch
    STA $85
    ; =
    STA _inv
    ; (expr stmt discarded)
    ; ch
    ; const 127
    LDA #$7F
    STA $85
    ; binop
    AND _ch
    STA $84
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; ch
    ; const 32
    LDA #$20
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> else
    BCS L6
    ; ch
    ; const 64
    LDA #$40
    STA $85
    ; binop
    CLC
    ADC _ch
    STA $86
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP L7
L6:
    ; ch
    ; const 64
    LDA #$40
    STA $85
    ; cmp
    LDA _ch
    CMP $85
    ; -> else
    BCS L8
    ; ch
    ; const 32
    LDA #$20
    STA $85
    ; binop
    SEC
    LDA _ch
    SBC $85
    STA $86
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP L9
L8:
    ; ch
    ; const 96
    LDA #$60
    STA $85
    ; cmp
    LDA _ch
    CMP $85
    ; -> else
    BCS L10
    ; ch
    ; const 32
    LDA #$20
    STA $85
    ; binop
    SEC
    LDA _ch
    SBC $85
    STA $81
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP L11
L10:
    ; ch
    STA $84
    LDA _ch
    ; =
    STA _sc
    ; (expr stmt discarded)
L11:
L9:
L7:
    ; sc
    ; inv
    LDA _inv
    ; binop
    ORA _sc
    STA $83
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; screenPtr
    LDX _screenPtr+1
    ; sc
    LDA _sc
    ; =
    LDA $83
    STA $B2
    LDA _screenPtr
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
    ; screenPtr
    LDX _screenPtr+1
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _screenPtr
    STA $85
    LDA _screenPtr+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; === end Stdio.putChar ===
    ; === method Stdio.print__s ===
_print__s:
    ; canPrint
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE L0
    ; return
    RTS
L0:
    ; s
    LDA _s
    LDX _s+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _ch
    ; (expr stmt discarded)
L2:
    ; ch
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _ch
    CMP $82
    ; -> end
    BEQ L3
    ; ch
    LDA _ch
    ; __SAVE__:11:10
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; s
    LDX _s+1
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _s
    STA $85
    LDA _s+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _s
    STX _s+1
    ; (expr stmt discarded)
    ; s
    LDA _s
    LDX _s+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP L2
L3:
    ; === end Stdio.print__s ===
    ; === method Stdio.print__u16 ===
_print__u16:
    ; val
    LDX _val+1
    ; const 10
    LDA #$0A
    STA $82
    ; cmp
    LDX #$00
    STX $83
    LDA _val+1
    CMP $83
    BNE _L3
    LDA _val
    CMP $82
_L3:
    ; -> else
    BCC L0
    ; val
    LDX _val+1
    ; const 10
    LDA #$0A
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _val
    JSR _div16
    STA $85
    STX $86
    ; =
    STA _d
    STX _d+1
    ; (expr stmt discarded)
    ; d
    LDA _d
    LDX _d+1
    ; __SAVE__:9:8
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
L0:
    ; val
    LDX _val+1
    ; const 10
    LDA #$0A
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _val
    JSR _mod16
    STA $85
    STX $86
    ; =
    STA _r
    ; (expr stmt discarded)
    ; r
    ; const 48
    LDA #$30
    STA $82
    ; binop
    CLC
    ADC _r
    STA $83
    ; __SAVE__:16:14
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__u16 ===
    ; === method Stdio.print__i16 ===
_print__i16:
    ; val
    LDX _val+1
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDX #$00
    STX $83
    LDA _val+1
    CMP $83
    BNE _L4
    LDA _val
    CMP $82
_L4:
    ; -> else
    BPL L0
    ; const 45
    LDA #$2D
    STA $80
    ; __SAVE__:5:4
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; val
    LDA _val
    LDX _val+1
    ; binop
    LDA $80
    LDX #$00
    STX $81
    SEC
    SBC _val
    STA $84
    LDA $81
    SBC _val+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _val
    STX _val+1
    ; (expr stmt discarded)
L0:
    ; val
    LDA _val
    LDX _val+1
    ; __SAVE__:11:10
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__i16 ===
    ; === method Stdio.print__u32 ===
_print__u32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; cmp
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    LDX #$00
    STX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    LDA _val+3
    CMP $87
    BNE _L5
    LDA _val+2
    CMP $86
    BNE _L5
    LDA _val+1
    CMP $85
    BNE _L5
    LDA _val
    CMP $84
_L5:
    ; -> else
    BCC L0
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; u32 div
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA _val+2
    STA $B2
    LDA _val+3
    STA $B3
    LDA _val
    JSR _div32
    STA $89
    STX $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    ; =
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _d
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STX _d+1
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _d+2
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _d+3
    ; (expr stmt discarded)
    ; d
    LDA _d
    STA $80
    LDA _d+1
    STA $81
    LDA _d+2
    STA $82
    LDA _d+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; __SAVE__:9:8
    ; call
    JSR _print__u32
    ; __RESTORE__
    ; (expr stmt discarded)
L0:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; u32 mod
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA _val+2
    STA $B2
    LDA _val+3
    STA $B3
    LDA _val
    JSR _mod32
    STA $89
    STX $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    ; =
    LDA $89
    STA _r
    ; (expr stmt discarded)
    ; r
    ; const 48
    LDA #$30
    STA $82
    ; binop
    CLC
    ADC _r
    STA $83
    ; __SAVE__:16:14
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__u32 ===
    ; === method Stdio.print__i32 ===
_print__i32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    LDX #$00
    STX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    LDA _val+3
    CMP $87
    BNE _L6
    LDA _val+2
    CMP $86
    BNE _L6
    LDA _val+1
    CMP $85
    BNE _L6
    LDA _val
    CMP $84
_L6:
    ; -> else
    BPL L0
    ; const 45
    LDA #$2D
    STA $80
    ; __SAVE__:5:4
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; val
    LDA _val
    STA $84
    LDA _val+1
    STA $85
    LDA _val+2
    STA $86
    LDA _val+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    LDX #$00
    STX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    SEC
    LDA $80
    SBC _val
    STA $88
    LDA $81
    SBC _val+1
    STA $89
    LDA $82
    SBC _val+2
    STA $8A
    LDA $83
    SBC _val+3
    STA $8B
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    LDX $89
    ; =
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    STA _val
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    STX _val+1
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    STA _val+2
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    STA _val+3
    ; (expr stmt discarded)
L0:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; __SAVE__:11:10
    ; call
    JSR _print__u32
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__i32 ===
    ; === method Stdio.printHex__u8 ===
_printHex__u8:
    ; n
    ; const 10
    LDA #$0A
    STA $81
    ; cmp
    LDA _n
    CMP $81
    ; -> else
    BCS L0
    ; n
    ; const 48
    LDA #$30
    STA $81
    ; binop
    CLC
    ADC _n
    STA $86
    ; __SAVE__:6:4
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP L1
L0:
    ; n
    ; const 55
    LDA #$37
    STA $81
    ; binop
    CLC
    ADC _n
    STA $82
    ; __SAVE__:10:8
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
L1:
    ; === end Stdio.printHex__u8 ===
    ; === method Stdio.printHex__u16 ===
_printHex__u16:
    ; val
    LDX _val+1
    ; const 12
    LDA #$0C
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $82
    BEQ _L8
_L7:
    LSR $B1
    ROR $B0
    DEX
    BNE _L7
_L8:
    LDA $B0
    STA $86
    LDA $B1
    STA $87
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $88
    ; binop
    LDX #$00
    STX $89
    AND $86
    STA $8A
    LDA $87
    AND $89
    STA $8B
    LDA $8A
    LDX $8B
    ; __SAVE__:5:1
    ; call
    JSR _printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    ; const 8
    LDA #$08
    STA $88
    ; binop
    LDA $86
    STA $B0
    LDA $87
    STA $B1
    LDX $88
    BEQ _L10
_L9:
    LSR $B1
    ROR $B0
    DEX
    BNE _L9
_L10:
    LDA $B0
    STA $8A
    LDA $B1
    STA $8B
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $84
    ; binop
    LDX #$00
    STX $85
    AND $8A
    STA $86
    LDA $8B
    AND $85
    STA $87
    LDA $86
    LDX $87
    ; __SAVE__:11:7
    ; call
    JSR _printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    ; const 4
    LDA #$04
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L12
_L11:
    LSR $B1
    ROR $B0
    DEX
    BNE _L11
_L12:
    LDA $B0
    STA $80
    LDA $B1
    STA $81
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $82
    ; binop
    LDX #$00
    STX $83
    AND $80
    STA $84
    LDA $81
    AND $83
    STA $85
    LDA $84
    LDX $85
    ; __SAVE__:17:13
    ; call
    JSR _printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    ; const 15
    LDA #$0F
    STA $84
    ; binop
    LDX #$00
    STX $85
    AND _val
    STA $86
    LDA _val+1
    AND $85
    STA $87
    LDA $86
    LDX $87
    ; __SAVE__:21:19
    ; call
    JSR _printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printHex__u16 ===
    ; === method Stdio.printHex__u32 ===
_printHex__u32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 16
    LDA #$10
    STA $84
    ; u32 op
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDX $84
    BEQ _L14
_L13:
    LSR $B3
    ROR $B2
    ROR $B1
    ROR $B0
    DEX
    BNE _L13
_L14:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B2
    STA $8A
    LDA $B3
    STA $8B
    LDA $B0
    LDX $B1
    LDY $B2
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $80
    STX $81
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    LDA $88
    AND $80
    STA $8C
    LDA $89
    AND $81
    STA $8D
    LDA $8A
    AND $82
    STA $8E
    LDA $8B
    AND $83
    STA $8F
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    LDX $8D
    ; __SAVE__:6:1
    ; call
    JSR _printHex__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $86
    STX $87
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $86
    LDA $B2
    STA $88
    LDA $B3
    STA $89
    LDA _val
    AND $86
    STA $8A
    LDA _val+1
    AND $87
    STA $8B
    LDA _val+2
    AND $88
    STA $8C
    LDA _val+3
    AND $89
    STA $8D
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    LDX $8B
    ; __SAVE__:10:7
    ; call
    JSR _printHex__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printHex__u32 ===
    ; === method Stdio.print__f ===
_print__f:
    ; canPrint
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE L0
    ; return
    RTS
L0:
LDA f : STA $B0
LDA f+1 : STA $B1
LDA f+2 : STA $B2
LDA f+3 : STA $B3
LDA f+4 : STA $B4
LDA #< $04C0
STA $B5
LDY #_ivar_Stdio_fpBufPtr
STA ( __self ),Y
LDA #> $04C0
STA $B6
LDY #_ivar_Stdio_fpBufPtr+1
STA ( __self ),Y
JSR fp2Asc
    ; fpBufPtr
    LDA _fpBufPtr
    LDX _fpBufPtr+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _ch
    ; (expr stmt discarded)
L2:
    ; ch
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _ch
    CMP $82
    ; -> end
    BEQ L3
    ; ch
    LDA _ch
    ; __SAVE__:11:10
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fpBufPtr
    LDX _fpBufPtr+1
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _fpBufPtr
    STA $85
    LDA _fpBufPtr+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _fpBufPtr
    STX _fpBufPtr+1
    ; (expr stmt discarded)
    ; fpBufPtr
    LDA _fpBufPtr
    LDX _fpBufPtr+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP L2
L3:
    ; === end Stdio.print__f ===
    ; === method Stdio.setCursor ===
_setCursor:
    ; y
    LDA _y
    ; =
    LDX #$00
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; offset
    STX $81
    LDX _offset+1
    ; cols
    LDA _cols
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _offset
    JSR _mul16
    STA $84
    STX $85
    ; =
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; offset
    LDX _offset+1
    ; x
    LDA _x
    ; binop
    CLC
    LDX #$00
    STX $83
    ADC _offset
    STA $84
    LDA _offset+1
    ADC _x+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; screenBase
    ; offset
    LDA _offset
    LDX _offset+1
    ; binop
    CLC
    ADC _screenBase
    STA $84
    LDA _screenBase+1
    ADC _offset+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; === end Stdio.setCursor ===
    ; === method Stdio.printStruct ===
_printStruct:
    ; const 40
    LDA #$28
    STA $80
    ; __SAVE__:2:1
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8C
    LDA $8C
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8D
    ; binop
    CLC
    LDX #$00
    STX $8E
    ADC _psDesc
    STA $8F
    LDA _psDesc+1
    ADC $8E
    STA $90
    LDA $8F
    LDX $90
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $8B
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $8B
    ; =
    STA _depth
    ; (expr stmt discarded)
L0:
    ; const 1
    LDA #$01
    STA $8B
    ; -> end
    BEQ L1
    ; psIdx
    ; psFieldCount
    ; cmp
    LDA _psIdx
    CMP _psFieldCount
    ; -> else
    BCC L2
    ; const 41
    LDA #$29
    STA $91
    ; __SAVE__:19:18
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; depth
    ; const 0
    LDA #$00
    STA $91
    ; cmp
    LDA _depth
    CMP $91
    ; -> else
    BNE L4
    ; return
    RTS
L4:
LDY #$00
DEC $82 : BCS .pop_a : DEC $83
.pop_a :
LDA ( $82 ),Y : STA __sdata_Stdio+14 ; psIdx
DEC $82 : BCS .pop_b : DEC $83
.pop_b :
LDA ( $82 ),Y : STA __sdata_Stdio+13 ; psFieldCount
DEC $82 : BCS .pop_c : DEC $83
.pop_c :
LDA ( $82 ),Y : STA __sdata_Stdio+12 ; psDesc hi
DEC $82 : BCS .pop_d : DEC $83
.pop_d :
LDA ( $82 ),Y : STA __sdata_Stdio+11 ; psDesc lo
DEC $82 : BCS .pop_e : DEC $83
.pop_e :
LDA ( $82 ),Y : STA __sdata_Stdio+10 ; psDp hi
DEC $82 : BCS .pop_f : DEC $83
.pop_f :
LDA ( $82 ),Y : STA __sdata_Stdio+9 ; psDp lo
    ; depth
    ; const 1
    LDA #$01
    STA $91
    ; binop
    SEC
    LDA _depth
    SBC $91
    STA $92
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; continue
    JMP L0
L2:
    ; psIdx
    ; const 0
    LDA #$00
    STA $91
    ; cmp
    LDA _psIdx
    CMP $91
    ; -> else
    BEQ L6
    BCC L6
    ; const 44
    LDA #$2C
    STA $93
    ; __SAVE__:31:30
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 32
    LDA #$20
    STA $93
    ; __SAVE__:33:32
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
L6:
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8C
    LDA $8C
    ; =
    STA _fieldType
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $84
    ; binop
    CLC
    LDX #$00
    STX $85
    ADC _psDesc
    STA $95
    LDA _psDesc+1
    ADC $85
    STA $96
    LDA $95
    LDX $96
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8C
    LDA $8C
    ; =
    STA _fieldSize
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $93
    ; binop
    CLC
    LDX #$00
    STX $94
    ADC _psDesc
    STA $95
    LDA _psDesc+1
    ADC $94
    STA $96
    LDA $95
    LDX $96
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; fieldType
    ; const 0
    LDA #$00
    STA $8C
    ; cmp
    LDA _fieldType
    CMP $8C
    ; -> else
    BNE L8
    ; psDp
    LDA _psDp
    STX $92
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $91
    LDA $91
    ; __SAVE__:53:51
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $91
    ; binop
    CLC
    LDX #$00
    STX $92
    ADC _psDp
    STA $93
    LDA _psDp+1
    ADC $92
    STA $94
    LDA $93
    LDX $94
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; -> end
    JMP L9
L8:
    ; fieldType
    ; const 2
    LDA #$02
    STA $8C
    ; cmp
    LDA _fieldType
    CMP $8C
    ; -> else
    BNE L10
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8B
    ; binop
    CLC
    LDX #$00
    STX $8C
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC $8C
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8B
    ; binop
    CLC
    LDX #$00
    STX $8C
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC $8C
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    LDA _hi
    ; =
    LDX #$00
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    STX $81
    LDX _fieldVal+1
    ; const 8
    LDA #$08
    STA $8B
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8B
    BEQ _L16
_L15:
    ASL $B0
    ROL $B1
    DEX
    BNE _L15
_L16:
    LDA $B0
    STA $91
    LDA $B1
    STA $92
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $91
    STA $8B
    LDA $92
    ORA _lo+1
    STA $8C
    LDA $8B
    LDX $8C
    ; =
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    LDA _fieldVal
    LDX _fieldVal+1
    ; __SAVE__:84:83
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP L11
L10:
    ; fieldType
    ; const 3
    LDA #$03
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE L12
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    LDA _hi
    ; =
    LDX #$00
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    STX $81
    LDX _fieldVal+1
    ; const 8
    LDA #$08
    STA $8A
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8A
    BEQ _L18
_L17:
    ASL $B0
    ROL $B1
    DEX
    BNE _L17
_L18:
    LDA $B0
    STA $91
    LDA $B1
    STA $92
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $91
    STA $8A
    LDA $92
    ORA _lo+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    LDA _fieldVal
    LDX _fieldVal+1
    ; __SAVE__:111:110
    ; call
    JSR _print__i16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP L13
L12:
    ; fieldType
    ; const 8
    LDA #$08
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE L14
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $91
    LDA _psDesc+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $91
    LDA _psDesc+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psIdx
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $83
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; =
    STA _psSaveDp
    STX _psSaveDp+1
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; fieldSize
    LDA _fieldSize
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC _fieldSize+1
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
LDY #$00
LDA __sdata_Stdio+9 : STA ( $82 ),Y ; psDp lo ( post - struct )
INC $82 : BNE .push8_a : INC $83
.push8_a :
LDA __sdata_Stdio+10 : STA ( $82 ),Y ; psDp hi
INC $82 : BNE .push8_b : INC $83
.push8_b :
LDA __sdata_Stdio+11 : STA ( $82 ),Y ; psDesc lo
INC $82 : BNE .push8_c : INC $83
.push8_c :
LDA __sdata_Stdio+12 : STA ( $82 ),Y ; psDesc hi
INC $82 : BNE .push8_d : INC $83
.push8_d :
LDA __sdata_Stdio+13 : STA ( $82 ),Y ; psFieldCount
INC $82 : BNE .push8_e : INC $83
.push8_e :
LDA __sdata_Stdio+14 : STA ( $82 ),Y ; psIdx
INC $82 : BNE .push8_f : INC $83
.push8_f :
    ; depth
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _depth
    STA $83
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; psSaveDp
    LDA _psSaveDp
    LDX _psSaveDp+1
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    ; const 8
    LDA #$08
    STA $8A
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8A
    BEQ _L20
_L19:
    ASL $B0
    ROL $B1
    DEX
    BNE _L19
_L20:
    LDA $B0
    STA $91
    LDA $B1
    STA $92
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $91
    STA $8A
    LDA $92
    ORA _lo+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $91
    LDA _psDesc+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 40
    LDA #$28
    STA $91
    ; __SAVE__:161:160
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; continue
    JMP L0
    ; -> end
    JMP L15
L14:
    ; fieldType
    ; const 9
    LDA #$09
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE L16
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _dpLo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $8C
    LDA _psDp+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _dpHi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $8C
    LDA _psDp+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $8C
    LDA _psDesc+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $8C
    LDA _psDesc+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psIdx
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $83
    ; =
    STA _psIdx
    ; (expr stmt discarded)
LDY #$00
LDA __sdata_Stdio+9 : STA ( $82 ),Y ; psDp lo ( post - pointer )
INC $82 : BNE .push9_a : INC $83
.push9_a :
LDA __sdata_Stdio+10 : STA ( $82 ),Y ; psDp hi
INC $82 : BNE .push9_b : INC $83
.push9_b :
LDA __sdata_Stdio+11 : STA ( $82 ),Y ; psDesc lo
INC $82 : BNE .push9_c : INC $83
.push9_c :
LDA __sdata_Stdio+12 : STA ( $82 ),Y ; psDesc hi
INC $82 : BNE .push9_d : INC $83
.push9_d :
LDA __sdata_Stdio+13 : STA ( $82 ),Y ; psFieldCount
INC $82 : BNE .push9_e : INC $83
.push9_e :
LDA __sdata_Stdio+14 : STA ( $82 ),Y ; psIdx
INC $82 : BNE .push9_f : INC $83
.push9_f :
    ; depth
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _depth
    STA $83
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; dpHi
    ; const 8
    LDA #$08
    STA $8A
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8A
    BEQ _L22
_L21:
    ASL $B0
    ROL $B1
    DEX
    BNE _L21
_L22:
    LDA $B0
    STA $8C
    LDA $B1
    STA $8D
    LDA $B0
    LDX $B1
    ; dpLo
    LDA _dpLo
    ; binop
    LDX #$00
    STX $81
    ORA $8C
    STA $8A
    LDA $8D
    ORA _dpLo+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _psSaveDp
    STX _psSaveDp+1
    ; (expr stmt discarded)
    ; psSaveDp
    LDA _psSaveDp
    LDX _psSaveDp+1
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    ; const 8
    LDA #$08
    STA $8A
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8A
    BEQ _L24
_L23:
    ASL $B0
    ROL $B1
    DEX
    BNE _L23
_L24:
    LDA $B0
    STA $8C
    LDA $B1
    STA $8D
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $8C
    STA $8A
    LDA $8D
    ORA _lo+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $8C
    LDA _psDesc+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 40
    LDA #$28
    STA $8A
    ; __SAVE__:225:224
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; continue
    JMP L0
    ; -> end
    JMP L17
L16:
    ; psDp
    LDX _psDp+1
    ; fieldSize
    LDA _fieldSize
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _psDp
    STA $8A
    LDA _psDp+1
    ADC _fieldSize+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; const 63
    LDA #$3F
    STA $8A
    ; __SAVE__:231:230
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
L17:
L15:
L13:
L11:
L9:
    ; psIdx
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $82
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; -> loop
    JMP L0
L1:
    ; === end Stdio.printStruct ===
    ; === method Stdio.printf ===
_printf:
    ; canPrint
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE L0
    ; return
    RTS
L0:
    ; ap
    LDA _ap
    ; __SAVE__:5:4
    ; call
    JSR __intrinsic_va_start
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $81
    LDA $81
    ; =
    STA _ch
    ; (expr stmt discarded)
L2:
    ; ch
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> end
    BEQ L3
    ; ch
    ; const 37
    LDA #$25
    STA $86
    ; cmp
    LDA _ch
    CMP $86
    ; -> else
    BNE L4
    ; fmt
    LDX _fmt+1
    ; const 1
    LDA #$01
    STA $88
    ; binop
    CLC
    LDX #$00
    STX $89
    ADC _fmt
    STA $8A
    LDA _fmt+1
    ADC $89
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _fmt
    STX _fmt+1
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $81
    LDA $81
    ; =
    STA _spec
    ; (expr stmt discarded)
    ; spec
    ; const 37
    LDA #$25
    STA $86
    ; cmp
    LDA _spec
    CMP $86
    ; -> else
    BNE L6
    ; const 37
    LDA #$25
    STA $86
    ; __SAVE__:26:25
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP L7
L6:
    ; spec
    ; const 117
    LDA #$75
    STA $87
    ; cmp
    LDA _spec
    CMP $87
    ; -> else
    BNE L8
    ; ap
    LDA _ap
    ; __SAVE__:32:31
    ; call
    JSR __intrinsic_va_arg_u16
    STA $88
    STX $89
    ; __RESTORE__
    ; __SAVE__:31:30
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
L8:
L7:
    ; -> end
    JMP L5
L4:
    ; ch
    LDA _ch
    ; __SAVE__:34:33
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
L5:
    ; fmt
    LDX _fmt+1
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _fmt
    STA $84
    LDA _fmt+1
    ADC $87
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _fmt
    STX _fmt+1
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP L2
L3:
    ; ap
    LDA _ap
    ; __SAVE__:43:42
    ; call
    JSR __intrinsic_va_end
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printf ===
    ; === method Stdio.printfAt ===
_printfAt:
    ; x
    ; y
    LDA _y
    ; __SAVE__:2,3:1
    ; call
    JSR _setCursor
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; __SAVE__:5:4
    ; call
    JSR _printf
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printfAt ===
    ; === method Assert.init ===
_init:
    ; const 0
    LDA #$00
    STA $80
    ; =
    LDX #$00
    STA _count
    STX _count+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STX $81
    LDX #$00
    STA _fails
    STX _fails+1
    ; (expr stmt discarded)
    ; === end Assert.init ===
    ; === method Assert.isTrue ===
_isTrue:
    ; count
    STX $85
    LDX _count+1
    ; const 1
    LDA #$01
    STA $84
    ; binop
    CLC
    LDX #$00
    STX $85
    ADC _count
    STA $86
    LDA _count+1
    ADC $85
    STA $87
    LDA $86
    LDX $87
    ; =
    STA _count
    STX _count+1
    ; (expr stmt discarded)
    ; ok
    STA $82
    LDA _ok
    ; → true
    BEQ L2
    LDA #$00
    STA $80
    ; → end
    JMP L3
L2:
    LDA #$01
    STA $80
L3:
    ; -> else
    BEQ L0
    ; fails
    STX $83
    LDX _fails+1
    ; const 1
    LDA #$01
    STA $84
    ; binop
    CLC
    LDX #$00
    STX $85
    ADC _fails
    STA $82
    LDA _fails+1
    ADC $85
    STA $83
    LDA $82
    LDX $83
    ; =
    STA _fails
    STX _fails+1
    ; (expr stmt discarded)
    ; Stdio
    LDA _Stdio
    STA $80
    LDA _Stdio+1
    STA $81
    LDA _Stdio+2
    STA $82
    LDA _Stdio+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; string literal
    LDA #_str_0
    LDX #_str_0+1
    STA $84
    STX $85
_str_0: .byte $46,$41,$49,$4C,$20,$54,$25,$75,$0A,0
    ; count
    LDA _count
    LDX _count+1
    ; __SAVE__:11,13,14:12
    ; mcall
    JSR _printf
    ; __RESTORE__
    ; (expr stmt discarded)
L0:
    ; === end Assert.isTrue ===
    ; === method Assert.isFalse ===
_isFalse:
    ; ok
    LDA _ok
    ; → true
    BEQ L0
    LDA #$00
    STA $80
    ; → end
    JMP L1
L0:
    LDA #$01
    STA $80
L1:
    ; __SAVE__:3:1
    ; call
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isFalse ===
    ; === method Assert.isEqual__u16_u16 ===
_isEqual__u16_u16:
    ; a
    ; b
    LDX _b+1
    ; cmp
    LDA _a+1
    CMP _b+1
    BNE _L25
    LDA _a
    CMP _b
_L25:
    ; __SAVE__:3:1
    ; call
    BNE _L26
    LDA #$01
    JMP _L27
_L26:
    LDA #$00
_L27:
    STA $84
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isEqual__u16_u16 ===
    ; === method Assert.isEqual__u32_u32 ===
_isEqual__u32_u32:
    ; a
    LDA _a
    STA $80
    LDA _a+1
    STA $81
    LDA _a+2
    STA $82
    LDA _a+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; b
    LDA _b
    STA $84
    LDA _b+1
    STA $85
    LDA _b+2
    STA $86
    LDA _b+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; cmp
    LDA _a+3
    CMP _b+3
    BNE _L28
    LDA _a+2
    CMP _b+2
    BNE _L28
    LDA _a+1
    CMP _b+1
    BNE _L28
    LDA _a
    CMP _b
_L28:
    ; __SAVE__:3:1
    ; call
    BNE _L29
    LDA #$01
    JMP _L30
_L29:
    LDA #$00
_L30:
    STA $88
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isEqual__u32_u32 ===
    ; === method Assert.isEqual__i16_i16 ===
_isEqual__i16_i16:
    ; a
    ; b
    LDX _b+1
    ; cmp
    LDA _a+1
    CMP _b+1
    BNE _L31
    LDA _a
    CMP _b
_L31:
    ; __SAVE__:3:1
    ; call
    BNE _L32
    LDA #$01
    JMP _L33
_L32:
    LDA #$00
_L33:
    STA $84
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isEqual__i16_i16 ===
    ; === method Assert.isEqual__i32_i32 ===
_isEqual__i32_i32:
    ; a
    LDA _a
    STA $80
    LDA _a+1
    STA $81
    LDA _a+2
    STA $82
    LDA _a+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; b
    LDA _b
    STA $84
    LDA _b+1
    STA $85
    LDA _b+2
    STA $86
    LDA _b+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; cmp
    LDA _a+3
    CMP _b+3
    BNE _L34
    LDA _a+2
    CMP _b+2
    BNE _L34
    LDA _a+1
    CMP _b+1
    BNE _L34
    LDA _a
    CMP _b
_L34:
    ; __SAVE__:3:1
    ; call
    BNE _L35
    LDA #$01
    JMP _L36
_L35:
    LDA #$00
_L36:
    STA $88
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isEqual__i32_i32 ===
    ; === method Assert.isNotEqual__u16_u16 ===
_isNotEqual__u16_u16:
    ; a
    ; b
    LDX _b+1
    ; cmp
    LDA _a+1
    CMP _b+1
    BNE _L37
    LDA _a
    CMP _b
_L37:
    ; __SAVE__:3:1
    ; call
    BEQ _L38
    LDA #$01
    JMP _L39
_L38:
    LDA #$00
_L39:
    STA $84
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isNotEqual__u16_u16 ===
    ; === method Assert.isNotEqual__u32_u32 ===
_isNotEqual__u32_u32:
    ; a
    LDA _a
    STA $80
    LDA _a+1
    STA $81
    LDA _a+2
    STA $82
    LDA _a+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; b
    LDA _b
    STA $84
    LDA _b+1
    STA $85
    LDA _b+2
    STA $86
    LDA _b+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; cmp
    LDA _a+3
    CMP _b+3
    BNE _L40
    LDA _a+2
    CMP _b+2
    BNE _L40
    LDA _a+1
    CMP _b+1
    BNE _L40
    LDA _a
    CMP _b
_L40:
    ; __SAVE__:3:1
    ; call
    BEQ _L41
    LDA #$01
    JMP _L42
_L41:
    LDA #$00
_L42:
    STA $88
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isNotEqual__u32_u32 ===
    ; === method Assert.isNull ===
_isNull:
    ; p
    ; const 0
    LDA #$00
    LDX #$00
    STA $82
    STX $83
    ; cmp
    LDA _p+1
    CMP $83
    BNE _L43
    LDA _p
    CMP $82
_L43:
    ; __SAVE__:3:1
    ; call
    BNE _L44
    LDA #$01
    JMP _L45
_L44:
    LDA #$00
_L45:
    STA $84
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isNull ===
    ; === method Assert.isNotNull ===
_isNotNull:
    ; p
    ; const 0
    LDA #$00
    LDX #$00
    STA $82
    STX $83
    ; cmp
    LDA _p+1
    CMP $83
    BNE _L46
    LDA _p
    CMP $82
_L46:
    ; __SAVE__:3:1
    ; call
    BEQ _L47
    LDA #$01
    JMP _L48
_L47:
    LDA #$00
_L48:
    STA $84
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isNotNull ===
    ; === method Assert.isInRange ===
_isInRange:
    ; v
    ; lo
    LDX _lo+1
    ; cmp
    LDA _v+1
    CMP _lo+1
    BNE _L49
    LDA _v
    CMP _lo
_L49:
    ; → false
    BCC L0
    ; v
    ; hi
    LDX _hi+1
    ; cmp
    LDA _v+1
    CMP _hi+1
    BNE _L50
    LDA _v
    CMP _hi
_L50:
    ; logand: rhs
    BCC _L53
    BEQ _L53
    JMP _L51
_L53:
    LDA #$01
    JMP _L52
_L51:
    LDA #$00
_L52:
    STA $84
    LDA $84
    STA $80
    LDA $85
    STA $81
    LDA $80
    LDX $81
    ; → end
    JMP L1
L0:
    LDA #$00
    LDX #$00
    STA $80
    STX $81
L1:
    ; __SAVE__:5:1
    ; call
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isInRange ===
    ; === method Assert.isLess ===
_isLess:
    ; a
    ; b
    LDX _b+1
    ; cmp
    LDA _a+1
    CMP _b+1
    BNE _L54
    LDA _a
    CMP _b
_L54:
    ; __SAVE__:3:1
    ; call
    BCS _L55
    LDA #$01
    JMP _L56
_L55:
    LDA #$00
_L56:
    STA $84
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isLess ===
    ; === method Assert.isGreater ===
_isGreater:
    ; a
    ; b
    LDX _b+1
    ; cmp
    LDA _a+1
    CMP _b+1
    BNE _L57
    LDA _a
    CMP _b
_L57:
    ; __SAVE__:3:1
    ; call
    BCC _L58
    BEQ _L58
    LDA #$01
    JMP _L59
_L58:
    LDA #$00
_L59:
    STA $84
    JSR _isTrue
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Assert.isGreater ===
    ; === method Assert.summary ===
_summary:
    ; Stdio
    LDA _Stdio
    STA $80
    LDA _Stdio+1
    STA $81
    LDA _Stdio+2
    STA $82
    LDA _Stdio+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; string literal
    LDA #_str_1
    LDX #_str_1+1
    STA $84
    STX $85
_str_1: .byte $44,$4F,$4E,$45,$20,$25,$75,$0A,0
    ; count
    LDA _count
    LDX _count+1
    ; __SAVE__:1,3,4:2
    ; mcall
    JSR _printf
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fails
    LDX _fails+1
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDX #$00
    STX $83
    LDA _fails+1
    CMP $83
    BNE _L60
    LDA _fails
    CMP $82
_L60:
    ; -> else
    BEQ L0
    ; Stdio
    LDA _Stdio
    STA $80
    LDA _Stdio+1
    STA $81
    LDA _Stdio+2
    STA $82
    LDA _Stdio+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; string literal
    LDA #_str_2
    LDX #_str_2+1
    STA $84
    STX $85
_str_2: .byte $46,$41,$49,$4C,$20,$25,$75,$20,$74,$65,$73,$74,$73,$0A,0
    ; fails
    LDA _fails
    LDX _fails+1
    ; __SAVE__:8,10,11:9
    ; mcall
    JSR _printf
    ; __RESTORE__
    ; (expr stmt discarded)
L0:
    ; === end Assert.summary ===
    ; === method Assert.reset ===
_reset:
    ; const 0
    LDA #$00
    STA $80
    ; =
    LDX #$00
    STA _count
    STX _count+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STX $81
    LDX #$00
    STA _fails
    STX _fails+1
    ; (expr stmt discarded)
    ; === end Assert.reset ===
    ; === method Assert.testCount ===
_testCount:
    ; count
    LDA _count
    STX $81
    LDX _count+1
    ; retain return
    LDY #$00
    JSR _obj_retain
    STA $82
    STX $83
    ; return
    RTS
    ; === end Assert.testCount ===
    ; === method Assert.failCount ===
_failCount:
    ; fails
    LDA _fails
    LDX _fails+1
    ; retain return
    LDY #$00
    JSR _obj_retain
    STA $82
    STX $83
    ; return
    RTS
    ; === end Assert.failCount ===
    ; === method Item.dealloc ===
_dealloc:
    ; itemDealloc
    LDX _itemDealloc+1
    ; const 1
    LDA #$01
    STA $84
    ; binop
    CLC
    LDX #$00
    STX $85
    ADC _itemDealloc
    STA $86
    LDA _itemDealloc+1
    ADC $85
    STA $87
    LDA $86
    LDX $87
    ; =
    STA _itemDealloc
    STX _itemDealloc+1
    ; (expr stmt discarded)
    ; === end Item.dealloc ===
    ; === function makeSmall ===
_makeSmall:
    STA $80
    STX $81
	PLA
	STA $B0
	PLA
	STA $B1
    ; id
    PLA
    STA $80
	LDA $B1
	PHA
	LDA $B0
	PHA
    ; &base
    LDA #_h
    LDX #_h+1
    STA $82
    STX $83
    ; new
    JSR _new_Item
    STA $84
    STX $85
    ; old field value
    LDA $82
    LDX $83
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $88
    INY
    LDA ($B0),Y
    STA $89
    LDA $88
    LDX $89
    ; release old field
    LDY #$00
    JSR _obj_decref
    ; =
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDA $82
    LDX $83
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    INY
    LDA $B3
    STA ($B0),Y
    LDA $84
    STA $86
    LDA $85
    STA $87
    LDA $86
    LDX $87
    ; (expr stmt discarded)
    ; &base
    LDA #_h
    LDX #_h+1
    STA $82
    STX $83
    ; .payload
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $84
    INY
    LDA ($B0),Y
    STA $85
    LDA $84
    LDX $85
    ; field offset
    LDA #$01
    LDX #$00
    STA $88
    STX $89
    ; base+offset
    CLC
    ADC $84
    STA $8A
    LDA $85
    ADC $89
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    LDA $80
    STA $B2
    LDA $8A
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
    ; &base
    LDA #_h
    LDX #_h+1
    STA $80
    STX $81
    ; field offset
    LDA #$02
    LDX #$00
    STA $84
    STX $85
    ; base+offset
    CLC
    ADC $80
    STA $86
    LDA $81
    ADC $85
    STA $87
    LDA $86
    LDX $87
    ; const 7
    LDA #$07
    STA $80
    ; =
    LDA $80
    STA $B2
    LDA $86
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
    ; h
    LDA _h
    LDX _h+1
    LDY _h+2
    ; retain return
    LDY #$00
    JSR _obj_retain
    STA $83
    STX $84
    ; return
    RTS
    ; === end makeSmall ===
    ; === function makeLarge ===
_makeLarge:
	PLA
	STA $B0
	PLA
	STA $B1
    ; id
    PLA
    STA $80
	LDA $B1
	PHA
	LDA $B0
	PHA
    ; &base
    LDA #_h
    LDX #_h+1
    STA $82
    STX $83
    ; new
    JSR _new_Item
    STA $86
    STX $87
    ; old field value
    LDA $82
    LDX $83
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $88
    INY
    LDA ($B0),Y
    STA $89
    LDA $88
    LDX $89
    ; release old field
    LDY #$00
    JSR _obj_decref
    ; =
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $82
    LDX $83
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    INY
    LDA $B3
    STA ($B0),Y
    LDA $86
    STA $84
    LDA $87
    STA $85
    LDA $84
    LDX $85
    ; (expr stmt discarded)
    ; &base
    LDA #_h
    LDX #_h+1
    STA $8A
    STX $8B
    ; .payload
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8C
    INY
    LDA ($B0),Y
    STA $8D
    LDA $8C
    LDX $8D
    ; field offset
    LDA #$01
    LDX #$00
    STA $8A
    STX $8B
    ; base+offset
    CLC
    ADC $8C
    STA $8E
    LDA $8D
    ADC $8B
    STA $8F
    LDA $8E
    LDX $8F
    ; =
    LDA $80
    STA $B2
    LDA $8E
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    LDA $80
    STA $8A
    LDA $8A
    ; (expr stmt discarded)
    ; &base
    LDA #_h
    LDX #_h+1
    STA $90
    STX $91
    ; field offset
    LDA #$02
    LDX #$00
    STA $92
    STX $93
    ; base+offset
    CLC
    ADC $90
    STA $94
    LDA $91
    ADC $93
    STA $95
    LDA $94
    LDX $95
    ; const 1
    LDA #$01
    STA $90
    ; =
    LDA $90
    STA $B2
    LDA $91
    STA $B3
    LDA $94
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    INY
    LDA $B3
    STA ($B0),Y
    ; (expr stmt discarded)
    ; &base
    LDA #_h
    LDX #_h+1
    STA $80
    STX $81
    ; field offset
    LDA #$04
    LDX #$00
    STA $90
    STX $91
    ; base+offset
    CLC
    ADC $80
    STA $92
    LDA $81
    ADC $91
    STA $93
    LDA $92
    LDX $93
    ; const 2
    LDA #$02
    STA $80
    ; =
    LDA $80
    STA $B2
    LDA $81
    STA $B3
    LDA $92
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    INY
    LDA $B3
    STA ($B0),Y
    ; (expr stmt discarded)
    ; &base
    LDA #_h
    LDX #_h+1
    STA $80
    STX $81
    ; field offset
    LDA #$06
    LDX #$00
    STA $84
    STX $85
    ; base+offset
    CLC
    ADC $80
    STA $8A
    LDA $81
    ADC $85
    STA $8B
    LDA $8A
    LDX $8B
    ; const 3
    LDA #$03
    STA $80
    ; =
    LDA $80
    STA $B2
    LDA $81
    STA $B3
    LDA $8A
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    INY
    LDA $B3
    STA ($B0),Y
    ; (expr stmt discarded)
    ; &base
    LDA #_h
    LDX #_h+1
    STA $80
    STX $81
    ; field offset
    LDA #$08
    LDX #$00
    STA $82
    STX $83
    ; base+offset
    CLC
    ADC $80
    STA $84
    LDA $81
    ADC $83
    STA $85
    LDA $84
    LDX $85
    ; const 4
    LDA #$04
    STA $80
    ; =
    LDA $80
    STA $B2
    LDA $81
    STA $B3
    LDA $84
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    INY
    LDA $B3
    STA ($B0),Y
    ; (expr stmt discarded)
    ; &base
    LDA #_h
    LDX #_h+1
    STA $80
    STX $81
    ; field offset
    LDA #$0A
    LDX #$00
    STA $82
    STX $83
    ; base+offset
    CLC
    ADC $80
    STA $84
    LDA $81
    ADC $83
    STA $85
    LDA $84
    LDX $85
    ; const 5
    LDA #$05
    STA $80
    ; =
    LDA $80
    STA $B2
    LDA $81
    STA $B3
    LDA $84
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    INY
    LDA $B3
    STA ($B0),Y
    ; (expr stmt discarded)
    ; h
    LDA _h
    STA $80
    LDA _h+1
    STA $81
    LDA _h+2
    STA $82
    LDA _h+3
    STA $83
    LDA _h+4
    STA $84
    LDA _h+5
    STA $85
    LDA _h+6
    STA $86
    LDA _h+7
    STA $87
    LDA _h+8
    STA $88
    LDA _h+9
    STA $89
    LDA _h+10
    STA $8A
    LDA _h+11
    STA $8B
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    LDA $B4
    STA $84
    LDA $B5
    STA $85
    LDA $B6
    STA $86
    LDA $B7
    STA $87
    LDA $84
    STA $88
    LDA ?
    STA $89
    LDA ?
    STA $8A
    LDA ?
    STA $8B
    ; retain return
    LDA _h
    LDY #$00
    JSR _obj_retain
    STA $8C
    STX $8D
    ; return
    RTS
    ; === end makeLarge ===
    ; === function exerciseSmall ===
_exerciseSmall:
    ; var x =
    ; const 1
    LDA #$01
    STA $83
    ; arg
    PHA
    ; call
    JSR _makeSmall
    STA $80
    STX $81
    STY $82
    STA _x
    STX _x+1
    STY _x+2
    ; var mid1 =
    ; itemDealloc
    LDA _itemDealloc
    LDX _itemDealloc+1
    STA _mid1
    STX _mid1+1
    ; const 2
    LDA #$02
    STA $80
    ; arg
    PHA
    ; call
    JSR _makeSmall
    STA $83
    STX $84
    STY $85
    ; =
    STA _x
    STX _x+1
    STY _x+2
    ; (expr stmt discarded)
    ; var mid2 =
    ; itemDealloc
    LDA _itemDealloc
    LDX _itemDealloc+1
    STA _mid2
    STX _mid2+1
    ; mid1
    LDX _mid1+1
    ; const 100
    LDA #$64
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _mid1
    JSR _mul16
    STA $84
    STX $85
    ; mid2
    LDA _mid2
    LDX _mid2+1
    ; binop
    CLC
    ADC $84
    STA $82
    LDA $85
    ADC _mid2+1
    STA $83
    LDA $82
    LDX $83
    ; retain return
    LDY #$00
    JSR _obj_retain
    STA $80
    STX $81
    ; return
    RTS
    ; === end exerciseSmall ===
    ; === function exerciseLarge ===
_exerciseLarge:
    ; var x =
    ; const 1
    LDA #$01
    STA $8C
    ; arg
    PHA
    ; call
    JSR _makeLarge
    STA $80
    STX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    LDA $B4
    STA $84
    LDA $B5
    STA $85
    LDA $B6
    STA $86
    LDA $B7
    STA $87
    LDA $84
    STA $88
    LDA ?
    STA $89
    LDA ?
    STA $8A
    LDA ?
    STA $8B
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STX _x+1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+2
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+3
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+4
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+5
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+6
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+7
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+8
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+9
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+10
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA $88
    STA $84
    LDA $89
    STA ?
    LDA $8A
    STA ?
    LDA $8B
    STA ?
    LDA $80
    STA _x+11
    ; var mid1 =
    ; itemDealloc
    LDA _itemDealloc
    LDX _itemDealloc+1
    STA _mid1
    STX _mid1+1
    ; const 2
    LDA #$02
    STA $80
    ; arg
    PHA
    ; call
    JSR _makeLarge
    STA $8C
    STX $8D
    LDA $B2
    STA $8E
    LDA $B3
    STA $8F
    LDA $B4
    STA $90
    LDA $B5
    STA $91
    LDA $B6
    STA $92
    LDA $B7
    STA $93
    LDA $84
    STA $94
    LDA ?
    STA $95
    LDA ?
    STA $96
    LDA ?
    STA $97
    ; =
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STX _x+1
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+3
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+4
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+5
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+6
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+7
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+8
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+9
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+10
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $90
    STA $B4
    LDA $91
    STA $B5
    LDA $92
    STA $B6
    LDA $93
    STA $B7
    LDA $94
    STA $84
    LDA $95
    STA ?
    LDA $96
    STA ?
    LDA $97
    STA ?
    LDA $8C
    STA _x+11
    ; (expr stmt discarded)
    ; var mid2 =
    ; itemDealloc
    LDA _itemDealloc
    LDX _itemDealloc+1
    STA _mid2
    STX _mid2+1
    ; mid1
    LDX _mid1+1
    ; const 100
    LDA #$64
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _mid1
    JSR _mul16
    STA $84
    STX $85
    ; mid2
    LDA _mid2
    LDX _mid2+1
    ; binop
    CLC
    ADC $84
    STA $80
    LDA $85
    ADC _mid2+1
    STA $81
    LDA $80
    LDX $81
    ; retain return
    LDY #$00
    JSR _obj_retain
    STA $82
    STX $83
    ; return
    RTS
    ; === end exerciseLarge ===
    ; === function main ===
_main:
    ; Assert
    LDA _Assert
    STA $80
    LDA _Assert+1
    STA $81
    LDA _Assert+2
    STA $82
    LDA _Assert+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; mcall
    JSR _reset
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $88
    ; =
    LDX #$00
    STA _itemDealloc
    STX _itemDealloc+1
    ; (expr stmt discarded)
    ; var smallMid =
    ; call
    STX $89
    JSR _exerciseSmall
    STA $88
    STX $89
    STA _smallMid
    STX _smallMid+1
    ; Assert
    LDA _Assert
    STA $88
    LDA _Assert+1
    STA $89
    LDA _Assert+2
    STA $8A
    LDA _Assert+3
    STA $8B
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    LDX $89
    LDA $B2
    STA $8A
    LDA $B3
    STA $8B
    ; smallMid
    LDX _smallMid+1
    ; const 1
    LDA #$01
    STA $90
    ; mcall
    JSR _isEqual__u16_u16
    ; (expr stmt discarded)
    ; Assert
    LDA _Assert
    STA $88
    LDA _Assert+1
    STA $89
    LDA _Assert+2
    STA $8A
    LDA _Assert+3
    STA $8B
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    LDX $89
    LDA $B2
    STA $8A
    LDA $B3
    STA $8B
    ; itemDealloc
    LDX _itemDealloc+1
    ; const 2
    LDA #$02
    STA $90
    ; mcall
    JSR _isEqual__u16_u16
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $88
    ; =
    LDX #$00
    STA _itemDealloc
    STX _itemDealloc+1
    ; (expr stmt discarded)
    ; var largeMid =
    ; call
    STX $89
    JSR _exerciseLarge
    STA $88
    STX $89
    STA _largeMid
    STX _largeMid+1
    ; Assert
    LDA _Assert
    STA $88
    LDA _Assert+1
    STA $89
    LDA _Assert+2
    STA $8A
    LDA _Assert+3
    STA $8B
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    LDX $89
    LDA $B2
    STA $8A
    LDA $B3
    STA $8B
    ; largeMid
    LDX _largeMid+1
    ; const 1
    LDA #$01
    STA $90
    ; mcall
    JSR _isEqual__u16_u16
    ; (expr stmt discarded)
    ; Assert
    LDA _Assert
    STA $80
    LDA _Assert+1
    STA $81
    LDA _Assert+2
    STA $82
    LDA _Assert+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; itemDealloc
    LDX _itemDealloc+1
    ; const 2
    LDA #$02
    STA $8C
    ; mcall
    JSR _isEqual__u16_u16
    ; (expr stmt discarded)
    ; Assert
    LDA _Assert
    STA $80
    LDA _Assert+1
    STA $81
    LDA _Assert+2
    STA $82
    LDA _Assert+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; mcall
    JSR _summary
    ; (expr stmt discarded)
    ; return
    RTS
    ; === end main ===

    ; === Global variables ===
    _Assert:
        .space 4
    _Stdio:
        .space 4
    _a:
        .space 4
    _ap:
        .space 1
    _b:
        .space 4
    _botlin:
        .space 1
    _cLo:
        .space 1
    _canPrint:
        .space 1
    _ch:
        .space 1
    _cols:
        .space 1
    _count:
        .space 2
    _d:
        .space 4
    _depth:
        .space 1
    _dpHi:
        .space 1
    _dpLo:
        .space 1
    _dst:
        .space 2
    _endPtr:
        .space 2
    _fails:
        .space 2
    _fieldSize:
        .space 1
    _fieldType:
        .space 1
    _fieldVal:
        .space 2
    _fmt:
        .space 2
    _fpBufPtr:
        .space 2
    _h:
        .space 12
    _hi:
        .space 2
    _inv:
        .space 1
    _itemDealloc:
        .space 2
    _largeMid:
        .space 2
    _lo:
        .space 2
    _mid1:
        .space 2
    _mid2:
        .space 2
    _mode:
        .space 1
    _n:
        .space 1
    _numCols:
        .space 2
    _off:
        .space 2
    _offset:
        .space 2
    _ok:
        .space 1
    _p:
        .space 2
    _psDesc:
        .space 2
    _psDp:
        .space 2
    _psFieldCount:
        .space 1
    _psIdx:
        .space 1
    _psSaveDp:
        .space 2
    _ptr:
        .space 2
    _r:
        .space 1
    _rem:
        .space 2
    _rows:
        .space 1
    _s:
        .space 2
    _sb:
        .space 2
    _sbase:
        .space 2
    _sc:
        .space 1
    _scrMode:
        .space 1
    _screenBase:
        .space 2
    _screenPtr:
        .space 2
    _size:
        .space 2
    _smallMid:
        .space 2
    _spec:
        .space 1
    _src:
        .space 2
    _szHi:
        .space 1
    _szLo:
        .space 1
    _v:
        .space 2
    _val:
        .space 4
    _x:
        .space 12
    _y:
        .space 1

    ; === Runtime routines ===

_mul16:
    LDA $B4
    STA $B2
    LDA $B5
    STA $B3
    ; Save lhs since we shift multiplicand
    LDA $B0
    STA $B6
    LDA $B1
    STA $B7
    ; Determine sign
    LDA #$00
    STA $B8         ; sign flag
    LDA $B7
    BPL .mul_op1_pos
    ; Negate operand1
    LDA $B6 : EOR #$FF : STA $B6
    LDA $B7 : EOR #$FF : STA $B7
    INC $B6 : BNE .mul_op1_pos : INC $B7
    INC $B8
.mul_op1_pos:
    LDA $B3
    BPL .mul_op2_pos
    ; Negate operand2
    LDA $B2 : EOR #$FF : STA $B2
    LDA $B3 : EOR #$FF : STA $B3
    INC $B2 : BNE .mul_op2_pos : INC $B3
    INC $B8
.mul_op2_pos:
    ; Unsigned multiply: $B6-$B7 x $B2-$B3 -> $B0-$B3
    LDA #$00
    STA $B0
    STA $B1
    STA $B4
    STA $B5
    LDX #16
.mul_loop:
    LSR $B3
    ROR $B2
    BCC .mul_no_add
    CLC
    LDA $B0
    ADC $B6
    STA $B0
    LDA $B1
    ADC $B7
    STA $B1
    LDA $B4
    ADC #$00
    STA $B4
    LDA $B5
    ADC #$00
    STA $B5
.mul_no_add:
    ASL $B6
    ROL $B7
    DEX
    BNE .mul_loop
    ; Apply sign
    LDA $B8
    AND #$01
    BEQ .mul_done
    LDA $B0 : EOR #$FF : STA $B0
    LDA $B1 : EOR #$FF : STA $B1
    INC $B0 : BNE .mul_done : INC $B1
.mul_done:
    ; Return result in A/X
    LDA $B0
    LDX $B1
    RTS
_div16:
    JSR _udiv16
    LDA $B0
    LDX $B1
    RTS
_mod16:
    JSR _udiv16
    LDA $B2
    LDX $B3
    RTS
_div32:
    ; 32-bit division (placeholder)
    LDA #$00
    STA $B0
    STA $B1
    STA $B2
    STA $B3
    RTS
_mod32:
    ; 32-bit modulo (placeholder)
    LDA #$00
    STA $B0
    STA $B1
    STA $B2
    STA $B3
    RTS

    ; === ARC retain-count runtime (flat heap) ===

_heap_save_caller_bank:
    RTS
_heap_select_bank:
    RTS
_heap_restore_caller_bank:
    RTS
_obj_ptr:
        .byte $00, $00
_obj_bank:
        .byte $00
_arc_retval_lo:
        .byte $00
_arc_retval_hi:
        .byte $00
_arc_retval_bank:
        .byte $00
_arc_assign_old_lo:
        .byte $00
_arc_assign_old_hi:
        .byte $00
_arc_assign_old_bank:
        .byte $00
_arc_tx_ptr_lo:
        .byte $00
_arc_tx_ptr_hi:
        .byte $00

_obj_retain:
    JSR _heap_save_caller_bank
    STA _obj_ptr
    STX _obj_ptr+1
    ORA _obj_ptr+1
    BEQ _or_done
    SEC
    LDA _obj_ptr
    SBC #$02
    STA $B0
    LDA _obj_ptr+1
    SBC #$00
    STA $B0+1
    LDY #$01
    LDA ($B0),Y
    CMP #$FF
    BNE _or_inc
    LDY #$00
    LDA ($B0),Y
    CMP #$FF
    BEQ _or_done
_or_inc:
    LDY #$00
    LDA ($B0),Y
    CLC
    ADC #$01
    STA ($B0),Y
    BCC _or_done
    INY
    LDA ($B0),Y
    ADC #$00
    STA ($B0),Y
_or_done:
    JMP _heap_restore_caller_bank

_obj_decref:
    JSR _heap_save_caller_bank
    STA _obj_ptr
    STX _obj_ptr+1
    LDA #$00
    STA _obj_bank
    ORA _obj_ptr+1
    BEQ _od_restore_cc
    SEC
    LDA _obj_ptr
    SBC #$02
    STA $B0
    LDA _obj_ptr+1
    SBC #$00
    STA $B0+1
    LDY #$00
    LDA ($B0),Y
    INY
    ORA ($B0),Y
    BEQ _od_restore_cc
    LDY #$00
    LDA ($B0),Y
    SEC
    SBC #$01
    STA ($B0),Y
    BCS _od_check_zero
    INY
    LDA ($B0),Y
    SBC #$00
    STA ($B0),Y
_od_check_zero:
    LDY #$00
    LDA ($B0),Y
    INY
    ORA ($B0),Y
    BNE _od_restore_cc
    ; (no weak slots in this program)
    JSR _heap_restore_caller_bank
    LDA _obj_ptr
    LDX _obj_ptr+1
    LDY _obj_bank
    SEC
    RTS
_od_restore_cc:
    JSR _heap_restore_caller_bank
    LDA _obj_ptr
    LDX _obj_ptr+1
    LDY _obj_bank
    CLC
    RTS

