;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/asm_var.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module asm_var

    ; === function main ===
_main:
    ; var val =
    ; const 4660
    LDA #$34
    LDX #$12
    STA $80
    STX $81
    STA _val
    STX _val+1
LDA #< val
STA $D40E
LDA #> val
NOP
    ; return
    RTS
    ; === end main ===

    ; === Global variables ===
    _val:
        .space 2

    ; === Runtime routines ===

