; Generated by xtc compiler — xt memory model
    .ORG $2400

heap_top = $7FFF
heap_low = $4000
heap_end = $8000
heap_bank_first = $01
heap_bank_last  = $01
heap_total_bytes = $4000
heap_total_bytes_b2 = $00
heap_total_bytes_b3 = $00
regC_heap_bank_first = $00
regC_heap_bank_last  = $00
regC_heap_low = $0000
regC_heap_end = $0000
WEAK_TABLE_ENTRIES = $40


    LDA $02F4
    STA _shadow_src+2
    LDX #$04
    LDY #$00
_shadow_src:
    LDA $FF00,Y
    STA $2000,Y
    INY
    BNE _shadow_src
    INC _shadow_src+2
    INC _shadow_src+5
    DEX
    BNE _shadow_src

    LDA #$20
    STA $02F4
    STA $D409

    LDA #<stack_low
    STA $82
    LDA #>stack_low
    STA $82 + 1

    LDA #<heap_top
    STA $86
    LDA #>heap_top
    STA $86 + 1

    LDA #$00
    STA $58
    LDA #$80
    STA $59
    LDA #$80
    STA $6A

    LDA #<_xe_dlist
    STA $0230 ; SDLSTL (OS shadow)
    STA $D402 ; DLISTL (ANTIC hw)
    LDA #>_xe_dlist
    STA $0231 ; SDLSTH
    STA $D403 ; DLISTH

    LDA $D301
    ORA #$33
    STA $D301

    SEI

    LDA $FFFE
    STA _shadow_irq_vec
    LDA $FFFF
    STA _shadow_irq_vec + 1

    LDA $D301
    AND #$FE
    STA $D301

    LDA #<_shadow_nmi
    STA $FFFA
    LDA #>_shadow_nmi
    STA $FFFB

    LDA #<_shadow_irq
    STA $FFFE
    LDA #>_shadow_irq
    STA $FFFF

    LDA #$40
    STA $D40E
    CLI
    JMP _L0000

_shadow_nmi:
    BIT $D40F
    BVS _shadow_vbi
    JMP ($0200)

_shadow_vbi:
    PHA
    TXA
    PHA
    TYA
    PHA

    LDA $D301
    ORA #$01
    STA $D301

    TSX
    LDA $0106,X
    STA _shadow_p_tmp

    LDA #>_shadow_nmi_epilogue
    PHA
    LDA #<_shadow_nmi_epilogue
    PHA
    LDA _shadow_p_tmp
    PHA

    CLD
    LDA #$00
    PHA
    PHA
    PHA

    STA $D40F
    JMP ($0222)

_shadow_nmi_epilogue:
    LDA $D301
    AND #$FE
    STA $D301

    PLA
    TAY
    PLA
    TAX
    PLA
    RTI

_shadow_p_tmp:
    .BYTE $00

_shadow_irq:
    PHA ; save caller's A
    TXA
    PHA ; save caller's X (via A)

    LDA $D301
    ORA #$01
    STA $D301 ; re-enable OS ROM

    TSX
    LDA $0103,X
    STA _shadow_irq_user_p
    LDA $0104,X
    STA _shadow_irq_user_pcl
    LDA $0105,X
    STA _shadow_irq_user_pch

    LDA $0103,X
    ORA #$04
    STA $0103,X

    LDA #<_shadow_irq_epilogue
    STA $0104,X
    LDA #>_shadow_irq_epilogue
    STA $0105,X

    PLA
    TAX ; restore caller's X
    PLA ; restore caller's A

    JMP (_shadow_irq_vec) ; dispatch into OS IRQ / BRK handler

_shadow_irq_epilogue:
    PHA
    LDA $D301
    AND #$FE
    STA $D301
    PLA

    LDA _shadow_irq_user_pch
    PHA
    LDA _shadow_irq_user_pcl
    PHA
    LDA _shadow_irq_user_p
    PHA
    RTI

_shadow_irq_user_p:
    .BYTE $00
_shadow_irq_user_pcl:
    .BYTE $00
_shadow_irq_user_pch:
    .BYTE $00
_shadow_irq_vec:
    .WORD $0000

_xe_dlist:
    .BYTE $70, $70, $70
    .BYTE $42, $00, $80
    .BYTE $02, $02, $02, $02, $02, $02, $02, $02
    .BYTE $02, $02, $02, $02, $02, $02, $02, $02
    .BYTE $02, $02, $02, $02, $02, $02, $02
    .BYTE $41, <_xe_dlist, >_xe_dlist

_L0000:

    LDA $D301
    AND #$E3
    ORA #$04
    STA $D301

; global marker at $0092

; Non-banked startup — calls main, RTSes or loops after
main_entry:
    JSR _heap_init ; free-list heap one-time init
    JSR _fn_main
    LDA $D301 ; ROM on + BASIC off + banking off
    ORA #$13
    STA $D301
    JMP ($000A) ; exit through DOSVEC

; String constants
_str0000:
    .BYTE $54,$31,$20,$50,$41,$53,$53,$0A,$00
_str0001:
    .BYTE $54,$31,$20,$46,$41,$49,$4C,$0A,$00

; class-id → parent-id table (for `as` / `as?` downcast walks)
__class_parent:
    .BYTE $00,$00,$00

; Static class data
__sdata_Stdio:
    .BYTE $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
__sinit_Stdio:
    .BYTE $00

stack_low:
; xtc software stack grows upward from here toward heap_top

; Main code region
    .ORG $A000
    .CODE_REGIONS $A000-$BFFF, $C000-$CFFF, $D800-$FFF9, $2600-$3FFF
    .SHADOW_RANGES $C000-$CFFF, $D800-$FFF9
    .SHADOW_STAGE $4000
_ivar_Stdio_canPrint = 7
_ivar_Stdio_cols = 5
_ivar_Stdio_fpBufPtr = 8
_ivar_Stdio_mode = 6
_ivar_Stdio_psDesc = 12
_ivar_Stdio_psDp = 10
_ivar_Stdio_psFieldCount = 14
_ivar_Stdio_psIdx = 15
_ivar_Stdio_psSaveDp = 16
_ivar_Stdio_rows = 18
_ivar_Stdio_screenBase = 3
_ivar_Stdio_screenPtr = 1
_sizeof_Stdio = 19


; Auto-generated: Stdio.dealloc() — empty
_cls_Stdio_dealloc:
    RTS

; Function: main
_fn_main:

    ; marker = 0;
    LDA #$00
    STA $92 ; marker

    ; hello();
; call hello
    PHA
    TXA : PHA
    TYA : PHA
; :cloaked call → _fn_hello
    LDA $D301
    PHA
    LDA #$32 ; __xtc_portb_lit:_fn_hello
    STA $D301

    ; cloaked_hello.xt — stage 4 smoke test for the :cloaked library bank.
    ;
    ; The :cloaked function writes a marker byte to a global. The
    ; caller brackets the JSR in PORTB = $30 / restore (codegen emits
    ; the bracket automatically when it sees the :cloaked annotation)
    ; so the library image at $4000-$7FFF is exposed during the call.
    ; After return, main verifies the marker changed. xe-family only;
    ; on xl / xt sema + codegen reject the annotation.
    ; marker = $A5;
    LDA #$A5
    STA $92 ; marker
_inlcloaked_hello_0__L0011:
; store return value in $B0/$B1 (lo/hi)
    STA $B0
    STX $B1
    STA _cloak_retval_lo
    PLA
    STA $D301
    LDA _cloak_retval_lo
    PLA : TAY
    PLA : TAX
    PLA
    LDA $B1
    TAX
    LDA $B0

    ; if (marker == $A5) {
    LDA $92 ; marker
    CMP #$A5
    BNE _L0110

    ; Stdio.printf("T1 PASS\n");
; static init Stdio (guarded)
    LDA __sinit_Stdio
    BNE _L0112
    INC __sinit_Stdio
    LDA #<__sdata_Stdio
    STA $84
    LDA #>__sdata_Stdio
    STA $85
; :cloaked call → _cls_Stdio_init
    LDA $D301
    PHA
    LDA #$32 ; __xtc_portb_lit:_cls_Stdio_init
    STA $D301
    JSR _cls_Stdio_init
    STA _cloak_retval_lo
    PLA
    STA $D301
    LDA _cloak_retval_lo
_L0112:
; method call Stdio.printf
    LDA #<_str0000
    LDX #>_str0000
    TAY
    TXA
    PHA
    TYA
    PHA
    LDA #<__sdata_Stdio
    STA $84
    LDA #>__sdata_Stdio
    STA $85
; banked JSR → _cls_Stdio_printf (via _xcall_main)
    LDA #$0C ; __xtc_bank_lit:_cls_Stdio_printf
    STA $88
    LDA #<_cls_Stdio_printf
    LDX #>_cls_Stdio_printf
    JSR _xcall_main
    JMP _L0111
_L0110:
; else branch

    ; Stdio.printf("T1 FAIL\n");
; static init Stdio (guarded)
    LDA __sinit_Stdio
    BNE _L0113
    INC __sinit_Stdio
    LDA #<__sdata_Stdio
    STA $84
    LDA #>__sdata_Stdio
    STA $85
; :cloaked call → _cls_Stdio_init
    LDA $D301
    PHA
    LDA #$32 ; __xtc_portb_lit:_cls_Stdio_init
    STA $D301
    JSR _cls_Stdio_init
    STA _cloak_retval_lo
    PLA
    STA $D301
    LDA _cloak_retval_lo
_L0113:
; method call Stdio.printf
    LDA #<_str0001
    LDX #>_str0001
    TAY
    TXA
    PHA
    TYA
    PHA
    LDA #<__sdata_Stdio
    STA $84
    LDA #>__sdata_Stdio
    STA $85
; banked JSR → _cls_Stdio_printf (via _xcall_main)
    LDA #$0C ; __xtc_bank_lit:_cls_Stdio_printf
    STA $88
    LDA #<_cls_Stdio_printf
    LDX #>_cls_Stdio_printf
    JSR _xcall_main
_L0111:

    ; return;
    RTS

; _xcall_vector: shared target address slot for _xcall* trampolines
_xcall_vector:
    .WORD $0000
; _xcall_retval_y: Y stash across the resume's caller_ret pop
_xcall_retval_y:
    .BYTE $00

; _xcall_main: shared cross-bank trampoline for non-banked callers
_xcall_main:
    STA _xcall_vector
    STX _xcall_vector+1
    LDY #$00
    PLA
    STA ($82),Y
    INC $82
    BNE _L0114
    INC $83
_L0114:
    PLA
    STA ($82),Y
    INC $82
    BNE _L0115
    INC $83
_L0115:
    LDA $D301
    STA ($82),Y
    INC $82
    BNE _L0116
    INC $83
_L0116:
    LDA $D301
    AND #$E3
    ORA $88
    STA $D301
    LDA #>_xcall_main_resume_m1
    PHA
    LDA #<_xcall_main_resume_m1
    PHA
    LDA _xcall_vector+1
    PHA
    LDA _xcall_vector
    SEC
    SBC #$01
    PHA
    BCS _xcall_main_no_borrow
    PLA
    TAX
    PLA
    SEC
    SBC #$01
    PHA
    TXA
    PHA
_xcall_main_no_borrow:
    RTS
_xcall_main_resume_m1:
    NOP
_xcall_main_resume:
    PHA
    TXA
    PHA
    TYA
    PHA
    LDY #$00
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0117
    DEC $83
_L0117:
    LDY #$00
    LDA ($82),Y
    STA $D301
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0118
    DEC $83
_L0118:
    LDY #$00
    LDA ($82),Y
    STA $85
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0119
    DEC $83
_L0119:
    LDY #$00
    LDA ($82),Y
    STA $84
    PLA
    STA _xcall_retval_y
    PLA
    TAX
    PLA
    STA _xcall_vector
    STX _xcall_vector+1
    LDA $85
    PHA
    LDA $84
    PHA
    LDY _xcall_retval_y
    LDA _xcall_vector
    RTS

; _xcall_cloaked_portb: target PORTB byte staged by call sites
_xcall_cloaked_portb:
    .BYTE $00
; _xcall_cloaked_saved_portb: caller's PORTB byte across the call
_xcall_cloaked_saved_portb:
    .BYTE $00
; _xcall_cloaked_caller_ret: caller's return address across the call
_xcall_cloaked_caller_ret:
    .WORD $0000

; _xcall_cloaked: cross-bank trampoline from banked → cloaked targets
_xcall_cloaked:
    LDA $D301
    STA _xcall_cloaked_saved_portb
    PLA
    STA _xcall_cloaked_caller_ret
    PLA
    STA _xcall_cloaked_caller_ret+1
    LDA _xcall_cloaked_portb
    STA $D301
    LDA #>_xcall_cloaked_resume_m1
    PHA
    LDA #<_xcall_cloaked_resume_m1
    PHA
    LDA _xcall_vector+1
    PHA
    LDA _xcall_vector
    SEC
    SBC #$01
    PHA
    BCS _xcall_cloaked_no_borrow
    PLA
    TAX
    PLA
    SEC
    SBC #$01
    PHA
    TXA
    PHA
_xcall_cloaked_no_borrow:
    RTS
_xcall_cloaked_resume_m1:
    NOP
_xcall_cloaked_resume:
    STA _xcall_vector
    STX _xcall_vector+1
    STY _xcall_retval_y
    LDA _xcall_cloaked_saved_portb
    STA $D301
    LDA _xcall_cloaked_caller_ret+1
    PHA
    LDA _xcall_cloaked_caller_ret
    PHA
    LDA _xcall_vector
    RTS

; Runtime library routines

; u16Div — unsigned 16-bit divide
; Input:  $B0,$B1 = dividend (u16), $B2,$B3 = divisor (u16)
; Output: $B0,$B1 = quotient (u16), $B2,$B3 = remainder (u16)

u16Div:
    LDA #$00
    STA $B4 ; remainder lo
    STA $B5 ; remainder hi
    LDX #16
.loop:
    ASL $B0
    ROL $B1 ; shift dividend left
    ROL $B4
    ROL $B5 ; shift into remainder
    ; Compare remainder with divisor
    LDA $B4
    CMP $B2
    LDA $B5
    SBC $B3
    BCC .no_sub
    ; remainder >= divisor: subtract
    LDA $B4
    SEC
    SBC $B2
    STA $B4
    LDA $B5
    SBC $B3
    STA $B5
    INC $B0 ; set quotient bit
.no_sub:
    DEX
    BNE .loop
    LDA $B4 : STA $B2
    LDA $B5 : STA $B3
    RTS


; u16Mod — unsigned 16-bit modulus
; Input:  $B0,$B1 = dividend (u16), $B2,$B3 = divisor (u16)
; Output: $B0,$B1 = remainder (u16)

u16Mod:
    JSR u16Div
    LDA $B2 : STA $B0
    LDA $B3 : STA $B1
    RTS


; u16Mul — unsigned 16-bit multiply
; Input:  $B0,$B1 = operand1 (u16 little-endian)
;         $B2,$B3 = operand2 (u16 little-endian)
; Output: $B0,$B1,$B2,$B3 = result (u32 little-endian)
;
; Method: shift-and-add (16x16 -> 32)

u16Mul:
    ; result in $B4-$B7, then copy to $B0-$B3
    LDA #$00
    STA $B4
    STA $B5
    STA $B6
    STA $B7
    LDX #16 ; 16 bits
.loop:
    LSR $B3
    ROR $B2 ; shift multiplier right
    BCC .no_add
    CLC
    LDA $B4
    ADC $B0
    STA $B4
    LDA $B5
    ADC $B1
    STA $B5
    LDA $B6
    ADC #$00
    STA $B6
    LDA $B7
    ADC #$00
    STA $B7
.no_add:
    ASL $B0
    ROL $B1 ; shift multiplicand left
    DEX
    BNE .loop
    ; Copy result
    LDA $B4 : STA $B0
    LDA $B5 : STA $B1
    LDA $B6 : STA $B2
    LDA $B7 : STA $B3
    RTS



_heap_advance_bank:
    LDA _heap_bank_cur
    BMI _hab_regC
    CMP #heap_bank_last
    BCC _hab_inc_data
    LDA #regC_heap_bank_first
    BEQ _hab_oom
    STA _heap_bank_cur
    CLC
    RTS
_hab_inc_data:
    INC _heap_bank_cur
    CLC
    RTS
_hab_regC:
    CMP #regC_heap_bank_last
    BCS _hab_oom
    INC _heap_bank_cur
    CLC
    RTS
_hab_oom:
    SEC
    RTS

_heap_setup_window:
    LDA _heap_bank_cur
    BMI _hsw_regC
    LDA #<heap_low
    STA _hp_win_lo_lo
    LDA #>heap_low
    STA _hp_win_lo_hi
    LDA #<heap_end
    STA _hp_win_end_lo
    LDA #>heap_end
    STA _hp_win_end_hi
    RTS
_hsw_regC:
    LDA #<regC_heap_low
    STA _hp_win_lo_lo
    LDA #>regC_heap_low
    STA _hp_win_lo_hi
    LDA #<regC_heap_end
    STA _hp_win_end_lo
    LDA #>regC_heap_end
    STA _hp_win_end_hi
    RTS

_heap_init:
    JSR _heap_save_caller_bank
    LDA #heap_bank_first
    STA _heap_bank_cur
_hi_bank_loop:
    LDA _heap_bank_cur
    JSR _heap_select_bank
    JSR _heap_setup_window
    LDA _hp_win_lo_lo
    STA $86
    LDA _hp_win_lo_hi
    STA $86+1

    SEC
    LDA _hp_win_end_lo
    SBC _hp_win_lo_lo
    STA _heap_init_sz
    LDA _hp_win_end_hi
    SBC _hp_win_lo_hi
    ORA #$80 ; set free flag on high byte
    STA _heap_init_sz+1

    LDY #$00
    LDA _heap_init_sz
    STA ($86),Y
    INY
    LDA _heap_init_sz+1
    STA ($86),Y

    JSR _heap_advance_bank
    BCC _hi_bank_loop
_hi_done:
    JMP _heap_restore_caller_bank ; tail-call: RTS through restore

_heap_init_sz:
    .BYTE $00, $00

_heap_alloc:
    JSR _heap_save_caller_bank
    LDX #$00
_ha_body:
    CLC
    ADC #$04
    STA _heap_req
    TXA
    ADC #$00
    STA _heap_req+1

    LDA #heap_bank_first
    STA _heap_bank_cur

_ha_bank_loop:
    LDA _heap_bank_cur
    JSR _heap_select_bank
    JSR _heap_setup_window

    LDA _hp_win_lo_lo
    STA $86
    LDA _hp_win_lo_hi
    STA $86+1

_ha_loop:
    LDA $86+1
    CMP _hp_win_end_hi
    BCC _ha_read
    BNE _ha_next_bank
    LDA $86
    CMP _hp_win_end_lo
    BCS _ha_next_bank

_ha_read:
    LDY #$00
    LDA ($86),Y
    STA _heap_cur_size
    INY
    LDA ($86),Y
    STA _heap_cur_hdr ; preserve raw byte (with free flag)
    AND #$7F
    STA _heap_cur_size+1

    LDA _heap_cur_hdr
    BPL _ha_advance ; allocated → skip

    LDA _heap_cur_size
    CMP _heap_req
    LDA _heap_cur_size+1
    SBC _heap_req+1
    BCC _ha_advance ; too small

    SEC
    LDA _heap_cur_size
    SBC _heap_req
    STA _heap_rem
    LDA _heap_cur_size+1
    SBC _heap_req+1
    STA _heap_rem+1

    LDA _heap_rem+1
    BNE _ha_split
    LDA _heap_rem
    CMP #$04
    BCS _ha_split

    LDY #$01
    LDA _heap_cur_size+1
    STA ($86),Y
    JMP _ha_ret

_ha_split:
    CLC
    LDA $86
    ADC _heap_req
    STA $84
    LDA $86+1
    ADC _heap_req+1
    STA $84+1

    LDY #$00
    LDA _heap_rem
    STA ($84),Y
    INY
    LDA _heap_rem+1
    ORA #$80
    STA ($84),Y

    LDY #$00
    LDA _heap_req
    STA ($86),Y
    INY
    LDA _heap_req+1
    STA ($86),Y

_ha_ret:
    LDY #$02
    LDA #$01
    STA ($86),Y ; retain lo
    INY
    LDA #$00
    STA ($86),Y ; retain hi

    CLC
    LDA $86
    ADC #$04
    STA _heap_ret_lo
    LDA $86+1
    ADC #$00
    STA _heap_ret_hi
    JSR _heap_restore_caller_bank
    LDA _heap_ret_lo
    LDX _heap_ret_hi
    LDY _heap_bank_cur
    RTS

_ha_advance:
    CLC
    LDA $86
    ADC _heap_cur_size
    STA $86
    LDA $86+1
    ADC _heap_cur_size+1
    STA $86+1
    JMP _ha_loop

_ha_next_bank:
    JSR _heap_advance_bank
    BCS _ha_oom
    JMP _ha_bank_loop

_ha_oom:
    JSR _heap_restore_caller_bank
    LDA #$00
    TAX
    TAY
    RTS

_heap_req:
    .BYTE $00, $00
_heap_cur_size:
    .BYTE $00, $00
_heap_cur_hdr:
    .BYTE $00
_heap_rem:
    .BYTE $00, $00
_heap_prev_ptr:
    .BYTE $00, $00
_heap_free_ptr:
    .BYTE $00, $00
_heap_free_bank:
    .BYTE $00
_heap_bank_cur:
    .BYTE $00
_hp_win_lo_lo:
    .BYTE $00
_hp_win_lo_hi:
    .BYTE $00
_hp_win_end_lo:
    .BYTE $00
_hp_win_end_hi:
    .BYTE $00
_heap_ret_lo:
    .BYTE $00
_heap_ret_hi:
    .BYTE $00
_heap_total_lo:
    .BYTE $00
_heap_total_hi:
    .BYTE $00

_heap_del_saved:
    .BYTE $00, $00
_heap_del_hdr:
    .BYTE $00, $00
_heap_del_size:
    .BYTE $00, $00
_heap_del_end:
    .BYTE $00, $00
_heap_del_cur:
    .BYTE $00, $00


; _heap_select_bank: A = 1-based bank id → bank window points at it
_heap_select_bank:
    JSR _xe_deposit_bank ; A ← PORTB bits
    STA _bank_val ; stash bits
    LDA $D301
    AND #$E3 ; preserve non-banking bits
    ORA _bank_val
    STA $D301
    RTS

; _heap_save_caller_bank: snapshot caller's bank register
_heap_save_caller_bank:
    PHA
    LDA $D301
    STA _heap_caller_bank
    PLA
    RTS

; _heap_restore_caller_bank: reselect caller's bank
_heap_restore_caller_bank:
    PHA
    LDA _heap_caller_bank
    STA $D301
    PLA
    RTS

_heap_caller_bank:
    .BYTE $00, $00

__self_bank:
    .BYTE $00

; Banked-pointer load/store helpers (per-target bank switch)
_banked_load_byte:
    LDA $D301
    STA _bank_scratch
    LDA $91 ; bank index
    STA _bank_val ; idx scratch
    TYA
    PHA ; save caller's Y
    TXA
    PHA ; save caller's X
    LDA _bank_val ; reload idx
    JSR _xe_deposit_bank ; A ← PORTB bits for this bank
    STA _bank_val
    LDA $D301
    AND #$E3 ; preserve non-banking bits
    ORA _bank_val
    STA $D301 ; volatile (bank select)
    PLA
    TAX ; restore caller's X
    PLA
    TAY ; restore caller's Y
    LDA ($8F),Y
    PHA
    LDA _bank_scratch
    STA $D301 ; volatile (bank restore)
    PLA
    RTS

_xe_deposit_bank:
    STA _xdb_idx ; A = 0-based index
    LDA #$00
    STA _bank_tmp ; output bits
    LDY #$00
_xdb_loop:
    LDA _xe_mask_bits,Y
    BEQ _xdb_done
    STA _bank_mask ; this mask bit
    LDA _xdb_idx
    LSR A
    STA _xdb_idx
    BCC _xdb_next ; bit 0 — don't deposit
    LDA _bank_tmp
    ORA _bank_mask
    STA _bank_tmp
_xdb_next:
    INY
    JMP _xdb_loop
_xdb_done:
    LDA _bank_tmp
    RTS

_xe_mask_bits:
    .BYTE $04,$08,$00

; ivar (self),Y access bracket — cloaked heap-class bodies
_ivar_store_byte:
    PHA ; save value
    LDA $D301
    STA _ivar_caller_portb
    LDA _ivar_target_portb
    STA $D301 ; PORTB → receiver bank
    PLA ; restore value
    STA ($8A),Y
    PHA ; save value across PORTB restore
    LDA _ivar_caller_portb
    STA $D301
    PLA
    RTS

_bank_scratch:
    .BYTE $00
_bank_val:
    .BYTE $00
_bank_tmp:
    .BYTE $00
_bank_mask:
    .BYTE $00
_xdb_idx:
    .BYTE $00
_ivar_caller_portb:
    .BYTE $00
_ivar_dep_scratch:
    .BYTE $00
_ivar_load_result:
    .BYTE $00
_ivar_offset_save:
    .BYTE $00
_ivar_target_portb:
    .BYTE $00
_cloaked_bracket_portb:
    .BYTE $00
_cloak_retval_lo:
    .BYTE $00
_cloak_retval_hi:
    .BYTE $00

; Cloaked region 'lib' (bank none, $4000-$7FFF)
    .CLOAKED_SEGMENT $4000 none

; Function hello
_fn_hello:

    ; cloaked_hello.xt — stage 4 smoke test for the :cloaked library bank.
    ;
    ; The :cloaked function writes a marker byte to a global. The
    ; caller brackets the JSR in PORTB = $30 / restore (codegen emits
    ; the bracket automatically when it sees the :cloaked annotation)
    ; so the library image at $4000-$7FFF is exposed during the call.
    ; After return, main verifies the marker changed. xe-family only;
    ; on xl / xt sema + codegen reject the annotation.
    ; marker = $A5;
    LDA #$A5
    STA $92 ; marker
; store return value in $B0/$B1 (lo/hi)
    STA $B0
    STX $B1
    RTS

; Method: Stdio.init
_cls_Stdio_init:
; frame save
    LDA $8A
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0019
    INC $83
_L0019:
    LDA $8B
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0020
    INC $83
_L0020:
    LDA $93
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0021
    INC $83
_L0021:
    LDA $94
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0022
    INC $83
_L0022:
    LDA $95
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0023
    INC $83
_L0023:
    LDA $96
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0024
    INC $83
_L0024:
    LDA $97
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0025
    INC $83
_L0025:
    LDA $98
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0026
    INC $83
_L0026:
; self pointer
    LDA $84
    STA $8A
    LDA $85
    STA $8B
; self bank snapshot
    LDA __self_bank
    STA $8C
; ivar target portb cache
    LDA $D301
    AND #$E3 ; clear PORTB mask bits
    PHA
    LDA $8C
    JSR _xe_deposit_bank
    STA _ivar_dep_scratch
    PLA
    ORA _ivar_dep_scratch
    STA _ivar_target_portb ; cached for ivar helpers
    ; asm clobbers(A)
    LDA $57
    STA $95
    LDY #$06 ; mode
    STA ($8A),Y ; mode
    ; asm clobbers(A)
    LDA $58
    STA $96
    LDA $59
    STA $96+1
    LDA $96 ; sbase
    LDX $97 ; sbase
    LDY #$03 ; screenBase
    STA ($8A),Y ; screenBase
    TXA
    LDY #$04
    STA ($8A),Y ; screenBase
    LDA $96 ; sbase
    LDY #$01 ; screenPtr
    STA ($8A),Y ; screenPtr
    TXA
    LDY #$02
    STA ($8A),Y ; screenPtr
    LDY #$06 ; mode
    LDA ($8A),Y
    BNE _L0013
    LDA #$28
    LDY #$05 ; cols
    STA ($8A),Y ; cols
    LDA #$01
    LDY #$07 ; canPrint
    STA ($8A),Y ; canPrint
    JMP _L0014
_L0013:
; else branch
    LDY #$06 ; mode
    LDA ($8A),Y
    CMP #$04
    BCS _L0015
    LDA #$14
    LDY #$05 ; cols
    STA ($8A),Y ; cols
    LDA #$01
    LDY #$07 ; canPrint
    STA ($8A),Y ; canPrint
    JMP _L0016
_L0015:
; else branch
    LDA #$00
    LDY #$05 ; cols
    STA ($8A),Y ; cols
    LDY #$07 ; canPrint
    STA ($8A),Y ; canPrint
_L0016:
_L0014:
    ; asm clobbers(A)
    LDA $02BF
    STA $98
    CMP #$00
    BNE _L0017
    LDA #$18
    LDY #$12 ; rows
    STA ($8A),Y ; rows
    JMP _L0018
_L0017:
; else branch
    LDA $98 ; botlin
    LDY #$12 ; rows
    STA ($8A),Y ; rows
_L0018:
; frame restore
    PHA
    TXA
    PHA
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0027
    DEC $83
_L0027:
    LDY #$00
    LDA ($82),Y
    STA $98
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0028
    DEC $83
_L0028:
    LDY #$00
    LDA ($82),Y
    STA $97
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0029
    DEC $83
_L0029:
    LDY #$00
    LDA ($82),Y
    STA $96
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0030
    DEC $83
_L0030:
    LDY #$00
    LDA ($82),Y
    STA $95
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0031
    DEC $83
_L0031:
    LDY #$00
    LDA ($82),Y
    STA $94
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0032
    DEC $83
_L0032:
    LDY #$00
    LDA ($82),Y
    STA $93
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0033
    DEC $83
_L0033:
    LDY #$00
    LDA ($82),Y
    STA $8B
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0034
    DEC $83
_L0034:
    LDY #$00
    LDA ($82),Y
    STA $8A
    PLA
    TAX
    PLA
    RTS

; Static method: Stdio.scroll
_cls_Stdio_scroll:
; frame save
    LDA $8A
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0036
    INC $83
_L0036:
    LDA $8B
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0037
    INC $83
_L0037:
    LDA $93
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0038
    INC $83
_L0038:
    LDA $94
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0039
    INC $83
_L0039:
    LDA $95
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0040
    INC $83
_L0040:
    LDA $96
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0041
    INC $83
_L0041:
    LDA $97
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0042
    INC $83
_L0042:
    LDA $98
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0043
    INC $83
_L0043:
    LDA $99
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0044
    INC $83
_L0044:
    LDA $9A
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0045
    INC $83
_L0045:
    LDA $9B
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0046
    INC $83
_L0046:
    LDA $9C
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0047
    INC $83
_L0047:
    LDA $9D
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0048
    INC $83
_L0048:
    LDA $9E
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0049
    INC $83
_L0049:
    LDA $9F
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0050
    INC $83
_L0050:
; self pointer
    LDA $84
    STA $8A
    LDA $85
    STA $8B
; self bank snapshot
    LDA __self_bank
    STA $8C
; ivar target portb cache
    LDA $D301
    AND #$E3 ; clear PORTB mask bits
    PHA
    LDA $8C
    JSR _xe_deposit_bank
    STA _ivar_dep_scratch
    PLA
    ORA _ivar_dep_scratch
    STA _ivar_target_portb ; cached for ivar helpers
    LDY #$03 ; screenBase
    LDA ($8A),Y
    PHA
    LDY #$04
    LDA ($8A),Y
    TAX
    PLA
    STA $93 ; sb
    STX $94 ; sb
    LDY #$05 ; cols
    LDA ($8A),Y
    LDX #$00
    STA $95 ; numCols
    STX $96 ; numCols
    PHA
    TXA
    PHA
    LDY #$12 ; rows
    LDA ($8A),Y
    SEC
    SBC #$01
    LDX #$00
    STA $84
    STX $85
    PLA
    TAX
    PLA
    STA $B0
    STX $B1
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    JSR u16Mul
    LDA $B0
    LDX $B1
    STA $97 ; size
    STX $98 ; size
    CLC
    LDA $93 ; sb
    ADC $95
    STA $99 ; src
    LDA $94 ; sb
    ADC $96
    STA $9A ; src
    LDA $93 ; sb
    LDX $94 ; sb
    STA $9B ; dst
    STX $9C ; dst
    LDA $97 ; size
    LDX $98 ; size
    AND #$FF
    PHA
    TXA
    AND #$00
    TAX
    PLA
    STA $9D ; szLo
    LDA $97 ; size
    LDX $98 ; size
    TXA
    LDX #$00
    STA $9E ; szHi
    LDA $95 ; numCols
    LDX $96 ; numCols
    STA $9F ; cLo
    ; asm clobbers(A,X,Y)
    ; Set up indirect pointers in $B0 / $B1 ( $9B ) and
    ; $B2 / $B3 ( $99 ) .The runtime - params region $B0 - $BF
    ; is reserved against ZP - allocated locals so $9B /
    ; $99 can ' t collide with anything sema gave us .
    LDA $9B
    STA $B0
    LDA $9B+1
    STA $B1
    LDA $99
    STA $B2
    LDA $99+1
    STA $B3
    ; -- -- Move ( __sdata_Stdio+18 - 1 ) * __sdata_Stdio+5 bytes up by one row -- --
    ; Outer loop uses $9E pages ( 256 - byte chunks ) plus
    ; an inner DEX / BNE for $9D trailing bytes .Y is
    ; the byte offset within the current page .After
    ; each page wrap we INC the high bytes of both
    ; pointers and walk the next 256 bytes .
    LDX $9E
    BEQ _stdio_scroll_tail
    LDY #$00
_stdio_scroll_page:
    LDA ( $B2 ),Y
    STA ( $B0 ),Y
    INY
    BNE _stdio_scroll_page
    INC $B1
    INC $B3
    DEX
    BNE _stdio_scroll_page
_stdio_scroll_tail:
    LDX $9D
    BEQ _stdio_scroll_clear
    LDY #$00
_stdio_scroll_tail_lp:
    LDA ( $B2 ),Y
    STA ( $B0 ),Y
    INY
    DEX
    BNE _stdio_scroll_tail_lp
    ; Advance the $9B pointer past the bytes we just
    ; copied so the bottom - row clear lands at the
    ; right address .Y holds the byte offset we ended
    ; on ; CLC+ADC walks $B0 forward .
    CLC
    TYA
    ADC $B0
    STA $B0
    BCC _stdio_scroll_clear
    INC $B1
_stdio_scroll_clear:
    ; Clear $95 bytes ( $9F,always less than 256 )
    ; at the $9B ' s current location to give the new
    ; bottom row a blank screen - code - 0 fill .
    LDX $9F
    BEQ _stdio_scroll_done
    LDY #$00
    LDA #$00
_stdio_scroll_clear_lp:
    STA ( $B0 ),Y
    INY
    DEX
    BNE _stdio_scroll_clear_lp
_stdio_scroll_done:
; frame restore
    PHA
    TXA
    PHA
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0051
    DEC $83
_L0051:
    LDY #$00
    LDA ($82),Y
    STA $9F
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0052
    DEC $83
_L0052:
    LDY #$00
    LDA ($82),Y
    STA $9E
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0053
    DEC $83
_L0053:
    LDY #$00
    LDA ($82),Y
    STA $9D
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0054
    DEC $83
_L0054:
    LDY #$00
    LDA ($82),Y
    STA $9C
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0055
    DEC $83
_L0055:
    LDY #$00
    LDA ($82),Y
    STA $9B
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0056
    DEC $83
_L0056:
    LDY #$00
    LDA ($82),Y
    STA $9A
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0057
    DEC $83
_L0057:
    LDY #$00
    LDA ($82),Y
    STA $99
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0058
    DEC $83
_L0058:
    LDY #$00
    LDA ($82),Y
    STA $98
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0059
    DEC $83
_L0059:
    LDY #$00
    LDA ($82),Y
    STA $97
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0060
    DEC $83
_L0060:
    LDY #$00
    LDA ($82),Y
    STA $96
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0061
    DEC $83
_L0061:
    LDY #$00
    LDA ($82),Y
    STA $95
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0062
    DEC $83
_L0062:
    LDY #$00
    LDA ($82),Y
    STA $94
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0063
    DEC $83
_L0063:
    LDY #$00
    LDA ($82),Y
    STA $93
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0064
    DEC $83
_L0064:
    LDY #$00
    LDA ($82),Y
    STA $8B
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0065
    DEC $83
_L0065:
    LDY #$00
    LDA ($82),Y
    STA $8A
    PLA
    TAX
    PLA
    RTS

; Static method: Stdio.putChar
_cls_Stdio_putChar:
; frame save
    LDA $8A
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0083
    INC $83
_L0083:
    LDA $8B
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0084
    INC $83
_L0084:
    LDA $93
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0085
    INC $83
_L0085:
    LDA $94
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0086
    INC $83
_L0086:
    LDA $95
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0087
    INC $83
_L0087:
    LDA $96
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0088
    INC $83
_L0088:
    LDA $97
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0089
    INC $83
_L0089:
    LDA $98
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0090
    INC $83
_L0090:
    LDA $99
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0091
    INC $83
_L0091:
    LDA $9A
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0092
    INC $83
_L0092:
    LDA $9B
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0093
    INC $83
_L0093:
    LDA $9C
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0094
    INC $83
_L0094:
    LDA $FF
    LDY #$00
    STA ($82),Y
    INC $82
    BNE _L0095
    INC $83
_L0095:
; self pointer
    LDA $84
    STA $8A
    LDA $85
    STA $8B
; self bank snapshot
    LDA __self_bank
    STA $8C
; ivar target portb cache
    LDA $D301
    AND #$E3 ; clear PORTB mask bits
    PHA
    LDA $8C
    JSR _xe_deposit_bank
    STA _ivar_dep_scratch
    PLA
    ORA _ivar_dep_scratch
    STA _ivar_target_portb ; cached for ivar helpers
    LDA $B0
    STA $FF
    LDY #$07 ; canPrint
    LDA ($8A),Y
    BNE _L0067
    JMP _L0066
_L0067:
    LDY #$03 ; screenBase
    LDA ($8A),Y
    PHA
    LDY #$04
    LDA ($8A),Y
    TAX
    PLA
    PHA
    TXA
    PHA
    LDY #$05 ; cols
    LDA ($8A),Y
    LDX #$00
    PHA
    TXA
    PHA
    LDY #$12 ; rows
    LDA ($8A),Y
    STA $84
    STX $85
    PLA
    TAX
    PLA
    STA $B0
    STX $B1
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    JSR u16Mul
    LDA $B0
    LDX $B1
    STA $84
    STX $85
    PLA
    TAX
    PLA
    CLC
    ADC $84
    PHA
    TXA
    ADC $85
    TAX
    PLA
    STA $95 ; endPtr
    STX $96 ; endPtr
    LDY #$01 ; screenPtr
    LDA ($8A),Y
    PHA
    LDY #$02
    LDA ($8A),Y
    TAX
    PLA
    STA $97 ; ptr
    STX $98 ; ptr
    LDA $97+1
    CMP $95+1
    BCC _L0071
    BNE _L0074
    LDA $97
    CMP $95
    BCC _L0071
    BNE _L0074
    JMP _L0073
_L0071:
    JMP _L0069
_L0073:
_L0074:
; self.scroll
    LDA $8A
    STA $84
    LDA $8B
    STA $85
; :cloaked → :cloaked same-region (lib) — bracket elided
    JSR _cls_Stdio_scroll
    LDA $95 ; endPtr
    LDX $96 ; endPtr
    PHA
    TXA
    PHA
    LDY #$05 ; cols
    LDA ($8A),Y
    LDX #$00
    STA $84
    STX $85
    PLA
    TAX
    PLA
    SEC
    SBC $84
    PHA
    TXA
    SBC $85
    TAX
    PLA
    LDY #$01 ; screenPtr
    STA ($8A),Y ; screenPtr
    TXA
    LDY #$02
    STA ($8A),Y ; screenPtr
    LDY #$01 ; screenPtr
    LDA ($8A),Y
    PHA
    LDY #$02
    LDA ($8A),Y
    TAX
    PLA
    STA $97 ; ptr
    STX $98 ; ptr
_L0069:
    LDA $FF ; ch
    CMP #$0A
    BNE _L0075
    LDA $97 ; ptr
    LDX $98 ; ptr
    PHA
    TXA
    PHA
    LDY #$03 ; screenBase
    LDA ($8A),Y
    PHA
    LDY #$04
    LDA ($8A),Y
    TAX
    PLA
    STA $84
    STX $85
    PLA
    TAX
    PLA
    SEC
    SBC $84
    PHA
    TXA
    SBC $85
    TAX
    PLA
    STA $99 ; off
    STX $9A ; off
    PHA
    TXA
    PHA
    LDY #$05 ; cols
    LDA ($8A),Y
    STA $84
    LDA #$00
    STA $85
    PLA
    TAX
    PLA
    STA $B0
    STX $B1
    LDA $84
    STA $B2
    LDA #$00
    STA $B3
    JSR u16Mod
    LDA $B0
    LDX $B1
    STA $9B ; rem
    STX $9C ; rem
    LDA $97 ; ptr
    LDX $98 ; ptr
    PHA
    TXA
    PHA
    LDY #$05 ; cols
    LDA ($8A),Y
    LDX #$00
    SEC
    SBC $9B
    PHA
    TXA
    SBC $9C
    TAX
    PLA
    STA $84
    STX $85
    PLA
    TAX
    PLA
    CLC
    ADC $84
    PHA
    TXA
    ADC $85
    TAX
    PLA
    STA $97 ; ptr
    STX $98 ; ptr
    LDY #$01 ; screenPtr
    STA ($8A),Y ; screenPtr
    TXA
    LDY #$02
    STA ($8A),Y ; screenPtr
    JMP _L0066
_L0075:
    LDA $FF ; ch
    AND #$80
    STA $94 ; inv
    LDA $FF ; ch
    AND #$7F
    STA $FF ; ch
    CMP #$20
    BCS _L0077
    LDA $FF ; ch
    CLC
    ADC #$40
    STA $93 ; sc
    JMP _L0078
_L0077:
; else branch
    LDA $FF ; ch
    CMP #$40
    BCS _L0079
    LDA $FF ; ch
    SEC
    SBC #$20
    STA $93 ; sc
    JMP _L0080
_L0079:
; else branch
    LDA $FF ; ch
    CMP #$60
    BCS _L0081
    LDA $FF ; ch
    SEC
    SBC #$20
    STA $93 ; sc
    JMP _L0082
_L0081:
; else branch
    LDA $FF ; ch
    STA $93 ; sc
_L0082:
_L0080:
_L0078:
    LDA $93 ; sc
    ORA $94
    STA $93 ; sc
    PHA
    LDY #$01
    LDA ($8A),Y
    STA $84
    LDY #$02
    LDA ($8A),Y
    STA $85
    PLA
    LDY #$00
    STA ($84),Y ; @screenPtr
    LDY #$01 ; screenPtr
    LDA ($8A),Y
    PHA
    LDY #$02
    LDA ($8A),Y
    TAX
    PLA
    CLC
    ADC #$01
    PHA
    TXA
    ADC #$00
    TAX
    PLA
    LDY #$01 ; screenPtr
    STA ($8A),Y ; screenPtr
    TXA
    LDY #$02
    STA ($8A),Y ; screenPtr
_L0066:
; frame restore
    PHA
    TXA
    PHA
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0096
    DEC $83
_L0096:
    LDY #$00
    LDA ($82),Y
    STA $FF
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0097
    DEC $83
_L0097:
    LDY #$00
    LDA ($82),Y
    STA $9C
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0098
    DEC $83
_L0098:
    LDY #$00
    LDA ($82),Y
    STA $9B
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0099
    DEC $83
_L0099:
    LDY #$00
    LDA ($82),Y
    STA $9A
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0100
    DEC $83
_L0100:
    LDY #$00
    LDA ($82),Y
    STA $99
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0101
    DEC $83
_L0101:
    LDY #$00
    LDA ($82),Y
    STA $98
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0102
    DEC $83
_L0102:
    LDY #$00
    LDA ($82),Y
    STA $97
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0103
    DEC $83
_L0103:
    LDY #$00
    LDA ($82),Y
    STA $96
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0104
    DEC $83
_L0104:
    LDY #$00
    LDA ($82),Y
    STA $95
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0105
    DEC $83
_L0105:
    LDY #$00
    LDA ($82),Y
    STA $94
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0106
    DEC $83
_L0106:
    LDY #$00
    LDA ($82),Y
    STA $93
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0107
    DEC $83
_L0107:
    LDY #$00
    LDA ($82),Y
    STA $8B
    LDA $82
    SEC
    SBC #$01
    STA $82
    BCS _L0108
    DEC $83
_L0108:
    LDY #$00
    LDA ($82),Y
    STA $8A
    PLA
    TAX
    PLA
    RTS
    .CLOAKED_SEGMENT_END

; Bank page $0001 (reserved — placeholder)
    .ORG $4000

; Bank page $0002 (reserved — placeholder)
    .ORG $4000

; Bank page $0003 starts at $4000
    .ORG $4000

; Static method: Stdio.printf
_cls_Stdio_printf:
; frame save (static slot $0500)
    LDA $8A
    STA $0500
    LDA $8B
    STA $0501
    LDA $93
    STA $0502
    LDA $94
    STA $0503
    LDA $95
    STA $0504
    LDA $FE
    STA $0505
    LDA $FF
    STA $0506
; self pointer
    LDA $84
    STA $8A
    LDA $85
    STA $8B
; self bank snapshot
    LDA __self_bank
    STA $8C
    PLA
    STA $84
    PLA
    STA $85
    PLA
    STA $FE
    PLA
    STA $FF
    LDA $85
    PHA
    LDA $84
    PHA
    LDY #$07 ; canPrint
    LDA ($8A),Y
    BNE _L0002
    JMP _L0001
_L0002:
; va_start(ap)  ; header=2
    LDA #$02
    STA $95
    LDA $FE ; fmt
    LDX $FF ; fmt
    STA $84
    STX $85
    LDY #$00
    LDA ($84),Y
    STA $93 ; ch
    JMP _L0004
_L0005:
    LDA $93 ; ch
    CMP #$25
    BNE _L0007
    CLC
    LDA $FE ; fmt
    ADC #$01
    STA $FE ; fmt
    LDA $FF ; fmt
    ADC #$00
    STA $FF ; fmt
    LDA $FE ; fmt
    LDX $FF ; fmt
    STA $84
    STX $85
    LDY #$00
    LDA ($84),Y
    STA $94 ; spec
    CMP #$25
    BNE _L0009
; self.putChar
    LDA #$25
    STA $B0
    LDA $8A
    STA $84
    LDA $8B
    STA $85
; banked → :cloaked _cls_Stdio_putChar (via _xcall_cloaked)
    LDA #<_cls_Stdio_putChar
    STA _xcall_vector
    LDA #>_cls_Stdio_putChar
    STA _xcall_vector+1
    LDA #$32 ; __xtc_portb_lit:_cls_Stdio_putChar
    STA _xcall_cloaked_portb
    JSR _xcall_cloaked
_L0009:
    JMP _L0008
_L0007:
; else branch
; self.putChar
    LDA $93
    STA $B0
    LDA $8A
    STA $84
    LDA $8B
    STA $85
; banked → :cloaked _cls_Stdio_putChar (via _xcall_cloaked)
    LDA #<_cls_Stdio_putChar
    STA _xcall_vector
    LDA #>_cls_Stdio_putChar
    STA _xcall_vector+1
    LDA #$32 ; __xtc_portb_lit:_cls_Stdio_putChar
    STA _xcall_cloaked_portb
    JSR _xcall_cloaked
_L0008:
    CLC
    LDA $FE ; fmt
    ADC #$01
    STA $FE ; fmt
    LDA $FF ; fmt
    ADC #$00
    STA $FF ; fmt
    LDA $FE ; fmt
    LDX $FF ; fmt
    STA $84
    STX $85
    LDY #$00
    LDA ($84),Y
    STA $93 ; ch
_L0004:
    LDA $93 ; ch
    BNE _L0005
; va_end (no-op)
_L0001:
; frame restore (static slot $0500)
    PHA
    TXA
    PHA
    LDA $0506
    STA $FF
    LDA $0505
    STA $FE
    LDA $0504
    STA $95
    LDA $0503
    STA $94
    LDA $0502
    STA $93
    LDA $0501
    STA $8B
    LDA $0500
    STA $8A
    PLA
    TAX
    PLA
    RTS
