;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/comments.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module comments

    ; === function main ===
_main:
    ; var color =
    ; const 40
    LDA #$28
    STA $81
    STA _color
    ; var colbk =
    ; const 53274
    LDA #$1A
    LDX #$D0
    STA $82
    STX $83
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $80
    LDA $80
    LDX #$00
    STA _colbk
    STX _colbk+1
    ; colbk
    STX $81
    LDX _colbk+1
    ; color
    LDA _color
    ; =
    LDA $82
    STA $B2
    LDA _colbk
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
    RTS
    ; === end main ===

    ; === Global variables ===
    _colbk:
        .space 2
    _color:
        .space 1

    ; === Runtime routines ===

