;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/constant.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module constant

    ; === function main ===
_main:
    ; var ram =
    ; const 4
    LDA #$04
    LDX #$00
    STA $80
    STX $81
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    LDX #$00
    STA _ram
    STX _ram+1
    RTS
    ; === end main ===

    ; === Global variables ===
    _ram:
        .space 2

    ; === Runtime routines ===

