;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/enums.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module enums

    ; === function main ===
_main:
    ; var card =
    ; hearts
    LDA _hearts
    STA _card
    ; var prio =
    ; critical
    LDA _critical
    STA _prio
    ; return
    RTS
    ; === end main ===

    ; === Global variables ===
    _card:
        .space 1
    _critical:
        .space 1
    _hearts:
        .space 1
    _prio:
        .space 1

    ; === Runtime routines ===

