;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/funcptr.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module funcptr

    ; === function myISR ===
_myISR:
LDA $D40B
STA $D40A
RTI
    RTS
    ; === end myISR ===
    ; === function main ===
_main:
    ; const 520
    LDA #$08
    LDX #$02
    STA $82
    STX $83
    ; &x
    LDA #_myISR
    LDX #_myISR+1
    STA $80
    STX $81
    ; =
    LDA $80
    STA $B2
    LDA $82
    LDX $83
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
    RTS
    ; === end main ===

    ; === Global variables ===

    ; === Runtime routines ===

