;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/ifthen.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module ifthen

    ; === function main ===
_main:
    ; var vals =
    ; unhandled expr: XTBlockNode
    LDA #$00
    STA $80
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    LDX #$00
    STA _vals
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STX _vals+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _vals+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _vals+3
    ; var t =
    ; const 0
    LDA #$00
    STA $84
    STA _t
    ; for-in
    ; idx = 0
    LDA #$00
    STA $84
    ; vals
    LDA _vals
    STA $85
    LDA _vals+1
    STA $86
    LDA _vals+2
    STA $87
    LDA _vals+3
    STA $88
    LDA $87
    STA $B2
    LDA $88
    STA $B3
    LDA $85
    STX $81
    LDX $86
    LDA $B2
    STA $87
    LDA $B3
    STA $88
    ; heap ptr .length:
    LDA #$04
    LDX #$00
    STA $89
    STX $8A
    ; header = ptr - 4
    SEC
    LDA _vals
    SBC $89
    STA $8B
    LDA _vals+1
    SBC $8A
    STA $8C
    LDA $8B
    LDX $8C
    ; load size from header
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8D
    INY
    LDA ($B0),Y
    STA $8E
    LDA $8D
    LDX $8E
    LDA #$FF
    LDX #$7F
    STA $8F
    STX $90
    ; mask free-flag
    AND $8D
    STA $8B
    LDA $8E
    AND $90
    STA $8C
    LDA $8B
    LDX $8C
    ; size -= header(4)
    SEC
    SBC $89
    STA $8D
    LDA $8C
    SBC $8A
    STA $8E
    LDA $8D
    LDX $8E
    ; cap = size (elemWidth=1)
    ; elemSize
    STA $89
    LDA #$01
    STA $8A
L0:
    ; idx < cap?
    LDA $84
    CMP $89
    ; → end
    BCS L2
    ; load arr[idx]
    LDA _vals
    LDX _vals+1
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $89
    LDA $89
    ; var = arr[idx]
    STA _val
    ; t
    ; val
    LDA _val
    ; compound assign
    CLC
    ADC _t
    STA $8D
    STA _t
    ; (expr stmt discarded)
L1:
    LDA #$01
    STA $89
    ; idx++
    CLC
    ADC $84
    STA $84
    ; addr += elemSize
    CLC
    LDA $8A
    LDX #$00
    STX $8B
    ADC $85
    STA $85
    LDA $86
    ADC $8B
    STA $86
    LDA $85
    LDX $86
    ; → loop
    JMP L0
L2:
    ; t
    ; const 30
    LDA #$1E
    STA $82
    ; cmp
    LDA _t
    CMP $82
    ; -> else
    BEQ L3
    BCC L3
    ; t
    ; const 10
    LDA #$0A
    STA $81
    ; compound assign
    SEC
    LDA _t
    SBC $81
    STA $82
    STA _t
    ; (expr stmt discarded)
    ; -> end
    JMP L4
L3:
    ; t
    ; const 10
    LDA #$0A
    STA $81
    ; compound assign
    CLC
    ADC _t
    STA $82
    STA _t
    ; (expr stmt discarded)
L4:
    RTS
    ; === end main ===

    ; === Global variables ===
    _t:
        .space 1
    _val:
        .space 1
    _vals:
        .space 4

    ; === Runtime routines ===

