;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/largevar.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module largevar

    ; === function main ===
_main:
    ; &arr
    LDA #_val
    LDX #_val+1
    STA $80
    STX $81
    ; const 270
    LDA #$0E
    LDX #$01
    STA $82
    STX $83
    ; arr+idx
    CLC
    ADC $80
    STA $84
    LDA $81
    ADC $83
    STA $85
    LDA $84
    LDX $85
    ; const 4
    LDA #$04
    STA $80
    ; =
    LDA $80
    STA $B2
    LDA $84
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
    RTS
    ; === end main ===

    ; === Global variables ===

    ; === Runtime routines ===

