;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/many-vars.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module many-vars

    ; === function main ===
_main:
    ; var v1 =
    ; const 1
    LDA #$01
    STA $80
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    LDX #$00
    STA _v1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STX _v1+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _v1+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _v1+3
    ; var v2 =
    ; const 2
    LDA #$02
    STA $84
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    STX $81
    LDX #$00
    STA _v2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    STX _v2+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    STA _v2+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    STA _v2+3
    ; var v3 =
    ; const 3
    LDA #$03
    STA $88
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $88
    STX $85
    LDX #$00
    STA _v3
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $88
    STX _v3+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $88
    STA _v3+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $88
    STA _v3+3
    ; var v4 =
    ; const 4
    LDA #$04
    STA $8C
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $8C
    STX $89
    LDX #$00
    STA _v4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $8C
    STX _v4+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $8C
    STA _v4+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $8C
    STA _v4+3
    ; var v5 =
    ; const 5
    LDA #$05
    STA $90
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STX $8D
    LDX #$00
    STA _v5
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STX _v5+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STA _v5+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STA _v5+3
    ; var v6 =
    ; const 6
    LDA #$06
    STA $94
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $94
    STX $91
    LDX #$00
    STA _v6
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $94
    STX _v6+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $94
    STA _v6+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $94
    STA _v6+3
    ; var v7 =
    ; const 7
    LDA #$07
    STA $98
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX $95
    LDX #$00
    STA _v7
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX _v7+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _v7+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _v7+3
    ; var v8 =
    ; const 8
    LDA #$08
    STA $9C
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $9C
    STX $99
    LDX #$00
    STA _v8
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $9C
    STX _v8+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $9C
    STA _v8+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $9C
    STA _v8+3
    ; var v9 =
    ; const 9
    LDA #$09
    STA $A0
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A0
    STX $9D
    LDX #$00
    STA _v9
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A0
    STX _v9+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A0
    STA _v9+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A0
    STA _v9+3
    ; var w1 =
    ; const 1
    LDA #$01
    STA $A4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX $A1
    LDX #$00
    STA _w1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX _w1+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w1+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w1+3
    ; var w2 =
    ; const 2
    LDA #$02
    STA $A4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX $A5
    LDX #$00
    STA _w2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX _w2+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w2+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w2+3
    ; var w3 =
    ; const 3
    LDA #$03
    STA $A4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX $A5
    LDX #$00
    STA _w3
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX _w3+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w3+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w3+3
    ; var w4 =
    ; const 4
    LDA #$04
    STA $A4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX $A5
    LDX #$00
    STA _w4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX _w4+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w4+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w4+3
    ; var w5 =
    ; const 5
    LDA #$05
    STA $A4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX $A5
    LDX #$00
    STA _w5
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX _w5+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w5+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w5+3
    ; var w6 =
    ; const 6
    LDA #$06
    STA $A4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX $A5
    LDX #$00
    STA _w6
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX _w6+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w6+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w6+3
    ; var w7 =
    ; const 7
    LDA #$07
    STA $A4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX $A5
    LDX #$00
    STA _w7
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STX _w7+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w7+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $A4
    STA _w7+3
    ; var w8 =
    ; const 8
    LDA #$08
    STA $98
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX $A5
    LDX #$00
    STA _w8
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX _w8+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _w8+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _w8+3
    ; var w9 =
    ; const 9
    LDA #$09
    STA $98
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX $99
    LDX #$00
    STA _w9
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX _w9+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _w9+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _w9+3
    ; var x1 =
    ; const 1
    LDA #$01
    STA $98
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX $99
    LDX #$00
    STA _x1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX _x1+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x1+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x1+3
    ; var x2 =
    ; const 2
    LDA #$02
    STA $98
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX $99
    LDX #$00
    STA _x2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX _x2+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x2+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x2+3
    ; var x3 =
    ; const 3
    LDA #$03
    STA $98
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX $99
    LDX #$00
    STA _x3
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX _x3+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x3+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x3+3
    ; var x4 =
    ; const 4
    LDA #$04
    STA $98
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX $99
    LDX #$00
    STA _x4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX _x4+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x4+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x4+3
    ; var x5 =
    ; const 5
    LDA #$05
    STA $98
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX $99
    LDX #$00
    STA _x5
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STX _x5+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x5+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $98
    STA _x5+3
    ; var x6 =
    ; const 6
    LDA #$06
    STA $90
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STX $99
    LDX #$00
    STA _x6
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STX _x6+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STA _x6+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STA _x6+3
    ; var a1 =
    ; const 1
    LDA #$01
    STA $90
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STX $91
    LDX #$00
    STA _a1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STX _a1+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STA _a1+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $90
    STA _a1+3
    ; var a2 =
    ; const 2
    LDA #$02
    STA $80
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STX $91
    LDX #$00
    STA _a2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STX _a2+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _a2+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _a2+3
    ; var a3 =
    ; const 3
    LDA #$03
    STA $80
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STX $81
    LDX #$00
    STA _a3
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STX _a3+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _a3+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _a3+3
    ; var a4 =
    ; const 4
    LDA #$04
    STA $80
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STX $81
    LDX #$00
    STA _a4
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STX _a4+1
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _a4+2
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    STA _a4+3
    RTS
    ; === end main ===

    ; === Global variables ===
    _a1:
        .space 4
    _a2:
        .space 4
    _a3:
        .space 4
    _a4:
        .space 4
    _v1:
        .space 4
    _v2:
        .space 4
    _v3:
        .space 4
    _v4:
        .space 4
    _v5:
        .space 4
    _v6:
        .space 4
    _v7:
        .space 4
    _v8:
        .space 4
    _v9:
        .space 4
    _w1:
        .space 4
    _w2:
        .space 4
    _w3:
        .space 4
    _w4:
        .space 4
    _w5:
        .space 4
    _w6:
        .space 4
    _w7:
        .space 4
    _w8:
        .space 4
    _w9:
        .space 4
    _x1:
        .space 4
    _x2:
        .space 4
    _x3:
        .space 4
    _x4:
        .space 4
    _x5:
        .space 4
    _x6:
        .space 4

    ; === Runtime routines ===

