;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/mul_u8u8.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module mul_u8u8

    ; === function main ===
_main:
    ; var t =
    ; const 54
    LDA #$36
    STA $81
    STA _t
    ; var y =
    ; t
    ; t
    LDA _t
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B4
    LDA _t
    JSR _mul16
    STA $82
    LDX #$00
    STA _y
    STX _y+1
    RTS
    ; === end main ===

    ; === Global variables ===
    _t:
        .space 1
    _y:
        .space 2

    ; === Runtime routines ===

_mul16:
    LDA $B4
    STA $B2
    LDA $B5
    STA $B3
    ; Save lhs since we shift multiplicand
    LDA $B0
    STA $B6
    LDA $B1
    STA $B7
    ; Determine sign
    LDA #$00
    STA $B8         ; sign flag
    LDA $B7
    BPL .mul_op1_pos
    ; Negate operand1
    LDA $B6 : EOR #$FF : STA $B6
    LDA $B7 : EOR #$FF : STA $B7
    INC $B6 : BNE .mul_op1_pos : INC $B7
    INC $B8
.mul_op1_pos:
    LDA $B3
    BPL .mul_op2_pos
    ; Negate operand2
    LDA $B2 : EOR #$FF : STA $B2
    LDA $B3 : EOR #$FF : STA $B3
    INC $B2 : BNE .mul_op2_pos : INC $B3
    INC $B8
.mul_op2_pos:
    ; Unsigned multiply: $B6-$B7 x $B2-$B3 -> $B0-$B3
    LDA #$00
    STA $B0
    STA $B1
    STA $B4
    STA $B5
    LDX #16
.mul_loop:
    LSR $B3
    ROR $B2
    BCC .mul_no_add
    CLC
    LDA $B0
    ADC $B6
    STA $B0
    LDA $B1
    ADC $B7
    STA $B1
    LDA $B4
    ADC #$00
    STA $B4
    LDA $B5
    ADC #$00
    STA $B5
.mul_no_add:
    ASL $B6
    ROL $B7
    DEX
    BNE .mul_loop
    ; Apply sign
    LDA $B8
    AND #$01
    BEQ .mul_done
    LDA $B0 : EOR #$FF : STA $B0
    LDA $B1 : EOR #$FF : STA $B1
    INC $B0 : BNE .mul_done : INC $B1
.mul_done:
    ; Return result in A/X
    LDA $B0
    LDX $B1
    RTS
