;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/multi-call.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module multi-call

    ; === function add ===
_add:
	PLA
	STA $B0
	PLA
	STA $B1
    ; val
    PLA
    STA $80
	LDA $B1
	PHA
	LDA $B0
	PHA
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC $80
    STA $82
    ; retain return
    LDX #$00
    LDY #$00
    JSR _obj_retain
    STX $83
    STA $80
    STX $81
    ; return
    RTS
    ; === end add ===
    ; === function main ===
_main:
    ; var t =
    ; const 5
    LDA #$05
    STA $81
    ; arg
    PHA
    ; call
    JSR _add
    STA $83
    ; arg
    PHA
    ; call
    JSR _add
    STA $82
    STA _t
    ; var t2 =
    ; const 5
    LDA #$05
    STA $81
    ; arg
    PHA
    ; call
    JSR _add
    STA $83
    ; arg
    PHA
    ; call
    JSR _add
    STA $80
    ; arg
    PHA
    ; call
    JSR _add
    STA $81
    STA _t2
    ; var t3 =
    ; const 5
    LDA #$05
    STA $81
    ; arg
    PHA
    ; call
    JSR _add
    STA $80
    ; arg
    PHA
    ; call
    JSR _add
    STA $81
    ; arg
    PHA
    ; call
    JSR _add
    STA $80
    ; arg
    PHA
    ; call
    JSR _add
    STA $81
    STA _t3
    RTS
    ; === end main ===

    ; === Global variables ===
    _t:
        .space 1
    _t2:
        .space 1
    _t3:
        .space 1

    ; === Runtime routines ===


    ; === ARC retain-count runtime (flat heap) ===

_heap_save_caller_bank:
    RTS
_heap_select_bank:
    RTS
_heap_restore_caller_bank:
    RTS
_obj_ptr:
        .byte $00, $00
_obj_bank:
        .byte $00
_arc_retval_lo:
        .byte $00
_arc_retval_hi:
        .byte $00
_arc_retval_bank:
        .byte $00
_arc_assign_old_lo:
        .byte $00
_arc_assign_old_hi:
        .byte $00
_arc_assign_old_bank:
        .byte $00
_arc_tx_ptr_lo:
        .byte $00
_arc_tx_ptr_hi:
        .byte $00

_obj_retain:
    JSR _heap_save_caller_bank
    STA _obj_ptr
    STX _obj_ptr+1
    ORA _obj_ptr+1
    BEQ _or_done
    SEC
    LDA _obj_ptr
    SBC #$02
    STA $B0
    LDA _obj_ptr+1
    SBC #$00
    STA $B0+1
    LDY #$01
    LDA ($B0),Y
    CMP #$FF
    BNE _or_inc
    LDY #$00
    LDA ($B0),Y
    CMP #$FF
    BEQ _or_done
_or_inc:
    LDY #$00
    LDA ($B0),Y
    CLC
    ADC #$01
    STA ($B0),Y
    BCC _or_done
    INY
    LDA ($B0),Y
    ADC #$00
    STA ($B0),Y
_or_done:
    JMP _heap_restore_caller_bank

_obj_decref:
    JSR _heap_save_caller_bank
    STA _obj_ptr
    STX _obj_ptr+1
    LDA #$00
    STA _obj_bank
    ORA _obj_ptr+1
    BEQ _od_restore_cc
    SEC
    LDA _obj_ptr
    SBC #$02
    STA $B0
    LDA _obj_ptr+1
    SBC #$00
    STA $B0+1
    LDY #$00
    LDA ($B0),Y
    INY
    ORA ($B0),Y
    BEQ _od_restore_cc
    LDY #$00
    LDA ($B0),Y
    SEC
    SBC #$01
    STA ($B0),Y
    BCS _od_check_zero
    INY
    LDA ($B0),Y
    SBC #$00
    STA ($B0),Y
_od_check_zero:
    LDY #$00
    LDA ($B0),Y
    INY
    ORA ($B0),Y
    BNE _od_restore_cc
    ; (no weak slots in this program)
    JSR _heap_restore_caller_bank
    LDA _obj_ptr
    LDX _obj_ptr+1
    LDY _obj_bank
    SEC
    RTS
_od_restore_cc:
    JSR _heap_restore_caller_bank
    LDA _obj_ptr
    LDX _obj_ptr+1
    LDY _obj_bank
    CLC
    RTS

