;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/shifts.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module shifts

    ; === function main ===
_main:
    ; var v8 =
    ; const 255
    LDA #$FF
    STA $81
    STA _v8
    ; var asl8 =
    ; v8
    ; const 3
    LDA #$03
    STA $81
    ; binop
    LDA $80
    STA $B0
    LDX $81
    BEQ _L1
_L0:
    ASL $B0
    DEX
    BNE _L0
_L1:
    LDA $B0
    STA $82
    LDA $B0
    STA _asl8
    ; var rol8 =
    ; v8
    ; const 3
    LDA #$03
    STA $84
    ; binop
    LDA $83
    STA $B0
    LDX $84
    BEQ _L3
_L2:
    ROR $B0
    DEX
    BNE _L2
_L3:
    LDA $B0
    STA $85
    LDA $B0
    STA _rol8
    ; var asr8 =
    ; v8
    ; const 3
    LDA #$03
    STA $84
    ; binop
    LDA $83
    STA $B0
    LDX $84
    BEQ _L5
_L4:
    LSR $B0
    DEX
    BNE _L4
_L5:
    LDA $B0
    STA $85
    LDA $B0
    STA _asr8
    ; var ror8 =
    ; v8
    ; const 3
    LDA #$03
    STA $85
    ; binop
    LDA $84
    STA $B0
    LDX $85
    BEQ _L7
_L6:
    ROL $B0
    DEX
    BNE _L6
_L7:
    LDA $B0
    STA $82
    LDA $B0
    STA _ror8
    ; v8
    ; const 2
    LDA #$02
    STA $84
    ; binop
    LDA $82
    STA $B0
    LDX $84
    BEQ _L9
_L8:
    ASL $B0
    DEX
    BNE _L8
_L9:
    LDA $B0
    STA $85
    LDA $B0
    ; =
    STA _asl8
    ; (expr stmt discarded)
    ; v8
    ; const 2
    LDA #$02
    STA $84
    ; binop
    LDA $82
    STA $B0
    LDX $84
    BEQ _L11
_L10:
    ROR $B0
    DEX
    BNE _L10
_L11:
    LDA $B0
    STA $85
    LDA $B0
    ; =
    STA _rol8
    ; (expr stmt discarded)
    ; v8
    ; const 2
    LDA #$02
    STA $84
    ; binop
    LDA $82
    STA $B0
    LDX $84
    BEQ _L13
_L12:
    LSR $B0
    DEX
    BNE _L12
_L13:
    LDA $B0
    STA $85
    LDA $B0
    ; =
    STA _asr8
    ; (expr stmt discarded)
    ; v8
    ; const 2
    LDA #$02
    STA $84
    ; binop
    LDA $82
    STA $B0
    LDX $84
    BEQ _L15
_L14:
    ROL $B0
    DEX
    BNE _L14
_L15:
    LDA $B0
    STA $80
    LDA $B0
    ; =
    STA _ror8
    ; (expr stmt discarded)
    ; var v16 =
    ; const 48879
    LDA #$EF
    LDX #$BE
    STA $86
    STX $87
    STA _v16
    STX _v16+1
    ; var asl16 =
    ; v16
    LDX _v16+1
    ; const 8
    LDA #$08
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L17
_L16:
    ASL $B0
    ROL $B1
    DEX
    BNE _L16
_L17:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B0
    LDX $B1
    STA _asl16
    STX _asl16+1
    ; var rol16 =
    ; v16
    LDX _v16+1
    ; const 8
    LDA #$08
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L19
_L18:
    ROR $B1
    ROR $B0
    DEX
    BNE _L18
_L19:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B0
    LDX $B1
    STA _rol16
    STX _rol16+1
    ; var asr16 =
    ; v16
    LDX _v16+1
    ; const 8
    LDA #$08
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L21
_L20:
    LSR $B1
    ROR $B0
    DEX
    BNE _L20
_L21:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B0
    LDX $B1
    STA _asr16
    STX _asr16+1
    ; var ror16 =
    ; v16
    LDX _v16+1
    ; const 8
    LDA #$08
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L23
_L22:
    ROL $B0
    ROL $B1
    DEX
    BNE _L22
_L23:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B0
    LDX $B1
    STA _ror16
    STX _ror16+1
    ; v16
    LDX _v16+1
    ; const 4
    LDA #$04
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L25
_L24:
    ASL $B0
    ROL $B1
    DEX
    BNE _L24
_L25:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B0
    LDX $B1
    ; =
    STA _asl16
    STX _asl16+1
    ; (expr stmt discarded)
    ; v16
    LDX _v16+1
    ; const 4
    LDA #$04
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L27
_L26:
    ROR $B1
    ROR $B0
    DEX
    BNE _L26
_L27:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B0
    LDX $B1
    ; =
    STA _rol16
    STX _rol16+1
    ; (expr stmt discarded)
    ; v16
    LDX _v16+1
    ; const 4
    LDA #$04
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L29
_L28:
    LSR $B1
    ROR $B0
    DEX
    BNE _L28
_L29:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B0
    LDX $B1
    ; =
    STA _asr16
    STX _asr16+1
    ; (expr stmt discarded)
    ; v16
    LDX _v16+1
    ; const 4
    LDA #$04
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L31
_L30:
    ROL $B0
    ROL $B1
    DEX
    BNE _L30
_L31:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B0
    LDX $B1
    ; =
    STA _ror16
    STX _ror16+1
    ; (expr stmt discarded)
    ; var v32 =
    ; const 3735928559
    LDA #$EF
    STA $84
    LDA #$BE
    STA $85
    LDA #$AD
    STA $86
    LDA #$DE
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    STA _v32
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    STX _v32+1
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    STA _v32+2
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    STA _v32+3
    ; var asl32 =
    ; v32
    LDA _v32
    STA $84
    LDA _v32+1
    STA $85
    LDA _v32+2
    STA $86
    LDA _v32+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; const 8
    LDA #$08
    STA $88
    ; u32 op
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDX $88
    BEQ _L33
_L32:
    ASL $B0
    ROL $B1
    ROL $B2
    ROL $B3
    DEX
    BNE _L32
_L33:
    LDA $B0
    STA $8C
    LDA $B1
    STA $8D
    LDA $B2
    STA $8E
    LDA $B3
    STA $8F
    LDA $B0
    LDX $B1
    LDY $B2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _asl32
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STX _asl32+1
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _asl32+2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _asl32+3
    ; var rol32 =
    ; v32
    LDA _v32
    STA $84
    LDA _v32+1
    STA $85
    LDA _v32+2
    STA $86
    LDA _v32+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; const 8
    LDA #$08
    STA $88
    ; u32 op
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDX $88
    BEQ _L35
_L34:
    ROL $B0
    ROL $B1
    ROL $B2
    ROL $B3
    DEX
    BNE _L34
_L35:
    LDA $B0
    STA $8C
    LDA $B1
    STA $8D
    LDA $B2
    STA $8E
    LDA $B3
    STA $8F
    LDA $B0
    LDX $B1
    LDY $B2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _rol32
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STX _rol32+1
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _rol32+2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _rol32+3
    ; var asr32 =
    ; v32
    LDA _v32
    STA $84
    LDA _v32+1
    STA $85
    LDA _v32+2
    STA $86
    LDA _v32+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; const 8
    LDA #$08
    STA $88
    ; u32 op
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDX $88
    BEQ _L37
_L36:
    LSR $B3
    ROR $B2
    ROR $B1
    ROR $B0
    DEX
    BNE _L36
_L37:
    LDA $B0
    STA $8C
    LDA $B1
    STA $8D
    LDA $B2
    STA $8E
    LDA $B3
    STA $8F
    LDA $B0
    LDX $B1
    LDY $B2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _asr32
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STX _asr32+1
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _asr32+2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _asr32+3
    ; var ror32 =
    ; v32
    LDA _v32
    STA $84
    LDA _v32+1
    STA $85
    LDA _v32+2
    STA $86
    LDA _v32+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; const 8
    LDA #$08
    STA $88
    ; u32 op
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDX $88
    BEQ _L39
_L38:
    ROR $B3
    ROR $B2
    ROR $B1
    ROR $B0
    DEX
    BNE _L38
_L39:
    LDA $B0
    STA $8C
    LDA $B1
    STA $8D
    LDA $B2
    STA $8E
    LDA $B3
    STA $8F
    LDA $B0
    LDX $B1
    LDY $B2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _ror32
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STX _ror32+1
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _ror32+2
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    STA _ror32+3
    ; v32
    LDA _v32
    STA $82
    LDA _v32+1
    STA $83
    LDA _v32+2
    STA $84
    LDA _v32+3
    STA $85
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDA $82
    LDX $83
    LDA $B2
    STA $84
    LDA $B3
    STA $85
    ; const 4
    LDA #$04
    STA $86
    ; u32 op
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDX $86
    BEQ _L41
_L40:
    ASL $B0
    ROL $B1
    ROL $B2
    ROL $B3
    DEX
    BNE _L40
_L41:
    LDA $B0
    STA $8A
    LDA $B1
    STA $8B
    LDA $B2
    STA $8C
    LDA $B3
    STA $8D
    LDA $B0
    LDX $B1
    LDY $B2
    ; =
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _asl32
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STX _asl32+1
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _asl32+2
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _asl32+3
    ; (expr stmt discarded)
    ; v32
    LDA _v32
    STA $82
    LDA _v32+1
    STA $83
    LDA _v32+2
    STA $84
    LDA _v32+3
    STA $85
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDA $82
    LDX $83
    LDA $B2
    STA $84
    LDA $B3
    STA $85
    ; const 4
    LDA #$04
    STA $86
    ; u32 op
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDX $86
    BEQ _L43
_L42:
    ROR $B3
    ROR $B2
    ROR $B1
    ROR $B0
    DEX
    BNE _L42
_L43:
    LDA $B0
    STA $8A
    LDA $B1
    STA $8B
    LDA $B2
    STA $8C
    LDA $B3
    STA $8D
    LDA $B0
    LDX $B1
    LDY $B2
    ; =
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _rol32
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STX _rol32+1
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _rol32+2
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _rol32+3
    ; (expr stmt discarded)
    ; v32
    LDA _v32
    STA $82
    LDA _v32+1
    STA $83
    LDA _v32+2
    STA $84
    LDA _v32+3
    STA $85
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDA $82
    LDX $83
    LDA $B2
    STA $84
    LDA $B3
    STA $85
    ; const 4
    LDA #$04
    STA $86
    ; u32 op
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDX $86
    BEQ _L45
_L44:
    LSR $B3
    ROR $B2
    ROR $B1
    ROR $B0
    DEX
    BNE _L44
_L45:
    LDA $B0
    STA $8A
    LDA $B1
    STA $8B
    LDA $B2
    STA $8C
    LDA $B3
    STA $8D
    LDA $B0
    LDX $B1
    LDY $B2
    ; =
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _asr32
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STX _asr32+1
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _asr32+2
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _asr32+3
    ; (expr stmt discarded)
    ; v32
    LDA _v32
    STA $82
    LDA _v32+1
    STA $83
    LDA _v32+2
    STA $84
    LDA _v32+3
    STA $85
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDA $82
    LDX $83
    LDA $B2
    STA $84
    LDA $B3
    STA $85
    ; const 4
    LDA #$04
    STA $86
    ; u32 op
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDX $86
    BEQ _L47
_L46:
    ROL $B0
    ROL $B1
    ROL $B2
    ROL $B3
    DEX
    BNE _L46
_L47:
    LDA $B0
    STA $8A
    LDA $B1
    STA $8B
    LDA $B2
    STA $8C
    LDA $B3
    STA $8D
    LDA $B0
    LDX $B1
    LDY $B2
    ; =
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _ror32
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STX _ror32+1
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _ror32+2
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _ror32+3
    ; (expr stmt discarded)
    RTS
    ; === end main ===

    ; === Global variables ===
    _asl16:
        .space 2
    _asl32:
        .space 4
    _asl8:
        .space 1
    _asr16:
        .space 2
    _asr32:
        .space 4
    _asr8:
        .space 1
    _rol16:
        .space 2
    _rol32:
        .space 4
    _rol8:
        .space 1
    _ror16:
        .space 2
    _ror32:
        .space 4
    _ror8:
        .space 1
    _v16:
        .space 2
    _v32:
        .space 4
    _v8:
        .space 1

    ; === Runtime routines ===

