;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/static.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module static

    ; === function main ===
_main:
    ; call
    JSR _fn
    ; (expr stmt discarded)
    ; call
    JSR _fn
    ; (expr stmt discarded)
    RTS
    ; === end main ===
    ; === function fn ===
_fn:
    ; var a =
    ; const 4
    LDA #$04
    STA $80
    STA _a
    LDA #$01
    STA $82
    ; a
    LDA _a
    ; post++
    CLC
    STA $81
    LDA $80
    ADC $82
    STA $80
    STA _a
    ; (expr stmt discarded)
    RTS
    ; === end fn ===

    ; === Global variables ===
    _a:
        .space 1

    ; === Runtime routines ===

