// AUTOGENERATED — DO NOT EDIT BY HAND.
// Source of truth: tests/gen_struct_byval.py (run to regenerate).
//
// Regression test for struct-by-value parameter passing across
// every struct width from 1 to 20 bytes. Each Sn struct has n
// u8 fields named a0..a{n-1}; sumSn takes Sn by value and
// returns the u16 sum of its fields. main fills 1..n into the
// fields, calls sumSn(s), and checks against n*(n+1)/2.
//
// The 1-16 range fits in the banked target's $B0..$BF register
// window. Widths 17-20 force the compiler onto the wide-arg
// spill path: the banked caller packs bytes into a per-callee
// `_args_<fn>` data-section buffer and the callee prologue
// reads them back from there.
//
// Expected output is 20 consecutive "PASS" lines (one per
// width), at every optimisation level, on both -m xl
// and -m banked. Any divergence means struct-by-value is
// broken at that width — either caller-side push truncation,
// callee-side pop mis-sizing, ZP allocator spill, wide-arg
// label mismatch, or the bank-register routing on the
// banked target.
//
// Fixture hygiene notes:
//   - All fields are u8 so the orthogonal u16-literal-
//     assignment stale-X bug doesn't poison the setup.
//   - Struct instances are globals so main doesn't burn
//     hundreds of bytes of ZP on 32 struct instances and
//     interfere with the banked swappable bank region.
//   - The check logic is inlined at each call site rather
//     than factored into a helper function — a banked helper
//     would itself cross-bank-call Stdio.printf and cross-
//     bank calls from a banked caller are currently broken
//     (the inline bank-switch sequence is interrupted mid-
//     fetch when $82 changes), out of scope for this test.

#import "Stdio.xc"

struct S1 { u8 a0; }
struct S2 { u8 a0; u8 a1; }
struct S3 { u8 a0; u8 a1; u8 a2; }
struct S4 { u8 a0; u8 a1; u8 a2; u8 a3; }
struct S5 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; }
struct S6 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; }
struct S7 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; }
struct S8 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; }
struct S9 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; }
struct S10 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; }
struct S11 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; }
struct S12 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; }
struct S13 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; u8 a12; }
struct S14 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; u8 a12; u8 a13; }
struct S15 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; u8 a12; u8 a13; u8 a14; }
struct S16 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; u8 a12; u8 a13; u8 a14; u8 a15; }
struct S17 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; u8 a12; u8 a13; u8 a14; u8 a15; u8 a16; }
struct S18 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; u8 a12; u8 a13; u8 a14; u8 a15; u8 a16; u8 a17; }
struct S19 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; u8 a12; u8 a13; u8 a14; u8 a15; u8 a16; u8 a17; u8 a18; }
struct S20 { u8 a0; u8 a1; u8 a2; u8 a3; u8 a4; u8 a5; u8 a6; u8 a7; u8 a8; u8 a9; u8 a10; u8 a11; u8 a12; u8 a13; u8 a14; u8 a15; u8 a16; u8 a17; u8 a18; u8 a19; }

S1 g1;
S2 g2;
S3 g3;
S4 g4;
S5 g5;
S6 g6;
S7 g7;
S8 g8;
S9 g9;
S10 g10;
S11 g11;
S12 g12;
S13 g13;
S14 g14;
S15 g15;
S16 g16;
S17 g17;
S18 g18;
S19 g19;
S20 g20;

u16 sumS1(S1 s) { return (u16)s.a0; }
u16 sumS2(S2 s) { return (u16)s.a0 + (u16)s.a1; }
u16 sumS3(S3 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2; }
u16 sumS4(S4 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3; }
u16 sumS5(S5 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4; }
u16 sumS6(S6 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5; }
u16 sumS7(S7 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6; }
u16 sumS8(S8 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7; }
u16 sumS9(S9 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8; }
u16 sumS10(S10 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9; }
u16 sumS11(S11 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10; }
u16 sumS12(S12 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11; }
u16 sumS13(S13 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11 + (u16)s.a12; }
u16 sumS14(S14 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11 + (u16)s.a12 + (u16)s.a13; }
u16 sumS15(S15 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11 + (u16)s.a12 + (u16)s.a13 + (u16)s.a14; }
u16 sumS16(S16 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11 + (u16)s.a12 + (u16)s.a13 + (u16)s.a14 + (u16)s.a15; }
u16 sumS17(S17 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11 + (u16)s.a12 + (u16)s.a13 + (u16)s.a14 + (u16)s.a15 + (u16)s.a16; }
u16 sumS18(S18 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11 + (u16)s.a12 + (u16)s.a13 + (u16)s.a14 + (u16)s.a15 + (u16)s.a16 + (u16)s.a17; }
u16 sumS19(S19 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11 + (u16)s.a12 + (u16)s.a13 + (u16)s.a14 + (u16)s.a15 + (u16)s.a16 + (u16)s.a17 + (u16)s.a18; }
u16 sumS20(S20 s) { return (u16)s.a0 + (u16)s.a1 + (u16)s.a2 + (u16)s.a3 + (u16)s.a4 + (u16)s.a5 + (u16)s.a6 + (u16)s.a7 + (u16)s.a8 + (u16)s.a9 + (u16)s.a10 + (u16)s.a11 + (u16)s.a12 + (u16)s.a13 + (u16)s.a14 + (u16)s.a15 + (u16)s.a16 + (u16)s.a17 + (u16)s.a18 + (u16)s.a19; }

void t_chunk1(void)
{
    u16 exp;
    u16 got;
    u16 id;
    g1.a0 = 1;
    id = 1;
    exp = 1;
    got = sumS1(g1);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g2.a0 = 1;
    g2.a1 = 2;
    id = 2;
    exp = 3;
    got = sumS2(g2);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g3.a0 = 1;
    g3.a1 = 2;
    g3.a2 = 3;
    id = 3;
    exp = 6;
    got = sumS3(g3);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g4.a0 = 1;
    g4.a1 = 2;
    g4.a2 = 3;
    g4.a3 = 4;
    id = 4;
    exp = 10;
    got = sumS4(g4);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g5.a0 = 1;
    g5.a1 = 2;
    g5.a2 = 3;
    g5.a3 = 4;
    g5.a4 = 5;
    id = 5;
    exp = 15;
    got = sumS5(g5);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

}

void t_chunk2(void)
{
    u16 exp;
    u16 got;
    u16 id;
    g6.a0 = 1;
    g6.a1 = 2;
    g6.a2 = 3;
    g6.a3 = 4;
    g6.a4 = 5;
    g6.a5 = 6;
    id = 6;
    exp = 21;
    got = sumS6(g6);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g7.a0 = 1;
    g7.a1 = 2;
    g7.a2 = 3;
    g7.a3 = 4;
    g7.a4 = 5;
    g7.a5 = 6;
    g7.a6 = 7;
    id = 7;
    exp = 28;
    got = sumS7(g7);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g8.a0 = 1;
    g8.a1 = 2;
    g8.a2 = 3;
    g8.a3 = 4;
    g8.a4 = 5;
    g8.a5 = 6;
    g8.a6 = 7;
    g8.a7 = 8;
    id = 8;
    exp = 36;
    got = sumS8(g8);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g9.a0 = 1;
    g9.a1 = 2;
    g9.a2 = 3;
    g9.a3 = 4;
    g9.a4 = 5;
    g9.a5 = 6;
    g9.a6 = 7;
    g9.a7 = 8;
    g9.a8 = 9;
    id = 9;
    exp = 45;
    got = sumS9(g9);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g10.a0 = 1;
    g10.a1 = 2;
    g10.a2 = 3;
    g10.a3 = 4;
    g10.a4 = 5;
    g10.a5 = 6;
    g10.a6 = 7;
    g10.a7 = 8;
    g10.a8 = 9;
    g10.a9 = 10;
    id = 10;
    exp = 55;
    got = sumS10(g10);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

}

void t_chunk3(void)
{
    u16 exp;
    u16 got;
    u16 id;
    g11.a0 = 1;
    g11.a1 = 2;
    g11.a2 = 3;
    g11.a3 = 4;
    g11.a4 = 5;
    g11.a5 = 6;
    g11.a6 = 7;
    g11.a7 = 8;
    g11.a8 = 9;
    g11.a9 = 10;
    g11.a10 = 11;
    id = 11;
    exp = 66;
    got = sumS11(g11);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g12.a0 = 1;
    g12.a1 = 2;
    g12.a2 = 3;
    g12.a3 = 4;
    g12.a4 = 5;
    g12.a5 = 6;
    g12.a6 = 7;
    g12.a7 = 8;
    g12.a8 = 9;
    g12.a9 = 10;
    g12.a10 = 11;
    g12.a11 = 12;
    id = 12;
    exp = 78;
    got = sumS12(g12);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g13.a0 = 1;
    g13.a1 = 2;
    g13.a2 = 3;
    g13.a3 = 4;
    g13.a4 = 5;
    g13.a5 = 6;
    g13.a6 = 7;
    g13.a7 = 8;
    g13.a8 = 9;
    g13.a9 = 10;
    g13.a10 = 11;
    g13.a11 = 12;
    g13.a12 = 13;
    id = 13;
    exp = 91;
    got = sumS13(g13);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g14.a0 = 1;
    g14.a1 = 2;
    g14.a2 = 3;
    g14.a3 = 4;
    g14.a4 = 5;
    g14.a5 = 6;
    g14.a6 = 7;
    g14.a7 = 8;
    g14.a8 = 9;
    g14.a9 = 10;
    g14.a10 = 11;
    g14.a11 = 12;
    g14.a12 = 13;
    g14.a13 = 14;
    id = 14;
    exp = 105;
    got = sumS14(g14);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g15.a0 = 1;
    g15.a1 = 2;
    g15.a2 = 3;
    g15.a3 = 4;
    g15.a4 = 5;
    g15.a5 = 6;
    g15.a6 = 7;
    g15.a7 = 8;
    g15.a8 = 9;
    g15.a9 = 10;
    g15.a10 = 11;
    g15.a11 = 12;
    g15.a12 = 13;
    g15.a13 = 14;
    g15.a14 = 15;
    id = 15;
    exp = 120;
    got = sumS15(g15);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

}

void t_chunk4(void)
{
    u16 exp;
    u16 got;
    u16 id;
    g16.a0 = 1;
    g16.a1 = 2;
    g16.a2 = 3;
    g16.a3 = 4;
    g16.a4 = 5;
    g16.a5 = 6;
    g16.a6 = 7;
    g16.a7 = 8;
    g16.a8 = 9;
    g16.a9 = 10;
    g16.a10 = 11;
    g16.a11 = 12;
    g16.a12 = 13;
    g16.a13 = 14;
    g16.a14 = 15;
    g16.a15 = 16;
    id = 16;
    exp = 136;
    got = sumS16(g16);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g17.a0 = 1;
    g17.a1 = 2;
    g17.a2 = 3;
    g17.a3 = 4;
    g17.a4 = 5;
    g17.a5 = 6;
    g17.a6 = 7;
    g17.a7 = 8;
    g17.a8 = 9;
    g17.a9 = 10;
    g17.a10 = 11;
    g17.a11 = 12;
    g17.a12 = 13;
    g17.a13 = 14;
    g17.a14 = 15;
    g17.a15 = 16;
    g17.a16 = 17;
    id = 17;
    exp = 153;
    got = sumS17(g17);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g18.a0 = 1;
    g18.a1 = 2;
    g18.a2 = 3;
    g18.a3 = 4;
    g18.a4 = 5;
    g18.a5 = 6;
    g18.a6 = 7;
    g18.a7 = 8;
    g18.a8 = 9;
    g18.a9 = 10;
    g18.a10 = 11;
    g18.a11 = 12;
    g18.a12 = 13;
    g18.a13 = 14;
    g18.a14 = 15;
    g18.a15 = 16;
    g18.a16 = 17;
    g18.a17 = 18;
    id = 18;
    exp = 171;
    got = sumS18(g18);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g19.a0 = 1;
    g19.a1 = 2;
    g19.a2 = 3;
    g19.a3 = 4;
    g19.a4 = 5;
    g19.a5 = 6;
    g19.a6 = 7;
    g19.a7 = 8;
    g19.a8 = 9;
    g19.a9 = 10;
    g19.a10 = 11;
    g19.a11 = 12;
    g19.a12 = 13;
    g19.a13 = 14;
    g19.a14 = 15;
    g19.a15 = 16;
    g19.a16 = 17;
    g19.a17 = 18;
    g19.a18 = 19;
    id = 19;
    exp = 190;
    got = sumS19(g19);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

    g20.a0 = 1;
    g20.a1 = 2;
    g20.a2 = 3;
    g20.a3 = 4;
    g20.a4 = 5;
    g20.a5 = 6;
    g20.a6 = 7;
    g20.a7 = 8;
    g20.a8 = 9;
    g20.a9 = 10;
    g20.a10 = 11;
    g20.a11 = 12;
    g20.a12 = 13;
    g20.a13 = 14;
    g20.a14 = 15;
    g20.a15 = 16;
    g20.a16 = 17;
    g20.a17 = 18;
    g20.a18 = 19;
    g20.a19 = 20;
    id = 20;
    exp = 210;
    got = sumS20(g20);
    if (got == exp) { Stdio.printf("T%u PASS\n", id); }
    else { Stdio.printf("T%u FAIL got=%u exp=%u\n", id, got, exp); }

}

void main(void)
{
    t_chunk1();
    t_chunk2();
    t_chunk3();
    t_chunk4();
}
