;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/struct_copy.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module struct_copy

    ; === function main ===
_main:
    ; var c =
    ; unhandled expr: XTBlockNode
    LDA #$00
    STA $80
    LDX #$00
    LDY #$00
    STA _c
    STX _c+1
    STY _c+2
    ; var val =
    ; const 43
    LDA #$2B
    STA $80
    STA _val
    ; var d =
    ; &x
    LDA #_c
    STX $81
    LDX #_c+1
    STA $80
    STX $81
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    STY $82
    LDY #$00
    LDA ($B0),Y
    STA $83
    INY
    LDA ($B0),Y
    STA $84
    INY
    LDA ($B0),Y
    STA $85
    LDA $83
    LDX $84
    LDY $85
    STA _d
    STX _d+1
    STY _d+2
    RTS
    ; === end main ===

    ; === Global variables ===
    _c:
        .space 3
    _d:
        .space 3
    _val:
        .space 1

    ; === Runtime routines ===

