;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/switch_stmt.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module switch_stmt

    ; === method Stdio.init ===
_init:
LDA $57
STA scrMode
    ; scrMode
    LDA _scrMode
    ; =
    STA _mode
    ; (expr stmt discarded)
    STA $81
LDA $58
STA sbase
LDA $59
STA sbase+1
    ; sbase
    LDA _sbase
    LDX _sbase+1
    ; =
    STA _screenBase
    STX _screenBase+1
    ; (expr stmt discarded)
    ; sbase
    LDA _sbase
    LDX _sbase+1
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; mode
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA _mode
    CMP $84
    ; -> else
    BNE L0
    ; const 40
    LDA #$28
    STA $84
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 1
    LDA #$01
    STA $80
    ; =
    STA _canPrint
    ; (expr stmt discarded)
    ; -> end
    JMP L1
L0:
    ; mode
    ; const 4
    LDA #$04
    STA $84
    ; cmp
    LDA _mode
    CMP $84
    ; -> else
    BCS L2
    ; const 20
    LDA #$14
    STA $80
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 1
    LDA #$01
    STA $82
    ; =
    STA _canPrint
    ; (expr stmt discarded)
    ; -> end
    JMP L3
L2:
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _canPrint
    ; (expr stmt discarded)
L3:
L1:
LDA $02BF
STA botlin
    ; botlin
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _botlin
    CMP $82
    ; -> else
    BNE L4
    ; const 24
    LDA #$18
    STA $81
    ; =
    STA _rows
    ; (expr stmt discarded)
    ; -> end
    JMP L5
L4:
    ; botlin
    LDA _botlin
    ; =
    STA _rows
    ; (expr stmt discarded)
L5:
    ; === end Stdio.init ===
    ; === method Stdio.scroll ===
_scroll:
    ; var sb =
    ; screenBase
    LDA _screenBase
    LDX _screenBase+1
    STA _sb
    STX _sb+1
    ; var numCols =
    ; cols
    LDA _cols
    LDX #$00
    STA _numCols
    STX _numCols+1
    ; var size =
    ; numCols
    STX $83
    LDX _numCols+1
    ; rows
    ; const 1
    LDA #$01
    STA $85
    ; binop
    SEC
    LDA _rows
    SBC $85
    STA $80
    ; binop
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDA $80
    STA $B4
    LDA $81
    STA $B5
    LDA _numCols
    JSR _mul16
    STA $84
    STX $85
    STA _size
    STX _size+1
    ; var src =
    ; sb
    ; numCols
    LDA _numCols
    LDX _numCols+1
    ; binop
    CLC
    ADC _sb
    STA $84
    LDA _sb+1
    ADC _numCols+1
    STA $85
    LDA $84
    LDX $85
    STA _src
    STX _src+1
    ; var dst =
    ; sb
    LDA _sb
    LDX _sb+1
    STA _dst
    STX _dst+1
    ; var szLo =
    ; size
    LDX _size+1
    ; const 255
    LDA #$FF
    STA $85
    ; binop
    LDX #$00
    STX $86
    AND _size
    STA $87
    LDA _size+1
    AND $86
    STA $88
    LDA $87
    LDX $88
    STA _szLo
    ; var szHi =
    ; size
    LDX _size+1
    ; const 8
    LDA #$08
    STA $84
    ; binop
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDX $84
    BEQ _L1
_L0:
    LSR $B1
    ROR $B0
    DEX
    BNE _L0
_L1:
    LDA $B0
    STA $80
    LDA $B1
    STA $81
    LDA $B0
    LDX $B1
    STA _szHi
    ; var cLo =
    ; numCols
    LDA _numCols
    LDX _numCols+1
    STA _cLo
; Set up indirect pointers in $B0 / $B1 ( dst ) and
; $B2 / $B3 ( src ) .The runtime - params region $B0 - $BF
; is reserved against ZP - allocated locals so dst /
; src can ' t collide with anything sema gave us .
LDA dst
STA $B0
LDA dst+1
STA $B1
LDA src
STA $B2
LDA src+1
STA $B3
; -- -- Move ( rows - 1 ) * cols bytes up by one row -- --
; Outer loop uses szHi pages ( 256 - byte chunks ) plus
; an inner DEX / BNE for szLo trailing bytes .Y is
; the byte offset within the current page .After
; each page wrap we INC the high bytes of both
; pointers and walk the next 256 bytes .
LDX szHi
BEQ _stdio_scroll_tail
LDY #$00
_stdio_scroll_page :
LDA ( $B2 ),Y
STA ( $B0 ),Y
INY
BNE _stdio_scroll_page
INC $B1
INC $B3
DEX
BNE _stdio_scroll_page
_stdio_scroll_tail :
LDX szLo
BEQ _stdio_scroll_clear
LDY #$00
_stdio_scroll_tail_lp :
LDA ( $B2 ),Y
STA ( $B0 ),Y
INY
DEX
BNE _stdio_scroll_tail_lp
; Advance the dst pointer past the bytes we just
; copied so the bottom - row clear lands at the
; right address .Y holds the byte offset we ended
; on ; CLC+ADC walks $B0 forward .
CLC
TYA
ADC $B0
STA $B0
BCC _stdio_scroll_clear
INC $B1
_stdio_scroll_clear :
; Clear numCols bytes ( cLo,always less than 256 )
; at the dst ' s current location to give the new
; bottom row a blank screen - code - 0 fill .
LDX cLo
BEQ _stdio_scroll_done
LDY #$00
LDA #$00
_stdio_scroll_clear_lp :
STA ( $B0 ),Y
INY
DEX
BNE _stdio_scroll_clear_lp
_stdio_scroll_done :
    ; === end Stdio.scroll ===
    ; === method Stdio.putChar ===
_putChar:
    ; canPrint
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE L0
    ; return
    RTS
L0:
    ; var endPtr =
    ; screenBase
    LDX _screenBase+1
    ; cols
    ; rows
    LDA _rows
    ; binop
    LDA $83
    STA $B0
    LDA $84
    STA $B1
    LDA $85
    STA $B4
    LDA $86
    STA $B5
    LDA _cols
    LDX #$00
    STX $84
    JSR _mul16
    STA $87
    STX $88
    ; binop
    CLC
    ADC _screenBase
    STA $83
    LDA _screenBase+1
    ADC $88
    STA $84
    LDA $83
    LDX $84
    STA _endPtr
    STX _endPtr+1
    ; var ptr =
    ; screenPtr
    LDA _screenPtr
    LDX _screenPtr+1
    STA _ptr
    STX _ptr+1
    ; ptr
    ; endPtr
    LDX _endPtr+1
    ; cmp
    LDA _ptr+1
    CMP _endPtr+1
    BNE _L2
    LDA _ptr
    CMP _endPtr
_L2:
    ; -> else
    BCC L2
    ; __SAVE__::13
    ; call
    JSR _scroll
    ; __RESTORE__
    ; (expr stmt discarded)
    ; endPtr
    LDX _endPtr+1
    ; cols
    LDA _cols
    ; binop
    SEC
    LDX #$00
    STX $86
    LDA _endPtr
    SBC _cols
    STA $87
    LDA _endPtr+1
    SBC _cols+1
    STA $88
    LDA $87
    LDX $88
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; screenPtr
    LDA _screenPtr
    LDX _screenPtr+1
    ; =
    STA _ptr
    STX _ptr+1
    ; (expr stmt discarded)
L2:
    ; ch
    ; const 10
    LDA #$0A
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> else
    BNE L4
    ; ptr
    ; screenBase
    LDA _screenBase
    LDX _screenBase+1
    ; binop
    SEC
    LDA _ptr
    SBC _screenBase
    STA $85
    LDA _ptr+1
    SBC _screenBase+1
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _off
    STX _off+1
    ; (expr stmt discarded)
    ; off
    LDX _off+1
    ; cols
    LDA _cols
    ; binop
    LDA $81
    STA $B0
    LDA $82
    STA $B1
    LDA $83
    STA $B4
    LDA $84
    STA $B5
    LDA _off
    JSR _mod16
    STA $85
    STX $86
    ; =
    STA _rem
    STX _rem+1
    ; (expr stmt discarded)
    ; ptr
    LDX _ptr+1
    ; cols
    ; rem
    LDA _rem
    LDX _rem+1
    ; binop
    LDA _cols
    LDX #$00
    STX $84
    SEC
    SBC _rem
    STA $87
    LDA _cols+1
    SBC _rem+1
    STA $88
    LDA $87
    LDX $88
    ; binop
    CLC
    ADC _ptr
    STA $83
    LDA _ptr+1
    ADC $88
    STA $84
    LDA $83
    LDX $84
    ; =
    STA _ptr
    STX _ptr+1
    ; (expr stmt discarded)
    ; ptr
    LDA _ptr
    LDX _ptr+1
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; return
    RTS
L4:
    ; ch
    ; const 128
    LDA #$80
    STA $84
    ; binop
    AND _ch
    STA $85
    ; =
    STA _inv
    ; (expr stmt discarded)
    ; ch
    ; const 127
    LDA #$7F
    STA $85
    ; binop
    AND _ch
    STA $84
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; ch
    ; const 32
    LDA #$20
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> else
    BCS L6
    ; ch
    ; const 64
    LDA #$40
    STA $85
    ; binop
    CLC
    ADC _ch
    STA $86
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP L7
L6:
    ; ch
    ; const 64
    LDA #$40
    STA $85
    ; cmp
    LDA _ch
    CMP $85
    ; -> else
    BCS L8
    ; ch
    ; const 32
    LDA #$20
    STA $85
    ; binop
    SEC
    LDA _ch
    SBC $85
    STA $86
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP L9
L8:
    ; ch
    ; const 96
    LDA #$60
    STA $85
    ; cmp
    LDA _ch
    CMP $85
    ; -> else
    BCS L10
    ; ch
    ; const 32
    LDA #$20
    STA $85
    ; binop
    SEC
    LDA _ch
    SBC $85
    STA $81
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP L11
L10:
    ; ch
    STA $84
    LDA _ch
    ; =
    STA _sc
    ; (expr stmt discarded)
L11:
L9:
L7:
    ; sc
    ; inv
    LDA _inv
    ; binop
    ORA _sc
    STA $83
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; screenPtr
    LDX _screenPtr+1
    ; sc
    LDA _sc
    ; =
    LDA $83
    STA $B2
    LDA _screenPtr
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
    ; screenPtr
    LDX _screenPtr+1
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _screenPtr
    STA $85
    LDA _screenPtr+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; === end Stdio.putChar ===
    ; === method Stdio.print__s ===
_print__s:
    ; canPrint
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE L0
    ; return
    RTS
L0:
    ; s
    LDA _s
    LDX _s+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _ch
    ; (expr stmt discarded)
L2:
    ; ch
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _ch
    CMP $82
    ; -> end
    BEQ L3
    ; ch
    LDA _ch
    ; __SAVE__:11:10
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; s
    LDX _s+1
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _s
    STA $85
    LDA _s+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _s
    STX _s+1
    ; (expr stmt discarded)
    ; s
    LDA _s
    LDX _s+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP L2
L3:
    ; === end Stdio.print__s ===
    ; === method Stdio.print__u16 ===
_print__u16:
    ; val
    LDX _val+1
    ; const 10
    LDA #$0A
    STA $82
    ; cmp
    LDX #$00
    STX $83
    LDA _val+1
    CMP $83
    BNE _L3
    LDA _val
    CMP $82
_L3:
    ; -> else
    BCC L0
    ; val
    LDX _val+1
    ; const 10
    LDA #$0A
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _val
    JSR _div16
    STA $85
    STX $86
    ; =
    STA _d
    STX _d+1
    ; (expr stmt discarded)
    ; d
    LDA _d
    LDX _d+1
    ; __SAVE__:9:8
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
L0:
    ; val
    LDX _val+1
    ; const 10
    LDA #$0A
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _val
    JSR _mod16
    STA $85
    STX $86
    ; =
    STA _r
    ; (expr stmt discarded)
    ; r
    ; const 48
    LDA #$30
    STA $82
    ; binop
    CLC
    ADC _r
    STA $83
    ; __SAVE__:16:14
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__u16 ===
    ; === method Stdio.print__i16 ===
_print__i16:
    ; val
    LDX _val+1
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDX #$00
    STX $83
    LDA _val+1
    CMP $83
    BNE _L4
    LDA _val
    CMP $82
_L4:
    ; -> else
    BPL L0
    ; const 45
    LDA #$2D
    STA $80
    ; __SAVE__:5:4
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; val
    LDA _val
    LDX _val+1
    ; binop
    LDA $80
    LDX #$00
    STX $81
    SEC
    SBC _val
    STA $84
    LDA $81
    SBC _val+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _val
    STX _val+1
    ; (expr stmt discarded)
L0:
    ; val
    LDA _val
    LDX _val+1
    ; __SAVE__:11:10
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__i16 ===
    ; === method Stdio.print__u32 ===
_print__u32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; cmp
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    LDX #$00
    STX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    LDA _val+3
    CMP $87
    BNE _L5
    LDA _val+2
    CMP $86
    BNE _L5
    LDA _val+1
    CMP $85
    BNE _L5
    LDA _val
    CMP $84
_L5:
    ; -> else
    BCC L0
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; u32 div
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA _val+2
    STA $B2
    LDA _val+3
    STA $B3
    LDA _val
    JSR _div32
    STA $89
    STX $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    ; =
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _d
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STX _d+1
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _d+2
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _d+3
    ; (expr stmt discarded)
    ; d
    LDA _d
    STA $80
    LDA _d+1
    STA $81
    LDA _d+2
    STA $82
    LDA _d+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; __SAVE__:9:8
    ; call
    JSR _print__u32
    ; __RESTORE__
    ; (expr stmt discarded)
L0:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; u32 mod
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA _val+2
    STA $B2
    LDA _val+3
    STA $B3
    LDA _val
    JSR _mod32
    STA $89
    STX $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    ; =
    LDA $89
    STA _r
    ; (expr stmt discarded)
    ; r
    ; const 48
    LDA #$30
    STA $82
    ; binop
    CLC
    ADC _r
    STA $83
    ; __SAVE__:16:14
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__u32 ===
    ; === method Stdio.print__i32 ===
_print__i32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    LDX #$00
    STX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    LDA _val+3
    CMP $87
    BNE _L6
    LDA _val+2
    CMP $86
    BNE _L6
    LDA _val+1
    CMP $85
    BNE _L6
    LDA _val
    CMP $84
_L6:
    ; -> else
    BPL L0
    ; const 45
    LDA #$2D
    STA $80
    ; __SAVE__:5:4
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; val
    LDA _val
    STA $84
    LDA _val+1
    STA $85
    LDA _val+2
    STA $86
    LDA _val+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    LDX #$00
    STX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    SEC
    LDA $80
    SBC _val
    STA $88
    LDA $81
    SBC _val+1
    STA $89
    LDA $82
    SBC _val+2
    STA $8A
    LDA $83
    SBC _val+3
    STA $8B
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    LDX $89
    ; =
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    STA _val
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    STX _val+1
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    STA _val+2
    LDA $8A
    STA $B2
    LDA $8B
    STA $B3
    LDA $88
    STA _val+3
    ; (expr stmt discarded)
L0:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; __SAVE__:11:10
    ; call
    JSR _print__u32
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__i32 ===
    ; === method Stdio.printHex__u8 ===
_printHex__u8:
    ; n
    ; const 10
    LDA #$0A
    STA $81
    ; cmp
    LDA _n
    CMP $81
    ; -> else
    BCS L0
    ; n
    ; const 48
    LDA #$30
    STA $81
    ; binop
    CLC
    ADC _n
    STA $86
    ; __SAVE__:6:4
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP L1
L0:
    ; n
    ; const 55
    LDA #$37
    STA $81
    ; binop
    CLC
    ADC _n
    STA $82
    ; __SAVE__:10:8
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
L1:
    ; === end Stdio.printHex__u8 ===
    ; === method Stdio.printHex__u16 ===
_printHex__u16:
    ; val
    LDX _val+1
    ; const 12
    LDA #$0C
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $82
    BEQ _L8
_L7:
    LSR $B1
    ROR $B0
    DEX
    BNE _L7
_L8:
    LDA $B0
    STA $86
    LDA $B1
    STA $87
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $88
    ; binop
    LDX #$00
    STX $89
    AND $86
    STA $8A
    LDA $87
    AND $89
    STA $8B
    LDA $8A
    LDX $8B
    ; __SAVE__:5:1
    ; call
    JSR _printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    ; const 8
    LDA #$08
    STA $88
    ; binop
    LDA $86
    STA $B0
    LDA $87
    STA $B1
    LDX $88
    BEQ _L10
_L9:
    LSR $B1
    ROR $B0
    DEX
    BNE _L9
_L10:
    LDA $B0
    STA $8A
    LDA $B1
    STA $8B
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $84
    ; binop
    LDX #$00
    STX $85
    AND $8A
    STA $86
    LDA $8B
    AND $85
    STA $87
    LDA $86
    LDX $87
    ; __SAVE__:11:7
    ; call
    JSR _printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    ; const 4
    LDA #$04
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _L12
_L11:
    LSR $B1
    ROR $B0
    DEX
    BNE _L11
_L12:
    LDA $B0
    STA $80
    LDA $B1
    STA $81
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $82
    ; binop
    LDX #$00
    STX $83
    AND $80
    STA $84
    LDA $81
    AND $83
    STA $85
    LDA $84
    LDX $85
    ; __SAVE__:17:13
    ; call
    JSR _printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    ; const 15
    LDA #$0F
    STA $84
    ; binop
    LDX #$00
    STX $85
    AND _val
    STA $86
    LDA _val+1
    AND $85
    STA $87
    LDA $86
    LDX $87
    ; __SAVE__:21:19
    ; call
    JSR _printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printHex__u16 ===
    ; === method Stdio.printHex__u32 ===
_printHex__u32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 16
    LDA #$10
    STA $84
    ; u32 op
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDX $84
    BEQ _L14
_L13:
    LSR $B3
    ROR $B2
    ROR $B1
    ROR $B0
    DEX
    BNE _L13
_L14:
    LDA $B0
    STA $88
    LDA $B1
    STA $89
    LDA $B2
    STA $8A
    LDA $B3
    STA $8B
    LDA $B0
    LDX $B1
    LDY $B2
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $80
    STX $81
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    LDA $88
    AND $80
    STA $8C
    LDA $89
    AND $81
    STA $8D
    LDA $8A
    AND $82
    STA $8E
    LDA $8B
    AND $83
    STA $8F
    LDA $8E
    STA $B2
    LDA $8F
    STA $B3
    LDA $8C
    LDX $8D
    ; __SAVE__:6:1
    ; call
    JSR _printHex__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $86
    STX $87
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $86
    LDA $B2
    STA $88
    LDA $B3
    STA $89
    LDA _val
    AND $86
    STA $8A
    LDA _val+1
    AND $87
    STA $8B
    LDA _val+2
    AND $88
    STA $8C
    LDA _val+3
    AND $89
    STA $8D
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    LDX $8B
    ; __SAVE__:10:7
    ; call
    JSR _printHex__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printHex__u32 ===
    ; === method Stdio.print__f ===
_print__f:
    ; canPrint
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE L0
    ; return
    RTS
L0:
LDA f : STA $B0
LDA f+1 : STA $B1
LDA f+2 : STA $B2
LDA f+3 : STA $B3
LDA f+4 : STA $B4
LDA #< $04C0
STA $B5
LDY #_ivar_Stdio_fpBufPtr
STA ( __self ),Y
LDA #> $04C0
STA $B6
LDY #_ivar_Stdio_fpBufPtr+1
STA ( __self ),Y
JSR fp2Asc
    ; fpBufPtr
    LDA _fpBufPtr
    LDX _fpBufPtr+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _ch
    ; (expr stmt discarded)
L2:
    ; ch
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _ch
    CMP $82
    ; -> end
    BEQ L3
    ; ch
    LDA _ch
    ; __SAVE__:11:10
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fpBufPtr
    LDX _fpBufPtr+1
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _fpBufPtr
    STA $85
    LDA _fpBufPtr+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _fpBufPtr
    STX _fpBufPtr+1
    ; (expr stmt discarded)
    ; fpBufPtr
    LDA _fpBufPtr
    LDX _fpBufPtr+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP L2
L3:
    ; === end Stdio.print__f ===
    ; === method Stdio.setCursor ===
_setCursor:
    ; y
    LDA _y
    ; =
    LDX #$00
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; offset
    STX $81
    LDX _offset+1
    ; cols
    LDA _cols
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _offset
    JSR _mul16
    STA $84
    STX $85
    ; =
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; offset
    LDX _offset+1
    ; x
    LDA _x
    ; binop
    CLC
    LDX #$00
    STX $83
    ADC _offset
    STA $84
    LDA _offset+1
    ADC _x+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; screenBase
    ; offset
    LDA _offset
    LDX _offset+1
    ; binop
    CLC
    ADC _screenBase
    STA $84
    LDA _screenBase+1
    ADC _offset+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; === end Stdio.setCursor ===
    ; === method Stdio.printStruct ===
_printStruct:
    ; const 40
    LDA #$28
    STA $80
    ; __SAVE__:2:1
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8C
    LDA $8C
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8D
    ; binop
    CLC
    LDX #$00
    STX $8E
    ADC _psDesc
    STA $8F
    LDA _psDesc+1
    ADC $8E
    STA $90
    LDA $8F
    LDX $90
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $8B
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $8B
    ; =
    STA _depth
    ; (expr stmt discarded)
L0:
    ; const 1
    LDA #$01
    STA $8B
    ; -> end
    BEQ L1
    ; psIdx
    ; psFieldCount
    ; cmp
    LDA _psIdx
    CMP _psFieldCount
    ; -> else
    BCC L2
    ; const 41
    LDA #$29
    STA $91
    ; __SAVE__:19:18
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; depth
    ; const 0
    LDA #$00
    STA $91
    ; cmp
    LDA _depth
    CMP $91
    ; -> else
    BNE L4
    ; return
    RTS
L4:
LDY #$00
DEC $82 : BCS .pop_a : DEC $83
.pop_a :
LDA ( $82 ),Y : STA __sdata_Stdio+14 ; psIdx
DEC $82 : BCS .pop_b : DEC $83
.pop_b :
LDA ( $82 ),Y : STA __sdata_Stdio+13 ; psFieldCount
DEC $82 : BCS .pop_c : DEC $83
.pop_c :
LDA ( $82 ),Y : STA __sdata_Stdio+12 ; psDesc hi
DEC $82 : BCS .pop_d : DEC $83
.pop_d :
LDA ( $82 ),Y : STA __sdata_Stdio+11 ; psDesc lo
DEC $82 : BCS .pop_e : DEC $83
.pop_e :
LDA ( $82 ),Y : STA __sdata_Stdio+10 ; psDp hi
DEC $82 : BCS .pop_f : DEC $83
.pop_f :
LDA ( $82 ),Y : STA __sdata_Stdio+9 ; psDp lo
    ; depth
    ; const 1
    LDA #$01
    STA $91
    ; binop
    SEC
    LDA _depth
    SBC $91
    STA $92
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; continue
    JMP L0
L2:
    ; psIdx
    ; const 0
    LDA #$00
    STA $91
    ; cmp
    LDA _psIdx
    CMP $91
    ; -> else
    BEQ L6
    BCC L6
    ; const 44
    LDA #$2C
    STA $93
    ; __SAVE__:31:30
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 32
    LDA #$20
    STA $93
    ; __SAVE__:33:32
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
L6:
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8C
    LDA $8C
    ; =
    STA _fieldType
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $84
    ; binop
    CLC
    LDX #$00
    STX $85
    ADC _psDesc
    STA $95
    LDA _psDesc+1
    ADC $85
    STA $96
    LDA $95
    LDX $96
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8C
    LDA $8C
    ; =
    STA _fieldSize
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $93
    ; binop
    CLC
    LDX #$00
    STX $94
    ADC _psDesc
    STA $95
    LDA _psDesc+1
    ADC $94
    STA $96
    LDA $95
    LDX $96
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; fieldType
    ; const 0
    LDA #$00
    STA $8C
    ; cmp
    LDA _fieldType
    CMP $8C
    ; -> else
    BNE L8
    ; psDp
    LDA _psDp
    STX $92
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $91
    LDA $91
    ; __SAVE__:53:51
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $91
    ; binop
    CLC
    LDX #$00
    STX $92
    ADC _psDp
    STA $93
    LDA _psDp+1
    ADC $92
    STA $94
    LDA $93
    LDX $94
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; -> end
    JMP L9
L8:
    ; fieldType
    ; const 2
    LDA #$02
    STA $8C
    ; cmp
    LDA _fieldType
    CMP $8C
    ; -> else
    BNE L10
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8B
    ; binop
    CLC
    LDX #$00
    STX $8C
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC $8C
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8B
    ; binop
    CLC
    LDX #$00
    STX $8C
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC $8C
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    LDA _hi
    ; =
    LDX #$00
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    STX $81
    LDX _fieldVal+1
    ; const 8
    LDA #$08
    STA $8B
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8B
    BEQ _L16
_L15:
    ASL $B0
    ROL $B1
    DEX
    BNE _L15
_L16:
    LDA $B0
    STA $91
    LDA $B1
    STA $92
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $91
    STA $8B
    LDA $92
    ORA _lo+1
    STA $8C
    LDA $8B
    LDX $8C
    ; =
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    LDA _fieldVal
    LDX _fieldVal+1
    ; __SAVE__:84:83
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP L11
L10:
    ; fieldType
    ; const 3
    LDA #$03
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE L12
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    LDA _hi
    ; =
    LDX #$00
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    STX $81
    LDX _fieldVal+1
    ; const 8
    LDA #$08
    STA $8A
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8A
    BEQ _L18
_L17:
    ASL $B0
    ROL $B1
    DEX
    BNE _L17
_L18:
    LDA $B0
    STA $91
    LDA $B1
    STA $92
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $91
    STA $8A
    LDA $92
    ORA _lo+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    LDA _fieldVal
    LDX _fieldVal+1
    ; __SAVE__:111:110
    ; call
    JSR _print__i16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP L13
L12:
    ; fieldType
    ; const 8
    LDA #$08
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE L14
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $91
    LDA _psDesc+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $91
    LDA _psDesc+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psIdx
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $83
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; =
    STA _psSaveDp
    STX _psSaveDp+1
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; fieldSize
    LDA _fieldSize
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $91
    LDA _psDp+1
    ADC _fieldSize+1
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
LDY #$00
LDA __sdata_Stdio+9 : STA ( $82 ),Y ; psDp lo ( post - struct )
INC $82 : BNE .push8_a : INC $83
.push8_a :
LDA __sdata_Stdio+10 : STA ( $82 ),Y ; psDp hi
INC $82 : BNE .push8_b : INC $83
.push8_b :
LDA __sdata_Stdio+11 : STA ( $82 ),Y ; psDesc lo
INC $82 : BNE .push8_c : INC $83
.push8_c :
LDA __sdata_Stdio+12 : STA ( $82 ),Y ; psDesc hi
INC $82 : BNE .push8_d : INC $83
.push8_d :
LDA __sdata_Stdio+13 : STA ( $82 ),Y ; psFieldCount
INC $82 : BNE .push8_e : INC $83
.push8_e :
LDA __sdata_Stdio+14 : STA ( $82 ),Y ; psIdx
INC $82 : BNE .push8_f : INC $83
.push8_f :
    ; depth
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _depth
    STA $83
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; psSaveDp
    LDA _psSaveDp
    LDX _psSaveDp+1
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    ; const 8
    LDA #$08
    STA $8A
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8A
    BEQ _L20
_L19:
    ASL $B0
    ROL $B1
    DEX
    BNE _L19
_L20:
    LDA $B0
    STA $91
    LDA $B1
    STA $92
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $91
    STA $8A
    LDA $92
    ORA _lo+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $91
    LDA _psDesc+1
    ADC $8B
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 40
    LDA #$28
    STA $91
    ; __SAVE__:161:160
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; continue
    JMP L0
    ; -> end
    JMP L15
L14:
    ; fieldType
    ; const 9
    LDA #$09
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE L16
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _dpLo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $8C
    LDA _psDp+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _dpHi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDp
    STA $8C
    LDA _psDp+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $8C
    LDA _psDesc+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $8C
    LDA _psDesc+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psIdx
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $83
    ; =
    STA _psIdx
    ; (expr stmt discarded)
LDY #$00
LDA __sdata_Stdio+9 : STA ( $82 ),Y ; psDp lo ( post - pointer )
INC $82 : BNE .push9_a : INC $83
.push9_a :
LDA __sdata_Stdio+10 : STA ( $82 ),Y ; psDp hi
INC $82 : BNE .push9_b : INC $83
.push9_b :
LDA __sdata_Stdio+11 : STA ( $82 ),Y ; psDesc lo
INC $82 : BNE .push9_c : INC $83
.push9_c :
LDA __sdata_Stdio+12 : STA ( $82 ),Y ; psDesc hi
INC $82 : BNE .push9_d : INC $83
.push9_d :
LDA __sdata_Stdio+13 : STA ( $82 ),Y ; psFieldCount
INC $82 : BNE .push9_e : INC $83
.push9_e :
LDA __sdata_Stdio+14 : STA ( $82 ),Y ; psIdx
INC $82 : BNE .push9_f : INC $83
.push9_f :
    ; depth
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _depth
    STA $83
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; dpHi
    ; const 8
    LDA #$08
    STA $8A
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8A
    BEQ _L22
_L21:
    ASL $B0
    ROL $B1
    DEX
    BNE _L21
_L22:
    LDA $B0
    STA $8C
    LDA $B1
    STA $8D
    LDA $B0
    LDX $B1
    ; dpLo
    LDA _dpLo
    ; binop
    LDX #$00
    STX $81
    ORA $8C
    STA $8A
    LDA $8D
    ORA _dpLo+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _psSaveDp
    STX _psSaveDp+1
    ; (expr stmt discarded)
    ; psSaveDp
    LDA _psSaveDp
    LDX _psSaveDp+1
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    ; const 8
    LDA #$08
    STA $8A
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8A
    BEQ _L24
_L23:
    ASL $B0
    ROL $B1
    DEX
    BNE _L23
_L24:
    LDA $B0
    STA $8C
    LDA $B1
    STA $8D
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $8C
    STA $8A
    LDA $8D
    ORA _lo+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    ; const 1
    LDA #$01
    STA $8A
    ; binop
    CLC
    LDX #$00
    STX $8B
    ADC _psDesc
    STA $8C
    LDA _psDesc+1
    ADC $8B
    STA $8D
    LDA $8C
    LDX $8D
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 40
    LDA #$28
    STA $8A
    ; __SAVE__:225:224
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; continue
    JMP L0
    ; -> end
    JMP L17
L16:
    ; psDp
    LDX _psDp+1
    ; fieldSize
    LDA _fieldSize
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _psDp
    STA $8A
    LDA _psDp+1
    ADC _fieldSize+1
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; const 63
    LDA #$3F
    STA $8A
    ; __SAVE__:231:230
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
L17:
L15:
L13:
L11:
L9:
    ; psIdx
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $82
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; -> loop
    JMP L0
L1:
    ; === end Stdio.printStruct ===
    ; === method Stdio.printf ===
_printf:
    ; canPrint
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE L0
    ; return
    RTS
L0:
    ; ap
    LDA _ap
    ; __SAVE__:5:4
    ; call
    JSR __intrinsic_va_start
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $81
    LDA $81
    ; =
    STA _ch
    ; (expr stmt discarded)
L2:
    ; ch
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> end
    BEQ L3
    ; ch
    ; const 37
    LDA #$25
    STA $86
    ; cmp
    LDA _ch
    CMP $86
    ; -> else
    BNE L4
    ; fmt
    LDX _fmt+1
    ; const 1
    LDA #$01
    STA $88
    ; binop
    CLC
    LDX #$00
    STX $89
    ADC _fmt
    STA $8A
    LDA _fmt+1
    ADC $89
    STA $8B
    LDA $8A
    LDX $8B
    ; =
    STA _fmt
    STX _fmt+1
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $81
    LDA $81
    ; =
    STA _spec
    ; (expr stmt discarded)
    ; spec
    ; const 37
    LDA #$25
    STA $86
    ; cmp
    LDA _spec
    CMP $86
    ; -> else
    BNE L6
    ; const 37
    LDA #$25
    STA $86
    ; __SAVE__:26:25
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP L7
L6:
    ; spec
    ; const 117
    LDA #$75
    STA $87
    ; cmp
    LDA _spec
    CMP $87
    ; -> else
    BNE L8
    ; ap
    LDA _ap
    ; __SAVE__:32:31
    ; call
    JSR __intrinsic_va_arg_u16
    STA $88
    STX $89
    ; __RESTORE__
    ; __SAVE__:31:30
    ; call
    JSR _print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
L8:
L7:
    ; -> end
    JMP L5
L4:
    ; ch
    LDA _ch
    ; __SAVE__:34:33
    ; call
    JSR _putChar
    ; __RESTORE__
    ; (expr stmt discarded)
L5:
    ; fmt
    LDX _fmt+1
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _fmt
    STA $84
    LDA _fmt+1
    ADC $87
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _fmt
    STX _fmt+1
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP L2
L3:
    ; ap
    LDA _ap
    ; __SAVE__:43:42
    ; call
    JSR __intrinsic_va_end
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printf ===
    ; === method Stdio.printfAt ===
_printfAt:
    ; x
    ; y
    LDA _y
    ; __SAVE__:2,3:1
    ; call
    JSR _setCursor
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; __SAVE__:5:4
    ; call
    JSR _printf
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printfAt ===
    ; === function checkU8 ===
_checkU8:
	PLA
	STA $B0
	PLA
	STA $B1
    ; got
    PLA
    STA $80
    ; want
    PLA
    STA $81
	LDA $B1
	PHA
	LDA $B0
	PHA
    ; testCount
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    ADC _testCount
    STA $84
    ; =
    STA _testCount
    ; (expr stmt discarded)
    ; cmp
    LDA $80
    CMP $81
    ; -> else
    BEQ L0
    ; failCount
    ; const 16
    LDA #$10
    STA $83
    ; cmp
    LDA _failCount
    CMP $83
    ; -> else
    BCS L2
    ; &arr
    LDA #_fails
    LDX #_fails+1
    STA $83
    STX $84
    ; failCount
    LDA _failCount
    ; arr+idx
    CLC
    LDX #$00
    STX $86
    ADC $83
    STA $87
    LDA $84
    ADC _failCount+1
    STA $88
    LDA $87
    LDX $88
    ; testCount
    LDA _testCount
    ; =
    LDA $81
    STA $B2
    LDA $87
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
L2:
    ; failCount
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    ADC _failCount
    STA $80
    ; =
    STA _failCount
    ; (expr stmt discarded)
L0:
    RTS
    ; === end checkU8 ===
    ; === function main ===
_main:
    ; const 0
    STA $8F
    LDA #$00
    STA $80
    ; =
    STA _testCount
    ; (expr stmt discarded)
    ; const 0
    STA $81
    LDA #$00
    STA $82
    ; =
    STA _failCount
    ; (expr stmt discarded)
    ; const 1
    STA $83
    LDA #$01
    STA $84
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    STA $85
    LDA #$00
    STA $86
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 1
    LDA #$01
    STA $89
    ; switch case
    LDA _gVal8
    CMP $89
    ; -> case
    BEQ L1
    ; const 2
    LDA #$02
    STA $8B
    ; switch case
    LDA _gVal8
    CMP $8B
    ; -> case
    BEQ L2
    ; const 3
    LDA #$03
    STA $8D
    ; switch case
    LDA _gVal8
    CMP $8D
    ; -> case
    BEQ L2
    ; const 4
    LDA #$04
    STA $8F
    ; switch case
    LDA _gVal8
    CMP $8F
    ; -> case
    BEQ L2
    ; const 5
    LDA #$05
    STA $91
    ; switch case
    LDA _gVal8
    CMP $91
    ; -> case
    BEQ L3
    ; -> default
    JMP L4
L1:
    ; const 17
    LDA #$11
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L0
L2:
    ; const 34
    STA $92
    LDA #$22
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L0
L3:
    ; const 51
    LDA #$33
    STA $94
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L0
L4:
    ; const 255
    LDA #$FF
    STA $95
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L0
L0:
    ; gOut
    ; const 17
    LDA #$11
    STA $99
    ; arg
    PHA
    ; arg
    LDA $95
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 5
    LDA #$05
    STA $95
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $93
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 1
    LDA #$01
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L6
    ; const 2
    LDA #$02
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L7
    ; const 3
    LDA #$03
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L7
    ; const 4
    LDA #$04
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L7
    ; const 5
    LDA #$05
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L8
    ; -> default
    JMP L9
L6:
    ; const 17
    LDA #$11
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L5
L7:
    ; const 34
    LDA #$22
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L5
L8:
    ; const 51
    LDA #$33
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L5
L9:
    ; const 255
    LDA #$FF
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L5
L5:
    ; gOut
    ; const 51
    LDA #$33
    STA $9D
    ; arg
    PHA
    ; arg
    LDA $99
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 3
    LDA #$03
    STA $96
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 1
    LDA #$01
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L11
    ; const 2
    LDA #$02
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L12
    ; const 3
    LDA #$03
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L12
    ; const 4
    LDA #$04
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L12
    ; const 5
    LDA #$05
    STA $97
    ; switch case
    LDA _gVal8
    CMP $97
    ; -> case
    BEQ L13
    ; -> default
    JMP L14
L11:
    ; const 17
    LDA #$11
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L10
L12:
    ; const 34
    LDA #$22
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L10
L13:
    ; const 51
    LDA #$33
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L10
L14:
    ; const 255
    LDA #$FF
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L10
L10:
    ; gOut
    ; const 34
    LDA #$22
    STA $9D
    ; arg
    PHA
    ; arg
    LDA $99
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 2
    LDA #$02
    STA $96
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 2
    LDA #$02
    STA $99
    ; switch case
    LDA _gVal8
    CMP $99
    ; -> case
    BEQ L16
    ; const 3
    LDA #$03
    STA $99
    ; switch case
    LDA _gVal8
    CMP $99
    ; -> case
    BEQ L16
    ; const 4
    LDA #$04
    STA $99
    ; switch case
    LDA _gVal8
    CMP $99
    ; -> case
    BEQ L16
    ; -> default
    JMP L17
L16:
    ; const 34
    LDA #$22
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L15
L17:
    ; const 255
    LDA #$FF
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L15
L15:
    ; gOut
    ; const 34
    LDA #$22
    STA $9D
    ; arg
    PHA
    ; arg
    LDA $99
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 4
    LDA #$04
    STA $96
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 2
    LDA #$02
    STA $9D
    ; switch case
    LDA _gVal8
    CMP $9D
    ; -> case
    BEQ L19
    ; const 3
    LDA #$03
    STA $9D
    ; switch case
    LDA _gVal8
    CMP $9D
    ; -> case
    BEQ L19
    ; const 4
    LDA #$04
    STA $9D
    ; switch case
    LDA _gVal8
    CMP $9D
    ; -> case
    BEQ L19
    ; -> default
    JMP L20
L19:
    ; const 34
    LDA #$22
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L18
L20:
    ; const 255
    LDA #$FF
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L18
L18:
    ; gOut
    ; const 34
    LDA #$22
    STA $A1
    ; arg
    PHA
    ; arg
    LDA $9D
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 99
    LDA #$63
    STA $96
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 1
    LDA #$01
    STA $9D
    ; switch case
    LDA _gVal8
    CMP $9D
    ; -> case
    BEQ L22
    ; -> default
    JMP L23
L22:
    ; const 17
    LDA #$11
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L21
L23:
    ; const 255
    LDA #$FF
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L21
L21:
    ; gOut
    ; const 255
    LDA #$FF
    STA $A2
    ; arg
    PHA
    ; arg
    LDA $9E
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 1
    LDA #$01
    STA $96
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 1
    LDA #$01
    STA $9E
    ; switch case
    LDA _gVal8
    CMP $9E
    ; -> case
    BEQ L25
    ; const 2
    LDA #$02
    STA $9E
    ; switch case
    LDA _gVal8
    CMP $9E
    ; -> case
    BEQ L26
    ; const 3
    LDA #$03
    STA $9E
    ; switch case
    LDA _gVal8
    CMP $9E
    ; -> case
    BEQ L27
    ; -> default
    JMP L28
L25:
    ; gOut
    ; const 1
    LDA #$01
    STA $9E
    ; binop
    CLC
    ADC _gOut
    STA $9F
    ; =
    STA _gOut
    ; (expr stmt discarded)
L26:
    ; gOut
    ; const 2
    LDA #$02
    STA $9E
    ; binop
    CLC
    ADC _gOut
    STA $9F
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L24
L27:
    ; gOut
    ; const 4
    LDA #$04
    STA $9E
    ; binop
    CLC
    ADC _gOut
    STA $9F
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L24
L28:
    ; gOut
    ; const 128
    LDA #$80
    STA $9E
    ; binop
    CLC
    ADC _gOut
    STA $9F
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L24
L24:
    ; gOut
    ; const 3
    LDA #$03
    STA $A2
    ; arg
    PHA
    ; arg
    LDA $9E
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 2
    LDA #$02
    STA $96
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    STA $AA
    LDA #$00
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 1
    LDA #$01
    STA $AB
    ; switch case
    LDA _gVal8
    CMP $AB
    ; -> case
    BEQ L30
    ; const 2
    LDA #$02
    STA $AB
    ; switch case
    LDA _gVal8
    CMP $AB
    ; -> case
    BEQ L31
    ; const 3
    LDA #$03
    STA $AC
    ; switch case
    LDA _gVal8
    CMP $AC
    ; -> case
    BEQ L32
    ; -> default
    JMP L33
L30:
    ; gOut
    ; const 1
    LDA #$01
    STA $AC
    ; binop
    CLC
    ADC _gOut
    STA $AD
    ; =
    STA _gOut
    ; (expr stmt discarded)
L31:
    ; gOut
    ; const 2
    LDA #$02
    STA $AC
    ; binop
    CLC
    ADC _gOut
    STA $AD
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L29
L32:
    ; gOut
    ; const 4
    LDA #$04
    STA $AC
    ; binop
    CLC
    ADC _gOut
    STA $AD
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L29
L33:
    ; gOut
    ; const 128
    LDA #$80
    STA $AC
    ; binop
    CLC
    ADC _gOut
    STA $AD
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L29
L29:
    ; gOut
    ; const 2
    LDA #$02
    STA $B8
    ; arg
    PHA
    ; arg
    LDA $AC
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 3
    LDA #$03
    STA $96
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $96
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 1
    LDA #$01
    STA $AC
    ; switch case
    LDA _gVal8
    CMP $AC
    ; -> case
    BEQ L35
    ; const 2
    LDA #$02
    STA $AC
    ; switch case
    LDA _gVal8
    CMP $AC
    ; -> case
    BEQ L36
    ; const 3
    LDA #$03
    STA $AD
    ; switch case
    LDA _gVal8
    CMP $AD
    ; -> case
    BEQ L37
    ; -> default
    JMP L38
L35:
    ; gOut
    ; const 1
    LDA #$01
    STA $AD
    ; binop
    CLC
    ADC _gOut
    STA $AE
    ; =
    STA _gOut
    ; (expr stmt discarded)
L36:
    ; gOut
    ; const 2
    LDA #$02
    STA $AE
    ; binop
    CLC
    ADC _gOut
    STA $AF
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L34
L37:
    ; gOut
    ; const 4
    LDA #$04
    STA $AE
    ; binop
    CLC
    ADC _gOut
    STA $AF
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L34
L38:
    ; gOut
    ; const 128
    LDA #$80
    STA $AE
    ; binop
    CLC
    ADC _gOut
    STA $AF
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L34
L34:
    ; gOut
    ; const 4
    LDA #$04
    STA $BC
    ; arg
    PHA
    ; arg
    LDA $B8
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 9
    LDA #$09
    STA $AD
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $AD
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 1
    LDA #$01
    STA $AE
    ; switch case
    LDA _gVal8
    CMP $AE
    ; -> case
    BEQ L40
    ; const 2
    LDA #$02
    STA $AE
    ; switch case
    LDA _gVal8
    CMP $AE
    ; -> case
    BEQ L41
    ; const 3
    LDA #$03
    STA $AE
    ; switch case
    LDA _gVal8
    CMP $AE
    ; -> case
    BEQ L42
    ; -> default
    JMP L43
L40:
    ; gOut
    ; const 1
    LDA #$01
    STA $AE
    ; binop
    CLC
    ADC _gOut
    STA $AF
    ; =
    STA _gOut
    ; (expr stmt discarded)
L41:
    ; gOut
    ; const 2
    LDA #$02
    STA $AE
    ; binop
    CLC
    ADC _gOut
    STA $AF
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L39
L42:
    ; gOut
    ; const 4
    LDA #$04
    STA $AE
    ; binop
    CLC
    ADC _gOut
    STA $AF
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L39
L43:
    ; gOut
    ; const 128
    LDA #$80
    STA $AE
    ; binop
    CLC
    ADC _gOut
    STA $AF
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L39
L39:
    ; gOut
    ; const 128
    LDA #$80
    STA $BC
    ; arg
    PHA
    ; arg
    LDA $B8
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 256
    LDA #$00
    LDX #$01
    STA $AD
    STX $AE
    ; =
    STA _gVal16
    STX _gVal16+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $B8
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal16
    ; const 256
    LDA #$00
    LDX #$01
    STA $BA
    STX $BB
    ; switch case
    LDA _gVal16+1
    CMP $BB
    BNE _L25
    LDA _gVal16
    CMP $BA
_L25:
    ; -> case
    BEQ L45
    ; const 512
    LDA #$00
    LDX #$02
    STA $BC
    STX $BD
    ; switch case
    LDA _gVal16+1
    CMP $BD
    BNE _L26
    LDA _gVal16
    CMP $BC
_L26:
    ; -> case
    BEQ L46
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $BE
    STX $BF
    ; switch case
    LDA _gVal16+1
    CMP $BF
    BNE _L27
    LDA _gVal16
    CMP $BE
_L27:
    ; -> case
    BEQ L47
    ; -> end (no match)
    JMP L44
L45:
    ; const 17
    LDA #$11
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L44
L46:
    ; const 34
    LDA #$22
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L44
L47:
    ; const 51
    LDA #$33
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L44
L44:
    ; gOut
    ; const 17
    LDA #$11
    STA $C2
    ; arg
    PHA
    ; arg
    LDA $BE
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 512
    LDA #$00
    LDX #$02
    STA $AD
    STX $AE
    ; =
    STA _gVal16
    STX _gVal16+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal16
    ; const 256
    LDA #$00
    LDX #$01
    STA $BE
    STX $BF
    ; switch case
    LDA _gVal16+1
    CMP $BF
    BNE _L28
    LDA _gVal16
    CMP $BE
_L28:
    ; -> case
    BEQ L49
    ; const 512
    LDA #$00
    LDX #$02
    STA $BE
    STX $BF
    ; switch case
    LDA _gVal16+1
    CMP $BF
    BNE _L29
    LDA _gVal16
    CMP $BE
_L29:
    ; -> case
    BEQ L50
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $BE
    STX $BF
    ; switch case
    LDA _gVal16+1
    CMP $BF
    BNE _L30
    LDA _gVal16
    CMP $BE
_L30:
    ; -> case
    BEQ L51
    ; -> end (no match)
    JMP L48
L49:
    ; const 17
    LDA #$11
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L48
L50:
    ; const 34
    LDA #$22
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L48
L51:
    ; const 51
    LDA #$33
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L48
L48:
    ; gOut
    ; const 34
    LDA #$22
    STA $C2
    ; arg
    PHA
    ; arg
    LDA $BE
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $AD
    STX $AE
    ; =
    STA _gVal16
    STX _gVal16+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal16
    ; const 256
    LDA #$00
    LDX #$01
    STA $BE
    STX $BF
    ; switch case
    LDA _gVal16+1
    CMP $BF
    BNE _L31
    LDA _gVal16
    CMP $BE
_L31:
    ; -> case
    BEQ L53
    ; const 512
    LDA #$00
    LDX #$02
    STA $BE
    STX $BF
    ; switch case
    LDA _gVal16+1
    CMP $BF
    BNE _L32
    LDA _gVal16
    CMP $BE
_L32:
    ; -> case
    BEQ L54
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $BE
    STX $BF
    ; switch case
    LDA _gVal16+1
    CMP $BF
    BNE _L33
    LDA _gVal16
    CMP $BE
_L33:
    ; -> case
    BEQ L55
    ; -> end (no match)
    JMP L52
L53:
    ; const 17
    LDA #$11
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L52
L54:
    ; const 34
    LDA #$22
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L52
L55:
    ; const 51
    LDA #$33
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L52
L52:
    ; gOut
    ; const 51
    LDA #$33
    STA $C2
    ; arg
    PHA
    ; arg
    LDA $BE
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 4660
    LDA #$34
    LDX #$12
    STA $AD
    STX $AE
    ; =
    STA _gVal16
    STX _gVal16+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal16
    ; const 256
    LDA #$00
    LDX #$01
    STA $BE
    STX $BF
    ; switch case
    LDA _gVal16+1
    CMP $BF
    BNE _L34
    LDA _gVal16
    CMP $BE
_L34:
    ; -> case
    BEQ L57
    ; const 512
    LDA #$00
    LDX #$02
    STA $B8
    STX $B9
    ; switch case
    LDA _gVal16+1
    CMP $B9
    BNE _L35
    LDA _gVal16
    CMP $B8
_L35:
    ; -> case
    BEQ L58
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $B8
    STX $B9
    ; switch case
    LDA _gVal16+1
    CMP $B9
    BNE _L36
    LDA _gVal16
    CMP $B8
_L36:
    ; -> case
    BEQ L59
    ; -> end (no match)
    JMP L56
L57:
    ; const 17
    LDA #$11
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L56
L58:
    ; const 34
    LDA #$22
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L56
L59:
    ; const 51
    LDA #$33
    STA $9D
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L56
L56:
    ; gOut
    ; const 0
    LDA #$00
    STA $C0
    ; arg
    PHA
    ; arg
    LDA $BC
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; red
    LDA _red
    ; =
    STA _gColor
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gColor
    ; red
    ; switch case
    LDA _gColor
    CMP _red
    ; -> case
    BEQ L61
    ; green
    ; switch case
    LDA _gColor
    CMP _green
    ; -> case
    BEQ L62
    ; blue
    ; switch case
    LDA _gColor
    CMP _blue
    ; -> case
    BEQ L63
    ; yellow
    ; switch case
    LDA _gColor
    CMP _yellow
    ; -> case
    BEQ L64
    ; -> default
    JMP L65
L61:
    ; const 1
    LDA #$01
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L60
L62:
    ; const 2
    LDA #$02
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L60
L63:
    ; const 3
    LDA #$03
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L60
L64:
    ; const 10
    LDA #$0A
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L60
L65:
    ; const 255
    LDA #$FF
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L60
L60:
    ; gOut
    ; const 1
    LDA #$01
    STA $C0
    ; arg
    PHA
    ; arg
    LDA $BC
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; green
    LDA _green
    ; =
    STA _gColor
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gColor
    ; red
    ; switch case
    LDA _gColor
    CMP _red
    ; -> case
    BEQ L67
    ; green
    ; switch case
    LDA _gColor
    CMP _green
    ; -> case
    BEQ L68
    ; blue
    ; switch case
    LDA _gColor
    CMP _blue
    ; -> case
    BEQ L69
    ; yellow
    ; switch case
    LDA _gColor
    CMP _yellow
    ; -> case
    BEQ L70
    ; -> default
    JMP L71
L67:
    ; const 1
    LDA #$01
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L66
L68:
    ; const 2
    LDA #$02
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L66
L69:
    ; const 3
    LDA #$03
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L66
L70:
    ; const 10
    LDA #$0A
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L66
L71:
    ; const 255
    LDA #$FF
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L66
L66:
    ; gOut
    ; const 2
    LDA #$02
    STA $C0
    ; arg
    PHA
    ; arg
    LDA $BC
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; blue
    LDA _blue
    ; =
    STA _gColor
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gColor
    ; red
    ; switch case
    LDA _gColor
    CMP _red
    ; -> case
    BEQ L73
    ; green
    ; switch case
    LDA _gColor
    CMP _green
    ; -> case
    BEQ L74
    ; blue
    ; switch case
    LDA _gColor
    CMP _blue
    ; -> case
    BEQ L75
    ; yellow
    ; switch case
    LDA _gColor
    CMP _yellow
    ; -> case
    BEQ L76
    ; -> default
    JMP L77
L73:
    ; const 1
    LDA #$01
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L72
L74:
    ; const 2
    LDA #$02
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L72
L75:
    ; const 3
    LDA #$03
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L72
L76:
    ; const 10
    LDA #$0A
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L72
L77:
    ; const 255
    LDA #$FF
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L72
L72:
    ; gOut
    ; const 3
    LDA #$03
    STA $C0
    ; arg
    PHA
    ; arg
    LDA $BC
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; yellow
    LDA _yellow
    ; =
    STA _gColor
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gColor
    ; red
    ; switch case
    LDA _gColor
    CMP _red
    ; -> case
    BEQ L79
    ; green
    ; switch case
    LDA _gColor
    CMP _green
    ; -> case
    BEQ L80
    ; blue
    ; switch case
    LDA _gColor
    CMP _blue
    ; -> case
    BEQ L81
    ; yellow
    ; switch case
    LDA _gColor
    CMP _yellow
    ; -> case
    BEQ L82
    ; -> default
    JMP L83
L79:
    ; const 1
    LDA #$01
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L78
L80:
    ; const 2
    LDA #$02
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L78
L81:
    ; const 3
    LDA #$03
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L78
L82:
    ; const 10
    LDA #$0A
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L78
L83:
    ; const 255
    LDA #$FF
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L78
L78:
    ; gOut
    ; const 10
    LDA #$0A
    STA $C0
    ; arg
    PHA
    ; arg
    LDA $BC
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 99
    LDA #$63
    STA $91
    ; =
    STA _gColor
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gColor
    ; red
    ; switch case
    LDA _gColor
    CMP _red
    ; -> case
    BEQ L85
    ; -> default
    JMP L86
L85:
    ; const 1
    LDA #$01
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L84
L86:
    ; const 255
    LDA #$FF
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L84
L84:
    ; gOut
    ; const 255
    LDA #$FF
    STA $BC
    ; arg
    PHA
    ; arg
    LDA $99
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gCount
    ; (expr stmt discarded)
    ; stmt (trying expr): XTAssignExprNode
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gIter
L87:
    ; gIter
    ; const 5
    LDA #$05
    STA $99
    ; cmp
    LDA _gIter
    CMP $99
    ; -> end
    BCS L89
    ; gIter
    ; const 0
    LDA #$00
    STA $99
    ; switch case
    LDA _gIter
    CMP $99
    ; -> case
    BEQ L91
    ; const 1
    LDA #$01
    STA $99
    ; switch case
    LDA _gIter
    CMP $99
    ; -> case
    BEQ L92
    ; const 2
    LDA #$02
    STA $99
    ; switch case
    LDA _gIter
    CMP $99
    ; -> case
    BEQ L93
    ; -> default
    JMP L94
L91:
    ; gCount
    ; const 1
    LDA #$01
    STA $99
    ; binop
    CLC
    ADC _gCount
    STA $9A
    ; =
    STA _gCount
    ; (expr stmt discarded)
    ; break
    JMP L90
L92:
    ; gCount
    ; const 2
    LDA #$02
    STA $99
    ; binop
    CLC
    ADC _gCount
    STA $9A
    ; =
    STA _gCount
    ; (expr stmt discarded)
    ; break
    JMP L90
L93:
    ; gCount
    ; const 4
    LDA #$04
    STA $99
    ; binop
    CLC
    ADC _gCount
    STA $9A
    ; =
    STA _gCount
    ; (expr stmt discarded)
    ; break
    JMP L90
L94:
    ; gCount
    ; const 16
    LDA #$10
    STA $99
    ; binop
    CLC
    ADC _gCount
    STA $9A
    ; =
    STA _gCount
    ; (expr stmt discarded)
    ; break
    JMP L90
L90:
L88:
    ; gIter
    ; const 1
    LDA #$01
    STA $99
    ; binop
    CLC
    ADC _gIter
    STA $9A
    ; =
    STA _gIter
    ; -> loop
    JMP L87
L89:
    ; gCount
    ; const 39
    LDA #$27
    STA $BC
    ; arg
    PHA
    ; arg
    LDA $99
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 5
    LDA #$05
    STA $91
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 5
    LDA #$05
    STA $91
    ; below lo → skip
    BCC L97
    ; const 9
    LDA #$09
    STA $91
    ; in range → case
    BEQ L96
    BCC L96
L97:
    ; -> default
    JMP L98
L96:
    ; const 170
    LDA #$AA
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L95
L98:
    ; const 0
    LDA #$00
    STA $91
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L95
L95:
    ; gOut
    ; const 170
    LDA #$AA
    STA $BC
    ; arg
    PHA
    ; arg
    LDA $98
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 7
    LDA #$07
    STA $91
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 5
    LDA #$05
    STA $91
    ; below lo → skip
    BCC L101
    ; const 9
    LDA #$09
    STA $91
    ; range hi check
    LDA _gVal8
    CMP $91
    ; in range → case
    BCC _L39
    BEQ _L39
    JMP _L37
_L39:
    LDA #$01
    JMP _L38
_L37:
    LDA #$00
_L38:
    STA $BA
    BEQ L100
    BCC L100
L101:
    ; -> default
    JMP L102
L100:
    ; const 170
    LDA #$AA
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L99
L102:
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L99
L99:
    ; gOut
    ; const 170
    LDA #$AA
    STA $B8
    ; arg
    PHA
    ; arg
    LDA $98
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 9
    LDA #$09
    STA $87
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 5
    LDA #$05
    STA $87
    ; below lo → skip
    BCC L105
    ; const 9
    LDA #$09
    STA $87
    ; in range → case
    BEQ L104
    BCC L104
L105:
    ; -> default
    JMP L106
L104:
    ; const 170
    LDA #$AA
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L103
L106:
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L103
L103:
    ; gOut
    ; const 170
    LDA #$AA
    STA $B8
    ; arg
    PHA
    ; arg
    LDA $98
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 4
    LDA #$04
    STA $87
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 5
    LDA #$05
    STA $87
    ; below lo → skip
    BCC L109
    ; const 9
    LDA #$09
    STA $87
    ; in range → case
    BEQ L108
    BCC L108
L109:
    ; -> default
    JMP L110
L108:
    ; const 170
    LDA #$AA
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L107
L110:
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L107
L107:
    ; gOut
    ; const 0
    LDA #$00
    STA $B8
    ; arg
    PHA
    ; arg
    LDA $98
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 5
    LDA #$05
    STA $87
    ; in range → case
    BEQ L112
    BCC L112
    ; -> default
    JMP L113
L112:
    ; const 85
    LDA #$55
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L111
L113:
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L111
L111:
    ; gOut
    ; const 85
    LDA #$55
    STA $B8
    ; arg
    PHA
    ; arg
    LDA $98
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 5
    LDA #$05
    STA $87
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 5
    LDA #$05
    STA $87
    ; in range → case
    BEQ L115
    BCC L115
    ; -> default
    JMP L116
L115:
    ; const 85
    LDA #$55
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L114
L116:
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L114
L114:
    ; gOut
    ; const 85
    LDA #$55
    STA $B8
    ; arg
    PHA
    ; arg
    LDA $98
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 6
    LDA #$06
    STA $87
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 5
    LDA #$05
    STA $84
    ; in range → case
    BEQ L118
    BCC L118
    ; -> default
    JMP L119
L118:
    ; const 85
    LDA #$55
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L117
L119:
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L117
L117:
    ; gOut
    ; const 0
    LDA #$00
    STA $B8
    ; arg
    PHA
    ; arg
    LDA $97
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 12
    LDA #$0C
    STA $84
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 12
    LDA #$0C
    STA $84
    ; in range → case
    BCS L121
    ; -> default
    JMP L122
L121:
    ; const 204
    LDA #$CC
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L120
L122:
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L120
L120:
    ; gOut
    ; const 204
    LDA #$CC
    STA $B8
    ; arg
    PHA
    ; arg
    LDA $97
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 200
    LDA #$C8
    STA $84
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 12
    LDA #$0C
    STA $84
    ; in range → case
    BCS L124
    ; -> default
    JMP L125
L124:
    ; const 204
    LDA #$CC
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L123
L125:
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L123
L123:
    ; gOut
    ; const 204
    LDA #$CC
    STA $AB
    ; arg
    PHA
    ; arg
    LDA $97
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; const 11
    LDA #$0B
    STA $84
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 12
    LDA #$0C
    STA $84
    ; in range → case
    BCS L127
    ; -> default
    JMP L128
L127:
    ; const 204
    LDA #$CC
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L126
L128:
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L126
L126:
    ; gOut
    ; const 0
    LDA #$00
    STA $9A
    ; arg
    PHA
    ; arg
    LDA $96
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; var j =
    ; const 0
    LDA #$00
    STA $84
    STA _j
L129:
    ; j
    ; const 4
    LDA #$04
    STA $87
    ; cmp
    LDA _j
    CMP $87
    ; -> end
    BCS L131
    ; j
    ; const 0
    LDA #$00
    STA $87
    ; cmp
    LDA _j
    CMP $87
    ; -> else
    BNE L132
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _pv
    ; (expr stmt discarded)
    ; const 160
    LDA #$A0
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; -> end
    JMP L133
L132:
    ; j
    ; const 1
    LDA #$01
    STA $87
    ; cmp
    LDA _j
    CMP $87
    ; -> else
    BNE L134
    ; const 2
    LDA #$02
    STA $84
    ; =
    STA _pv
    ; (expr stmt discarded)
    ; const 161
    LDA #$A1
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; -> end
    JMP L135
L134:
    ; j
    ; const 2
    LDA #$02
    STA $87
    ; cmp
    LDA _j
    CMP $87
    ; -> else
    BNE L136
    ; const 15
    LDA #$0F
    STA $84
    ; =
    STA _pv
    ; (expr stmt discarded)
    ; const 162
    LDA #$A2
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; -> end
    JMP L137
L136:
    ; const 255
    LDA #$FF
    STA $84
    ; =
    STA _pv
    ; (expr stmt discarded)
    ; const 163
    LDA #$A3
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
L137:
L135:
L133:
    ; pv
    LDA _pv
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 0
    LDA #$00
    STA $87
    ; switch case
    LDA _gVal8
    CMP $87
    ; -> case
    BEQ L139
    ; const 1
    LDA #$01
    STA $87
    ; below lo → skip
    BCC L141
    ; const 3
    LDA #$03
    STA $87
    ; in range → case
    BEQ L140
    BCC L140
L141:
    ; const 10
    LDA #$0A
    STA $87
    ; below lo → skip
    BCC L143
    ; const 20
    LDA #$14
    STA $87
    ; in range → case
    BEQ L142
    BCC L142
L143:
    ; const 255
    LDA #$FF
    STA $87
    ; switch case
    LDA _gVal8
    CMP $87
    ; -> case
    BEQ L144
    ; -> default
    JMP L145
L139:
    ; const 160
    LDA #$A0
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L138
L140:
    ; const 161
    LDA #$A1
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L138
L142:
    ; const 162
    LDA #$A2
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L138
L144:
    ; const 163
    LDA #$A3
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L138
L145:
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L138
L138:
    ; gOut
    ; want
    LDA _want
    ; arg
    PHA
    ; arg
    LDA $96
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
L130:
    ; j
    ; const 1
    LDA #$01
    STA $87
    ; binop
    CLC
    ADC _j
    STA $88
    ; =
    STA _j
    ; -> loop
    JMP L129
L131:
    ; green
    LDA _green
    ; =
    STA _gColor
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gColor
    ; red
    LDA _red
    ; below lo → skip
    BCC L148
    ; blue
    LDA _blue
    ; in range → case
    BEQ L147
    BCC L147
L148:
    ; yellow
    ; switch case
    LDA _gColor
    CMP _yellow
    ; -> case
    BEQ L149
    ; -> default
    JMP L150
L147:
    ; const 17
    LDA #$11
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L146
L149:
    ; const 34
    LDA #$22
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L146
L150:
    ; const 255
    LDA #$FF
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L146
L146:
    ; gOut
    ; const 17
    LDA #$11
    STA $9A
    ; arg
    PHA
    ; arg
    LDA $96
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
    ; stmt (trying expr): XTAssignExprNode
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gIter
L151:
    ; gIter
    ; const 8
    LDA #$08
    STA $87
    ; cmp
    LDA _gIter
    CMP $87
    ; -> end
    BCS L153
    ; gIter
    ; const 0
    LDA #$00
    STA $87
    ; switch case
    LDA _gIter
    CMP $87
    ; -> case
    BEQ L155
    ; const 1
    LDA #$01
    STA $87
    ; switch case
    LDA _gIter
    CMP $87
    ; -> case
    BEQ L156
    ; const 2
    LDA #$02
    STA $87
    ; switch case
    LDA _gIter
    CMP $87
    ; -> case
    BEQ L157
    ; const 3
    LDA #$03
    STA $87
    ; switch case
    LDA _gIter
    CMP $87
    ; -> case
    BEQ L158
    ; const 4
    LDA #$04
    STA $87
    ; switch case
    LDA _gIter
    CMP $87
    ; -> case
    BEQ L159
    ; const 5
    LDA #$05
    STA $87
    ; switch case
    LDA _gIter
    CMP $87
    ; -> case
    BEQ L160
    ; -> default
    JMP L161
L155:
    ; const 1
    LDA #$01
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L154
L156:
    ; const 2
    LDA #$02
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L154
L157:
    ; const 4
    LDA #$04
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L154
L158:
    ; const 8
    LDA #$08
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L154
L159:
    ; const 16
    LDA #$10
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L154
L160:
    ; const 32
    LDA #$20
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L154
L161:
    ; const 255
    LDA #$FF
    STA $84
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L154
L154:
    ; gIter
    LDA _gIter
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $84
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 0
    LDA #$00
    STA $87
    ; switch case
    LDA _gVal8
    CMP $87
    ; -> case
    BEQ L163
    ; const 1
    LDA #$01
    STA $87
    ; switch case
    LDA _gVal8
    CMP $87
    ; -> case
    BEQ L164
    ; const 2
    LDA #$02
    STA $87
    ; switch case
    LDA _gVal8
    CMP $87
    ; -> case
    BEQ L165
    ; const 3
    LDA #$03
    STA $87
    ; switch case
    LDA _gVal8
    CMP $87
    ; -> case
    BEQ L166
    ; const 4
    LDA #$04
    STA $83
    ; switch case
    LDA _gVal8
    CMP $83
    ; -> case
    BEQ L167
    ; const 5
    LDA #$05
    STA $83
    ; switch case
    LDA _gVal8
    CMP $83
    ; -> case
    BEQ L168
    ; -> default
    JMP L169
L163:
    ; const 1
    LDA #$01
    STA $83
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L162
L164:
    ; const 2
    LDA #$02
    STA $83
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L162
L165:
    ; const 4
    LDA #$04
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L162
L166:
    ; const 8
    LDA #$08
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L162
L167:
    ; const 16
    LDA #$10
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L162
L168:
    ; const 32
    LDA #$20
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L162
L169:
    ; const 255
    LDA #$FF
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L162
L162:
    ; gOut
    ; want
    LDA _want
    ; arg
    PHA
    ; arg
    LDA $82
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
L152:
    ; gIter
    ; const 1
    LDA #$01
    STA $82
    ; binop
    CLC
    ADC _gIter
    STA $83
    ; =
    STA _gIter
    ; -> loop
    JMP L151
L153:
    ; stmt (trying expr): XTAssignExprNode
    ; const 8
    LDA #$08
    STA $80
    ; =
    STA _gIter
L170:
    ; gIter
    ; const 17
    LDA #$11
    STA $82
    ; cmp
    LDA _gIter
    CMP $82
    ; -> end
    BCS L172
    ; gIter
    ; const 10
    LDA #$0A
    STA $82
    ; switch case
    LDA _gIter
    CMP $82
    ; -> case
    BEQ L174
    ; const 11
    LDA #$0B
    STA $82
    ; switch case
    LDA _gIter
    CMP $82
    ; -> case
    BEQ L175
    ; const 12
    LDA #$0C
    STA $82
    ; switch case
    LDA _gIter
    CMP $82
    ; -> case
    BEQ L176
    ; const 13
    LDA #$0D
    STA $82
    ; switch case
    LDA _gIter
    CMP $82
    ; -> case
    BEQ L177
    ; const 14
    LDA #$0E
    STA $82
    ; switch case
    LDA _gIter
    CMP $82
    ; -> case
    BEQ L178
    ; -> default
    JMP L179
L174:
    ; const 10
    LDA #$0A
    STA $80
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L173
L175:
    ; const 11
    LDA #$0B
    STA $80
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L173
L176:
    ; const 12
    LDA #$0C
    STA $80
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L173
L177:
    ; const 13
    LDA #$0D
    STA $80
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L173
L178:
    ; const 14
    LDA #$0E
    STA $80
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L173
L179:
    ; const 255
    LDA #$FF
    STA $80
    ; =
    STA _want
    ; (expr stmt discarded)
    ; break
    JMP L173
L173:
    ; gIter
    LDA _gIter
    ; =
    STA _gVal8
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; gVal8
    ; const 10
    LDA #$0A
    STA $82
    ; switch case
    LDA _gVal8
    CMP $82
    ; -> case
    BEQ L181
    ; const 11
    LDA #$0B
    STA $82
    ; switch case
    LDA _gVal8
    CMP $82
    ; -> case
    BEQ L182
    ; const 12
    LDA #$0C
    STA $82
    ; switch case
    LDA _gVal8
    CMP $82
    ; -> case
    BEQ L183
    ; const 13
    LDA #$0D
    STA $82
    ; switch case
    LDA _gVal8
    CMP $82
    ; -> case
    BEQ L184
    ; const 14
    LDA #$0E
    STA $82
    ; switch case
    LDA _gVal8
    CMP $82
    ; -> case
    BEQ L185
    ; -> default
    JMP L186
L181:
    ; const 10
    LDA #$0A
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L180
L182:
    ; const 11
    LDA #$0B
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L180
L183:
    ; const 12
    LDA #$0C
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L180
L184:
    ; const 13
    LDA #$0D
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L180
L185:
    ; const 14
    LDA #$0E
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L180
L186:
    ; const 255
    LDA #$FF
    STA $80
    ; =
    STA _gOut
    ; (expr stmt discarded)
    ; break
    JMP L180
L180:
    ; gOut
    ; want
    LDA _want
    ; arg
    PHA
    ; arg
    LDA $82
    PHA
    ; call
    JSR _checkU8
    ; (expr stmt discarded)
L171:
    ; gIter
    ; const 1
    LDA #$01
    STA $82
    ; binop
    CLC
    ADC _gIter
    STA $83
    ; =
    STA _gIter
    ; -> loop
    JMP L170
L172:
    ; stmt (trying expr): XTAssignExprNode
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _i
L187:
    ; i
    ; failCount
    ; cmp
    LDA _i
    CMP _failCount
    ; -> end
    BCS L189
    ; i
    ; const 16
    LDA #$10
    STA $82
    ; cmp
    LDA _i
    CMP $82
    ; -> else
    BCS L190
    ; Stdio
    LDA _Stdio
    STA $82
    LDA _Stdio+1
    STA $83
    LDA _Stdio+2
    STA $84
    LDA _Stdio+3
    STA $85
    LDA $84
    STA $B2
    LDA $85
    STA $B3
    LDA $82
    LDX $83
    LDA $B2
    STA $84
    LDA $B3
    STA $85
    ; string literal
    LDA #_str_0
    LDX #_str_0+1
    STA $86
    STX $87
_str_0: .byte $54,$25,$75,$20,$46,$41,$49,$4C,$0A,0
    ; &arr
    LDA #_fails
    LDX #_fails+1
    STA $8A
    STX $8B
    ; i
    LDA _i
    ; arr+idx
    CLC
    LDX #$00
    STX $8D
    ADC $8A
    STA $8E
    LDA $8B
    ADC _i+1
    STA $8F
    LDA $8E
    LDX $8F
    ; subscript load
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8A
    LDA $8A
    ; mcall
    JSR _printf
    ; (expr stmt discarded)
L190:
L188:
    ; i
    ; const 1
    LDA #$01
    STA $82
    ; binop
    CLC
    ADC _i
    STA $81
    ; =
    STA _i
    ; -> loop
    JMP L187
L189:
    ; Stdio
    LDA _Stdio
    STA $80
    LDA _Stdio+1
    STA $81
    LDA _Stdio+2
    STA $82
    LDA _Stdio+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; string literal
    LDA #_str_1
    LDX #_str_1+1
    STA $84
    STX $85
_str_1: .byte $44,$4F,$4E,$45,$20,$25,$75,$0A,0
    ; testCount
    LDA _testCount
    ; mcall
    JSR _printf
    ; (expr stmt discarded)
    RTS
    ; === end main ===

    ; === Global variables ===
    _Stdio:
        .space 4
    _ap:
        .space 1
    _blue:
        .space 1
    _botlin:
        .space 1
    _cLo:
        .space 1
    _canPrint:
        .space 1
    _ch:
        .space 1
    _cols:
        .space 1
    _d:
        .space 4
    _depth:
        .space 1
    _dpHi:
        .space 1
    _dpLo:
        .space 1
    _dst:
        .space 2
    _endPtr:
        .space 2
    _failCount:
        .space 1
    _fieldSize:
        .space 1
    _fieldType:
        .space 1
    _fieldVal:
        .space 2
    _fmt:
        .space 2
    _fpBufPtr:
        .space 2
    _gColor:
        .space 1
    _gCount:
        .space 1
    _gIter:
        .space 1
    _gOut:
        .space 1
    _gVal16:
        .space 2
    _gVal8:
        .space 1
    _green:
        .space 1
    _hi:
        .space 1
    _i:
        .space 1
    _inv:
        .space 1
    _j:
        .space 1
    _lo:
        .space 1
    _mode:
        .space 1
    _n:
        .space 1
    _numCols:
        .space 2
    _off:
        .space 2
    _offset:
        .space 2
    _psDesc:
        .space 2
    _psDp:
        .space 2
    _psFieldCount:
        .space 1
    _psIdx:
        .space 1
    _psSaveDp:
        .space 2
    _ptr:
        .space 2
    _pv:
        .space 1
    _r:
        .space 1
    _red:
        .space 1
    _rem:
        .space 2
    _rows:
        .space 1
    _s:
        .space 2
    _sb:
        .space 2
    _sbase:
        .space 2
    _sc:
        .space 1
    _scrMode:
        .space 1
    _screenBase:
        .space 2
    _screenPtr:
        .space 2
    _size:
        .space 2
    _spec:
        .space 1
    _src:
        .space 2
    _szHi:
        .space 1
    _szLo:
        .space 1
    _testCount:
        .space 1
    _val:
        .space 4
    _want:
        .space 1
    _x:
        .space 1
    _y:
        .space 1
    _yellow:
        .space 1

    ; === Runtime routines ===

_mul16:
    LDA $B4
    STA $B2
    LDA $B5
    STA $B3
    ; Save lhs since we shift multiplicand
    LDA $B0
    STA $B6
    LDA $B1
    STA $B7
    ; Determine sign
    LDA #$00
    STA $B8         ; sign flag
    LDA $B7
    BPL .mul_op1_pos
    ; Negate operand1
    LDA $B6 : EOR #$FF : STA $B6
    LDA $B7 : EOR #$FF : STA $B7
    INC $B6 : BNE .mul_op1_pos : INC $B7
    INC $B8
.mul_op1_pos:
    LDA $B3
    BPL .mul_op2_pos
    ; Negate operand2
    LDA $B2 : EOR #$FF : STA $B2
    LDA $B3 : EOR #$FF : STA $B3
    INC $B2 : BNE .mul_op2_pos : INC $B3
    INC $B8
.mul_op2_pos:
    ; Unsigned multiply: $B6-$B7 x $B2-$B3 -> $B0-$B3
    LDA #$00
    STA $B0
    STA $B1
    STA $B4
    STA $B5
    LDX #16
.mul_loop:
    LSR $B3
    ROR $B2
    BCC .mul_no_add
    CLC
    LDA $B0
    ADC $B6
    STA $B0
    LDA $B1
    ADC $B7
    STA $B1
    LDA $B4
    ADC #$00
    STA $B4
    LDA $B5
    ADC #$00
    STA $B5
.mul_no_add:
    ASL $B6
    ROL $B7
    DEX
    BNE .mul_loop
    ; Apply sign
    LDA $B8
    AND #$01
    BEQ .mul_done
    LDA $B0 : EOR #$FF : STA $B0
    LDA $B1 : EOR #$FF : STA $B1
    INC $B0 : BNE .mul_done : INC $B1
.mul_done:
    ; Return result in A/X
    LDA $B0
    LDX $B1
    RTS
_div16:
    JSR _udiv16
    LDA $B0
    LDX $B1
    RTS
_mod16:
    JSR _udiv16
    LDA $B2
    LDX $B3
    RTS
_div32:
    ; 32-bit division (placeholder)
    LDA #$00
    STA $B0
    STA $B1
    STA $B2
    STA $B3
    RTS
_mod32:
    ; 32-bit modulo (placeholder)
    LDA #$00
    STA $B0
    STA $B1
    STA $B2
    STA $B3
    RTS
