;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/ternary.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module ternary

    ; === function main ===
_main:
    ; var x =
    ; const 5
    LDA #$05
    STA $81
    STA _x
    ; var y =
    ; x
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    ADC _x
    STA $84
    STA _y
    ; var val =
    ; x
    ; y
    ; cmp
    LDA _x
    CMP _y
    ; -> else
    BEQ L0
    BCC L0
    ; const 1
    LDA #$01
    STA $80
    ; ? then
    ; -> end
    JMP L1
L0:
    ; const 0
    STA $81
    LDA #$00
    STA $80
    ; ? else
L1:
    STA _val
    RTS
    ; === end main ===

    ; === Global variables ===
    _val:
        .space 1
    _x:
        .space 1
    _y:
        .space 1

    ; === Runtime routines ===

