;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/valist.xt

    .org $2000


    LDA #<stack_low
    STA $82
    LDA #>stack_low
    STA $82 + 1

    LDA #<heap_top
    STA $86
    LDA #>heap_top
    STA $86 + 1


main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module valist

    ; === method Stdio.init ===
_cls_Stdio_init:
LDA $57
STA scrMode
    ; scrMode
    LDA _scrMode
    ; =
    STA _mode
    ; (expr stmt discarded)
    STA $81
LDA $58
STA sbase
LDA $59
STA sbase+1
    ; sbase
    LDA _sbase
    LDX _sbase+1
    ; =
    STA _screenBase
    STX _screenBase+1
    ; (expr stmt discarded)
    ; sbase
    LDA _sbase
    LDX _sbase+1
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; mode
    STA $80
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA _mode
    CMP $84
    ; -> else
    BNE _F0_L0
    ; const 40
    LDA #$28
    STA $84
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 1
    LDA #$01
    STA $80
    ; =
    STA _canPrint
    ; (expr stmt discarded)
    ; -> end
    JMP _F0_L1
_F0_L0:
    ; mode
    STA $80
    ; const 4
    LDA #$04
    STA $84
    ; cmp
    LDA _mode
    CMP $84
    ; -> else
    BCS _F0_L2
    ; const 20
    LDA #$14
    STA $80
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 1
    LDA #$01
    STA $82
    ; =
    STA _canPrint
    ; (expr stmt discarded)
    ; -> end
    JMP _F0_L3
_F0_L2:
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _cols
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _canPrint
    ; (expr stmt discarded)
_F0_L3:
_F0_L1:
LDA $02BF
STA botlin
    ; botlin
    STA $81
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _botlin
    CMP $82
    ; -> else
    BNE _F0_L4
    ; const 24
    LDA #$18
    STA $81
    ; =
    STA _rows
    ; (expr stmt discarded)
    ; -> end
    JMP _F0_L5
_F0_L4:
    ; botlin
    LDA _botlin
    ; =
    STA _rows
    ; (expr stmt discarded)
_F0_L5:
    ; === end Stdio.init ===
    ; === method Stdio.scroll ===
_cls_Stdio_scroll:
    ; var sb =
    ; screenBase
    LDA _screenBase
    LDX _screenBase+1
    STA _sb
    STX _sb+1
    ; var numCols =
    ; cols
    LDA _cols
    LDX #$00
    STA _numCols
    STX _numCols+1
    ; var size =
    ; numCols
    STX $83
    LDX _numCols+1
    STA $82
    ; rows
    STA $84
    ; const 1
    LDA #$01
    STA $85
    ; binop
    SEC
    LDA _rows
    SBC $85
    STA $80
    ; binop
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDA $80
    STA $B4
    LDA $81
    STA $B5
    LDA _numCols
    JSR _mul16
    STA $84
    STX $85
    STA _size
    STX _size+1
    ; var src =
    ; sb
    STA $80
    STX $81
    ; numCols
    LDA _numCols
    LDX _numCols+1
    ; binop
    CLC
    ADC _sb
    STA $84
    LDA _sb+1
    ADC _numCols+1
    STA $85
    LDA $84
    LDX $85
    STA _src
    STX _src+1
    ; var dst =
    ; sb
    LDA _sb
    LDX _sb+1
    STA _dst
    STX _dst+1
    ; var szLo =
    ; size
    LDX _size+1
    STA $82
    ; const 255
    LDA #$FF
    STA $85
    ; binop
    LDX #$00
    STX $86
    AND _size
    STA $89
    LDA _size+1
    AND $86
    STA $8A
    LDA $89
    LDX $8A
    STA _szLo
    ; var szHi =
    ; size
    LDX _size+1
    STA $82
    ; const 8
    LDA #$08
    STA $84
    ; binop
    LDA $82
    STA $B0
    LDA $83
    STA $B1
    LDX $84
    BEQ _F1__L3
_F1__L2:
    LSR $B1
    ROR $B0
    DEX
    BNE _F1__L2
_F1__L3:
    LDA $B0
    STA $80
    LDA $B1
    STA $81
    LDA $B0
    LDX $B1
    STA _szHi
    ; var cLo =
    ; numCols
    LDA _numCols
    LDX _numCols+1
    STA _cLo
; Set up indirect pointers in $B0 / $B1 ( dst ) and
; $B2 / $B3 ( src ) .The runtime - params region $B0 - $BF
; is reserved against ZP - allocated locals so dst /
; src can ' t collide with anything sema gave us .
LDA dst
STA $B0
LDA dst+1
STA $B1
LDA src
STA $B2
LDA src+1
STA $B3
; -- -- Move ( rows - 1 ) * cols bytes up by one row -- --
; Outer loop uses szHi pages ( 256 - byte chunks ) plus
; an inner DEX / BNE for szLo trailing bytes .Y is
; the byte offset within the current page .After
; each page wrap we INC the high bytes of both
; pointers and walk the next 256 bytes .
LDX szHi
BEQ _stdio_scroll_tail
LDY #$00
_stdio_scroll_page :
LDA ( $B2 ),Y
STA ( $B0 ),Y
INY
BNE _stdio_scroll_page
INC $B1
INC $B3
DEX
BNE _stdio_scroll_page
_stdio_scroll_tail :
LDX szLo
BEQ _stdio_scroll_clear
LDY #$00
_stdio_scroll_tail_lp :
LDA ( $B2 ),Y
STA ( $B0 ),Y
INY
DEX
BNE _stdio_scroll_tail_lp
; Advance the dst pointer past the bytes we just
; copied so the bottom - row clear lands at the
; right address .Y holds the byte offset we ended
; on ; CLC+ADC walks $B0 forward .
CLC
TYA
ADC $B0
STA $B0
BCC _stdio_scroll_clear
INC $B1
_stdio_scroll_clear :
; Clear numCols bytes ( cLo,always less than 256 )
; at the dst ' s current location to give the new
; bottom row a blank screen - code - 0 fill .
LDX cLo
BEQ _stdio_scroll_done
LDY #$00
LDA #$00
_stdio_scroll_clear_lp :
STA ( $B0 ),Y
INY
DEX
BNE _stdio_scroll_clear_lp
_stdio_scroll_done :
    ; === end Stdio.scroll ===
    ; === method Stdio.putChar ===
_cls_Stdio_putChar:
    ; canPrint
    STA $80
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE _F4_L0
    ; return
    RTS
_F4_L0:
    ; var endPtr =
    ; screenBase
    LDX _screenBase+1
    STA $81
    ; cols
    STA $83
    ; rows
    LDA _rows
    ; binop
    LDA $83
    STA $B0
    LDA $84
    STA $B1
    LDA $85
    STA $B4
    LDA $86
    STA $B5
    LDA _cols
    LDX #$00
    STX $84
    JSR _mul16
    STA $89
    STX $8A
    ; binop
    CLC
    ADC _screenBase
    STA $83
    LDA _screenBase+1
    ADC $8A
    STA $84
    LDA $83
    LDX $84
    STA _endPtr
    STX _endPtr+1
    ; var ptr =
    ; screenPtr
    LDA _screenPtr
    LDX _screenPtr+1
    STA _ptr
    STX _ptr+1
    ; ptr
    STA $81
    STX $82
    ; endPtr
    LDX _endPtr+1
    STA $83
    ; cmp
    LDA _ptr+1
    CMP _endPtr+1
    BNE _F4__L5
    LDA _ptr
    CMP _endPtr
_F4__L5:
    ; -> else
    BCC _F4_L2
    ; __SAVE__::13
    ; call
    JSR _cls_Stdio_scroll
    ; __RESTORE__
    ; (expr stmt discarded)
    ; endPtr
    LDX _endPtr+1
    STA $83
    ; cols
    LDA _cols
    ; binop
    SEC
    LDX #$00
    STX $86
    LDA _endPtr
    SBC _cols
    STA $89
    LDA _endPtr+1
    SBC _cols+1
    STA $8A
    LDA $89
    LDX $8A
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; screenPtr
    LDA _screenPtr
    LDX _screenPtr+1
    ; =
    STA _ptr
    STX _ptr+1
    ; (expr stmt discarded)
_F4_L2:
    ; ch
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> else
    BNE _F4_L4
    ; ptr
    STA $81
    STX $82
    ; screenBase
    LDA _screenBase
    LDX _screenBase+1
    ; binop
    SEC
    LDA _ptr
    SBC _screenBase
    STA $85
    LDA _ptr+1
    SBC _screenBase+1
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _off
    STX _off+1
    ; (expr stmt discarded)
    ; off
    LDX _off+1
    STA $81
    ; cols
    LDA _cols
    ; binop
    LDA $81
    STA $B0
    LDA $82
    STA $B1
    LDA $83
    STA $B4
    LDA $84
    STA $B5
    LDA _off
    JSR _mod16
    STA $85
    STX $86
    ; =
    STA _rem
    STX _rem+1
    ; (expr stmt discarded)
    ; ptr
    LDX _ptr+1
    STA $81
    ; cols
    STA $83
    ; rem
    LDA _rem
    LDX _rem+1
    ; binop
    LDA _cols
    LDX #$00
    STX $84
    SEC
    SBC _rem
    STA $89
    LDA _cols+1
    SBC _rem+1
    STA $8A
    LDA $89
    LDX $8A
    ; binop
    CLC
    ADC _ptr
    STA $83
    LDA _ptr+1
    ADC $8A
    STA $84
    LDA $83
    LDX $84
    ; =
    STA _ptr
    STX _ptr+1
    ; (expr stmt discarded)
    ; ptr
    LDA _ptr
    LDX _ptr+1
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; return
    RTS
_F4_L4:
    ; ch
    STA $83
    ; const 128
    LDA #$80
    STA $84
    ; binop
    AND _ch
    STA $85
    ; =
    STA _inv
    ; (expr stmt discarded)
    ; ch
    STA $83
    ; const 127
    LDA #$7F
    STA $85
    ; binop
    AND _ch
    STA $84
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; ch
    STA $83
    ; const 32
    LDA #$20
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> else
    BCS _F4_L6
    ; ch
    STA $83
    ; const 64
    LDA #$40
    STA $85
    ; binop
    CLC
    ADC _ch
    STA $86
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP _F4_L7
_F4_L6:
    ; ch
    STA $83
    ; const 64
    LDA #$40
    STA $85
    ; cmp
    LDA _ch
    CMP $85
    ; -> else
    BCS _F4_L8
    ; ch
    STA $83
    ; const 32
    LDA #$20
    STA $85
    ; binop
    SEC
    LDA _ch
    SBC $85
    STA $86
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP _F4_L9
_F4_L8:
    ; ch
    STA $83
    ; const 96
    LDA #$60
    STA $85
    ; cmp
    LDA _ch
    CMP $85
    ; -> else
    BCS _F4_L10
    ; ch
    STA $83
    ; const 32
    LDA #$20
    STA $85
    ; binop
    SEC
    LDA _ch
    SBC $85
    STA $81
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; -> end
    JMP _F4_L11
_F4_L10:
    ; ch
    STA $84
    LDA _ch
    ; =
    STA _sc
    ; (expr stmt discarded)
_F4_L11:
_F4_L9:
_F4_L7:
    ; sc
    STA $81
    ; inv
    LDA _inv
    ; binop
    ORA _sc
    STA $83
    ; =
    STA _sc
    ; (expr stmt discarded)
    ; screenPtr
    LDX _screenPtr+1
    STA $81
    ; sc
    LDA _sc
    ; =
    LDA $83
    STA $B2
    LDA _screenPtr
    STA $B0
    STX $B1
    LDY #$00
    LDA $B2
    STA ($B0),Y
    ; (expr stmt discarded)
    ; screenPtr
    LDX _screenPtr+1
    STA $81
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _screenPtr
    STA $85
    LDA _screenPtr+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; === end Stdio.putChar ===
    ; === method Stdio.print__s ===
_cls_Stdio_print__s:
    ; canPrint
    STA $80
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE _F6_L0
    ; return
    RTS
_F6_L0:
    ; s
    LDA _s
    LDX _s+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _ch
    ; (expr stmt discarded)
_F6_L2:
    ; ch
    STA $81
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _ch
    CMP $82
    ; -> end
    BEQ _F6_L3
    ; ch
    LDA _ch
    ; __SAVE__:11:10
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; s
    LDX _s+1
    STA $81
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _s
    STA $85
    LDA _s+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _s
    STX _s+1
    ; (expr stmt discarded)
    ; s
    LDA _s
    LDX _s+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP _F6_L2
_F6_L3:
    ; === end Stdio.print__s ===
    ; === method Stdio.print__u16 ===
_cls_Stdio_print__u16:
    ; val
    LDX _val+1
    STA $80
    ; const 10
    LDA #$0A
    STA $82
    ; cmp
    LDX #$00
    STX $83
    LDA _val+1
    CMP $83
    BNE _F7__L8
    LDA _val
    CMP $82
_F7__L8:
    ; -> else
    BCC _F7_L0
    ; val
    LDX _val+1
    STA $80
    ; const 10
    LDA #$0A
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _val
    JSR _div16
    STA $85
    STX $86
    ; =
    STA _d
    STX _d+1
    ; (expr stmt discarded)
    ; d
    LDA _d
    LDX _d+1
    ; __SAVE__:9:8
    ; arg
    TXA
    PHA
    LDA $80
    PHA
    ; call
    JSR _cls_Stdio_print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
_F7_L0:
    ; val
    LDX _val+1
    STA $80
    ; const 10
    LDA #$0A
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _val
    JSR _mod16
    STA $85
    STX $86
    ; =
    STA _r
    ; (expr stmt discarded)
    ; r
    STA $80
    ; const 48
    LDA #$30
    STA $82
    ; binop
    CLC
    ADC _r
    STA $83
    ; __SAVE__:16:14
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__u16 ===
    ; === method Stdio.print__i16 ===
_cls_Stdio_print__i16:
    ; val
    LDX _val+1
    STA $80
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDX #$00
    STX $83
    LDA _val+1
    CMP $83
    BNE _F9__L10
    LDA _val
    CMP $82
_F9__L10:
    ; -> else
    BPL _F9_L0
    ; const 45
    LDA #$2D
    STA $80
    ; __SAVE__:5:4
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; val
    LDA _val
    LDX _val+1
    ; binop
    LDA $80
    LDX #$00
    STX $81
    SEC
    SBC _val
    STA $84
    LDA $81
    SBC _val+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _val
    STX _val+1
    ; (expr stmt discarded)
_F9_L0:
    ; val
    LDA _val
    LDX _val+1
    ; __SAVE__:11:10
    ; arg
    TXA
    PHA
    LDA $80
    PHA
    ; call
    JSR _cls_Stdio_print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__i16 ===
    ; === method Stdio.print__u32 ===
_cls_Stdio_print__u32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; cmp
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    LDX #$00
    STX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    LDA _val+3
    CMP $87
    BNE _F11__L12
    LDA _val+2
    CMP $86
    BNE _F11__L12
    LDA _val+1
    CMP $85
    BNE _F11__L12
    LDA _val
    CMP $84
_F11__L12:
    ; -> else
    BCC _F11_L0
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; u32 div
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA _val+2
    STA $B2
    LDA _val+3
    STA $B3
    LDA _val
    JSR _div32
    STA $8A
    STX $8B
    LDA $B2
    STA $8C
    LDA $B3
    STA $8D
    ; =
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _d
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STX _d+1
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _d+2
    LDA $8C
    STA $B2
    LDA $8D
    STA $B3
    LDA $8A
    STA _d+3
    ; (expr stmt discarded)
    ; d
    LDA _d
    STA $80
    LDA _d+1
    STA $81
    LDA _d+2
    STA $82
    LDA _d+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; __SAVE__:9:8
    ; arg
    LDA $83
    PHA
    LDA $82
    PHA
    TXA
    PHA
    LDA $80
    PHA
    ; call
    JSR _cls_Stdio_print__u32
    ; __RESTORE__
    ; (expr stmt discarded)
_F11_L0:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 10
    LDA #$0A
    STA $84
    ; u32 mod
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $84
    STA $B4
    LDA $85
    STA $B5
    LDA $86
    STA $B6
    LDA $87
    STA $B7
    LDA _val+2
    STA $B2
    LDA _val+3
    STA $B3
    LDA _val
    JSR _mod32
    STA $8A
    STX $8B
    LDA $B2
    STA $8C
    LDA $B3
    STA $8D
    ; =
    LDA $8A
    STA _r
    ; (expr stmt discarded)
    ; r
    STA $80
    ; const 48
    LDA #$30
    STA $82
    ; binop
    CLC
    ADC _r
    STA $83
    ; __SAVE__:16:14
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__u32 ===
    ; === method Stdio.print__i32 ===
_cls_Stdio_print__i32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $84
    LDX #$00
    STX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    LDA _val+3
    CMP $87
    BNE _F13__L14
    LDA _val+2
    CMP $86
    BNE _F13__L14
    LDA _val+1
    CMP $85
    BNE _F13__L14
    LDA _val
    CMP $84
_F13__L14:
    ; -> else
    BPL _F13_L0
    ; const 45
    LDA #$2D
    STA $80
    ; __SAVE__:5:4
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; val
    LDA _val
    STA $84
    LDA _val+1
    STA $85
    LDA _val+2
    STA $86
    LDA _val+3
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    LDA $B2
    STA $86
    LDA $B3
    STA $87
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    LDX #$00
    STX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    SEC
    LDA $80
    SBC _val
    STA $89
    LDA $81
    SBC _val+1
    STA $8A
    LDA $82
    SBC _val+2
    STA $8B
    LDA $83
    SBC _val+3
    STA $8C
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    LDX $8A
    ; =
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _val
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STX _val+1
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _val+2
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    STA _val+3
    ; (expr stmt discarded)
_F13_L0:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; __SAVE__:11:10
    ; arg
    LDA $83
    PHA
    LDA $82
    PHA
    TXA
    PHA
    LDA $80
    PHA
    ; call
    JSR _cls_Stdio_print__u32
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.print__i32 ===
    ; === method Stdio.printHex__u8 ===
_cls_Stdio_printHex__u8:
    ; n
    STA $80
    ; const 10
    LDA #$0A
    STA $81
    ; cmp
    LDA _n
    CMP $81
    ; -> else
    BCS _F15_L0
    ; n
    STA $80
    ; const 48
    LDA #$30
    STA $81
    ; binop
    CLC
    ADC _n
    STA $89
    ; __SAVE__:6:4
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP _F15_L1
_F15_L0:
    ; n
    STA $80
    ; const 55
    LDA #$37
    STA $81
    ; binop
    CLC
    ADC _n
    STA $82
    ; __SAVE__:10:8
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
_F15_L1:
    ; === end Stdio.printHex__u8 ===
    ; === method Stdio.printHex__u16 ===
_cls_Stdio_printHex__u16:
    ; val
    LDX _val+1
    STA $80
    ; const 12
    LDA #$0C
    STA $82
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $82
    BEQ _F16__L18
_F16__L17:
    LSR $B1
    ROR $B0
    DEX
    BNE _F16__L17
_F16__L18:
    LDA $B0
    STA $86
    LDA $B1
    STA $87
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $89
    ; binop
    LDX #$00
    STX $8A
    AND $86
    STA $8B
    LDA $87
    AND $8A
    STA $8C
    LDA $8B
    LDX $8C
    ; __SAVE__:5:1
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    STA $86
    ; const 8
    LDA #$08
    STA $89
    ; binop
    LDA $86
    STA $B0
    LDA $87
    STA $B1
    LDX $89
    BEQ _F16__L20
_F16__L19:
    LSR $B1
    ROR $B0
    DEX
    BNE _F16__L19
_F16__L20:
    LDA $B0
    STA $8B
    LDA $B1
    STA $8C
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $84
    ; binop
    LDX #$00
    STX $85
    AND $8B
    STA $8D
    LDA $8C
    AND $85
    STA $8E
    LDA $8D
    LDX $8E
    ; __SAVE__:11:7
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    STA $84
    ; const 4
    LDA #$04
    STA $86
    ; binop
    LDA $84
    STA $B0
    LDA $85
    STA $B1
    LDX $86
    BEQ _F16__L22
_F16__L21:
    LSR $B1
    ROR $B0
    DEX
    BNE _F16__L21
_F16__L22:
    LDA $B0
    STA $80
    LDA $B1
    STA $81
    LDA $B0
    LDX $B1
    ; const 15
    LDA #$0F
    STA $82
    ; binop
    LDX #$00
    STX $83
    AND $80
    STA $84
    LDA $81
    AND $83
    STA $85
    LDA $84
    LDX $85
    ; __SAVE__:17:13
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDX _val+1
    STA $82
    ; const 15
    LDA #$0F
    STA $84
    ; binop
    LDX #$00
    STX $85
    AND _val
    STA $89
    LDA _val+1
    AND $85
    STA $8A
    LDA $89
    LDX $8A
    ; __SAVE__:21:19
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_printHex__u8
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printHex__u16 ===
    ; === method Stdio.printHex__u32 ===
_cls_Stdio_printHex__u32:
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 16
    LDA #$10
    STA $84
    ; u32 op
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDX $84
    BEQ _F23__L25
_F23__L24:
    LSR $B3
    ROR $B2
    ROR $B1
    ROR $B0
    DEX
    BNE _F23__L24
_F23__L25:
    LDA $B0
    STA $89
    LDA $B1
    STA $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    LDA $B0
    LDX $B1
    LDY $B2
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $80
    STX $81
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $80
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    LDA $89
    AND $80
    STA $8D
    LDA $8A
    AND $81
    STA $8E
    LDA $8B
    AND $82
    STA $8F
    LDA $8C
    AND $83
    STA $90
    LDA $8F
    STA $B2
    LDA $90
    STA $B3
    LDA $8D
    LDX $8E
    ; __SAVE__:6:1
    ; arg
    TXA
    PHA
    LDA $8D
    PHA
    ; call
    JSR _cls_Stdio_printHex__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; val
    LDA _val
    STA $80
    LDA _val+1
    STA $81
    LDA _val+2
    STA $82
    LDA _val+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; const 65535
    LDA #$FF
    LDX #$FF
    STA $89
    STX $8A
    ; u32 op
    LDA #$00
    STA $B2
    LDA #$00
    STA $B3
    LDA $89
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    LDA _val
    AND $89
    STA $84
    LDA _val+1
    AND $8A
    STA $85
    LDA _val+2
    AND $8B
    STA $86
    LDA _val+3
    AND $8C
    STA $87
    LDA $86
    STA $B2
    LDA $87
    STA $B3
    LDA $84
    LDX $85
    ; __SAVE__:10:7
    ; arg
    TXA
    PHA
    LDA $84
    PHA
    ; call
    JSR _cls_Stdio_printHex__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printHex__u32 ===
    ; === method Stdio.print__f ===
_cls_Stdio_print__f:
    ; canPrint
    STA $80
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE _F26_L0
    ; return
    RTS
_F26_L0:
LDA f : STA $B0
LDA f+1 : STA $B1
LDA f+2 : STA $B2
LDA f+3 : STA $B3
LDA f+4 : STA $B4
LDA #< $04C0
STA $B5
LDY #_ivar_Stdio_fpBufPtr
STA ( __self ),Y
LDA #> $04C0
STA $B6
LDY #_ivar_Stdio_fpBufPtr+1
STA ( __self ),Y
JSR fp2Asc
    ; fpBufPtr
    LDA _fpBufPtr
    LDX _fpBufPtr+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _ch
    ; (expr stmt discarded)
_F26_L2:
    ; ch
    STA $81
    ; const 0
    LDA #$00
    STA $82
    ; cmp
    LDA _ch
    CMP $82
    ; -> end
    BEQ _F26_L3
    ; ch
    LDA _ch
    ; __SAVE__:11:10
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fpBufPtr
    LDX _fpBufPtr+1
    STA $81
    ; const 1
    LDA #$01
    STA $83
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _fpBufPtr
    STA $85
    LDA _fpBufPtr+1
    ADC $84
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _fpBufPtr
    STX _fpBufPtr+1
    ; (expr stmt discarded)
    ; fpBufPtr
    LDA _fpBufPtr
    LDX _fpBufPtr+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP _F26_L2
_F26_L3:
    ; === end Stdio.print__f ===
    ; === method Stdio.setCursor ===
_cls_Stdio_setCursor:
    ; y
    LDA _y
    ; =
    LDX #$00
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; offset
    STX $81
    LDX _offset+1
    STA $80
    ; cols
    LDA _cols
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDA $82
    STA $B4
    LDA $83
    STA $B5
    LDA _offset
    JSR _mul16
    STA $84
    STX $85
    ; =
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; offset
    LDX _offset+1
    STA $80
    ; x
    LDA _x
    ; binop
    CLC
    LDX #$00
    STX $83
    ADC _offset
    STA $84
    LDA _offset+1
    ADC _x+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _offset
    STX _offset+1
    ; (expr stmt discarded)
    ; screenBase
    STA $80
    STX $81
    ; offset
    LDA _offset
    LDX _offset+1
    ; binop
    CLC
    ADC _screenBase
    STA $84
    LDA _screenBase+1
    ADC _offset+1
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _screenPtr
    STX _screenPtr+1
    ; (expr stmt discarded)
    ; === end Stdio.setCursor ===
    ; === method Stdio.printStruct ===
_cls_Stdio_printStruct:
    ; const 40
    LDA #$28
    STA $80
    ; __SAVE__:2:1
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $8D
    LDA $8D
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $8D
    ; const 1
    LDA #$01
    STA $8F
    ; binop
    CLC
    LDX #$00
    STX $90
    ADC _psDesc
    STA $91
    LDA _psDesc+1
    ADC $90
    STA $92
    LDA $91
    LDX $92
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $87
    ; =
    STA _depth
    ; (expr stmt discarded)
_F28_L0:
    ; const 1
    LDA #$01
    STA $87
    ; -> end
    BEQ _F28_L1
    ; psIdx
    STA $87
    ; psFieldCount
    STA $8D
    ; cmp
    LDA _psIdx
    CMP _psFieldCount
    ; -> else
    BCC _F28_L2
    ; const 41
    LDA #$29
    STA $93
    ; __SAVE__:19:18
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; depth
    STA $8D
    ; const 0
    LDA #$00
    STA $8E
    ; cmp
    LDA _depth
    CMP $8E
    ; -> else
    BNE _F28_L4
    ; return
    RTS
_F28_L4:
LDY #$00
DEC $82 : BCS .pop_a : DEC $83
.pop_a :
LDA ( $82 ),Y : STA __sdata_Stdio+14 ; psIdx
DEC $82 : BCS .pop_b : DEC $83
.pop_b :
LDA ( $82 ),Y : STA __sdata_Stdio+13 ; psFieldCount
DEC $82 : BCS .pop_c : DEC $83
.pop_c :
LDA ( $82 ),Y : STA __sdata_Stdio+12 ; psDesc hi
DEC $82 : BCS .pop_d : DEC $83
.pop_d :
LDA ( $82 ),Y : STA __sdata_Stdio+11 ; psDesc lo
DEC $82 : BCS .pop_e : DEC $83
.pop_e :
LDA ( $82 ),Y : STA __sdata_Stdio+10 ; psDp hi
DEC $82 : BCS .pop_f : DEC $83
.pop_f :
LDA ( $82 ),Y : STA __sdata_Stdio+9 ; psDp lo
    ; depth
    STA $8D
    ; const 1
    LDA #$01
    STA $8E
    ; binop
    SEC
    LDA _depth
    SBC $8E
    STA $93
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; continue
    JMP _F28_L0
_F28_L2:
    ; psIdx
    STA $8D
    ; const 0
    LDA #$00
    STA $8E
    ; cmp
    LDA _psIdx
    CMP $8E
    ; -> else
    BEQ _F28_L6
    BCC _F28_L6
    ; const 44
    LDA #$2C
    STA $93
    ; __SAVE__:31:30
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; const 32
    LDA #$20
    STA $93
    ; __SAVE__:33:32
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
_F28_L6:
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $95
    LDA $95
    ; =
    STA _fieldType
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $93
    ; const 1
    LDA #$01
    STA $84
    ; binop
    CLC
    LDX #$00
    STX $85
    ADC _psDesc
    STA $95
    LDA _psDesc+1
    ADC $85
    STA $96
    LDA $95
    LDX $96
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $95
    LDA $95
    ; =
    STA _fieldSize
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $93
    ; const 1
    LDA #$01
    STA $95
    ; binop
    CLC
    LDX #$00
    STX $96
    ADC _psDesc
    STA $97
    LDA _psDesc+1
    ADC $96
    STA $98
    LDA $97
    LDX $98
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; fieldType
    STA $87
    ; const 0
    LDA #$00
    STA $8D
    ; cmp
    LDA _fieldType
    CMP $8D
    ; -> else
    BNE _F28_L8
    ; psDp
    LDA _psDp
    STX $8E
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $93
    LDA $93
    ; __SAVE__:53:51
    ; arg
    LDA #$00
    PHA
    LDA $93
    PHA
    ; call
    JSR _cls_Stdio_print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    STA $8D
    ; const 1
    LDA #$01
    STA $93
    ; binop
    CLC
    LDX #$00
    STX $94
    ADC _psDp
    STA $95
    LDA _psDp+1
    ADC $94
    STA $96
    LDA $95
    LDX $96
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; -> end
    JMP _F28_L9
_F28_L8:
    ; fieldType
    STA $87
    ; const 2
    LDA #$02
    STA $8D
    ; cmp
    LDA _fieldType
    CMP $8D
    ; -> else
    BNE _F28_L10
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    STA $80
    ; const 1
    LDA #$01
    STA $8D
    ; binop
    CLC
    LDX #$00
    STX $8E
    ADC _psDp
    STA $93
    LDA _psDp+1
    ADC $8E
    STA $94
    LDA $93
    LDX $94
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    STA $80
    ; const 1
    LDA #$01
    STA $8D
    ; binop
    CLC
    LDX #$00
    STX $8E
    ADC _psDp
    STA $93
    LDA _psDp+1
    ADC $8E
    STA $94
    LDA $93
    LDX $94
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    LDA _hi
    ; =
    LDX #$00
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    STX $81
    LDX _fieldVal+1
    STA $80
    ; const 8
    LDA #$08
    STA $8D
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $8D
    BEQ _F28__L30
_F28__L29:
    ASL $B0
    ROL $B1
    DEX
    BNE _F28__L29
_F28__L30:
    LDA $B0
    STA $93
    LDA $B1
    STA $94
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $93
    STA $8D
    LDA $94
    ORA _lo+1
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    LDA _fieldVal
    LDX _fieldVal+1
    ; __SAVE__:84:83
    ; arg
    TXA
    PHA
    LDA $93
    PHA
    ; call
    JSR _cls_Stdio_print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP _F28_L11
_F28_L10:
    ; fieldType
    STA $80
    ; const 3
    LDA #$03
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE _F28_L12
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDp
    STA $8D
    LDA _psDp+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDp
    STA $8D
    LDA _psDp+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    LDA _hi
    ; =
    LDX #$00
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    STX $81
    LDX _fieldVal+1
    STA $80
    ; const 8
    LDA #$08
    STA $86
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $86
    BEQ _F28__L32
_F28__L31:
    ASL $B0
    ROL $B1
    DEX
    BNE _F28__L31
_F28__L32:
    LDA $B0
    STA $8D
    LDA $B1
    STA $8E
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $8D
    STA $86
    LDA $8E
    ORA _lo+1
    STA $87
    LDA $86
    LDX $87
    ; =
    STA _fieldVal
    STX _fieldVal+1
    ; (expr stmt discarded)
    ; fieldVal
    LDA _fieldVal
    LDX _fieldVal+1
    ; __SAVE__:111:110
    ; arg
    TXA
    PHA
    LDA $93
    PHA
    ; call
    JSR _cls_Stdio_print__i16
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP _F28_L13
_F28_L12:
    ; fieldType
    STA $80
    ; const 8
    LDA #$08
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE _F28_L14
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDesc
    STA $8D
    LDA _psDesc+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDesc
    STA $8D
    LDA _psDesc+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psIdx
    STA $80
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $83
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; =
    STA _psSaveDp
    STX _psSaveDp+1
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    STA $80
    ; fieldSize
    LDA _fieldSize
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDp
    STA $8D
    LDA _psDp+1
    ADC _fieldSize+1
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
LDY #$00
LDA __sdata_Stdio+9 : STA ( $82 ),Y ; psDp lo ( post - struct )
INC $82 : BNE .push8_a : INC $83
.push8_a :
LDA __sdata_Stdio+10 : STA ( $82 ),Y ; psDp hi
INC $82 : BNE .push8_b : INC $83
.push8_b :
LDA __sdata_Stdio+11 : STA ( $82 ),Y ; psDesc lo
INC $82 : BNE .push8_c : INC $83
.push8_c :
LDA __sdata_Stdio+12 : STA ( $82 ),Y ; psDesc hi
INC $82 : BNE .push8_d : INC $83
.push8_d :
LDA __sdata_Stdio+13 : STA ( $82 ),Y ; psFieldCount
INC $82 : BNE .push8_e : INC $83
.push8_e :
LDA __sdata_Stdio+14 : STA ( $82 ),Y ; psIdx
INC $82 : BNE .push8_f : INC $83
.push8_f :
    ; depth
    STA $80
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _depth
    STA $83
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; psSaveDp
    LDA _psSaveDp
    LDX _psSaveDp+1
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    STA $80
    ; const 8
    LDA #$08
    STA $86
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $86
    BEQ _F28__L34
_F28__L33:
    ASL $B0
    ROL $B1
    DEX
    BNE _F28__L33
_F28__L34:
    LDA $B0
    STA $8D
    LDA $B1
    STA $8E
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $8D
    STA $86
    LDA $8E
    ORA _lo+1
    STA $87
    LDA $86
    LDX $87
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDesc
    STA $8D
    LDA _psDesc+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 40
    LDA #$28
    STA $93
    ; __SAVE__:161:160
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; continue
    JMP _F28_L0
    ; -> end
    JMP _F28_L15
_F28_L14:
    ; fieldType
    STA $80
    ; const 9
    LDA #$09
    STA $81
    ; cmp
    LDA _fieldType
    CMP $81
    ; -> else
    BNE _F28_L16
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _dpLo
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDp
    STA $8D
    LDA _psDp+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDp
    LDA _psDp
    LDX _psDp+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _dpHi
    ; (expr stmt discarded)
    ; psDp
    LDX _psDp+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDp
    STA $8D
    LDA _psDp+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _lo
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDesc
    STA $8D
    LDA _psDesc+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _hi
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDesc
    STA $8D
    LDA _psDesc+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psIdx
    STA $80
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $83
    ; =
    STA _psIdx
    ; (expr stmt discarded)
LDY #$00
LDA __sdata_Stdio+9 : STA ( $82 ),Y ; psDp lo ( post - pointer )
INC $82 : BNE .push9_a : INC $83
.push9_a :
LDA __sdata_Stdio+10 : STA ( $82 ),Y ; psDp hi
INC $82 : BNE .push9_b : INC $83
.push9_b :
LDA __sdata_Stdio+11 : STA ( $82 ),Y ; psDesc lo
INC $82 : BNE .push9_c : INC $83
.push9_c :
LDA __sdata_Stdio+12 : STA ( $82 ),Y ; psDesc hi
INC $82 : BNE .push9_d : INC $83
.push9_d :
LDA __sdata_Stdio+13 : STA ( $82 ),Y ; psFieldCount
INC $82 : BNE .push9_e : INC $83
.push9_e :
LDA __sdata_Stdio+14 : STA ( $82 ),Y ; psIdx
INC $82 : BNE .push9_f : INC $83
.push9_f :
    ; depth
    STA $80
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _depth
    STA $83
    ; =
    STA _depth
    ; (expr stmt discarded)
    ; dpHi
    STA $80
    ; const 8
    LDA #$08
    STA $86
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $86
    BEQ _F28__L36
_F28__L35:
    ASL $B0
    ROL $B1
    DEX
    BNE _F28__L35
_F28__L36:
    LDA $B0
    STA $8D
    LDA $B1
    STA $8E
    LDA $B0
    LDX $B1
    ; dpLo
    LDA _dpLo
    ; binop
    LDX #$00
    STX $81
    ORA $8D
    STA $86
    LDA $8E
    ORA _dpLo+1
    STA $87
    LDA $86
    LDX $87
    ; =
    STA _psSaveDp
    STX _psSaveDp+1
    ; (expr stmt discarded)
    ; psSaveDp
    LDA _psSaveDp
    LDX _psSaveDp+1
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; hi
    STA $80
    ; const 8
    LDA #$08
    STA $86
    ; binop
    LDA $80
    STA $B0
    LDA $81
    STA $B1
    LDX $86
    BEQ _F28__L38
_F28__L37:
    ASL $B0
    ROL $B1
    DEX
    BNE _F28__L37
_F28__L38:
    LDA $B0
    STA $8D
    LDA $B1
    STA $8E
    LDA $B0
    LDX $B1
    ; lo
    LDA _lo
    ; binop
    LDX #$00
    STX $81
    ORA $8D
    STA $86
    LDA $8E
    ORA _lo+1
    STA $87
    LDA $86
    LDX $87
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; psDesc
    LDA _psDesc
    LDX _psDesc+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $83
    LDA $83
    ; =
    STA _psFieldCount
    ; (expr stmt discarded)
    ; psDesc
    LDX _psDesc+1
    STA $80
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _psDesc
    STA $8D
    LDA _psDesc+1
    ADC $87
    STA $8E
    LDA $8D
    LDX $8E
    ; =
    STA _psDesc
    STX _psDesc+1
    ; (expr stmt discarded)
    ; const 0
    LDA #$00
    STA $80
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; const 40
    LDA #$28
    STA $8D
    ; __SAVE__:225:224
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; continue
    JMP _F28_L0
    ; -> end
    JMP _F28_L17
_F28_L16:
    ; psDp
    LDX _psDp+1
    STA $80
    ; fieldSize
    LDA _fieldSize
    ; binop
    CLC
    LDX #$00
    STX $84
    ADC _psDp
    STA $85
    LDA _psDp+1
    ADC _fieldSize+1
    STA $86
    LDA $85
    LDX $86
    ; =
    STA _psDp
    STX _psDp+1
    ; (expr stmt discarded)
    ; const 63
    LDA #$3F
    STA $83
    ; __SAVE__:231:230
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
_F28_L17:
_F28_L15:
_F28_L13:
_F28_L11:
_F28_L9:
    ; psIdx
    STA $80
    ; const 1
    LDA #$01
    STA $81
    ; binop
    CLC
    ADC _psIdx
    STA $82
    ; =
    STA _psIdx
    ; (expr stmt discarded)
    ; -> loop
    JMP _F28_L0
_F28_L1:
    ; === end Stdio.printStruct ===
    ; === method Stdio.printf ===
_cls_Stdio_printf:
    ; canPrint
    STA $80
    ; const 0
    LDA #$00
    STA $81
    ; cmp
    LDA _canPrint
    CMP $81
    ; -> else
    BNE _F39_L0
    ; return
    RTS
_F39_L0:
    ; ap
    LDA _ap
    ; __SAVE__:5:4
    ; call
    JSR __intrinsic_va_start
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $81
    LDA $81
    ; =
    STA _ch
    ; (expr stmt discarded)
_F39_L2:
    ; ch
    STA $81
    ; const 0
    LDA #$00
    STA $84
    ; cmp
    LDA _ch
    CMP $84
    ; -> end
    BEQ _F39_L3
    ; ch
    STA $81
    ; const 37
    LDA #$25
    STA $86
    ; cmp
    LDA _ch
    CMP $86
    ; -> else
    BNE _F39_L4
    ; fmt
    LDX _fmt+1
    STA $86
    ; const 1
    LDA #$01
    STA $89
    ; binop
    CLC
    LDX #$00
    STX $8A
    ADC _fmt
    STA $8B
    LDA _fmt+1
    ADC $8A
    STA $8C
    LDA $8B
    LDX $8C
    ; =
    STA _fmt
    STX _fmt+1
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $81
    LDA $81
    ; =
    STA _spec
    ; (expr stmt discarded)
    ; spec
    STA $81
    ; const 37
    LDA #$25
    STA $86
    ; cmp
    LDA _spec
    CMP $86
    ; -> else
    BNE _F39_L6
    ; const 37
    LDA #$25
    STA $89
    ; __SAVE__:26:25
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
    ; -> end
    JMP _F39_L7
_F39_L6:
    ; spec
    STA $81
    ; const 117
    LDA #$75
    STA $87
    ; cmp
    LDA _spec
    CMP $87
    ; -> else
    BNE _F39_L8
    ; ap
    LDA _ap
    ; __SAVE__:32:31
    ; call
    JSR __intrinsic_va_arg_u16
    STA $89
    STX $8A
    ; __RESTORE__
    ; __SAVE__:31:30
    ; arg
    TXA
    PHA
    LDA $89
    PHA
    ; call
    JSR _cls_Stdio_print__u16
    ; __RESTORE__
    ; (expr stmt discarded)
_F39_L8:
_F39_L7:
    ; -> end
    JMP _F39_L5
_F39_L4:
    ; ch
    LDA _ch
    ; __SAVE__:34:33
    ; arg
    PHA
    ; call
    JSR _cls_Stdio_putChar
    ; __RESTORE__
    ; (expr stmt discarded)
_F39_L5:
    ; fmt
    LDX _fmt+1
    STA $81
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    LDX #$00
    STX $87
    ADC _fmt
    STA $84
    LDA _fmt+1
    ADC $87
    STA $85
    LDA $84
    LDX $85
    ; =
    STA _fmt
    STX _fmt+1
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $82
    LDA $82
    ; =
    STA _ch
    ; (expr stmt discarded)
    ; -> loop
    JMP _F39_L2
_F39_L3:
    ; ap
    LDA _ap
    ; __SAVE__:43:42
    ; call
    JSR __intrinsic_va_end
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printf ===
    ; === method Stdio.printfAt ===
_cls_Stdio_printfAt:
    ; x
    STA $80
    ; y
    LDA _y
    ; __SAVE__:2,3:1
    ; arg
    PHA
    ; arg
    LDA $80
    PHA
    ; call
    JSR _cls_Stdio_setCursor
    ; __RESTORE__
    ; (expr stmt discarded)
    ; fmt
    LDA _fmt
    LDX _fmt+1
    ; __SAVE__:5:4
    ; arg
    TXA
    PHA
    LDA $80
    PHA
    ; call
    JSR _cls_Stdio_printf
    ; __RESTORE__
    ; (expr stmt discarded)
    ; === end Stdio.printfAt ===
    ; === function checker ===
_checker:
	PLA
	STA $B0
	PLA
	STA $B1
    ; tag
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
	LDA $B1
	PHA
	LDA $B0
	PHA
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_start
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    TXA
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_u8
    STA $83
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $83
    STA _r_u8
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    TXA
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_i8
    STA $8D
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $8D
    STA _r_i8
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    TXA
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_u16
    STA $97
    STX $98
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $97
    LDX $98
    STA _r_u16
    STX _r_u16+1
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_i16
    STA $97
    STX $98
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $97
    LDX $98
    STA _r_i16
    STX _r_i16+1
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_u32
    STA $9D
    STX $9E
    LDA $B2
    STA $9F
    LDA $B3
    STA $A0
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $9D
    LDX $9E
    STA _r_u32
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $9D
    STX _r_u32+1
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $9D
    STA _r_u32+2
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $9D
    STA _r_u32+3
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_i32
    STA $9D
    STX $9E
    LDA $B2
    STA $9F
    LDA $B3
    STA $A0
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $9D
    LDX $9E
    STA _r_i32
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $9D
    STX _r_i32+1
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $9D
    STA _r_i32+2
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $9D
    STA _r_i32+3
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_float
    STA $9A
    STX $9B
    LDA $B2
    STA $9C
    LDA $B3
    STA $9D
    LDA $B4
    STA $9E
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $9C
    STA $B2
    LDA $9D
    STA $B3
    LDA $9E
    STA $B4
    LDA $9A
    LDX $9B
    STA _r_f
    LDA $9C
    STA $B2
    LDA $9D
    STA $B3
    LDA $9E
    STA $B4
    LDA $9A
    STX _r_f+1
    LDA $9C
    STA $B2
    LDA $9D
    STA $B3
    LDA $9E
    STA $B4
    LDA $9A
    STA _r_f+2
    LDA $9C
    STA $B2
    LDA $9D
    STA $B3
    LDA $9E
    STA $B4
    LDA $9A
    STA _r_f+3
    LDA $9C
    STA $B2
    LDA $9D
    STA $B3
    LDA $9E
    STA $B4
    LDA $9A
    STA _r_f+4
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_double
    STA $9D
    STX $9E
    LDA $B2
    STA $9F
    LDA $B3
    STA $A0
    LDA $B4
    STA $A1
    LDA $B5
    STA $A2
    LDA $B6
    STA $A3
    LDA $B7
    STA $A4
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $A1
    STA $B4
    LDA $A2
    STA $B5
    LDA $A3
    STA $B6
    LDA $A4
    STA $B7
    LDA $9D
    LDX $9E
    STA _r_d
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $A1
    STA $B4
    LDA $A2
    STA $B5
    LDA $A3
    STA $B6
    LDA $A4
    STA $B7
    LDA $9D
    STX _r_d+1
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $A1
    STA $B4
    LDA $A2
    STA $B5
    LDA $A3
    STA $B6
    LDA $A4
    STA $B7
    LDA $9D
    STA _r_d+2
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $A1
    STA $B4
    LDA $A2
    STA $B5
    LDA $A3
    STA $B6
    LDA $A4
    STA $B7
    LDA $9D
    STA _r_d+3
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $A1
    STA $B4
    LDA $A2
    STA $B5
    LDA $A3
    STA $B6
    LDA $A4
    STA $B7
    LDA $9D
    STA _r_d+4
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $A1
    STA $B4
    LDA $A2
    STA $B5
    LDA $A3
    STA $B6
    LDA $A4
    STA $B7
    LDA $9D
    STA _r_d+5
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $A1
    STA $B4
    LDA $A2
    STA $B5
    LDA $A3
    STA $B6
    LDA $A4
    STA $B7
    LDA $9D
    STA _r_d+6
    LDA $9F
    STA $B2
    LDA $A0
    STA $B3
    LDA $A1
    STA $B4
    LDA $A2
    STA $B5
    LDA $A3
    STA $B6
    LDA $A4
    STA $B7
    LDA $9D
    STA _r_d+7
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_ptr
    STA $84
    STX $85
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $84
    LDX $85
    STA _r_s
    STX _r_s+1
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_arg_ptr
    STA $84
    STX $85
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; =
    LDA $84
    LDX $85
    STA _r_p
    STX _r_p+1
    ; (expr stmt discarded)
    ; ap
    LDA _ap
    ; save param
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR __intrinsic_va_end
    ; restore param
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
    ; (expr stmt discarded)
    RTS
    ; === end checker ===
    ; === function check ===
_check:
	PLA
	STA $B0
	PLA
	STA $B1
    ; n
    PLA
    STA $80
    ; ok
    PLA
    STA $84
	LDA $B1
	PHA
	LDA $B0
	PHA
    ; testCount
    STA $85
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    ADC _testCount
    STA $87
    ; =
    STA _testCount
    ; (expr stmt discarded)
    ; → true
    LDA $84
    BEQ _F42_L2
    LDA #$00
    STA $85
    ; → end
    JMP _F42_L3
_F42_L2:
    LDA #$01
    STA $85
_F42_L3:
    ; -> else
    BEQ _F42_L0
    ; failCount
    STA $85
    ; const 1
    LDA #$01
    STA $86
    ; binop
    CLC
    ADC _failCount
    STA $87
    ; =
    STA _failCount
    ; (expr stmt discarded)
    ; Stdio
    LDA _Stdio
    STA $89
    LDA _Stdio+1
    STA $8A
    LDA _Stdio+2
    STA $8B
    LDA _Stdio+3
    STA $8C
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    LDX $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    ; string literal
    LDA #_str_0
    LDX #_str_0+1
    STA $8D
    STX $8E
_str_0: .byte $54,$25,$75,$20,$46,$41,$49,$4C,$0A,0
    ; save param
    LDA $80
    PHA
    ; save param
    LDA $84
    PHA
    ; arg
    LDA $8A
    PHA
    LDA $89
    PHA
    ; mcall
    JSR _cls_Stdio_printf
    ; restore param
    PLA
    STA $84
    ; restore param
    PLA
    STA $80
    ; (expr stmt discarded)
_F42_L0:
    RTS
    ; === end check ===
    ; === function main ===
_main:
    ; const 99
    LDA #$63
    STA $81
    ; =
    STA _sentinel
    ; (expr stmt discarded)
    ; var ptrArg =
    ; sentinel
    STA $82
    LDA _sentinel
    ; &x
    LDA #_sentinel
    LDX #_sentinel+1
    STA $84
    STX $85
    STA _ptrArg
    STX _ptrArg+1
    ; string literal
    LDA #_str_1
    LDX #_str_1+1
    STA $89
    STX $8A
_str_1: .byte $70,$72,$6F,$62,$65,0
    ; const 200
    LDA #$C8
    STA $8D
    ; const -7
    LDA #$F9
    STA $91
    ; const 1234
    LDA #$D2
    LDX #$04
    STA $97
    STX $98
    ; const -1000
    LDA #$18
    LDX #$FC
    STA $9B
    STX $9C
    ; const 100000
    LDA #$A0
    STA $9F
    LDA #$86
    STA $A0
    LDA #$01
    STA $A1
    LDA #$00
    STA $A2
    LDA $A1
    STA $B2
    LDA $A2
    STA $B3
    LDA $9F
    LDX $A0
    ; const -100000
    LDA #$60
    STA $A7
    LDA #$79
    STA $A8
    LDA #$FE
    STA $A9
    LDA #$FF
    STA $AA
    LDA $A9
    STA $B2
    LDA $AA
    STA $B3
    LDA $A7
    LDX $A8
    ; float
    LDA #$00
    STA $BA
    LDA #$00
    STA $BB
    LDA #$20
    STA $BC
    LDA #$40
    STA $BD
    LDA #$00
    STA $BE
    LDA $BC
    STA $B2
    LDA $BD
    STA $B3
    LDA $BE
    STA $B4
    LDA $BA
    LDX $BB
    ; float
    LDA #$00
    STA $BF
    LDA #$00
    STA $C0
    LDA #$C0
    STA $C1
    LDA #$3F
    STA $C2
    LDA #$00
    STA $C3
    LDA #$00
    STA $C4
    LDA #$00
    STA $C5
    LDA #$00
    STA $C6
    LDA $C1
    STA $B2
    LDA $C2
    STA $B3
    LDA $C3
    STA $B4
    LDA $C4
    STA $B5
    LDA $C5
    STA $B6
    LDA $C6
    STA $B7
    LDA $BF
    LDX $C0
    ; string literal
    LDA #_str_2
    LDX #_str_2+1
    STA $CF
    STX $D0
_str_2: .byte $68,$65,$6C,$6C,$6F,0
    ; ptrArg
    LDA _ptrArg
    LDX _ptrArg+1
    ; arg
    LDA $8A
    PHA
    LDA $89
    PHA
    ; call
    JSR _checker
    ; (expr stmt discarded)
    ; const 1
    LDA #$01
    STA $9F
    ; r_u8
    STA $87
    ; const 200
    LDA #$C8
    STA $A7
    ; cmp
    LDA _r_u8
    CMP $A7
    ; arg
    BNE _F43__L44
    LDA #$01
    JMP _F43__L45
_F43__L44:
    LDA #$00
_F43__L45:
    STA $BA
    PHA
    ; arg
    LDA $9F
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 2
    LDA #$02
    STA $9F
    ; r_i8
    STA $81
    ; const -7
    LDA #$F9
    STA $86
    ; cmp
    LDA _r_i8
    CMP $86
    ; arg
    BNE _F43__L46
    LDA #$01
    JMP _F43__L47
_F43__L46:
    LDA #$00
_F43__L47:
    STA $A7
    PHA
    ; arg
    LDA $9F
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 3
    LDA #$03
    STA $9F
    ; r_u16
    STA $86
    STX $87
    ; const 1234
    LDA #$D2
    LDX #$04
    STA $A7
    STX $A8
    ; cmp
    LDA _r_u16+1
    CMP $A8
    BNE _F43__L48
    LDA _r_u16
    CMP $A7
_F43__L48:
    ; arg
    BNE _F43__L49
    LDA #$01
    JMP _F43__L50
_F43__L49:
    LDA #$00
_F43__L50:
    STA $BA
    PHA
    ; arg
    LDA $9F
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 4
    LDA #$04
    STA $9F
    ; r_i16
    STA $83
    STX $84
    ; const -1000
    LDA #$18
    LDX #$FC
    STA $85
    STX $86
    ; cmp
    LDA _r_i16+1
    CMP $86
    BNE _F43__L51
    LDA _r_i16
    CMP $85
_F43__L51:
    ; arg
    BNE _F43__L52
    LDA #$01
    JMP _F43__L53
_F43__L52:
    LDA #$00
_F43__L53:
    STA $A7
    PHA
    ; arg
    LDA $9F
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 5
    LDA #$05
    STA $83
    ; r_u32
    LDA _r_u32
    STA $9F
    LDA _r_u32+1
    STA $A0
    LDA _r_u32+2
    STA $A1
    LDA _r_u32+3
    STA $A2
    LDA $A1
    STA $B2
    LDA $A2
    STA $B3
    LDA $9F
    LDX $A0
    LDA $B2
    STA $A1
    LDA $B3
    STA $A2
    ; const 100000
    LDA #$A0
    STA $A7
    LDA #$86
    STA $A8
    LDA #$01
    STA $A9
    LDA #$00
    STA $AA
    LDA $A9
    STA $B2
    LDA $AA
    STA $B3
    LDA $A7
    LDX $A8
    ; cmp
    LDA _r_u32+3
    CMP $AA
    BNE _F43__L54
    LDA _r_u32+2
    CMP $A9
    BNE _F43__L54
    LDA _r_u32+1
    CMP $A8
    BNE _F43__L54
    LDA _r_u32
    CMP $A7
_F43__L54:
    ; arg
    BNE _F43__L55
    LDA #$01
    JMP _F43__L56
_F43__L55:
    LDA #$00
_F43__L56:
    STA $A3
    PHA
    ; arg
    LDA $83
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 6
    LDA #$06
    STA $83
    ; r_i32
    LDA _r_i32
    STA $89
    LDA _r_i32+1
    STA $8A
    LDA _r_i32+2
    STA $8B
    LDA _r_i32+3
    STA $8C
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $89
    LDX $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    ; const -100000
    LDA #$60
    STA $9F
    LDA #$79
    STA $A0
    LDA #$FE
    STA $A1
    LDA #$FF
    STA $A2
    LDA $A1
    STA $B2
    LDA $A2
    STA $B3
    LDA $9F
    LDX $A0
    ; cmp
    LDA _r_i32+3
    CMP $A2
    BNE _F43__L57
    LDA _r_i32+2
    CMP $A1
    BNE _F43__L57
    LDA _r_i32+1
    CMP $A0
    BNE _F43__L57
    LDA _r_i32
    CMP $9F
_F43__L57:
    ; arg
    BNE _F43__L58
    LDA #$01
    JMP _F43__L59
_F43__L58:
    LDA #$00
_F43__L59:
    STA $A3
    PHA
    ; arg
    LDA $83
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 7
    LDA #$07
    STA $83
    ; r_f
    LDA _r_f
    STA $89
    LDA _r_f+1
    STA $8A
    LDA _r_f+2
    STA $8B
    LDA _r_f+3
    STA $8C
    LDA _r_f+4
    STA $8D
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $8D
    STA $B4
    LDA $89
    LDX $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    LDA $B4
    STA $8D
    ; float
    LDA #$00
    STA $9F
    LDA #$00
    STA $A0
    LDA #$20
    STA $A1
    LDA #$40
    STA $A2
    LDA #$00
    STA $A3
    LDA $A1
    STA $B2
    LDA $A2
    STA $B3
    LDA $A3
    STA $B4
    LDA $9F
    LDX $A0
    ; float compare
    LDA _r_f+4
    CMP $A3
    BNE _F43__L60
    LDA _r_f+3
    CMP $A2
    BNE _F43__L60
    LDA _r_f+2
    CMP $A1
    BNE _F43__L60
    LDA _r_f+1
    CMP $A0
    BNE _F43__L60
    LDA _r_f
    CMP $9F
_F43__L60:
    ; arg
    BNE _F43__L61
    LDA #$01
    JMP _F43__L62
_F43__L61:
    LDA #$00
_F43__L62:
    STA $A4
    PHA
    ; arg
    LDA $83
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 8
    LDA #$08
    STA $83
    ; r_d
    LDA _r_d
    STA $89
    LDA _r_d+1
    STA $8A
    LDA _r_d+2
    STA $8B
    LDA _r_d+3
    STA $8C
    LDA _r_d+4
    STA $8D
    LDA _r_d+5
    STA $8E
    LDA _r_d+6
    STA $8F
    LDA _r_d+7
    STA $90
    LDA $8B
    STA $B2
    LDA $8C
    STA $B3
    LDA $8D
    STA $B4
    LDA $8E
    STA $B5
    LDA $8F
    STA $B6
    LDA $90
    STA $B7
    LDA $89
    LDX $8A
    LDA $B2
    STA $8B
    LDA $B3
    STA $8C
    LDA $B4
    STA $8D
    LDA $B5
    STA $8E
    LDA $B6
    STA $8F
    LDA $B7
    STA $90
    ; float
    LDA #$00
    STA $9F
    LDA #$00
    STA $A0
    LDA #$C0
    STA $A1
    LDA #$3F
    STA $A2
    LDA #$00
    STA $A3
    LDA #$00
    STA $A4
    LDA #$00
    STA $A5
    LDA #$00
    STA $A6
    LDA $A1
    STA $B2
    LDA $A2
    STA $B3
    LDA $A3
    STA $B4
    LDA $A4
    STA $B5
    LDA $A5
    STA $B6
    LDA $A6
    STA $B7
    LDA $9F
    LDX $A0
    ; float compare
    LDA _r_d+7
    CMP $A6
    BNE _F43__L63
    LDA _r_d+6
    CMP $A5
    BNE _F43__L63
    LDA _r_d+5
    CMP $A4
    BNE _F43__L63
    LDA _r_d+4
    CMP $A3
    BNE _F43__L63
    LDA _r_d+3
    CMP $A2
    BNE _F43__L63
    LDA _r_d+2
    CMP $A1
    BNE _F43__L63
    LDA _r_d+1
    CMP $A0
    BNE _F43__L63
    LDA _r_d
    CMP $9F
_F43__L63:
    ; arg
    BNE _F43__L64
    LDA #$01
    JMP _F43__L65
_F43__L64:
    LDA #$00
_F43__L65:
    STA $A7
    PHA
    ; arg
    LDA $83
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 9
    LDA #$09
    STA $83
    ; r_s
    LDA _r_s
    LDX _r_s+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $81
    LDA $81
    ; const 104
    LDA #$68
    STA $87
    ; cmp
    LDA $81
    CMP $87
    ; → false
    BNE _F43_L0
    ; r_s
    LDX _r_s+1
    STA $89
    ; const 1
    LDA #$01
    STA $8B
    ; binop
    CLC
    LDX #$00
    STX $8C
    ADC _r_s
    STA $81
    LDA _r_s+1
    ADC $8C
    STA $82
    LDA $81
    LDX $82
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $87
    LDA $87
    ; const 101
    LDA #$65
    STA $82
    ; cmp
    LDA $87
    CMP $82
    ; logand: rhs
    BNE _F43__L66
    LDA #$01
    JMP _F43__L67
_F43__L66:
    LDA #$00
_F43__L67:
    STA $81
    ; → end
    JMP _F43_L1
_F43_L0:
    STA $89
    LDA #$00
    STA $89
_F43_L1:
    ; arg
    PHA
    ; arg
    LDA $83
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; const 10
    LDA #$0A
    STA $81
    ; r_p
    LDA _r_p
    LDX _r_p+1
    ; deref
    ; *ptr
    STA $B0
    STX $B1
    LDY #$00
    LDA ($B0),Y
    STA $87
    LDA $87
    ; const 99
    LDA #$63
    STA $85
    ; cmp
    LDA $87
    CMP $85
    ; arg
    BNE _F43__L68
    LDA #$01
    JMP _F43__L69
_F43__L68:
    LDA #$00
_F43__L69:
    STA $89
    PHA
    ; arg
    LDA $81
    PHA
    ; call
    JSR _check
    ; (expr stmt discarded)
    ; Stdio
    LDA _Stdio
    STA $80
    LDA _Stdio+1
    STA $81
    LDA _Stdio+2
    STA $82
    LDA _Stdio+3
    STA $83
    LDA $82
    STA $B2
    LDA $83
    STA $B3
    LDA $80
    LDX $81
    LDA $B2
    STA $82
    LDA $B3
    STA $83
    ; string literal
    LDA #_str_3
    LDX #_str_3+1
    STA $84
    STX $85
_str_3: .byte $44,$4F,$4E,$45,$20,$25,$75,$0A,0
    ; testCount
    LDA _testCount
    ; arg
    LDA $81
    PHA
    LDA $80
    PHA
    ; mcall
    JSR _cls_Stdio_printf
    ; (expr stmt discarded)
    RTS
    ; === end main ===

    ; === Global variables ===
    _Stdio:
        .space 4
    _ap:
        .space 1
    _botlin:
        .space 1
    _cLo:
        .space 1
    _canPrint:
        .space 1
    _ch:
        .space 1
    _cols:
        .space 1
    _d:
        .space 4
    _depth:
        .space 1
    _dpHi:
        .space 1
    _dpLo:
        .space 1
    _dst:
        .space 2
    _endPtr:
        .space 2
    _failCount:
        .space 1
    _fieldSize:
        .space 1
    _fieldType:
        .space 1
    _fieldVal:
        .space 2
    _fmt:
        .space 2
    _fpBufPtr:
        .space 2
    _hi:
        .space 1
    _inv:
        .space 1
    _lo:
        .space 1
    _mode:
        .space 1
    _n:
        .space 1
    _numCols:
        .space 2
    _off:
        .space 2
    _offset:
        .space 2
    _psDesc:
        .space 2
    _psDp:
        .space 2
    _psFieldCount:
        .space 1
    _psIdx:
        .space 1
    _psSaveDp:
        .space 2
    _ptr:
        .space 2
    _ptrArg:
        .space 2
    _r:
        .space 1
    _r_d:
        .space 8
    _r_f:
        .space 5
    _r_i16:
        .space 2
    _r_i32:
        .space 4
    _r_i8:
        .space 1
    _r_p:
        .space 2
    _r_s:
        .space 2
    _r_u16:
        .space 2
    _r_u32:
        .space 4
    _r_u8:
        .space 1
    _rem:
        .space 2
    _rows:
        .space 1
    _s:
        .space 2
    _sb:
        .space 2
    _sbase:
        .space 2
    _sc:
        .space 1
    _scrMode:
        .space 1
    _screenBase:
        .space 2
    _screenPtr:
        .space 2
    _sentinel:
        .space 1
    _size:
        .space 2
    _spec:
        .space 1
    _src:
        .space 2
    _szHi:
        .space 1
    _szLo:
        .space 1
    _testCount:
        .space 1
    _val:
        .space 4
    _x:
        .space 1
    _y:
        .space 1

    ; === Runtime routines ===

_mul16:
    LDA $B4
    STA $B2
    LDA $B5
    STA $B3
    ; Save lhs since we shift multiplicand
    LDA $B0
    STA $B6
    LDA $B1
    STA $B7
    ; Determine sign
    LDA #$00
    STA $B8         ; sign flag
    LDA $B7
    BPL .mul_op1_pos
    ; Negate operand1
    LDA $B6 : EOR #$FF : STA $B6
    LDA $B7 : EOR #$FF : STA $B7
    INC $B6 : BNE .mul_op1_pos : INC $B7
    INC $B8
.mul_op1_pos:
    LDA $B3
    BPL .mul_op2_pos
    ; Negate operand2
    LDA $B2 : EOR #$FF : STA $B2
    LDA $B3 : EOR #$FF : STA $B3
    INC $B2 : BNE .mul_op2_pos : INC $B3
    INC $B8
.mul_op2_pos:
    ; Unsigned multiply: $B6-$B7 x $B2-$B3 -> $B0-$B3
    LDA #$00
    STA $B0
    STA $B1
    STA $B4
    STA $B5
    LDX #16
.mul_loop:
    LSR $B3
    ROR $B2
    BCC .mul_no_add
    CLC
    LDA $B0
    ADC $B6
    STA $B0
    LDA $B1
    ADC $B7
    STA $B1
    LDA $B4
    ADC #$00
    STA $B4
    LDA $B5
    ADC #$00
    STA $B5
.mul_no_add:
    ASL $B6
    ROL $B7
    DEX
    BNE .mul_loop
    ; Apply sign
    LDA $B8
    AND #$01
    BEQ .mul_done
    LDA $B0 : EOR #$FF : STA $B0
    LDA $B1 : EOR #$FF : STA $B1
    INC $B0 : BNE .mul_done : INC $B1
.mul_done:
    ; Return result in A/X
    LDA $B0
    LDX $B1
    RTS
_div16:
    JSR _udiv16
    LDA $B0
    LDX $B1
    RTS
_mod16:
    JSR _udiv16
    LDA $B2
    LDX $B3
    RTS
_udiv16:
    LDA $B4
    STA $B6
    LDA $B5
    STA $B7
    LDA #$00
    STA $B2
    STA $B3
    LDX #16
.udiv_loop:
    ASL $B0
    ROL $B1
    ROL $B2
    ROL $B3
    SEC
    LDA $B2
    SBC $B6
    TAY
    LDA $B3
    SBC $B7
    BCC .udiv_no_sub
    STY $B2
    STA $B3
    INC $B0
.udiv_no_sub:
    DEX
    BNE .udiv_loop
    RTS
_div32:
    ; 32-bit division (placeholder)
    LDA #$00
    STA $B0
    STA $B1
    STA $B2
    STA $B3
    RTS
_mod32:
    ; 32-bit modulo (placeholder)
    LDA #$00
    STA $B0
    STA $B1
    STA $B2
    STA $B3
    RTS

; ============================================================
; BEGIN xtc-manifest v1
; module.name                      = valist
; module.source                    = valist.xt
; module.compiler                  = xtc 0.12 (IR route)
; module.target                    = atari/xl
;
; ─ Per-function call-graph attributes ─────────────────────
; function._cls_Stdio_init.class         = Stdio
; function._cls_Stdio_printHex__u16.class         = Stdio
; function._cls_Stdio_printHex__u32.class         = Stdio
; function._cls_Stdio_printHex__u8.class         = Stdio
; function._cls_Stdio_printStruct.class         = Stdio
; function._cls_Stdio_print__f.class         = Stdio
; function._cls_Stdio_print__i16.class         = Stdio
; function._cls_Stdio_print__i32.class         = Stdio
; function._cls_Stdio_print__s.class         = Stdio
; function._cls_Stdio_print__u16.class         = Stdio
; function._cls_Stdio_print__u32.class         = Stdio
; function._cls_Stdio_printf.class         = Stdio
; function._cls_Stdio_printfAt.class         = Stdio
; function._cls_Stdio_putChar.class         = Stdio
; function._cls_Stdio_scroll.class         = Stdio
; function._cls_Stdio_setCursor.class         = Stdio
; function._main.is_main       = true
;
; ─ Per-class inheritance + vtable info ────────────────────
; class.Object.class_id  = 1
; class.Stdio.parent    = Object
; class.Stdio.class_id  = 2
; END xtc-manifest
; ============================================================
