;; Generated by xtc --emit-asm-from-ir
;; Source: tests/fixtures/varargs.xt

    .org $2000

main_entry:
    JSR _main
    JMP ($000A)   ; exit through DOSVEC

.module varargs

    ; === function myprintf ===
_myprintf:
	PLA
	STA $B0
	PLA
	STA $B1
    ; fmt
    PLA
    STA $80
    PLA
    STA $81
    LDA $80
    LDX $81
	LDA $B1
	PHA
	LDA $B0
	PHA
    ; const 0
    LDA #$00
    STA $80
    ; return
    RTS
    ; === end myprintf ===
    ; === function main ===
_main:
    ; string literal
    LDA #_str_0
    LDX #_str_0+1
    STA $80
    STX $81
_str_0: .byte $74,$65,$73,$74,$20,$25,$64,$20,$25,$64,0
    ; const 1
    LDA #$01
    STA $82
    ; const 2
    LDA #$02
    STA $84
    ; arg
    LDA $81
    PHA
    LDA $80
    PHA
    ; call
    JSR _myprintf
    STA $83
    ; (expr stmt discarded)
    ; return
    RTS
    ; === end main ===

    ; === Global variables ===

    ; === Runtime routines ===

