#!/bin/sh
# gen-glibc-imports.sh — generate support/x86_64/glibc-imports.map, the
# symbol → library table `xcc -A x86_64 -dynamic` links against.
#
# A -dynamic executable imports glibc rather than carrying a libc of its own.
# The linker needs to know which library defines each symbol a program calls,
# so that libc.so.6 / libm.so.6 become DT_NEEDED only when used and a symbol no
# library defines is a link error rather than a failure at load. The table is
# generated ONCE on a glibc host and checked in, so linking needs no glibc on
# the machine that runs xcc (a Mac can link for Linux) — the same arrangement
# as support/win64/win32-imports.map.
#
# Symbols are listed without versions: the executable's references are
# unversioned, and ld.so binds them to the library's definition.
#
# Usage, on an x86-64 glibc Linux host: tools/gen-glibc-imports.sh [libdir]
set -e
# Byte order: under a natural-language locale sort ignores underscores, so
# `__write` and `write` compared equal and `sort -u` kept only one of them.
export LC_ALL=C
cd "$(dirname "$0")/.."
LIBDIR="${1:-/usr/lib/x86_64-linux-gnu}"
OUT=support/x86_64/glibc-imports.map
VER=$(ldd --version 2>/dev/null | head -1 | sed 's/.* //')
{
  echo "# glibc-imports.map — symbol<TAB>library, generated by tools/gen-glibc-imports.sh"
  echo "# from glibc $VER (x86-64). Consumed by xcc-ln-x86_64 -importmap under"
  echo "# -dynamic. Regenerate on a glibc host; do not hand-edit. A library becomes"
  echo "# DT_NEEDED only when a program references one of its symbols."
  for lib in libc.so.6 libm.so.6; do
    # Defined, non-absolute (the version nodes are 'A') dynamic symbols.
    nm -D --defined-only "$LIBDIR/$lib" | awk '$2 != "A" { print $3 }' |
      sed 's/@.*//' | sort -u | awk -v l="$lib" '{ print $1 "\t" l }'
  done | sort -t "$(printf '\t')" -k1,1 -u
} > "$OUT"
echo "$OUT: $(grep -vc '^#' "$OUT") symbols"
