@echo off
rem winbuild.bat — build the xtc compiler natively on Windows with clang-cl +
rem GNUstep (libobjc2, gnustep-2.0 runtime). No make/nmake needed. Run from the
rem repo root; produces build\bin\*.exe.
rem
rem Prerequisites:
rem   * LLVM (clang-cl, lld-link) on PATH.
rem   * GNUstep for Windows at C:\GNUstep\x64\Release (libobjc2 build), with its
rem     bin dir on PATH so the built .exes find the runtime DLLs.
rem   * flags.rsp and shared.rsp beside this script (generated by
rem     tools/gen-winbuild.sh on a Unix box, or by hand — see that script).
rem
rem CRITICAL: clang-cl silently ignores -fobjc-arc; it MUST be -Xclang -fobjc-arc
rem (already in flags.rsp). Without it every weak property fails to synthesise.
setlocal
if not exist build\obj   mkdir build\obj
if not exist build\mains  mkdir build\mains
if not exist build\bin   mkdir build\bin

echo === compiling shared objects ===
clang-cl @flags.rsp /MP /c @shared.rsp /Fobuild\obj\ 2>build\compile.log
if errorlevel 1 ( echo COMPILE FAILED: & type build\compile.log | findstr /c:"error:" & exit /b 1 )
echo === shared objects OK ===

call :link xtc          src\xtc\main.m
call :link xtc-fe       src\xtc-fe\main.m
call :link xtcg-win64   src\xtcg-win64\main.m
call :link xtcln-win64  src\xtcln-win64\main.m
call :link xtcg-x86_64  src\xtcg-x86_64\main.m
call :link xtcln-x86_64 src\xtcln-x86_64\main.m
call :link xtcg-arm64   src\xtcg-arm64\main.m
call :link xtcln-arm64  src\xtcln-arm64\main.m
call :link xtcg-6502    src\xtcg-6502\main.m
call :link xtcg-68k     src\xtcg-68k\main.m
call :link xtcg-arm9    src\xtcg-arm9\main.m
call :link xtcg-wasm32  src\xtcg-wasm32\main.m
call :link xtcln-wasm32 src\xtcln-wasm32\main.m
call :link xta          src\xta\main.m
echo === DONE (build\bin) ===
exit /b 0

:link
echo --- linking %1 ---
clang-cl @flags.rsp /c %2 /Fobuild\mains\main_%1.obj 2>>build\compile.log
clang-cl build\mains\main_%1.obj build\obj\*.obj gnustep-base.lib objc.lib dispatch.lib -fuse-ld=lld /MD -o build\bin\%1.exe /link /LIBPATH:C:\GNUstep\x64\Release\lib >build\link_%1.log 2>&1
if exist build\bin\%1.exe ( echo   %1.exe OK ) else ( echo   %1 LINK FAILED: & findstr /c:"error" build\link_%1.log )
exit /b 0
